### ISSUE TITLE
KCL Enums/Options

### ISSUE THREAD

**Issue by adamchalmers** [KittyCAD/modeling-app#1006]
KCL needs enums to help users write correct KCL programs. Right now users have to specify axes as strings, e.g. "XY". This is OK but will get confusing. Users will need to read the docs carefully to discover which strings are valid. This is especially painful when we add revolves in https://github.com/KittyCAD/modeling-app/discussions/496. The proposed syntax is something like

```js
revolve({
    sketch: part001,
    direction: 'ccw', //optional, default to cw
    angle: 180, //optional, default to 360
    axis: 'absoluteY' // absolute meaning world coordinate system
})

revolve({
    sketch: sketch001,
    direction: 'positive', //optional, default to positive. Uses right hand rule
    angle: 90, //optional, default to 360
    axis: 'revolveAxis' // absolute meaning world coordinate system
})
```

the possible values for `direction` and `axis` are not intuitive. 

If we have enums, then users can write `axis: Axis` and get suggestions like Axis.revolveAxis, axis.absoluteY etc.

**Comment by Irev-Dev** [comment]
Yeah sounds good.

This is likely just me being a typescript fan boy, but I really like typescript's union types from the perspective of they can resolve to strings and being able to define them inline.

So if we allowed
```typescript
enum Direction = 'cw' | 'ccw'
const myFn = (dir: Direction) => {/* ... */}
const result = myDirection = myFn(Direction.cw)
const result2 = myDirection = myFn('cw')
```
as well as inline
```typescript
const myFn = (dir: 'cw' | 'ccw') => {/* ... */}
const result = myDirection = myFn(Direction.cw)
const result2 = myDirection = myFn('cw')
```

Essentially I like being able to use a string still, but it being safe (getting an error if I make a typo `'cww'`. And being able to define things inline is very convenient when writing function definitions, this probably has some syntax implications because `const myFn = (dir: {cw, ccw}) => {/* ... */}` not the best (I just used the TS pipe for the examples but not wedded to it).

Anyway that's my 2c.

**Comment by jgomez720** [comment]
More of a side note. In the first example I used `direction: 'ccw'` but the second example I used `direction: 'positive'`. It's just a naming syntax, but just wanted to clarify for anyone reading. We can either go the cw/ccw or the pos/neg route.

**Comment by adamchalmers** [comment]
@jgomez720 oh I thought "ccw" and "cw" and "positive" and "negative" were all 4 different ways to revolve haha

@Irev-Dev Yeah I like the string unions in TS too. I want to ensure we can put docs on every case of an enum, but I guess we could do that just fine as long as people write each enum case on its own line. That would stop people from writing their enums inline like your `(dir: {cw, ccw}) => {}` example though. And we should probably encourage users to write docs for enums, because their meaning isn't always obvious.

**Comment by adamchalmers** [comment]
@Irev-Dev I think the enum system should be able to accommodate optionals, which would require enums that aren't just a union of some possible values within a type.

To get optionals you need true algebraic data types, i.e. enums where each variant has both a tag and a set of fields.

Maybe we can make TS-style unions just syntactic sugar for true enums?

Also enums require match syntax, which lets users basically get if/else syntax.

**Comment by lf94** [comment]
I was going to say, a lot of this talk reminds me of essentially KCL representing a small subset of Haskell.

I would like to see how enums accommodate optionals. The only thing I can imagine is:

```
type CircleArgSet1 = (radius);
type CircleArgSet2 = (radius, tag);
type CircleArgSet3 = (radius, tag, ...);
type CircleFnArgs = CircleArgSet1 | CircleArgSet2 | CircleArgSet3 | ...;
type circle T = CircleFnArgs -> Result<T>
```

**Comment by adamchalmers** [comment]
@lf94 yeah your CircleArgSet example is exactly why I wanted enums for the stdlib. But here's an alternative design:

```kcl
// Using enums but no optionals
type CircleFnArgs 
  = (radius: f32, center: Point2d) 
  | (radius: f32, center: Point2d, tag: string)

// Using enums to represent optionals
type CircleFnArgs 
  = radius: f32, center: Point2d, tag: (None | Some string)
```

**Comment by lf94** [comment]
Ok ok, good to know I'm on the same page. :)

Using Maybe/Optional type like that though, programmers typically still need to write "None" or "Some(x)". Not ideal for UX. But yes, both our sketches seem to express the same idea.

I agree, KCL needs "eventual equal power to common languages".

Really I am arguing for deferring things until you or someone really needs them, **or**, at least design KCL to be open/extensible (which I believe it already pretty much is, right?).

We need to also acknowledge that the idea of "optional values" is as old as programming, and many languages have shorthad to express optional values. It could be both easier impl. wise and more ergonomic to adopt `?` as an optional syntax in several contexts.

---

I think Kurt was emphasizing not needing to write `Axis.A`, or `Axis.B`, etc... Yeah, in the end, writing quotes around the type values don't add anything unless they really are strings.

**Comment by adamchalmers** [comment]
Well, the topic might be algebraic data types (a set of variants, each of which has a tag and 0 or more fields) -- or maybe full ADTs aren't necessary, and we can just do simpler enums like Typescript's "set of untagged values within a single type".

**Comment by adamchalmers** [comment]
@Irev-Dev I like your proposal but is it actually important that the variants be strings? How would you feel about


```ts
enum Direction = cw | ccw
const myFn = (dir: Direction) => {/* ... */}
const result = myFn(Direction.cw)
const result2 = myFn(cw)
```


```ts
const myFn = (dir: cw | ccw) => {/* ... */}
// cannot do const result = myFn(Direction.cw)
// because the Direction is defined inline
// but you can do:
const result2 = myFn(cw)
```

My feeling is that our stdlib wants enums just for matching on direction, and doesn't really need to do string manipulation on them (e.g. you'll never want to say `dir.uppercase()` or dir[0]`). Under the hood, in the Rust executor, we might map some enums to strings to send them in the API, but we might also map them to some other serde construct. So I don't think KCL users need to think of enums as strings.

**Comment by Irev-Dev** [comment]
Sorry I didn't mean to emphasise string so much in my first comment, It's more the easy of defining them inline that I like and yeah not having to do `thing1.thing2` syntax if possible.

Those examples look great to me @adamchalmers!

**Comment by adamchalmers** [comment]
So, one complication. Take a Rust-inspired union like

```
enum Axis = X | Y | Z
```

This isn't actually helpful for users unless we also ship a `match` expression. Without `match` there's no way to map the enum variants into useful KCL values. 

On the other hand, TS-inspired unions like
```
enum Axis = "x" | "y" | "z"
enum PossibleSpokesOnGear = 14 | 16 | 20
```

is immediately useful because each variant is a KCL literal, so you can use it in other KCL expressions. On the other hand, you can't build algebraic data types (including option, result, and domain-specific types like `enum MyPart = NoSpokes | Gear { numSpokes: Int}`) from this approach.

## Proposal

1. We ship Rust-inspired enums `enum Axis =  X | Y | Z` and a `match` statement. This lets users map their enums to ints, strings, etc and use them in expressions or other API calls. We don't support adding fields to each enum yet.
2. Support fields in each enum, e.g. `enum Extrude = Up | Down | Revolve Axis Direction Angle`
3. Support generics in fields, e.g. `enum Option<T> = Some T | None`

**Comment by adamchalmers** [comment]
Thinking more about this, I think I'm violating one my own guidelines for KCL: only add language features when we have concrete use-cases for it. Let's look at the existing KCL stdlib. There are 11 enums in the stdlib, all defined in [std/sketch.rs](https://github.com/KittyCAD/modeling-app/blob/f6f157498221e8d5fa70ffd5299d791fca3e1a6d/src/wasm-lib/kcl/src/std/sketch.rs#L1).

These are the enums which only exist to make a `tag` parameter optional:

1. [LineToData](https://github.com/KittyCAD/modeling-app/blob/f6f157498221e8d5fa70ffd5299d791fca3e1a6d/src/wasm-lib/kcl/src/std/sketch.rs#L23-L24)
2. [AxisLineToData](https://github.com/KittyCAD/modeling-app/blob/f6f157498221e8d5fa70ffd5299d791fca3e1a6d/src/wasm-lib/kcl/src/std/sketch.rs#L102-L103)
3. [LineData](https://github.com/KittyCAD/modeling-app/blob/f6f157498221e8d5fa70ffd5299d791fca3e1a6d/src/wasm-lib/kcl/src/std/sketch.rs#L175-L176)
4. [AxisLineData](https://github.com/KittyCAD/modeling-app/blob/f6f157498221e8d5fa70ffd5299d791fca3e1a6d/src/wasm-lib/kcl/src/std/sketch.rs#L253-L254)
5. [AngledLineData](https://github.com/KittyCAD/modeling-app/blob/f6f157498221e8d5fa70ffd5299d791fca3e1a6d/src/wasm-lib/kcl/src/std/sketch.rs#L321-L322)
6. [AngledLineToData](https://github.com/KittyCAD/modeling-app/blob/f6f157498221e8d5fa70ffd5299d791fca3e1a6d/src/wasm-lib/kcl/src/std/sketch.rs#L449-L450)
7. [TangentialArcToData](https://github.com/KittyCAD/modeling-app/blob/f6f157498221e8d5fa70ffd5299d791fca3e1a6d/src/wasm-lib/kcl/src/std/sketch.rs#L1184-L1185)
8. [BezierData](https://github.com/KittyCAD/modeling-app/blob/f6f157498221e8d5fa70ffd5299d791fca3e1a6d/src/wasm-lib/kcl/src/std/sketch.rs#L1249-L1250)

Enums that aren't just making tag optional:

1. [PlaneData](https://github.com/KittyCAD/modeling-app/blob/f6f157498221e8d5fa70ffd5299d791fca3e1a6d/src/wasm-lib/kcl/src/std/sketch.rs#L653) - has cases XY, -XY, XZ, -XZ, YZ, -YZ and custom plane with (origin, x y and z axes).
2. [ArcData](https://github.com/KittyCAD/modeling-app/blob/f6f157498221e8d5fa70ffd5299d791fca3e1a6d/src/wasm-lib/kcl/src/std/sketch.rs#L935-L936) has two main cases, {center, to, radius} and {angle_start, angle_end, radius} each with an optional tag.
3. [TangentialArcData](https://github.com/KittyCAD/modeling-app/blob/f6f157498221e8d5fa70ffd5299d791fca3e1a6d/src/wasm-lib/kcl/src/std/sketch.rs#L1072) has two main cases, {radius, offset} and {to, tag?}

Based on this, I think optional parameters are the only thing we really need right now, specifically because so many stdlib functions want to optionally take a tag. Optional tags are going to be a _very_ common pattern in KCL, they're central to Kurt's whole design, so I think a dedicated option syntax is the most important first step. We can design this to be forwards-compatible with a more generic enum system later -- options are their own special type now, but could become just a special case of more general ADTs later.

Enums like PlaneData, ArcData and TangentialArcData could be removed -- instead of having one function which takes an enum of N cases, just make N different functions. If we have special syntax for optional params, the value of N becomes much smaller, so this is feasible.

**Comment by Irev-Dev** [comment]
Thanks for thinking this through.

Okay, I'm partially concerned about optional params.

So part of the reason why fake-enums were used to allow optional tags was because I was trying to keep the argument length the same size, because I had ignorantly thought that was important for data-last.

To be fair I went with a data-last convention because I knew that it was a *useful* convention in a functional paradigm, without really knowing the in-and-outs of it, the short of my thinking was that it's useful for the pipe-operator if it goes hand in hand with auto-currying i.e.

```typescript
const part001 = startSketchOn('-XZ')
  |> startProfileAt([1.09, 10.99], %)
  |> line([15.36, 2.13], %)
```
becomes
```typescript
const part001 = startSketchOn('-XZ')
  |> startProfileAt([1.09, 10.99])
  |> line([15.36, 2.13])
```
not that we have auto-currying implemented anyway.

[This article cleared my head somewhat on the topic though](https://www.javierchavarri.com/data-first-and-data-last-a-comparison/) (interestingly they sprook data-first as having benefits for inference, but that's also because of OCaml's evaluating arg types from left to right, maybe we could evaluate from right to left when we get serious about types if it helps us with the data-last convention)

I thought there was a conflict between optional params and data-last because optional params had to be at the end of the definitional i.e. `fn myFn = (a:string, b=2, c:string) => {...}` was not allowed since calling it with `myFn('foo', 'bar') would try put `'bar'` into the `b` param, but I guess this is not something our language can't deal with.

[Sounds like it's a thing](https://www.javierchavarri.com/data-first-and-data-last-a-comparison/#worse-integration-with-optional-parameters), but the `unit` thing went over me head, I'm guessing an OCaml thing I need to look into.

With that said, so long as we can make optional params work with pipe operator, I'm happy.
I think the below reads well enough too :)

```typescript
const part001 = startSketchOn('-XZ')
  |> startProfileAt([1.09, 10.99], %)
  |> line([15, 2], 'myTag', %)
  |> line([10, 3], %)
```

**Comment by adamchalmers** [comment]
OK, I'm converting the stdlib to use Option<String> for tag, instead of enums.

**Comment by jessfraz** [comment]
closing since this comment is now reality https://github.com/KittyCAD/modeling-app/issues/1006#issuecomment-1863228315
