### ISSUE TITLE
GUI Extrude Button only works on StartProfileAt()

### ISSUE THREAD

**Issue by jgomez720** [KittyCAD/modeling-app#1016]
## Description
The extrude button is grayed out when I select the sketch or when I put my cursor on the startSketchOn() line of code. I believe these are both supposed to work (?). I can only get it to work when I click on the sketchProfileAt() line of code.

### Version
**v0.11.2**

### Supporting Material
https://github.com/KittyCAD/modeling-app/assets/114548659/59c1b29e-c3a1-4935-97cc-62b10f738fdf

tasks:
- [x] clicking the 2d sketch should put the cursor in the correct position for an extrude (#1019)
- [ ] `startSketchOn` and `close` should be a valid places for the cursor to enable the extrude button

**Comment by Irev-Dev** [comment]
Ah thanks.

**Comment by Irev-Dev** [comment]
Not being able to click the object in the 3d scene is a regression I introduced in #1013, so I've fixed that, but I agree that `startSketchOn` should be a valid place to extrude from so I've added two tasks to capture these both and I'll leave this open `til I get to the second one.

**Comment by jessfraz** [comment]
this works now
