### ISSUE TITLE
Compile-time KCL parser

### ISSUE THREAD

**Issue by adamchalmers** [KittyCAD/modeling-app#1018]
# Background

The KCL [lexer](https://github.com/KittyCAD/modeling-app/blob/2e419907e6ee0b9afe4640c4eaa9a7fa340c403f/src/wasm-lib/kcl/src/token/tokeniser.rs#L13) and [parser](https://github.com/KittyCAD/modeling-app/blob/0b9ba55bb44ab1af28bf505191f7176dd549b0dd/src/wasm-lib/kcl/src/parser.rs#L29) are both deterministic, pure functions. The lexer takes a Rust string and outputs a Vec<Token>. The parser takes that Vec<Token> and outputs a KCL [Program](https://github.com/KittyCAD/modeling-app/blob/809f1db30a6210f61ce281a49a03ed0d302dfbae/src/wasm-lib/kcl/src/ast/types.rs#L25).

# Problem

In #922 we want to create a KCL stdlib. Right now that involves compiling KCL at runtime, and if it can't be compiled, we panic. It'd be better to compile KCL to its AST at compiletime. This way we could check at compile time that the KCL standard library is valid.

# Solution

I suggest a `kcl!` macro like

```rust
let my_fn: Program = kcl! {
  fn cube = (pos, scale) => {
    const sg = startSketchAt(pos)
      |> line([0, scale], %)
      |> line([scale, 0], %)
      |> line([0, -scale], %)

    return sg
  }

  const b1 = cube([0,0], 10)
  const pt1 = b1[0]
  show(b1)
}
```

I think this would need to be a proc macro. It would take the text within the `kcl!{ ... }` block, put it into a Rust string, then run it through the KCL lexer and parser. If it succeeds, expand the macro into a KCL Program AST type. If it fails, compile error.

**Comment by lf94** [comment]
I would avoid the layer of abstraction and just go:

```
let my_fn: KCLProgram = kclCompile("...
...
...
");
```

It would make reasoning about any KCL code easier instead of guessing what the macro is doing, right?

**Comment by adamchalmers** [comment]
We already have a function to compile KCL at runtime, which is your suggestion.

A macro would be more complicated, but it would let you parse KCL at _compile_ time, not _runtime_. 

This solves the problem of never compiling the WASM with some static KCL program embedded (e.g. in the standard library) which is parsed at runtime and, at runtime, discovered to be invalid. A macro would let you know the KCL is valid before users open the wasm library let alone run it.
