### ISSUE TITLE
[nit] Rename project to kittycad-modeling-app

### ISSUE THREAD

**Issue by lf94** [KittyCAD/modeling-app#1041]
It's a common pattern for people to have a `~/Code/{other,mine}/` directory structure. When checking out projects that don't "namespace" themselves it's very easy to get lost quickly. When I checked out modeling-app I found myself doing `kitty<tab><tab>` to realize whoops, it's actually `modeling<tab><tab>` to auto-complete.

Extremely minor nit. ;p Feel free to close if it's really not worth it.

**Comment by jessfraz** [comment]
that stutters imo, i dont like repos that also include the org name

**Comment by jessfraz** [comment]
you can always `git clone {our-url} kittycad-modeling-app`

**Comment by lf94** [comment]
> that stutters imo, i dont like repos that also include the org name

Okie dokie
