### ISSUE TITLE
Build warning: "failed to parse serde attribute"

### ISSUE THREAD

**Issue by lf94** [KittyCAD/modeling-app#1043]
When doing `yarn build:wasm-dev`

```
$ rustc --version
rustc 1.73.0 (cc66ad468 2023-10-03)
2023-11-09 09:36:27-05:00
```

```
warning: failed to parse serde attribute
  | 
  | #[serde(rename = "XY", alias = "xy")]
  | 
  = note: ts-rs failed to parse this attribute. It will be ignored.

```

**Comment by adamchalmers** [comment]
Thanks for filing, this is a known issue -- see the ts-rs crate's docs on serde for why: https://docs.rs/ts-rs/latest/ts_rs/#serde-compatability

I haven't looked into it much yet, there might be a way to silence the warning, or maybe to use newtypes to break out the serde stuff from the ts-rs stuff.

**Comment by jessfraz** [comment]
thanks to paul
