### ISSUE TITLE
Window resize may be causing mouse pointer errors

### ISSUE THREAD

**Issue by jgomez720** [KittyCAD/modeling-app#1066]
Mentioned in the Discord: 
>Also, there was a significant offset from my actual mouse pointer to where the line endpoints were created. However, it is true in each case that the very first thing I did after starting the tool was to maximize the window... so it is quite possible that the window resize was not being accounted for during clicking.  

He's not 100% sure that resize is what causes the offset of the line tool to the cursor, but it's a good guess.

Let me know if this belongs to someone else @franknoirot

**Comment by jessfraz** [comment]
is this still a thing?

**Comment by jgomez720** [comment]
No, I never heard of someone else running into this. We can close
