### ISSUE TITLE
Loading stream

### ISSUE THREAD

**Issue by alynrockwood** [KittyCAD/modeling-app#1088]
Never loads. It says, "loading is taking longer than expected." (after about an hour)

**Comment by adamchalmers** [comment]
What OS are you running?

**Comment by paultag** [comment]
@alynrockwood in addition to the OS, are you running this through the KCMA (the desktop app) or via a web browser - and if a web browser, which one? Are you able to open the debug console (in the app, Right-click, click on "Inspect element", and then select the "Console" tab) and check for errors? Likely suspects here are anything that says "701" or "Too many active connections".

**Comment by alynrockwood** [comment]
I'm on Mac, running on Safari browser. The only thing I see in the Console
tab (in the pink highlight area) is the word "Fu"

**Comment by jessfraz** [comment]
alyn let us know if you are still having issues but i think we are good here!
