### ISSUE TITLE
Stdlib inconsistent about keyword vs. positional args

### ISSUE THREAD

**Issue by adamchalmers** [KittyCAD/modeling-app#1107]
## Background

A very common pattern in the stdlib is to have functions which take two params:

- A "data" param e.g. TangentialArcToData
- A sketch group param

This pattern is so common that we have a [get_data_and_sketch_group](https://github.com/KittyCAD/modeling-app/blob/b925ed9b65ac932928b4153bc3901443ef57020c/src/wasm-lib/kcl/src/std/mod.rs#L364) function.

The data param usually has an optional tag field. This means users can write KCL function calls like

```
tangentialArcTo([x, y], sg)
```

or 

```
tangentialArcTo({ to: [x, y], tag: "myArc" }, sg)
```

This is because, under the hood, the executor deserializes the first param into 

```rust
#[derive(Debug, Clone, Deserialize, Serialize, PartialEq, JsonSchema, ts_rs::TS)]
#[ts(export)]
#[serde(rename_all = "camelCase", untagged)]
pub enum TangentialArcToData {
    /// A point with a tag.
    PointWithTag {
        /// Where the arc should end. 
        to: [f64; 2],
        /// The tag.
        tag: String,
    },
    /// A point where the arc should end. 
    Point([f64; 2]),
}
```

This way, the user can either have an array or object as the first param, depending on if they need to tag the point or not. this avoid the user needing to put "" as a tag.

## Problem

This is convenient but I think it's confusing for users. What is the type signature of this function? If users want a tag, the first param is an object. If users don't want a tag, the first param is an array. I think KCL needs optional arguments for tags and will eventually want type signatures. I don't know how to write a type signature for this function!

## Solution

I would prefer if our functions were consistent. IMO we should either go all-in on positional arguments or all-in on objects with named fields. So, either

```
tangentialArcTo([x, y], sg)
tangentialArcTo([x, y], sg, "myArc")
```

or
```
tangentialArcTo({ to: [x, y], sketchGroup: sg, tag: "myArc"})
tangentialArcTo({ to: [x, y], sketchGroup: sg})
```

**Comment by Irev-Dev** [comment]
We could just nuke the array inputs for no tag, and keep the sketch group as a separate 2nd param.
```typescript
tangentialArcTo({ to: [x, y], tag: "myArc"}, sg)
tangentialArcTo({ to: [x, y]}, sg)
```
seems like the least refactoring and keeps the data-last convention.

**Comment by adamchalmers** [comment]
We could. I'm not convinced about the data last convention. Maybe it should be "data last thing before optional parameters" convention instead. 

I'm not worried about refactors at this point, alpha is the right time to do refactors.

**Comment by lf94** [comment]
> all-in on objects with named fields

My vote's on this

**Comment by iterion** [comment]
We decided to use an optional tag param instead of grouping tag into the first arg. See the decision here:
https://github.com/KittyCAD/modeling-app/issues/1006
