### ISSUE TITLE
you can reload the onboarding from any screen and the onboarding works

### ISSUE THREAD

**Issue by Irev-Dev** [KittyCAD/modeling-app#1110]
I thought this was a good one for you Frank since it's testing your work.

Read through [the playwright section of the readme](https://github.com/KittyCAD/modeling-app/pull/1039/files?short_path=b335630#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5) to cover the basics.

The start of the test should probably look like:
(the beforeEach script already dismisses the onboarding, so that's good for "reloading" the onboarding.
```typescript
test('Basic sketch', async ({ page }) => {
  const u = getUtils(page)
  page.setViewportSize({ width: 1200, height: 500 })
  await page.goto('localhost:3000')
  await u.waitForAuthSkipAppStart()
  await u.waitForDefaultPlanesVisibilityChange()
  // ...
})
```
Just to wait for the app to load, having said that maybe you don't need to wait for the stream to start for this test?
This test probably won't follow the example of many of the other tests, namely because you should be able normal playwright conventions and query mostly HTML for this

since that's the case maybe giving `yarn playwright codegen -b wk --load-storage ./store localhost:3000` is worth a shot?

<details>
<summary>

Where `./store` should look like this

</summary>

```JSON
{
  "cookies": [],
  "origins": [
    {
      "origin": "http://localhost:3000",
      "localStorage": [
        {
          "name": "store",
          "value": "{\"state\":{\"openPanes\":[\"code\"]},\"version\":0}"
        },
        {
          "name": "persistCode",
          "value": ""
        },
        {
          "name": "TOKEN_PERSIST_KEY",
          "value": "your-token"
        }
      ]
    }
  ]
}
```

</details>

lmk if that works.

btw if as part of this you want to test the onboarding when it loads for the first time, override the beforeEach script with the following.

```typescript
test('Basic sketch', async ({ page, context }) => {
  context.addInitScript(async (token) => {
    localStorage.setItem(
      'SETTINGS_PERSIST_KEY',
      JSON.stringify({
        baseUnit: 'in',
        cameraControls: 'KittyCAD',
        defaultDirectory: '',
        defaultProjectName: 'project-$nnn',
        onboardingStatus: '', // triggers first time onboarding etc
        showDebugPanel: true,
        textWrapping: 'On',
        theme: 'system',
        unitSystem: 'imperial',
      })
    )
  })
  const u = getUtils(page)
  page.setViewportSize({ width: 1200, height: 500 })
  await page.goto('localhost:3000')
  await u.waitForAuthSkipAppStart()
  await u.waitForDefaultPlanesVisibilityChange()
```

**Comment by Irev-Dev** [comment]
There's another task in #833
`if you restart the onboarding it re-executes with the new code for the onboarding`
That maybe should be covered as part of this?

**Comment by franknoirot** [comment]
> There's another task in https://github.com/KittyCAD/modeling-app/issues/833
> `if you restart the onboarding it re-executes with the new code for the onboarding`
> That maybe should be covered as part of this?

I'm not sure how I should be testing "re-executes". Should I be checking if the stream video frame:
1. exists
2. is different than before
3. is correct
or should I be using something to do with the debug panel to proxy testing the actual stream?
