### ISSUE TITLE
you can move lines in a fresh sketch from `Start Sketch` and it updates the code (more than once)

### ISSUE THREAD

**Issue by Irev-Dev** [KittyCAD/modeling-app#1112]
I would probably resolve this issue and the task `you can move lines in edit sketch and it updates the code (more than once)` also in #833 in the same test, but could also be separate, 

Read through [the playwright section of the readme](https://github.com/KittyCAD/modeling-app/pull/1039/files?short_path=b335630#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5) to cover the basics.

The start of the test should probably look like:
```typescript
test('Basic sketch', async ({ page }) => {
  const u = getUtils(page)
  page.setViewportSize({ width: 1200, height: 500 })
  await page.goto('localhost:3000')
  await u.waitForAuthSkipAppStart()
  await u.waitForDefaultPlanesVisibilityChange()
  // ...
})
```

This one is probably challenging because it involves interacting with the stream quiet a bit, but you can probably draw a fair bit of inspiration from `Basic sketch` in `e2e/playwright/flow-tests.spec.ts` because it also interacts with the stream.

But also here's a snippet from `change camera, show planes` in `e2e/playwright/snapshot-tests.spec.ts`

```typescript
  await u.closeDebugPanel()
  await page.mouse.move(700, 200)
  await page.mouse.down({ button: 'right' })
  await page.mouse.move(600, 300)
  await page.mouse.up({ button: 'right' })

  await u.openDebugPanel()
  await u.waitForCmdReceive('camera_drag_end')
```

Which might be useful since it's a click and drag event which you'll have to do for move, though I think `camera_drag_end` is likely to be different (it is I've since checked 👇).

https://github.com/KittyCAD/modeling-app/assets/29681384/4974e345-ff99-48ef-9814-e529514f712e

**Comment by jessfraz** [comment]
im pretty sure we've covered this by now we have lots of similar tests ive seen
