### ISSUE TITLE
startSketchOn z_axis ignored

### ISSUE THREAD

**Issue by lf94** [KittyCAD/modeling-app#1117]
![1700705642](https://github.com/KittyCAD/modeling-app/assets/547923/bc042b82-eea3-4539-a165-2fe71e2d3ec9)
![1700705620](https://github.com/KittyCAD/modeling-app/assets/547923/1ecc3d05-38c6-4c2b-a66f-1129dd8d0818)

Root cause: `src/wasm-lib/kcl/src/std/sketch.rs:773`, ignores it

**Comment by Irev-Dev** [comment]
I believe the x and y axis in the API are what's going to be the x and y of the plane you will be sketching on
So if you wanted to sketch on the XZ plane you would define`{ x_axis: {x: 1, y:0, z:0 }, y_axis: {x:0, y:0, z:1}}`. I might be wrong though.

**Comment by lf94** [comment]
Correct, that defines the X and Y axis normals. But the `z_axis` normal further defines what is "up", which KCMA strips out (as shown)

**Comment by jessfraz** [comment]
here's some test code:
```

const a1 = startSketchOn({
    plane: {
        origin: { x: 0, y: 0, z: 0 },
        x_axis: { x: 1, y: 0, z: 0 },
        y_axis: { x: 0, y: 1, z: 0 },
        z_axis: { x: 0, y: 0, z: 1 }
    }
})
|> startProfileAt([0, 0], %)
|> line([100.0, 0], %)
|> yLine(-100.0, %)
|> xLine(-100.0, %)
|> yLine(100.0, %)
|> close(%)
|> extrude(3.14, %)

```

**Comment by Irev-Dev** [comment]
@jessfraz I think we can close this, maybe I missunderstand, but it sure seems to flip things for me

![image](https://github.com/KittyCAD/modeling-app/assets/29681384/4fd02abb-5e76-4a47-8cc4-a48c498c8135)

vs

![image](https://github.com/KittyCAD/modeling-app/assets/29681384/fc458058-d4bc-4d00-911f-7c6781199f38)

**Comment by Irev-Dev** [comment]
imo I kinda don't think we should give user's the ability to flip normals like this, but that's an aside.

**Comment by jessfraz** [comment]
Note to self tomorrow make sure we have tests for this I think we do but I’ll checj
