### ISSUE TITLE
gltf-standard is two files, that causes some UX problem for exports

### ISSUE THREAD

**Issue by Irev-Dev** [KittyCAD/modeling-app#1151]
https://github.com/KittyCAD/modeling-app/assets/29681384/0feb40f9-2209-4cb2-8286-c02b8d53f32c

like I said above fix is awaiting a promise so the pickers open up one after the other, but I'm not 100% sure about this,
Rolling with it because it's better than before but
1. two consecutive file pickers is a weird experience
2. in the gltf json there `buffers [ {uri: "output.bin"}]` so if we let the user name the bin file something else it will likely break.

Fixes are
1. skip picker for gltf standard (but would be weird it not having picker when every other format does
2. remove gltf-standard as an export option
3. zip both files together

I think 3 is the best

**Comment by lf94** [comment]
Yea, 3 is best here also because some other formats like obj can reference other files too within it. It's nice if 2 or more export files default to zip, otherwise their original format.

**Comment by Irev-Dev** [comment]
@lf94 is resolving this issue/ziping gltf-standard something you would be interested in doing?

**Comment by lf94** [comment]
Consider me interested :)

**Comment by Irev-Dev** [comment]
Awesome!

Note: changing this will break the `exports of each format should work` e2e test, shouldn't be too hard to fix up and we can cross that bridge when we get to it.
But there's a whole 
```typescript
if (output.type === 'gltf' && output.storage === 'standard') {
// wait for second download
```
that will need to be removed.

**Comment by lf94** [comment]
Thanks for the heads-up!

**Comment by lf94** [comment]
This'll require a change somewhere on the server side to return a zip when appropriate.

**Comment by jessfraz** [comment]
No we want to handle it client side after we get the response.

**Comment by lf94** [comment]
Oh ok - I initially thought about doing it that way, but quickly I could see every single client needs to do then implement or include a zip package in order to offer the same functionality which doesn't seem great.

Are we concerned about returning a zip from the server too resource intensive or adding a complication over there?

**Comment by jessfraz** [comment]
We already use this endpoint as is in the diff viewer and cli and in text to cad ui, changing the whole endpoint just for modeling app makes no sense then all those apps would have to unzip to keep the same functionality

**Comment by lf94** [comment]
Gotchya gotchya. :slightly_smiling_face: Thanks for filling me in! I think it would make sense but it's a good argument to not create unnecessary toil at this stage :laughing:
