### ISSUE TITLE
things from @paultags riddle to track

### ISSUE THREAD

**Issue by jessfraz** [KittyCAD/modeling-app#1162]
1. mostly batch would have helped a bunch so #914 
2. when the model finally started rendering correctly for the code (no spoilers) it was out of view of the camera so would be nice to use the pan to object at start of render
3. the blur needs to go away when we have 1, was bad user experience
4. clear all at once

anything im forgetting @paultag @greg-kcio 

just wanted over all list to track

and we should add this file to tests for batch
[thing.txt](https://github.com/KittyCAD/modeling-app/files/13530990/thing.txt)

**Comment by paultag** [comment]
I think that was the big stuff, the focus one and time to render were the big things I was going to bring up off the back of this one, after that, I filed #1022 earlier which was related to this but mostly a design decision not a bug per se

**Comment by greg-kcio** [comment]
that's all of it

**Comment by jessfraz** [comment]
most of these are taken care of or have other issues
