### ISSUE TITLE
"[...] better as a desktop app!" modal is annoying

### ISSUE THREAD

**Issue by lf94** [KittyCAD/modeling-app#1197]
Every time when I see these two modals I find myself clicking "dismiss" first, followed by confusion, because it doesn't close.

The issue with this is the orange modal is overlaid on top of that one, so it needs to be dismissed first.

![1702343869](https://github.com/KittyCAD/modeling-app/assets/547923/f00d6fb4-5d6c-4bc8-a19d-199ee4c80837)

**Comment by franknoirot** [comment]
Yeah this has annoyed me too, thanks for logging it'll be very easy to make either be dismissible first
