### ISSUE TITLE
Clean up circular import dependencies

### ISSUE THREAD

**Issue by franknoirot** [KittyCAD/modeling-app#1203]
I [read here](https://github.com/vitejs/vite/issues/3033) that one of the reasons that hot module reloading isn't working reliably could be because of circular dependencies between React components. I installed [this VS Code extension](https://marketplace.visualstudio.com/items?itemName=iulian-radu-at.find-unused-exports) to check it out and sure enough there are a lot of circular dependencies in the app.

It'd be some pleasant work to clean them up, and I think there might be some larger benefits than just HMR working more nicely if we ensure there are none.

**Comment by jessfraz** [comment]
are we good here?

**Comment by franknoirot** [comment]
Yes, @Irev-Dev's work on singletons in https://github.com/KittyCAD/modeling-app/pull/1863
