### ISSUE TITLE
Migrate to xstate v5

### ISSUE THREAD

**Issue by Irev-Dev** [KittyCAD/modeling-app#1248]
Just finished with our migration to xstate and now have to migrate to a new version.
https://stately.ai/blog/2023-12-01-xstate-v5#migration-and-breaking-changes
But it does sound like there are plenty of improvements.

Migration guide is here.
https://stately.ai/docs/migration

I've not dug into it yet.

**Comment by davidkpiano** [comment]
Happy to help if you need.

**Comment by farskid** [comment]
Ok kicking off the migration discussion again. I just got access to the codebase and will share feedbacks and thoughts here.
