### ISSUE TITLE
Pasting error when trying to rotate view in Creo or NX controls.

### ISSUE THREAD

**Issue by jgomez720** [KittyCAD/modeling-app#1307]
Mentioned in Discord.

>When using Blender style controls (Creo or NX) If I have anything in my clipboard it will paste it into the code whenever I try to rotate the 3D view

This was on the web app.

v.0.14.0

**Comment by franknoirot** [comment]
Fascinating! That'll be interesting to look into

**Comment by jessfraz** [comment]
same as https://github.com/KittyCAD/modeling-app/issues/2285 closing this one as david gave better details
