### ISSUE TITLE
Unexpected Application Error (Position __ is out of range of length 171)

### ISSUE THREAD

**Issue by jgomez720** [KittyCAD/modeling-app#1335]
### Version
0.14.0

### Repeatable
Not easily repeatable

### Solutions
Refresh the app

### Problem

<img width="1582" alt="Screenshot 2024-01-29 at 11 40 01 AM" src="https://github.com/KittyCAD/modeling-app/assets/114548659/9d56663e-e1d7-49f0-a0b5-60a677589ecb">

Tauri App Console:
[Warning] Ignoring Event: localhost (script.js, line 1)
[Log] Full URL for WASM: tauri://localhost/wasm_lib_bg.wasm (index-1e6e8c59.js, line 1074)
[Log] Yu (index-1e6e8c59.js, line 1014)
[Error] error parsing code
Yu

kind: "syntax"

msg: "Unexpected token"

sourceRanges: [[359, 360]] (1)

Yu Prototype
	(anonymous function) (index-1e6e8c59.js:1014:198)
	safeParse (index-1e6e8c59.js:1131:6037)
	(anonymous function) (index-1e6e8c59.js:1131:3766)
	i (index-1e6e8c59.js:1074:35653)
	r (index-1e6e8c59.js:1028:1791)
[Log] connect was called (index-1e6e8c59.js, line 1014)
[Log] timeout set (index-1e6e8c59.js, line 1014)
[Log] engine connection is not ready (index-1e6e8c59.js, line 1014)
[Log] Connected to websocket, waiting for ICE servers (index-1e6e8c59.js, line 1014)
[Log] received ice_server_info (index-1e6e8c59.js, line 1014)
[Log] sent sdp_offer begin (index-1e6e8c59.js, line 1014)
[Log] received track – MediaStream (index-1e6e8c59.js, line 1014)
MediaStream
[Log] sending trickle ice candidate (index-1e6e8c59.js, line 1014)
[Log] accepted unreliable data channel – "unreliable_modeling_cmds" (index-1e6e8c59.js, line 1014)
[Log] unreliable data channel opened – Event (index-1e6e8c59.js, line 1014)
Event
[Log] sending command – "make_axes_gizmo" (index-1e6e8c59.js, line 1014)
[Log] sending command – "make_plane" (index-1e6e8c59.js, line 1014)
[Log] All spans finished, reporting (index-1e6e8c59.js, line 1014)
[Log] sending command – "plane_set_color" (index-1e6e8c59.js, line 1014)
[Log] sending command – "object_visible" (index-1e6e8c59.js, line 1014)
[Log] sending command – "make_plane" (index-1e6e8c59.js, line 1014)
[Log] sending command – "plane_set_color" (index-1e6e8c59.js, line 1014)
[Log] sending command – "object_visible" (index-1e6e8c59.js, line 1014)
[Log] sending command – "make_plane" (index-1e6e8c59.js, line 1014)
[Log] sending command – "plane_set_color" (index-1e6e8c59.js, line 1014)
[Log] sending command – "object_visible" (index-1e6e8c59.js, line 1014)
[Log] Yu (index-1e6e8c59.js, line 1014)
[Error] Unhandled Promise Rejection: [object Object]
	zf (index-1e6e8c59.js:1074:30356)
	executeCode (index-1e6e8c59.js:1147:37614)
	(anonymous function) (index-1e6e8c59.js:1065:5014)
[Log] sending command – "highlight_set_entity" (index-1e6e8c59.js, line 1014)
[Log] sending command – "camera_drag_start" (index-1e6e8c59.js, line 1014)
[Log] sending command – "camera_drag_move" (index-1e6e8c59.js, line 1014)
[Log] sending command – "default_camera_zoom" (index-1e6e8c59.js, line 1014)
[Log] sending command – "camera_drag_end" (index-1e6e8c59.js, line 1014)
[Log] sending command – "highlight_set_entity" (index-1e6e8c59.js, line 1014)
[Warning] Ignoring Event: localhost (index-1e6e8c59.js, line 1014, x2)
[Log] sending command – "select_clear" (index-1e6e8c59.js, line 1014)
[Log] sending command – "select_add" (index-1e6e8c59.js, line 1014)
[Log] sending command – "highlight_set_entity" (index-1e6e8c59.js, line 1014)
[Log] Yu (index-1e6e8c59.js, line 1014)
[Error] Yu
	(anonymous function) (index-1e6e8c59.js:1014:198)
	(anonymous function) (index-1e6e8c59.js:1131:3869)
	i (index-1e6e8c59.js:1074:35653)
	r (index-1e6e8c59.js:1028:1791)
[Warning] Ignoring Event: localhost (index-1e6e8c59.js, line 1014, x2)
[Log] sending command – "select_clear" (index-1e6e8c59.js, line 1014)
[Log] sending command – "select_add" (index-1e6e8c59.js, line 1014)
[Log] sending command – "highlight_set_entity" (index-1e6e8c59.js, line 1014)
[Log] sending command – "camera_drag_start" (index-1e6e8c59.js, line 1014)
[Log] sending command – "highlight_set_entity" (index-1e6e8c59.js, line 1014)
[Log] sending command – "camera_drag_start" (index-1e6e8c59.js, line 1014)
[Log] sending command – "camera_drag_end" (index-1e6e8c59.js, line 1014)
[Log] sending command – "highlight_set_entity" (index-1e6e8c59.js, line 1014)
[Warning] Ignoring Event: localhost (index-1e6e8c59.js, line 1014, x2)
[Log] sending command – "select_clear" (index-1e6e8c59.js, line 1014)
[Log] sending command – "select_add" (index-1e6e8c59.js, line 1014)
[Log] sending command – "highlight_set_entity" (index-1e6e8c59.js, line 1014)
[Error] RangeError: Position 276 is out of range for changeset of length 171
	(anonymous function) (index-1e6e8c59.js:1014:198)
	Ux (index-1e6e8c59.js:40:167)
	(anonymous function) (index-1e6e8c59.js:40:679)
	WI (index-1e6e8c59.js:38:9891)
	a3 (index-1e6e8c59.js:40:31902)
	l8 (index-1e6e8c59.js:40:31482)
	xq (index-1e6e8c59.js:40:31032)
	Pq (index-1e6e8c59.js:40:40920)
	Hc (index-1e6e8c59.js:40:40278)
	u3 (index-1e6e8c59.js:40:36888)
	Dc (index-1e6e8c59.js:38:3281)
	(anonymous function) (index-1e6e8c59.js:40:34266)
[Error] React Router caught the following error during render (2)
RangeError: Position 276 is out of range for changeset of length 171
Object
	(anonymous function) (index-1e6e8c59.js:1014:198)
	componentDidCatch (index-1e6e8c59.js:1122:3585)
	(anonymous function) (index-1e6e8c59.js:40:787)
	WI (index-1e6e8c59.js:38:9891)
	a3 (index-1e6e8c59.js:40:31902)
	l8 (index-1e6e8c59.js:40:31482)
	xq (index-1e6e8c59.js:40:31032)
	Pq (index-1e6e8c59.js:40:40920)
	Hc (index-1e6e8c59.js:40:40278)
	u3 (index-1e6e8c59.js:40:36888)
	Dc (index-1e6e8c59.js:38:3281)
	(anonymous function) (index-1e6e8c59.js:40:34266)
> Selected Element
< <h2>Unexpected Application Error!</h2>

**Comment by jessfraz** [comment]
has this happened again recently?

**Comment by jessfraz** [comment]
closing as we havent seen this in a while and i think a lot of the editor stuff fixed this
