### ISSUE TITLE
Add Samples to Modeling App

### ISSUE THREAD

**Issue by jgomez720** [KittyCAD/modeling-app#1350]
This would give users a button in which they can access our sample KCL files (pulls directly from kcl-samples repo). When user selects the option, they get prompted with "Are you sure you want to import the **sample code**? This will overwrite the code you currently have"

<img width="1582" alt="Screenshot 2024-02-06 at 12 02 00 PM" src="https://github.com/KittyCAD/modeling-app/assets/114548659/89209a34-cdb2-444f-a5b6-1d891439b2bc">

**Comment by jgomez720** [comment]
Having a direct import of the code would be great for the future, but I am fine settling with this for now:
https://github.com/KittyCAD/modeling-app/pull/1352

**Comment by franknoirot** [comment]
Yes, I think we could add an `Import example` command with the following arguments:
1. `method`: will be `new file` by default on desktop and can only be `overwrite` on web
2. `example`: will have a list of all the KCL samples from the repo as options. Will be used to fetch the actual code when executed

We'll hook up a confirmation dialog if the `method` is `overwrite`

**Comment by jgomez720** [comment]
Yeah this would be sick!
