### ISSUE TITLE
avoid a pipe with no %

### ISSUE THREAD

**Issue by jessfraz** [KittyCAD/modeling-app#1411]
we should fail in the parser if there is a `|>` with no following `%` in a function

for example the following code:

```
startSketchOn('XY')
    |> startProfileAt([pos[0] + radius, pos[1]], %)
    |> arc({
       angle_end: 360,
       angle_start: 0,
       radius: radius
     }, %)
    |> close(%)
    |> startSketchOn('XY')
    |> startProfileAt([pos[0] + radius, pos[1]], %)
    |> arc({
       angle_end: 360,
       angle_start: 0,
       radius: radius
     }, %)
    |> close(%)
```

in the above they are piping to anoteer start sketch on but that function is not taking the output, it doesnt do anything so people might think at the end of this the % references two sketch groups when in fact it only represents the last one.

having a parser error on the line without a % would avoid users mistakingly doing this

friend of mine actually tried this, not this exact code but something similar then went to extrude and was like why doesnt it extrude both. I dont think we should make it extrude both, i think it is an anti pattern we want to avoid with an error.

thoughts? @adamchalmers @Irev-Dev

**Comment by Irev-Dev** [comment]
Yeah I think that's a good idea, if your using a pipe without the %, than there's no point of the pipe in the first place, so I think an error is justified.

**Comment by jessfraz** [comment]
@adamchalmers i need some ideas on how best to parse this but i am getting better at winnow just this is advanced

**Comment by adamchalmers** [comment]
So currently the parser allows a lot of different values to be the steps in a pipeline, but afaict, it should only allow function calls (and those function calls must have a % in them).
