### ISSUE TITLE
UI Bugging out on MacOS

### ISSUE THREAD

**Issue by jgomez720** [KittyCAD/modeling-app#1437]
Reported by Patrick, one of our users. 

>Hey Josh,
>
>Nice to be in touch with you. I'm excited about what you're working on & the things to come.
>
>Heads-up—  I downloaded Zoo Modeling App on Mac OS (M1), but the UI seams to bug-out when I try to use it. Video attached.
>
>Cheers,
>Patrick

https://github.com/KittyCAD/modeling-app/assets/114548659/679ed54f-0c5b-4930-bd45-3c050b12026e

**Comment by Irev-Dev** [comment]
That's so bizarre.
We're all no macs right?
Is anyone able to replicate it?
I'm on a M1 chip too and have never seen anything like this.

**Comment by jgomez720** [comment]
Yeah I've never seen this either. What's strange is that his profile pic in the top-right isn't affected at all by it

**Comment by franknoirot** [comment]
Is it possible to ask Patrick what their [display accessibility settings are](https://support.apple.com/lv-lv/guide/mac-help/unac089/mac)? Is there any chance they have things like this set?
- Invert colors (smart)
- Increase contrast
- or some of their color filters?

I'll see if I can reproduce with any of those set

**Comment by franknoirot** [comment]
I can't seem to reproduce by toggling the accessibility settings 😕

**Comment by jessfraz** [comment]
can we ask patrick if its still happenign?

**Comment by jgomez720** [comment]
I can't seem to find this message on discord anywhere. Pretty certain he dm'd me this, but can't find it. Haven't seen this message nor anyone having the same issue. Closing
