### ISSUE TITLE
Show API version in UI

### ISSUE THREAD

**Issue by adamchalmers** [KittyCAD/modeling-app#144]
**Background**
I need to know which version of the API server untitled-app.kittycad.io is connected so, so I know which features will be working. The API itself has an endpoint which exposes information like server version, its git hash, etc. This information is at `GET /_meta/info` (defined [here](https://github.com/KittyCAD/api-deux/blob/20a3062b0881fa586da2a02b39b1d9283843e098/src/server/endpoints.rs#L147)) and is only available to kittycad employees.

**Problem**
Frontend doesn't show this information.

**Solution**
Frontend should GET `/_meta/info` and and display its output unobtrusively. Maybe show it in the bottom-right corner? Or maybe show it in a pop-over modal when users hit the ? key (or a ? button in the UI). Note that the API call will verify users are KittyCAD employees and return a HTTP 400 otherwise.

**Comment by jessfraz** [comment]
we have a lot of app info in the app now, not necessarily api version but i think we have enough to debug issues since api is main
