### ISSUE TITLE
Provide option to disable blinking cursor

### ISSUE THREAD

**Issue by alteous** [KittyCAD/modeling-app#1451]
There is a configuration option: https://codemirror.net/docs/ref/#view.drawSelection^config.cursorBlinkRate

**Comment by Irev-Dev** [comment]
Note we're actually using `@uiw/react-codemirror` but there should be away to pass config options through.

**Comment by Irev-Dev** [comment]
I think #2065 resolved this, 

Feel free to open again if I got that wrong.
