### ISSUE TITLE
Can't sketch on top of more than 1 face

### ISSUE THREAD

**Issue by lf94** [KittyCAD/modeling-app#1492]
I pulled the "box on a box" test from executor, and tried to do another extrusion on the top most box, but I get an error.

![out](https://github.com/KittyCAD/modeling-app/assets/547923/87068820-11ee-4850-bc92-faf7aa9d2063)

And the associated code:

```
      fn cube = (pos, scale) => {
  const sg = startSketchOn('XY')
    |> startProfileAt(pos, %)
    |> line([0, scale], %)
    |> line([scale, 0], %)
    |> line([0, -scale], %)

  return sg
}
const part001 = cube([0,0], 20)
    |> close(%)
    |> extrude(20, %)

const part002 = startSketchOn(part001, "end")
  |> startProfileAt([0, 0], %)
  |> line([0, 10], %)
  |> line([10, 0], %)
  |> line([0, -10], %)
  |> close(%)
  |> extrude(5, %)

const part003 = startSketchOn(part002, "end")
  |> startProfileAt([0, 0], %)
  |> line([0, 5], %)
  |> line([5, 0], %)
  |> line([0, -5], %)
  |> close(%)
  |> extrude(5, %)

```

**Comment by jessfraz** [comment]
ah okay this is engine side will file a bug there!

**Comment by jessfraz** [comment]
I have a test and some debugging here. https://github.com/KittyCAD/modeling-app/compare/main...sketch-on-face-of-face

**Comment by mlfarrell** [comment]
See final comment on https://github.com/KittyCAD/engine/issues/1790 for likely resolution

**Comment by mlfarrell** [comment]
also note that you (currently) cannot sketch on a face where the boundaries of the sub-sketch intersect (or touch) the boundaries of the outer sketch.  that'll create faces that are not properly mated and may have watertightness issues.
