### ISSUE TITLE
Disable Export button if engine connection is bad or scene is empty

### ISSUE THREAD

**Issue by franknoirot** [KittyCAD/modeling-app#1497]
Export relies on an engine connection so it shouldn't be available when the connection is down, and @JBEmbedded noted that it would probably be good to disable it if the scene is empty too since that doesn't really make sense.

This will be easier done if we can make the Export command a part of the modelingMachine, and will also make adding the Export command to the command bar easier. Although adding it to command bar is blocked by "Make command arguments able to be conditional based on argument values" (issue to be made).

**Comment by franknoirot** [comment]
Provisional assignment if you've got time @dshaw. Some additional context:
1. We have made [Export a modelingMachine event](https://github.com/KittyCAD/modeling-app/blob/main/src/machines/modelingMachine.ts#L210-L215) since this issue was made
2. We have also added this Export to the command bar as a result. Its command bar config is defined [here](https://github.com/KittyCAD/modeling-app/blob/main/src/lib/commandBarConfigs/modelingCommandConfig.ts#L40-L113) and those commands are loaded into the command bar [here](https://github.com/KittyCAD/modeling-app/blob/main/src/components/ModelingMachineProvider.tsx#L529-L537)
3. The Export button lives [here in the ProjectSidebarMenuPopover component](https://github.com/KittyCAD/modeling-app/blob/main/src/components/ProjectSidebarMenu.tsx#L176-L189). The button just opens the command bar and selects the Extrude command from it.

Because the modelingMachine's command bar commands are flagged with [`allCommandsRequireNetwork` here](https://github.com/KittyCAD/modeling-app/blob/main/src/components/ModelingMachineProvider.tsx#L535) I think we already fulfill the "if engine connection is bad" part of the requirements, but you should double check my understanding.

However, I don't think we yet satisfy the "or scene is empty" requirement of this issue. Here's an idea of what you could do:
1. add [an optional `hideFn` prop to the Command type](https://github.com/KittyCAD/modeling-app/blob/main/src/lib/commandTypes.ts#L78) that takes the a function passing in the state machine's actor as an argument and returns a boolean (type `(actor: AnyActor) => boolean`)
2. add logic to filter based on it if it is defined for a given Command while processing in [useStateMachineCommands](https://github.com/KittyCAD/modeling-app/blob/main/src/hooks/useStateMachineCommands.ts#L60-L61)
3. augment the Export command's config to have a `hideFn` of its own that returns `false` if the modelingMachine has no code.

**Comment by jessfraz** [comment]
I dont think we should hide or diable I think thatys kinda confusing I would lean towards a way that also explains why, like a toast popup saying "your internet is bad" or "scene is empty" is so much better, most people using the app are always super confused why they can't use a button but its there

**Comment by dshaw** [comment]
As @franknoirot mentions, exporting bad engine connection is already disabled. We might want to create an issue to address notifying the user when their connection is bad and they find a disabled button. That should prevent interaction with the button, but we still might be able to detect events.

**Comment by franknoirot** [comment]
Fair point @jessfraz yeah maybe short circuiting and error toasting is the way to go. I just don't want users to have to step through the export steps in the command bar to discover the error via toast.

**Comment by jessfraz** [comment]
Well it could be immediately instead if we check network on clickOn May 23, 2024, at 08:09, Frank Noirot ***@***.***> wrote:﻿
Fair point @jessfraz yeah maybe short circuiting and error toasting is the way to go. I just don't want users to have to step through the export steps in the command bar to discover the error via toast.
