### ISSUE TITLE
Add support for snap-to-horizontal and snap-to-vertical

### ISSUE THREAD

**Issue by franknoirot** [KittyCAD/modeling-app#1498]
Automatically apply horizontal and vertical constraints if the user is drawing straight segments and the uncommitted line's angle is near vertical or horizontal.

## Engine notes
None
## API/KCL notes
We have KCL standard library functions for horizontal and vertical lines, [`xLine`](https://zoo.dev/docs/kcl/xLine) and [`yLine`](https://zoo.dev/docs/kcl/yLine).
## Point-and-click notes
1. The snapping logic will live somewhere in `sceneEntities.ts` in an `onMove` listener
2. You will be changing the code mod that gets applied from a `line()` function to the respective function mentioned above
3. The sketch scene already has logic to handle these functions, so everything after the line is placed—such as dragging behavior—will "just work"
4. As noted by Jess below, adding a listener for the <kbd>Alt/Option</kbd> could be useful to allow the user to opt out of this snapping behavior. Not all CAD tools have this option so it is not required for a first pass

**Comment by jessfraz** [comment]
if you are drawing close enough to horizontal it should snap, feedback from jordan, default do the snapping, then when you hold alt + shift it lets you freely move, so kinda the opposite this is originally worded

parallel as well

**Comment by franknoirot** [comment]
This was completed with #4465
