### ISSUE TITLE
`tag` field is required in kcl function `angledLine()` but doesn't need to be

### ISSUE THREAD

**Issue by franknoirot** [KittyCAD/modeling-app#1499]
The [angledLine](https://github.com/KittyCAD/modeling-app/blob/main/docs/kcl/std.md#angledLine) function's `tag` parameter should probably be optional, since the function also accepts an array of 2 numbers which I assume are the angle and the length.

Here's the error I get in modeling app:

![Screenshot 2024-02-23 at 10 33 03 AM](https://github.com/KittyCAD/modeling-app/assets/23481541/37cbc3d6-78c1-4a53-bb75-bbcad54ec0bd)

**Comment by Irev-Dev** [comment]
I might be wrong, but I think this might be made redundant by #1006

**Comment by franknoirot** [comment]
That makes sense, I'll close this as duplicate
