### ISSUE TITLE
Strange UI Sizing Bug

### ISSUE THREAD

**Issue by jgomez720** [KittyCAD/modeling-app#1505]
A few things are happening here
- The stream is clipped on the top and the bottom.
- The grid disappears  as I'm using the modeling app for some reason
- Console doesn't show any errors

https://github.com/KittyCAD/modeling-app/assets/114548659/b16fabc6-bebe-4242-bc91-cc2ff2dcf8c2

**Version**
v0.15.2

**Solution**
Reloading

**Comment by jgomez720** [comment]
More information. This seems to happen when I close my laptop and come back and reload.

<img width="1582" alt="Screenshot 2024-02-23 at 12 42 36 PM" src="https://github.com/KittyCAD/modeling-app/assets/114548659/4d20154d-84db-4f28-aa87-d9b8803cc1fe">

**Comment by franknoirot** [comment]
Hm I don't know much about this part, it seems like a stream/engine connection issue, so I've tagged @lf94 and @Irev-Dev

**Comment by lf94** [comment]
Yep. I suspect Kurt had visibility on this and is hammering it out in that PR

**Comment by jessfraz** [comment]
considering this happens on laptop close im throwing this into idle https://github.com/KittyCAD/modeling-app/issues/563
