### ISSUE TITLE
Edges Appearing as Squiggles

### ISSUE THREAD

**Issue by jgomez720** [KittyCAD/modeling-app#1506]
I started the video expecting a different bug and then got this instead

https://github.com/KittyCAD/modeling-app/assets/114548659/d5e3b3c2-55bc-4604-b75a-94fe0aa471df

**Comment by mlfarrell** [comment]
@jgomez720 is this a consistently reproducible situation?  I haven't been able to reproduce this in pure engine yet.

![image](https://github.com/KittyCAD/modeling-app/assets/7664370/3b8e2aa1-a4b0-4c4c-9eb8-f3e4e92f1eda)

**Comment by mlfarrell** [comment]
also not producable on prod.    I suspect the frontend may have been doing something out of order during your test.  If we can find a way to consistently reproduce it, i'd like to know the API commands being sent.

![image](https://github.com/KittyCAD/modeling-app/assets/7664370/10e50b26-9526-4c53-9d9d-784737235f7b)

**Comment by jessfraz** [comment]
@jgomez720 please close if no longer an issue

**Comment by jgomez720** [comment]
Yeah I haven't seen this in a while. Closing
