### ISSUE TITLE
Sketch on Face creating red edges

### ISSUE THREAD

**Issue by jgomez720** [KittyCAD/modeling-app#1508]
I'm not sure what these red edges are for. They only show up once I do an extrude off a face

https://github.com/KittyCAD/modeling-app/assets/114548659/c47969e0-e5bf-4646-b0a7-90673a7c626c

**Comment by jessfraz** [comment]
They mean that when you export you wont get a brep thats one item, remember that bug for when its outside the bounds

noted here: https://github.com/KittyCAD/modeling-app/blob/main/docs/kcl/KNOWN-ISSUES.md

**Comment by jessfraz** [comment]
closing sincce its engine side and a known issue

**Comment by jgomez720** [comment]
ahhh okay. Thank you
