### ISSUE TITLE
Stream fails to reconnect after closing laptop and reopening

### ISSUE THREAD

**Issue by jgomez720** [KittyCAD/modeling-app#1509]
Closing my laptop for a couple minutes and opening it back up to the modeling app causes the stream to fail to reconnect. I have to reload in order to get it back.

**Version**
v0.15.2

**MacOS Version**
14.1.2

<img width="1582" alt="Screenshot 2024-02-23 at 12 39 56 PM" src="https://github.com/KittyCAD/modeling-app/assets/114548659/ff5957c7-0e73-4b68-b360-5becbfc6a9df">

**Comment by jessfraz** [comment]
same as https://github.com/KittyCAD/modeling-app/issues/563
