### ISSUE TITLE
Change cursor when a sketch tool is equipped

### ISSUE THREAD

**Issue by franknoirot** [KittyCAD/modeling-app#1522]
Here is an example from Figma:

When general selection/move is equipped:
![Screenshot 2024-02-26 at 12 39 30 PM](https://github.com/KittyCAD/modeling-app/assets/23481541/9a21ee01-f212-4de5-a10f-d27d42aefd75)

With a geometry-creating tool equipped, such as Rectangle:
![Screenshot 2024-02-26 at 12 39 53 PM](https://github.com/KittyCAD/modeling-app/assets/23481541/43b07a97-005d-4fc4-9ceb-7f80c9968a7c)

The crosshair shape visually centers the point at which the user will click to lay their first corner.

There is a [CSS `cursor: crosshair`](https://developer.mozilla.org/en-US/docs/Web/CSS/cursor) value that we can use.

**Comment by Irev-Dev** [comment]
Oh dope, this will be an easy one, should just be a cursor depends on xstate state deal.

**Comment by Irev-Dev** [comment]
We needed this sooner than we thought, so this got closed out by https://github.com/KittyCAD/modeling-app/pull/1995
