### ISSUE TITLE
Make option to format KCL code automatically

### ISSUE THREAD

**Issue by greg-kcio** [KittyCAD/modeling-app#1530]
Currently, the KCL autoformatter will (sometimes?) run when I load a project. We should be able to configure when the formatter runs, e.g. on project load, on project save (manual save not supported yet), or not at all.

**Comment by greg-kcio** [comment]
💯 for having an opinionated formatter. I would normally choose to have it run automatically. Today I'd want to trigger it manually only because formatting is not working the way I expect, see https://github.com/KittyCAD/modeling-app/issues/1532

**Comment by jessfraz** [comment]
Does this matter now that I fixed the formatting bugs?

**Comment by greg-kcio** [comment]
> Does this matter now that I fixed the formatting bugs?

Na let's close now that #1532 and #1533 are fixed, there is no drawback to formatting.

**Comment by jessfraz** [comment]
I was not pressuring you to close! but yeah lmk if you find weird formatting things, easy to fix / add regression tests for
