### ISSUE TITLE
Lines are not showing up in a new sketch

### ISSUE THREAD

**Issue by jgomez720** [KittyCAD/modeling-app#1544]
### Version 
v0.15.2

### Description
When selecting "Start Sketch", I am clicking in the UI and the lines are appearing in the code field, but there are no lines shown.  Once I open up the console, you can see that the lines show up.

https://github.com/KittyCAD/modeling-app/assets/114548659/e19e6f31-536c-446a-b66f-104a0fd43856

**Comment by Irev-Dev** [comment]
So I think this bug has been fixed, let me check by asking a couple of questions.

Is the steps to replicate that you start sketching fairly zoomed out. i.e. the scale is 10cm or greater, but below that it's fine? Is this something that you can't replicate on app.zoo.dev?

If yes to both of the above, then we just need to cut a release.

If no to either of them, could you give me steps to replicate, as I'm not able to on main, just from the video.

**Comment by jgomez720** [comment]
I will take a look and let you know

**Comment by jgomez720** [comment]
The answer is yes to both above so I will close. Fixed in the upcoming release.

**Comment by Irev-Dev** [comment]
Awesome!
