### ISSUE TITLE
Add tags to close statement

### ISSUE THREAD

**Issue by jgomez720** [KittyCAD/modeling-app#1545]
Currently, we cannot add tags to the `close(%)` statement. We need this to be able to sketch off that face. See example below.

**KCL**
```
const box_width = 20
const box_length = 12
const box_height = 6

const part001 = startSketchOn('XY')
  |> startProfileAt([-box_width / 2, box_length / 2], %)
  |> line([box_width, 0], %)
  |> line([0, -box_length], %)
  |> line({ to: [-box_width, 0], tag: 'face01' }, %)
  |> close(%)
  |> extrude(box_height, %)
```

How would I access face 4 in this example?
![Screenshot 2024-02-27 at 11 21 42 AM](https://github.com/KittyCAD/modeling-app/assets/114548659/de6f3d0c-b4c4-4c7a-8fd5-0a4942f44def)

**Comment by jessfraz** [comment]
we need https://github.com/KittyCAD/engine/issues/1832 for this to work
