### ISSUE TITLE
core dump from settings and hot key

### ISSUE THREAD

**Issue by jessfraz** [KittyCAD/modeling-app#1573]
we should allow a user to "core dump" the app information into a zip file from the settings

HOTKEY is `command` + `shift` + `.`

this information should include:

- [x] version of the app
- [x] operating system
- [x] https://github.com/KittyCAD/modeling-app/issues/2338
- [x] a screenshot of the current app at time of hot key for core dump
- [x] auto populate gh issue
- [ ] https://github.com/KittyCAD/modeling-app/issues/2738
- [x] make work in editor
- [x] console log

cc @franknoirot @Irev-Dev for any other relevant state and @paultag for any webrtc data we might want to collect

then users can just upload this data to github and we can look it over, will make our lives so much easier

**Comment by paultag** [comment]
Core must-have WebRTC metrics I'd love in a tombstone like this via the WebRTC metrics JavaScript stubs:

 - packetsLost
 - framesReceived/s
 - frameWidth
 - frameHeight
 - framesPerSecond
 - keyFramesDecoded
 - framesDropped
 - pauseCount
 - totalPausesDuration
 - freezeCount
 - totalFreezesDuration
 - pliCount

I don't know offhand how to get the following (but I want to see if we can):

  - decoderImplementation
  - powerEfficientDecoder

**Comment by paultag** [comment]
Specific javascript breadcrums for the above:

We likely need to pull the [RTCStatsReport](https://developer.mozilla.org/en-US/docs/Web/API/RTCStatsReport) via the [RTCPeerConnection.getStats()](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/getStats) call, which is accessible from `this.pc?` and `this.mediaStream` in `engineConnection.js`; an example of collecting some of the stats we report via the WebSocket connection is [here](https://github.com/KittyCAD/modeling-app/blob/main/src/lang/std/engineConnection.ts#L386-L437)

**Comment by Irev-Dev** [comment]
There should be a way to grab all fo the xstate history, 
There are a few singleton classes that are probably easy to just serialise and dump out as well.

**Comment by dshaw** [comment]
`EngineCommandManager` singleton implemented in the branch [coredump-clientstate](https://github.com/KittyCAD/modeling-app/tree/coredump-clientstate)

**Comment by dshaw** [comment]
I'm pretty sure the last item, `console.log`, is fully implemented in https://github.com/KittyCAD/modeling-app/pull/2653. To validate. Open the developer console in the browser, then trigger a core dump with `Shift-META-.`. There are a couple console entries that let you know that things are happening. If there are any errors, that will output to the console. When the core dump is complete a JavaScript object representation of the core dump is logged followed by a stringified version which can be copied directly from the console and inspected.

I went ahead and ticked it off. Please revert if there are any further expectations not fulfilled in the [v0.22.3 release](https://github.com/KittyCAD/modeling-app/releases/tag/v0.22.3).

@jessfraz Did you have anything else in mind?

**Comment by jessfraz** [comment]
the last thing (integrating into the button) has its own issue so ill close this thanks @dshaw !
