### ISSUE TITLE
speed up code-mirror parsing

### ISSUE THREAD

**Issue by Irev-Dev** [KittyCAD/modeling-app#1614]
if you watch the playwright test `if you write invalid kcl you get inlined errors` in headed mode, it seems to run far slower than it should.

The errors that it's showing are parsing errors, which should be fast af, so something is slowing it down, we suspect that it's the debounced execution that we have in the code-mirror editor.

If that's the case, we can fix it by eagerly parsing the user's code, while still debouncing the execution.

**Comment by jessfraz** [comment]
did this get any better w the editor refactors? we should be able to make it a lot faster now, will play around

**Comment by Irev-Dev** [comment]
I think this is a non-issue, it still waits for the debounce time out, i.e.:

https://github.com/user-attachments/assets/d983d9b1-efc6-4eb9-9eb3-f395a222f7c8

But after that, it's plenty fast, and the errors waiting until the user is done typing is probably the correct behaviour anyway.
