### ISSUE TITLE
🧙 Port ast-mods from TS to Rust 🦀 

### ISSUE THREAD

**Issue by Irev-Dev** [KittyCAD/modeling-app#163]
- [x] Tokeniser
- [x] Recaster
- [x] Parser(abstractSyntaxTree.ts)
- [x] Executor  
- [ ] Ast-Mod utils (`src/lang/queryAst.ts` and `src/lang/modifyAst.ts`)

Original description
---
The language has partly been ported to rust, that is the [tokeniser](https://github.com/KittyCAD/untitled-lang/pull/28).

<img width="1299" alt="image" src="https://github.com/KittyCAD/untitled-lang/assets/29681384/99edfff0-db86-4159-9abf-e4d24160de7c">

However the tokeniser was very much the lowest of hanging fruit, here's why. The next best candidates for porting would be `abstractSyntaxTree.ts`, `executor.ts` or `recast.ts`, with recast probably being the best of the three. However because all three of these deal with the AST datastructure, really need equivalent typing of the data structure on both sides (i.e. rust as well)

- So the first step would be to create equivalent AST types in rust ([TS types here](https://github.com/KittyCAD/untitled-lang/blob/main/src/lang/abstractSyntaxTree.ts))
- An optional step might be to then have TS types generated from the new rust types so we can throw away the TS manual types and not have to keep the two in sync
- Than port recast.ts to rust (it's < 300 lines)

**Comment by jessfraz** [comment]
i think we decided ts is better for these w plugins etc, reopen if otherwise
