### ISSUE TITLE
Add support for dropdowns for tools

### ISSUE THREAD

**Issue by franknoirot** [KittyCAD/modeling-app#1645]
In order to make the toolbar stay dense we are considering implementing dropdowns for toolbar buttons.

Here is a mockup of how that would look:

![Flow 02 Step 2](https://github.com/KittyCAD/modeling-app/assets/23481541/a6bcde5b-4fd5-4585-b65c-e58a4d4970a1)

That is taken from [this flow in Figma](https://www.figma.com/file/5UUPOawPLEs3D0Gptf42vy/Designs?type=design&node-id=1626-28742&mode=design&t=6Hsu8NAuz1eVI6bD-11) for how a three-point arc tool would work.

**Comment by jessfraz** [comment]
we seem to have dropdowns now so closing but let me know if otherwise, constraints is a dropdown
