### ISSUE TITLE
Shorten Changelog for Tauri App

### ISSUE THREAD

**Issue by jgomez720** [KittyCAD/modeling-app#1663]
## Description
When opening the Tauri app, the user will be prompted to update to the newest version of the Modeling App. If the change log is too large, the user can't select "Yes" in the pop-up window.

## Version 
v0.15.5

## Resolution
I had to rotate my display by 90 degrees to see the "yes" button. It would probably help to truncate the changelog, and give a link or say "see full changelog in the settings" for something like this.

## Screenshots
**Changelog**
![Screenshot 2024-03-06 at 12 06 25 PM](https://github.com/KittyCAD/modeling-app/assets/114548659/f4ec69ac-3402-4416-9828-ece7b71e70ac)

This is on my 1920 x 1080 screen. You can see that it's cut off on the bottom.
![Screenshot 2024-03-06 at 12 08 06 PM](https://github.com/KittyCAD/modeling-app/assets/114548659/60c96d17-1cd2-4e7f-bdab-912678f369a4)

I had to rotate my display 90 degrees to see the "yes" button
![Screenshot 2024-03-06 at 12 10 17 PM](https://github.com/KittyCAD/modeling-app/assets/114548659/f64c886d-a5ff-4d23-9467-c01241c95037)

**Comment by Irev-Dev** [comment]
This is me being lazy and using the auto-generate notes. 🤦 sorry.

I just kinda thing doing patch releases should be hassle free and easy to do. But that does seem like a problem, I might use an llm to summarise next time.

**Comment by jessfraz** [comment]
unless we error or something

**Comment by Irev-Dev** [comment]
Probably good to get @pierremtb's thoughts.

**Comment by pierremtb** [comment]
Sounds like a good long term fix would be to have a custom dialog https://tauri.app/v1/guides/distribution/updater/#custom-dialog. The tauri API provides the required hooks

**Comment by pierremtb** [comment]
@Irev-Dev @franknoirot Might be worth noting that the API changes a bit when moving to tauri v2, as things like updater moved into separate plugins https://github.com/tauri-apps/plugins-workspace/blob/v2/plugins/updater/src/updater.rs.

But shouldn't be a huge lift, we can have it on `main` first and then I'll port it in #1400

**Comment by franknoirot** [comment]
I can mock a simple dialog up, and for now all it'll give us is nicer branding and a scrollable, collapsible Release Notes section, but in future it'll be nice to have something we can make more sophisticated.

**Comment by pierremtb** [comment]
Alright branch created. Got a functional thing going on a branch (which is on purpose 2 versions late). Now let's make it pretty!

<img width="1710" alt="image" src="https://github.com/KittyCAD/modeling-app/assets/10795683/1ab921d0-17a3-41c3-afe0-2f37373823f9">
