### ISSUE TITLE
patternLinear remains when switching to another file

### ISSUE THREAD

**Issue by jgomez720** [KittyCAD/modeling-app#1667]
## Description
I was working on a gear rack that uses a `patternLinear` function. I went back to the main file menu, selected my bracket.kcl file, and the patternLinear rendering remained in the stream. It was there before the bracket even rendered.

## Version
v0.15.5 - Tauri App

## Repeatable?
For this session, yes. I can open up any file right now and the `patternLinear` is still there.

## Screenshots
So this is what I was working on first
![Screenshot 2024-03-07 at 2 11 02 PM](https://github.com/KittyCAD/modeling-app/assets/114548659/38774aed-be3e-4810-aee0-b4eeafdd396d)
**KCL**
```
// 100mm Gear Rack
// a flat bar or rail that is engraved with teeth along its length. These teeth are designed to mesh with the teeth of a gear, known as a pinion. When the pinion, a small cylindrical gear, rotates, its teeth engage with the teeth on the rack, causing the rack to move linearly. Conversely, linear motion applied to the rack will cause the pinion to rotate.

// Define constants
const length = 100
const pitch_height = 11.5
const width = 5
const height = 12
const min_height = 10.875

// Create the body of the rack
const rackBody = startSketchOn('XY')
  |> startProfileAt([-length / 2, 0], %)
  |> line([length, 0], %)
  |> line([0, min_height], %)
  |> line([-length, 0], %)
  |> close(%)
  |> extrude(width, %)

// Create a function for sketch of a single tooth
fn tooth = () => {
  const toothSketch = startSketchOn('XY')
  |> startProfileAt([-length / 2 + 0.567672, min_height], %)
  |> tangentialArc([0.157636, 0.110378], %)
  |> line([0.329118, 0.904244], %)
  |> tangentialArc([0.157636, 0.110378], %)
  |> line([0.186505, 0], %)
  |> tangentialArc([0.157636, -0.110378], %)
  |> line([0.329118, -0.904244], %)
  |> tangentialArc([0.157636, -0.110378], %)
  |> close(%)
  |> extrude(width, %)
  return toothSketch
}

// Pattern the single tooth over the length of the rack body
const teeth = tooth()
  |> patternLinear({
       axis: [10, 0],
       distance: 1.570796,
       repetitions: 62
     }, %)

// Sketch and extrude the first end cap. This is a partial tooth
const endCapTooth = startSketchOn('XY')
  |> startProfileAt([-length / 2, 11.849525], %)
  |> line([0.314524, -0.864147], %)
  |> tangentialArc([0.157636, -0.110378], %)
  |> lineTo([-length / 2, min_height], %)
  |> close(%)
  |> extrude(width, %)

//Sketch and extrude the second end cap. This is a partial tooth
const endCapTooth2 = startSketchOn('XY')
  |> startProfileAt([length / 2, 11.849525], %)
  |> line([-0.314524, -0.864147], %)
  |> tangentialArc([-0.157636, -0.110378], %)
  |> lineTo([length / 2, min_height], %)
  |> close(%)
  |> extrude(width, %)
```

Then, I went back to the main menu, selected Bracket, and it rendered this
![Screenshot 2024-03-07 at 2 08 02 PM](https://github.com/KittyCAD/modeling-app/assets/114548659/ea546a32-a1d4-4497-8f07-4704b151b758)
**KCL**
```
// Bracket
// This is a bracket that holds a shelf. It is made of aluminum and is designed to hold a force of 150 lbs. The bracket is 6 inches wide and the force is applied 6 inches from the wall. The bracket has a factor of safety of 20. The legs of the bracket are 5 inches and 8 inches long. The bracket is 1/4 inch thick. What is the minimum thickness of the bracket?

// define constants
const sigmaAllow = 15000 // psi
const width = 6 // inch
const p = 150 // Force on shelf - lbs
const distance = 6 // inches
const FOS = 20
const leg1 = 5 // inches
const leg2 = 8 // inches

// calculate required thickness of bracket
const thickness = sqrt(distance * p * FOS * 6 / (sigmaAllow * width))
const bracket = startSketchAt([0, 0])
  |> line([0, leg1], %)
  |> line([leg2, 0], %)
  |> line([0, -thickness], %)
  |> line([-1 * leg2 + thickness, 0], %)
  |> line([0, -1 * leg1 + thickness], %)
  |> close(%)
  |> extrude(width, %)
```

Shows up in any file
![Screenshot 2024-03-07 at 2 14 07 PM](https://github.com/KittyCAD/modeling-app/assets/114548659/e7a16dd5-2c17-44df-9c5e-f27a85339ddf)

**Comment by jgomez720** [comment]
Sorry @Irev-Dev I tend to assign you first if I don't know who the issue belongs to, so please reassign if needed. @gserena01 I brought you in just in case this is specific to `patternLinear`

**Comment by Irev-Dev** [comment]
This is definitely a me problem, I've removed @gserena01.

This is most likely a clean up problem, I just checked and it does successfully clean up on re-execute, but obviously, it's different code-path for changing files. (I'll try and unify it when I fix this).

for context, I have to loop through everything we've added to scene and remove it before starting with the next execution. And I have to make sure to delete only certain types of files (other wise the engine returns errors), we really need a "nuke all" endpoint, because this is a source of bugs.

**Comment by jessfraz** [comment]
actually the nuke all endpoint seeem great for @gserena01 to implement I've had it on my list for a while but i havent gotten to it!

**Comment by Irev-Dev** [comment]
Yeah cool!

**Comment by Irev-Dev** [comment]
Engine clear all endpoint will make this much easier to fix

https://github.com/KittyCAD/engine/pull/1864
