### ISSUE TITLE
getOppositeEdge() not executing properly

### ISSUE THREAD

**Issue by jgomez720** [KittyCAD/modeling-app#1675]
## Description
When using the getOppsositeEdge() function for filleting, it is not executing as expected. You'll see in the video I replace all of them with getNextAdjacentEdge() and they execute no problem (albeit, it doesn't look pretty, but it still renders properly).

Note: the rest of the code is no issue, I did the filleting last.

## Version
v0.15.6 - web app

## Screenshots/videos
https://github.com/KittyCAD/modeling-app/assets/114548659/9f9928ba-8025-4ca6-8630-2bc57b1e795c

**Update**
I noticed in the video I use a radius of 4, so I reduced this down to 0.25, and it renders the first edge and nothing else.
<img width="1581" alt="Screenshot 2024-03-08 at 9 19 15 AM" src="https://github.com/KittyCAD/modeling-app/assets/114548659/775c6a8c-ac3d-4b53-aaa2-de7b0dc1c888">

**Comment by jessfraz** [comment]
What’s the error say that it is throwing

**Comment by jessfraz** [comment]
I think it’s likely that fillets next to each other doesn’t work yet so you get a fillet error. It is def throwing an error

**Comment by jgomez720** [comment]
<img width="558" alt="Screenshot 2024-03-08 at 10 07 05 AM" src="https://github.com/KittyCAD/modeling-app/assets/114548659/b9822a74-7c5f-4e74-893d-239f8c9dcbd5">

Also, @franknoirot, can we have the KCL errors scrollable? I can't see the errors if I open all the objects within the pane, it exceeds lower than the screen. I also cannot copy and paste the information (hence the screenshot above).

Forgot to include the KCL
```
const l1 = 10
const l2 = 10
const arcR = 2
const footH = 3.5
const bodyHeight = 2.5
const filletRadius = 0.25

fn kittLeg = (sk1, sk2) => {
  const legExtrude = startSketchAt([sk1, sk2])
  |> line([3, 0], %)
  |> line([0, -3], %)
  |> line([-3, 0], %)
  |> close(%)
  |> extrude(bodyHeight, %)
  return legExtrude
}

fn kittEar = (sk1, sk2) => {
  const earExtrude = startSketchAt([sk1, sk2])
  |> bezierCurve({
       control1: [0, 3],
       control2: [3, 3],
       to: [3, 0]
     }, %)
  |> close(%)
  |> extrude(bodyHeight, %)
  return earExtrude
}

fn kittFoot = (sk1, sk2) => {
  const footExtrude = startSketchAt([sk1, sk2])
  |> line([3, 0], %)
  |> line([0, -1.5], %)
  |> line([-3, 0], %)
  |> close(%)
  |> extrude(footH, %)
  return footExtrude
}

const kittBody = startSketchAt([0, 0])
  |> line({to: [0, l1], tag: 'fillet1'}, %)
  |> line({to: [l2, 0], tag: 'fillet2'}, %)
  |> line({to: [0, -l1], tag: 'fillet3'}, %)
  |> close(%, 'fillet4')
  |> extrude(bodyHeight, %)
  |> fillet({
       radius: 0.25,
       tags: [
  getOppositeEdge('fillet1', %),
  getOppositeEdge('fillet2', %),
  getOppositeEdge('fillet3', %),
  getOppositeEdge('fillet4', %)
]
     }, %)

const leg1 = kittLeg(1, 0)
const leg2 = kittLeg(6, 0)
const ear1 = kittEar(1, 10)
const ear2 = kittEar(6, 10)
const foot1 = kittFoot(1, -3)
const foot2 = kittFoot(6, -3)

const face = startSketchOn(kittBody, 'end')
  |> startProfileAt([1, 1], %)
  |> line([l1 - 2, 0], %)
  |> line([0, l2 - 2], %)
  |> line([(-l1+2), 0], %)
  |> close(%)
  |> extrude(-.5, %)

fn button = (start1, start2, w, l, h) => {
  const buttonSketch = startSketchOn(kittBody, 'end')
  |> startProfileAt([start1, start2], %)
  |> line([w, 0], %)
  |> line([0, l], %)
  |> line([-w, 0], %)
  |> close(%)
  |> extrude(h, %)
  return buttonSketch
}

const button1 = button(0.25, 0.25, 1, .25, .125)
const button2 = button(2, 0.25, 1, .25, .125)
const button3 = button(3.75, 0.25, 1, .25, .125)
```

**Comment by jessfraz** [comment]
Just try to fillet one edge, those are next to each other I think that’s why it’s failing. We have no fillet intersections yet

**Comment by jessfraz** [comment]
Or try two not next to each other

**Comment by jessfraz** [comment]
the problem is they intersect i need to add to known-issues

https://github.com/KittyCAD/modeling-app/assets/1445228/d2d67b48-6b9f-4db0-8f11-8b7c2d0e072d
