### ISSUE TITLE
angledLineOfLength advertised in code completion but not available

### ISSUE THREAD

**Issue by mlfarrell** [KittyCAD/modeling-app#1692]
![image](https://github.com/KittyCAD/modeling-app/assets/7664370/f597db5f-6a3a-48b8-bc8d-093f315a31c9)

**Comment by jessfraz** [comment]
I see the XLength and YLength one but not angledLineOfLength

https://github.com/KittyCAD/modeling-app/assets/1445228/dba7de43-96d3-42ef-a345-3841d3e45080
