### ISSUE TITLE
Grackle: port stdlib

### ISSUE THREAD

**Issue by adamchalmers** [KittyCAD/modeling-app#1727]
The current executor supports around 66 stdlib calls. Currently, only `startSketchAt`, `extrude`, `close` and `lineTo` have been ported to Grackle. Port the rest.

- [x] abs (@lf94 https://github.com/KittyCAD/modeling-api/pull/222)
- [x] acos (@lf94 https://github.com/KittyCAD/modeling-api/pull/222)
- [ ] angleToMatchLengthX
- [ ] angleToMatchLengthY
- [ ] angledLine (@lf94 https://github.com/KittyCAD/modeling-app/pull/1787)
- [ ] angledLineOfXLength (@lf94 https://github.com/KittyCAD/modeling-app/pull/1787)
- [ ] angledLineOfYLength (@lf94 https://github.com/KittyCAD/modeling-app/pull/1787)
- [ ] angledLineThatIntersects
- [ ] angledLineToX (@lf94 https://github.com/KittyCAD/modeling-app/pull/1787)
- [ ] angledLineToY (@lf94 https://github.com/KittyCAD/modeling-app/pull/1787)
- [ ] angledLineToX (original) -> angledLineX (@lf94 https://github.com/KittyCAD/modeling-app/pull/1787)
- [ ] angledLineToY (original) -> angledLineY (@lf94 https://github.com/KittyCAD/modeling-app/pull/1787)
- [ ] arc (@lf94)
- [x] asin (@lf94 https://github.com/KittyCAD/modeling-api/pull/222)
- [x] atan (@lf94 https://github.com/KittyCAD/modeling-api/pull/222)
- [ ] bezierCurve
- [x] ceil (@lf94 https://github.com/KittyCAD/modeling-api/pull/222)
- [ ] circle (@lf94)
- [x] close
- [x] cos (@lf94 https://github.com/KittyCAD/modeling-api/pull/222)
- [x] e (@lf94 https://github.com/KittyCAD/modeling-api/pull/231)
- [x] extrude
- [ ] fillet
- [x] floor (@lf94 https://github.com/KittyCAD/modeling-api/pull/222)
- [ ] getExtrudeWallTransform
- [ ] getNextAdjacentEdge
- [ ] getOppositeEdge
- [ ] getPreviousAdjacentEdge
- [ ] hole
- [x] import (@lf94, https://github.com/KittyCAD/modeling-api/pull/184, https://github.com/KittyCAD/modeling-app/pull/1643)
- [ ] lastSegX
- [ ] lastSegY
- [ ] legAngX (@lf94 https://github.com/KittyCAD/modeling-app/pull/1787)
- [ ] legAngY (@lf94 https://github.com/KittyCAD/modeling-app/pull/1787)
- [ ] legLen (@lf94 https://github.com/KittyCAD/modeling-app/pull/1787)
- [x] line (@lf94 https://github.com/KittyCAD/modeling-app/pull/1754)
- [x] lineTo
- [x] ln (@lf94 https://github.com/KittyCAD/modeling-api/pull/222)
- [x] log (@lf94 https://github.com/KittyCAD/modeling-api/pull/223)
- [x] log10 (@lf94 https://github.com/KittyCAD/modeling-api/pull/222)
- [x] log2 (@lf94 https://github.com/KittyCAD/modeling-api/pull/222)
- [x] max (@lf94 https://github.com/KittyCAD/modeling-api/pull/223)
- [x] min (@lf94 https://github.com/KittyCAD/modeling-api/pull/223)
- [ ] patternCircular2d
- [ ] patternCircular3d
- [ ] patternLinear2d
- [ ] patternLinear3d
- [x] pi (@lf94 https://github.com/KittyCAD/modeling-api/pull/231)
- [x] pow
- [ ] segAng
- [ ] segEndX
- [ ] segEndY
- [ ] segLen
- [x] sin (@lf94 https://github.com/KittyCAD/modeling-api/pull/222)
- [x] sqrt (@lf94 https://github.com/KittyCAD/modeling-api/pull/222)
- [ ] startProfileAt
- [x] startSketchAt
- [ ] startSketchOn
- [x] tan (@lf94 https://github.com/KittyCAD/modeling-api/pull/222)
- [ ] tangentialArc
- [x] tangentialArcTo (@iterion, https://github.com/KittyCAD/modeling-app/pull/1731)
- [ ] tau (@lf94 https://github.com/KittyCAD/modeling-app/pull/1787)
- [x] toDegrees (@lf94 https://github.com/KittyCAD/modeling-api/pull/222)
- [x] toRadians (@lf94 https://github.com/KittyCAD/modeling-api/pull/222)
- [x] xLine  (@lf94 https://github.com/KittyCAD/modeling-app/pull/1754)
- [x] xLineTo  (@lf94 https://github.com/KittyCAD/modeling-app/pull/1754)
- [x] yLine  (@lf94 https://github.com/KittyCAD/modeling-app/pull/1754)
- [x] yLineTo  (@lf94 https://github.com/KittyCAD/modeling-app/pull/1754)

**Comment by lf94** [comment]
Note to self:

* [ ] expose unary functions in KCL
* [ ] expose remaining binary functions in KCL

**Comment by lf94** [comment]
NOTE: I must call toRadians on the Grackle backend for all trig functions...

**Comment by jessfraz** [comment]
The reason why I have those functions as radians is I could not find a popular programming language where they were not radians, meaning any ai model and human is going to assume they are radians, if we are the outlier its unintuitive

**Comment by lf94** [comment]
Oh so we want cos and sin to remain radians? Because that's 100% what I want lol, but I know we have the whole "default to degrees" thing.

**Comment by jessfraz** [comment]
These functions are the exception since it’s unintuitive

**Comment by jessfraz** [comment]
Make them work like the current stdlib which is radians

**Comment by alteous** [comment]
[`atan2`](https://doc.rust-lang.org/stable/std/primitive.f32.html#method.atan2) is important too.

**Comment by jessfraz** [comment]
We are only porting the current stdlib adding new functions can be outside this
