### ISSUE TITLE
lineTo tag should be consistent with tangentialArcTo and others

### ISSUE THREAD

**Issue by iterion** [KittyCAD/modeling-app#1730]
We adopted a new standard of using an optional tag parameter at the end of commands.
lineTo came before this decision, so it hasn't yet been updated to that new standard.

See https://github.com/KittyCAD/modeling-app/issues/1006 for details on the change.

**Comment by jessfraz** [comment]
Line, arc, most of them are the old way

**Comment by jessfraz** [comment]
Bezier, tangentialArc, xLine, yLine
