### ISSUE TITLE
[BUG]: Onboarding step 11 "Create Sketch" text should be "Start Sketch"

### ISSUE THREAD

**Issue by McSneaky** [KittyCAD/modeling-app#1789]
### Describe the bug

When onborading, then on step 11 it asks you to "Create Sketch". But there's no "Create Sketch" button. There's "Start Sketch" one

### Steps to Reproduce

1. Install app
2. Log in for first time
3. Follow onboarding steps
4. Go to step 11

### Expected Behavior

Button and help text should be the same

### Screenshots and Recordings

![image](https://github.com/KittyCAD/modeling-app/assets/6796697/279e9b01-3397-41dc-b823-b9acb677be13)

### Desktop OS

Windows 11

### Version

0.16.0

**Comment by franknoirot** [comment]
Thanks for the catch @McSneaky 🕵️
