### ISSUE TITLE
💅 Design icons for each CAD and code operation

### ISSUE THREAD

**Issue by franknoirot** [KittyCAD/modeling-app#179]
It is best practice to have all of the following for any given operation within a GUI app like this:
- Icon: quick, graphic representation
- Label: clear text identifier
- Short description: 1-sentence description for tooltips and help dialogs
- Long description: multi-sentence description for docs and tutorials
- Keyboard shortcut (optional): assigned key combo for power use without clicking

This issue is meant to track all of the possible operations in KittyCAD Modeling App to ensure that we have an icon created for each. It's crazy to say but we have a slightly _harder_ task ahead of us than most CAD apps, because we want to have GUI interactions that operate on the _code_ in addition to the traditional kinds that operate on CAD entities.

All designs will be added to [this Figma page](https://www.figma.com/file/5UUPOawPLEs3D0Gptf42vy/Designs?type=design&node-id=43-697&mode=design&t=g3k138mz4aRVDMEM-11) as they are designed.

Please feel free to add to this tasklist if there are operations I am missing:

```[tasklist]
### CAD Operations
- [x] Sketch
- [x] Extrude
- [x] Sweep
- [x] Loft
- [x] Fillet
- [x] Chamfer
- [x] Shell
- [x] Hole
- [x] Split
- [x] Plane
- [x] Boolean (Unite/Subtract/Intersect)
```

```[tasklist]
### Sketch Operations
- [x] Line
- [x] Arc
- [x] Spline
- [x] Polygon
- [x] Linear Pattern
- [x] Circular Pattern
- [x] Mirror
- [ ] Vertical constraint (applys individually)
- [ ] Horizontal constraint (applys individually)
- [ ] Angle constraint (relational)
- [ ] Parallel constraint (relational)
- [ ] Distance constraint (relational, not sure if should be broken down into vertical, horizontal and perpendicular distance)
```

```[tasklist]
### Code Operations
- [x] Make variable
- [x] Make function
```

```[tasklist]
### Assembly Operations
- [x] Linear Pattern
- [x] Radial Pattern
```

**Comment by jessfraz** [comment]
seem good here? reopen if otherwise
