### ISSUE TITLE
[BUG]: Onboarding step 11 is slightly confusing

### ISSUE THREAD

**Issue by McSneaky** [KittyCAD/modeling-app#1790]
### Describe the bug

- Related: https://github.com/KittyCAD/modeling-app/issues/1789

- On onboarding step 11 it asks you to create new sketch, then select line tool and then click on 3D view. But there seems to be no 3D view button anywhere (Just realized, 3D view is not "button" to click.. It's area where I should select plane.. Maybe  I shouldn't try new 3 at night.. 😅 )

- After clicking "Line" twice, I'm able to draw lines, but no idea how to get out of line tool. Tried to click on starting point several times, which seemed to do nothing. Tried to hit ESC too, but that took me out of onboarding flow

### Steps to Reproduce

- Start onboarding process
- Go to step 11
- Click on line tool

### Expected Behavior

Button to be there or more easily findable

Maybe some tutorial how to exit line tool

### Screenshots and Recordings

https://github.com/KittyCAD/modeling-app/assets/6796697/6266c00f-7a89-4126-b46b-c1409cb8e8ea

### Desktop OS

Windows 11

### Version

0.16.0

**Comment by franknoirot** [comment]
Thanks for the video and the explanation here @McSneaky! You're right the wording here is not clear and doesn't match the UX anymore. The term "3D view" is jargon-y and doesn't even need to be mentioned; people know to just click and draw. Here's what I'm updating that step to say now:

## Sketching
Our 3D modeling tools are still very much a work in progress, but we want to show you some early features. Try sketching by clicking Start Sketch in the top toolbar and selecting a plane to draw on. Now you can start clicking to draw lines and shapes.

The Line tool will be equipped by default, but you can switch it to as you go by clicking another tool in the toolbar, or unequip it by clicking the Line tool button. With no tool selected, you can move points and add constraints to your sketch.

Watch the code pane as you click. Point-and-click interactions are always just modifying and generating code in Zoo Modeling App.
