### ISSUE TITLE
Allow the nightly builds to be installed side-by-side with released builds

### ISSUE THREAD

**Issue by pierremtb** [KittyCAD/modeling-app#1867]
Right now what's produced at https://github.com/KittyCAD/modeling-app/actions/workflows/ci.yml?query=event%3Aschedule every night is also named `Zoo Modeling App` and therefore can't be installed on a system alongside an official release.

At least a new name and probably identifier, best would be to have a different icon as well (stretch).

Open for thoughts @franknoirot @Irev-Dev

**Comment by Irev-Dev** [comment]
No extra thoughts, sounds like a good idea to me.

@franknoirot the icon could just be a different color?
