### ISSUE TITLE
[BUG]: Must be a zoo employee to access the preview environment

### ISSUE THREAD

**Issue by aapatni** [KittyCAD/modeling-app#1893]
### Describe the bug

**Problem Description**
Hey! I'm trying to get a local build up and am running into problems with logging in.

I've enabled 3rd party cookies, but when trying to move past the /signin page I keep getting redirected back to signing in. 

Error Message: (timestamp 00:36) 
`API Error: You must be a zoo employee to access the preview environment | authMachine.ts:149`

However, for a brief instance I am routed to the modeling app (1 frame between 00:44-00:45).

Did a quick screen recording, hope it helps. 

**Environment Details:**

- **Yarn Version:** 1.22.22
- **Operating System:** MacOS Sonoma 14.4
- **Device:** 2019 MacBook Pro 16-inch
- **Browser:** Chrome Version 123.0.6312.58 (Official Build) (x86_64)
- **Commit Hash:** 68b61c9

### Steps to Reproduce

1. Follow the steps in "Running a development build"
2. Go to localhost:3000/signin
3. Attempt to sign in with a variety of methods (github,google, email)

### Expected Behavior

view the modeling app - ideally /file/new/onboarding

### Screenshots and Recordings

https://github.com/KittyCAD/modeling-app/assets/21110240/e9884e74-807e-4ecf-b399-21f02f0f0b53

### Desktop OS

MacOS Sonoma 14.4.1

### Browser

Chrome Version 

### Version

123.0.6312.58 (Official Build) (x86_64)

### Additional Context

[localhost-1711407224560.log](https://github.com/KittyCAD/modeling-app/files/14750328/localhost-1711407224560.log)

**Comment by aapatni** [comment]
will I be able to connect to the backend to test out modeling if I do this? Right now I don't think the lsp server will start without an auth token. 

`Uncaught (in promise) Error: kcl: auth token is required for lsp server to start`
`Uncaught (in promise) Error: copilot: auth token is required for lsp server to start`

I want to start sketches so I can validate the cursor changes work in: https://github.com/KittyCAD/modeling-app/issues/1522

**Comment by aapatni** [comment]
this one `__Secure-next-auth.session-token`?

**Comment by jessfraz** [comment]
perfect yes!

**Comment by aapatni** [comment]
![img_sc](https://github.com/KittyCAD/modeling-app/assets/21110240/b2c19443-7867-421c-b2dc-2e6458b3e991)

Pasted in the cookie, back to the issue with not being a zoo employee

**Comment by jessfraz** [comment]
oh can you ignore teh kcl lsp failures for this?

**Comment by jessfraz** [comment]
its basically hitting dev still due to DEV the env variable being there i think so if your change doesn't involve the lsp server i wouldnt worry about it

**Comment by aapatni** [comment]
<img width="1280" alt="Screenshot 2024-03-25 at 6 42 04 PM" src="https://github.com/KittyCAD/modeling-app/assets/21110240/609a4504-1429-47b2-b13b-ec7dd9c19666">

Might have misunderstood the errors before. What I'm trying to figure out is how to get this stream to work, so that I can test out clicking the various buttons in the modeling (ie starting sketches).

**Comment by jessfraz** [comment]
hmm yeah we might have to just whitelist you on dev

**Comment by aapatni** [comment]
Great, can you add the one associated with my github acc?

**Comment by jessfraz** [comment]
throw it in an email to me :)

**Comment by aapatni** [comment]
will do!

**Comment by Irev-Dev** [comment]
sorry bit late to this, but `localStorage.setItem('TOKEN_PERSIST_KEY', "<your-token>")` works for auth too.

**Comment by aapatni** [comment]
Hey folks, been fighting the auth problem for a bit now. Do you have any experience with non-employees contributing to the modeling-app before? Thinking I can reach out to them for some advice/tips.

Commit Hash: 868a560

My diff on authMachine.ts
```
diff --git a/src/machines/authMachine.ts b/src/machines/authMachine.ts
index 8bf0a5d..bf8fc73 100644
--- a/src/machines/authMachine.ts
+++ b/src/machines/authMachine.ts
@@ -5,8 +5,7 @@ import { isTauri } from 'lib/isTauri'
 import { invoke } from '@tauri-apps/api'
 import { VITE_KC_API_BASE_URL } from 'env'
 
-const SKIP_AUTH =
-  import.meta.env.VITE_KC_SKIP_AUTH === 'true' && import.meta.env.DEV
+const SKIP_AUTH = true
 const LOCAL_USER: Models['User_type'] = {
   id: '8675309',
   name: 'Test User',
@@ -39,6 +38,7 @@ export type Events =
     }
 
 export const TOKEN_PERSIST_KEY = 'TOKEN_PERSIST_KEY'
+localStorage.setItem(TOKEN_PERSIST_KEY, '018e34d6-REST-IS-HIDDEN')
 const persistedToken =
   localStorage?.getItem(TOKEN_PERSIST_KEY) ||
   getCookie('__Secure-next-auth.session-token') ||
```

my `.env.local`
```
VITE_KC_API_WS_MODELING_URL=wss://api.zoo.dev/ws/modeling/commands
VITE_KC_API_BASE_URL=https://api.zoo.dev
VITE_KC_SITE_BASE_URL=https://zoo.dev
VITE_KC_SKIP_AUTH=true
VITE_KC_CONNECTION_TIMEOUT_MS=15000
DEV=true
```

Results with these methods have not been proving fruitful, I'm still stuck on the stream loading
![Screenshot 2024-03-27 at 1 13 52 PM](https://github.com/KittyCAD/modeling-app/assets/21110240/aace5f54-9391-48dd-8545-0f851a0d6642)

I've tried each of the line diffs independently and together (using the Test User vs my own account with and without my token).

Relevant console messages:
```
engine connection is not ready             | selections.ts:297
{"type":"connecting","value":{"type":"websocket-connecting"}} → {"type":"connecting","value":{"type":"websocket-established"}} | engineConnection.sts:189
{"type":"connecting","value":{"type":"websocket-established"}} → {"type":"disconnecting","value":{"type":"timeout"}} | engineConnection.sts:189
``` 

full console log:
[localhost-1711570989899.log](https://github.com/KittyCAD/modeling-app/files/14780853/localhost-1711570989899.log)

**Comment by jessfraz** [comment]
oh so now i added you to dev can you change your env.local back to the development one?

**Comment by jessfraz** [comment]
we had people contribute before but not really since we locked down dev haha sorry aabout that

**Comment by aapatni** [comment]
No worries, should I also revert the diffs in authMachine.ts? Also confirming that there is no DEV=true in the .env.development?

**Comment by aapatni** [comment]
I got the stream working! However parts aren't rendering as expected

From the modeling-app (release)
![Screenshot 2024-03-27 at 1 45 02 PM](https://github.com/KittyCAD/modeling-app/assets/21110240/4bf7e2f9-8293-4eef-b18c-4acc8e06652c)

From dev (seems like nothing is happening)
![Screenshot 2024-03-27 at 1 45 27 PM](https://github.com/KittyCAD/modeling-app/assets/21110240/66a08e99-a4a8-43dd-8b94-8c5627542c28)

**Comment by Irev-Dev** [comment]
Are there any errors in the console?

**Comment by aapatni** [comment]
whoops, forgot to attach this
```
ICE candidate returned an error: 701: STUN host lookup received error. for stun:k8s-stunner-gateway-94f1ca3fd0-78ea8509707b5436.elb.us-east-1.amazonaws.com:3478

{
    "kind": "engine",
    "sourceRanges": [
        [
            0,
            0
        ]
    ],
    "msg": "SyntaxError: \"undefined\" is not valid JSON"
}
```

[localhost-1711575671547.log](https://github.com/KittyCAD/modeling-app/files/14781412/localhost-1711575671547.log)

**Comment by Irev-Dev** [comment]
@aapatni did some pair programming and we were able to get past the auth issue, but he hit another weird vite issue, He's going to try and see if he can't find a solution himself, if not chime back in here again.

**Comment by Irev-Dev** [comment]
I might close this, there are instructions on how to connect to prod in the read me, and we've had folks outside of Zoo use this successfully.
