### ISSUE TITLE
After creating a new project the user is asked once again if they'd like to create a new project

### ISSUE THREAD

**Issue by lf94** [KittyCAD/modeling-app#1917]
It's a bit confusing to create a new project, then to get this message:

![out](https://github.com/KittyCAD/modeling-app/assets/547923/319921df-3a43-405f-9686-416c1764273b)

The user hasn't done anything yet but the prose implies the user has already been working on something.

**Comment by jessfraz** [comment]
these two are def related https://github.com/KittyCAD/modeling-app/actions/runs/9184258812

**Comment by jessfraz** [comment]
queue the twilight zone song thats weird as fuck also will be nice to have "tauri tests" i know speaking to the choir but i want issues that we close that will need them to be searchable by those keywords lol

**Comment by franknoirot** [comment]
I hear if you say "tauri tests" three times looking at a mirror Pierre appears

**Comment by jessfraz** [comment]
so we are keeping open for the "takes two clicks for dismissing bug" just noting so we dont lose track

**Comment by jessfraz** [comment]
or should we make new bug
lets make a new bug
