### ISSUE TITLE
Tutorial says try changing line 2 (width) but actual line is 5

### ISSUE THREAD

**Issue by lf94** [KittyCAD/modeling-app#1918]
![out](https://github.com/KittyCAD/modeling-app/assets/547923/41ed49fd-f98f-4508-9992-7bae8ac2b9a4)

**Comment by franknoirot** [comment]
Thanks @lf94! I'm making it so those line numbers are dynamic and find the line in the example code, and throw an error on load if it ever can't find the search term in the example code's text, so anyone updating the example code should see the app start failing loudly if they break them.

**Comment by lf94** [comment]
Should we maybe just use less "absolute" language? In this case, "search for the variable `width` and try adjusting it with `Alt + mouse`" ? Just a suggestion

**Comment by franknoirot** [comment]
> Should we maybe just use less "absolute" language? In this case, "search for the variable width and try adjusting it with Alt + mouse" ? Just a suggestion

This is a fair idea and might be better if this continues to be a PITA, but since I found a light lift to make it dynamic I figured why not, keeps us from putting that cognitive load on the user.
