### ISSUE TITLE
Seeing old model when sketching gives perception nothing is happening

### ISSUE THREAD

**Issue by lf94** [KittyCAD/modeling-app#1924]
At https://youtu.be/NEkh8A-pmSM?t=584 you can see I'm modifying a sketch but the model is not being updated.

**I** understand that I have to exit the sketch to see the updated model, but had I not been a Zoo employee, I would totally expect the model to follow the sketch as I modify it.

I propose we hide the model during sketching.

**Comment by Irev-Dev** [comment]
https://github.com/KittyCAD/modeling-app/assets/29681384/bdb66f0f-1375-4b98-b514-b600d032c88d

This whole background half visible was really just a happy accident or maybe less so happy accident that came out of doing the client side sketch, but it probably didn't have enough intention behind it so maybe it's best to hide it and circle back if we think it's valuable.
But would want to get @franknoirot sign off, but if we agree it would be a very quick change.

**Comment by jessfraz** [comment]
frank and I talked about this one and since its no longer green and really offputting its kinda nice as a diff, let me know if you disagree
