### ISSUE TITLE
Sketch view mode doesn't honor the current theme

### ISSUE THREAD

**Issue by lf94** [KittyCAD/modeling-app#1925]
For some reason we have view -> sketch mode transition going to a completely different color (white to black).

![out](https://github.com/KittyCAD/modeling-app/assets/547923/2cbf5353-4aff-4fe6-9c96-5071aea5df5f)

![out2](https://github.com/KittyCAD/modeling-app/assets/547923/db26d7ed-066e-42cb-9210-a3bae5be9da6)

**Comment by jessfraz** [comment]
oh this is weird something didnt carry over w the background change

**Comment by franknoirot** [comment]
Yeah the overlay in the client-side sketch mode is still dark so users can still see the sketch lines. @Irev-Dev and I have to let the sketch scene's colors follow the theme too, I'll rename the issue

**Comment by jessfraz** [comment]
frank fixed this so closing
