### ISSUE TITLE
Seeing sketch lines in view mode is very hard

### ISSUE THREAD

**Issue by lf94** [KittyCAD/modeling-app#1926]
The lines don't have enough contrast with the grid:

![out](https://github.com/KittyCAD/modeling-app/assets/547923/2aeb5895-4fa6-4de6-b345-1de6ed1e6796)

**Comment by franknoirot** [comment]
I'll make an engine issue, we need a feature there first

**Comment by franknoirot** [comment]
Hey hey this is fixed!
1. The engine now supports light mode, so completed sketch lines are dark
2. our client-side sketch scene now supports light mode, so in-progress sketch lines are dark
