### ISSUE TITLE
Original project name is not kept when going through the tutorial

### ISSUE THREAD

**Issue by lf94** [KittyCAD/modeling-app#1928]
I had called my original project "Wrist brace", but clearly at this timestamp https://youtu.be/NEkh8A-pmSM?t=798 we see ZMA created a new project instead.

**Comment by jessfraz** [comment]
related to https://github.com/KittyCAD/modeling-app/issues/1917

**Comment by franknoirot** [comment]
This is the currently-implemented intended behavior whenever you replay the onboarding, because as a part of it it rewrites KCL on your behalf. #1917 is a bug but when you click the "Create a new project" button this is what it's supposed to do.

**Comment by jessfraz** [comment]
tauri test when we can
