### ISSUE TITLE
Export button is too hidden

### ISSUE THREAD

**Issue by lf94** [KittyCAD/modeling-app#1930]
You can see me struggling to find the export at https://youtu.be/NEkh8A-pmSM?t=816

It would be really nice to use conventional desktop UI language here: File -> Export As..., File -> Open... etc.

**Comment by jessfraz** [comment]
i think @franknoirot has a better design for this he is working on!

**Comment by franknoirot** [comment]
Yeah we're going to add this to the side ribbon as a part of my next redesign. Does this location seem alright to you?

**Comment by franknoirot** [comment]
But you also bring up a great point. [Tauri has a great API for adding native menus](https://docs.rs/tauri/1.6.1/tauri/struct.Menu.html), we just haven't spent any time on how to lay them out or implement them.

**Comment by lf94** [comment]
Ah the button in that side ribbon is perfect. I would maybe make this icon the usual floppy disk in combination with the arrow icon.
