### ISSUE TITLE
getNextAdjacentEdge and getPreviousAdjacentEdge convention issue

### ISSUE THREAD

**Issue by jgomez720** [KittyCAD/modeling-app#1935]
## Description
When using `getNextAdjacentEdge` and `getPreviousAdjacentEdge`, I am expecting the former to select the edge adjacent to the tip of the line, and the latter to select the edge that is adjacent to the start of that edge. 

## Screenshots/Recordings
https://github.com/KittyCAD/modeling-app/assets/114548659/05f2e107-2a72-4800-a171-0cd122315eb7

## Version
v0.17.0

**Comment by jessfraz** [comment]
are you saying i should swap the logic on these becausse that is easy enough!

**Comment by jessfraz** [comment]
ah yeah watched the vid, switching the logic one sec

**Comment by jgomez720** [comment]
yes exactly lol. thank you

**Comment by jessfraz** [comment]
its def not intentional what you are saying makes sense i merely stole the names from teh engine but like we can swap, i assumed it was working how you said as well

**Comment by jgomez720** [comment]
Yeah I didn't see how that could be intentional. Having them swapped is much more intuitive
