### ISSUE TITLE
Executor errors on valid pipe expressions

### ISSUE THREAD

**Issue by adamchalmers** [KittyCAD/modeling-app#1940]
Here's a valid KCL program with a pipeline `p`.

```
let w = 100
const p = startSketchAt([0,0])
  |> lineTo([w, 0], %)
  |> lineTo([w, w], %)
  |> lineTo([0, w], %)
  |> lineTo([0, 0], %)
  |> close(%)
  |> extrude(w, %)
```

Now if I split this pipeline into two halves `p` and `q`, it should work the exact same way.

```
let w = 100
const p = startSketchAt([0,0])
  |> lineTo([w, 0], %)
  |> lineTo([w, w], %)
  |> lineTo([0, w], %)
const q = p
  |> lineTo([0, 0], %)
  |> close(%)
  |> extrude(w, %)
```

But it doesn't, it gives an error "PipeExpression not implemented here":

<img width="533" alt="Screenshot 2024-03-27 at 4 09 49 PM" src="https://github.com/KittyCAD/modeling-app/assets/5407457/a208e98d-3a99-4bd8-813f-db1ea99de687">

This error string comes from two places in `fn execute()` so it's not a parser problem, it's an executor problem. The program actually parses just fine when I check in a unit test.

**Comment by jessfraz** [comment]
I literally just fixed this bug on main for @lf94 are you on the most updated branch?

**Comment by jessfraz** [comment]
https://github.com/KittyCAD/modeling-app/commit/5d69a6232446bfa0f180bcb11f595b17919f5021 this was the fix

**Comment by adamchalmers** [comment]
Oh awesome, thanks. No I was testing this on 0.17 release.

**Comment by adamchalmers** [comment]
OK confirmed it works on `main`. Sorry!
