### ISSUE TITLE
SetSceneUnits being sent many times

### ISSUE THREAD

**Issue by adamchalmers** [KittyCAD/modeling-app#1971]
## Background

SetSceneUnits is a modeling command that says what units the lengths sent via API should use. E.g is a Point2d(3, 4) mean 3cm or 3ft?

## Problem

The test case [riddle_small.kcl](https://github.com/KittyCAD/modeling-app/blob/main/src/wasm-lib/tests/executor/inputs/riddle_small.kcl)  sends SetSceneUnits three times across two batches. This is unnecessary. SetSceneUnits should only be sent once.

**Comment by jessfraz** [comment]
that seeems weird i thought it was just called at the very start of execute

**Comment by jessfraz** [comment]
oh oh my god its the recursion https://github.com/KittyCAD/modeling-app/blob/b0417114afb7ae8ee25c768d297114466d0a356d/src/wasm-lib/kcl/src/executor.rs#L1011

**Comment by jessfraz** [comment]
face palm

**Comment by jessfraz** [comment]
damn that was a good riddle, exposing a lot
