### ISSUE TITLE
Don't create the same planes multiple times

### ISSUE THREAD

**Issue by adamchalmers** [KittyCAD/modeling-app#1974]
If you run the test [riddle_small.kcl](https://github.com/KittyCAD/modeling-app/blob/main/src/wasm-lib/tests/executor/inputs/riddle_small.kcl) and println the API calls, you'll see that the exact same `MakePlane` command is being sent twice. In the real riddle program, MakePlane is sent _many_ times. We shouldn't send multiple MakePlanes for the exact same plane, that's just causing unnecessary IO and potentially breaking batches.

**Comment by jessfraz** [comment]
ah yeah we used to do this and store the ids of the planes for later use let me try and find the pr that changed it, i think it was client side sketch mode and there wasnt a great reason other than we can get away with just sending them i think

**Comment by jessfraz** [comment]
yeah here it is, anyways worth storing the id again https://github.com/KittyCAD/modeling-app/pull/1271/files#diff-0c3612325cd093337ac34105d7069606628dcbba2e4876c2623fa4744d4dbcf2L776

**Comment by jessfraz** [comment]
ah i fixed this as a part of some other pr
