### ISSUE TITLE
Better instructions to avoid confusion during application update

### ISSUE THREAD

**Issue by Ishan-002** [KittyCAD/modeling-app#1979]
### Problem
I had the v0.10.0 version of the modeling app, which was called the KittyCAD modeling app. Upon updating the application, it installed the new Zoo modeling app but proceeded to open the KittyCAD modeling app, which then asked for an update again. This cycle kept on going.

Initially, I was very confused and assumed that the update process might have failed, so I retried a couple more times only to encounter the same update window repeatedly. After some time, I luckily noticed a new icon on my desktop, which was the Zoo modeling app!

### Suggestion
The instructions seem unclear since there was no mention that a new app was being installed as part of the update (apart from Windows 10 asking for administrator access, which mentioned Zoo Modeling app as the name). Hence, I was expecting just the KittyCAD application to update. 
Ideally, if a separate new application is being installed as a part of the update, the experience could be better if that is communicated in the update window and the new application opens up after the update. Additionally, it could be helpful if the user gets the option to delete the older application during the update process.

### Desktop OS
Windows 10

### Steps to reproduce
1. Install the v0.10.0 version of KittyCAD Modelling App.
2. Update it.

### Version
Original version: v0.10.0 
Updated version: v0.17.1

**Comment by jessfraz** [comment]
I promise if we rename again we will make this better but i think its hard to solve for now after the fact so closing but let me know if you think otherwise
