### ISSUE TITLE
[BUG]: Export part button not working on browser version

### ISSUE THREAD

**Issue by ben-coo-per** [KittyCAD/modeling-app#1991]
### Describe the bug

The first time I attempted to export the part, the command bar opened to the last thing I was using it for (setting my theme).
After I exited that cmd bar state, I tried to export the part again and the button would not work.

### Steps to Reproduce

*Using the browser version*
1. open side menu
2. click "Export Part"

### Expected Behavior

Part is downloaded or a menu opens up where I can choose a format to download the part in

### Screenshots and Recordings

https://github.com/KittyCAD/modeling-app/assets/40070554/8671f3f8-3379-4ec5-9fd4-90c5b1bd1bfd

Here is the console error I am receiving when clicking the export button:
<img width="327" alt="Screenshot 2024-04-02 at 4 57 14 PM" src="https://github.com/KittyCAD/modeling-app/assets/40070554/1e37bdc1-7010-4a3a-84e8-193c3dc7014e">

### Desktop OS

MacOS Ventura 13.1

### Browser

Arc (chromium wrapper)

### Version

 0.17.1

**Comment by jgomez720** [comment]
Thanks for submitting @ben-coo-per. I believe this is you @franknoirot

**Comment by Irev-Dev** [comment]
I had a quick go at trying to replicate, haven't had any luck so far.

**Comment by franknoirot** [comment]
You're super right this should be me, I'll try to replicate to see why `argumentsToSubmit` is ending up undefined. Thanks @jgomez720 and @ben-coo-per

**Comment by franknoirot** [comment]
This is indeed tricky to try to recreate. I feel pretty certain that `command` is resolving to `undefined` in [this line](https://github.com/kittycad/modeling-app/blob/add-rectangle-tool/src/machines/commandBarMachine.ts#L406) so optional chaining will help guard against that, but I can't seem to replicate the behavior that made that possible; getting this half-dismissal that led to the command bar opening back on the theme command step.

Thanks for the video and logs to study, they'll be helpful as we continue to investigate.

**Comment by franknoirot** [comment]
I wasn't able to recreate the bug but this should make it impossible to hit the last part of it. I'm still stumped by how a half-finished command stayed in the modelingMachine's context after executing the command unfortunately, but we know it's related to this if we come across it again.
