### ISSUE TITLE
[BUG]: Axes gizmo dissapears shortly after launch

### ISSUE THREAD

**Issue by alteous** [KittyCAD/modeling-app#2003]
### Describe the bug

The axes gizmo appears briefly upon launch of the web app and missing thereon.

### Steps to Reproduce

Open app.zoo.dev in a new tab or window; the issue is not reproducible upon refresh.

### Expected Behavior

The gizmo would be there always.

### Screenshots and Recordings

Observe the bottom right hand corner of the video:

[Screencast from 2024-04-03 13-19-57.webm](https://github.com/KittyCAD/modeling-app/assets/8549126/d1fe2c46-0e19-4fc5-a549-3455dc22c005)

### Desktop OS

Ubuntu 23.10

### Browser

Firefox 124.0.2

### Version

0.17.1

**Comment by r-barton** [comment]
Bump on this, seeing this in 0.18.1
