### ISSUE TITLE
Ghost of Sketch after switching from point and click -> code -> point and click

### ISSUE THREAD

**Issue by jgomez720** [KittyCAD/modeling-app#2006]
## Description
Reported by Nick Boone
> In this attempt, I created a quick sketch using point and click, typed in a revolve command, then went back to modify the sketch. Now I'm seeing the ghost of that sketch on every new part I create. Restarting the stream fixed it.

![image](https://github.com/KittyCAD/modeling-app/assets/114548659/b246735b-5a0e-46e5-a04c-1930c08567b5)

Not much past this. 

## Version
v0.17.1 (this is a guess, but based on timeline it should be this version)

**Comment by jessfraz** [comment]
I honestly think clear all should have fixed this, closing but if it happens again reopen
