### ISSUE TITLE
expectorate usually fails on Markdown docs because they contain PNG bytes

### ISSUE THREAD

**Issue by adamchalmers** [KittyCAD/modeling-app#2038]
Two PNGs whose images are basically identical (visually) might have very different binary data. This is why we compare PNGs with docs.rs/twenty-twenty instead of checking their bytes are identical.

But, our KCL docs are stored in Markdown, and we check the Markdown is identical to previous runs using docs.rs/expectorate.

The problem is that now KCL docs contain embedded PNGs, using the raw image bytes encoded in Base64. This means that small differences in the PNG (which are visually indistinguishable) cause expectorate to fail.

We should instead

1. store the images as separate files in the repo (separate to the markdown docs)
2. link the images into the markdown docs
3. visually check the images with twenty-twenty

Then the docs will still contain images, but tiny changes to the images won't cause expectorate to fail.

**Comment by jessfraz** [comment]
I don’t understand because if the images failed then we’d update them then the markdown would change but if the images don’t fail then we don’t update them so the markdown shouldn’t change. Basically if the files in the repo are not changing the markdown should not change. I don’t think this is an issue

**Comment by jessfraz** [comment]
It just sounds like we are out of sync

**Comment by jessfraz** [comment]
They are literally read from disk, from the files in the repo

**Comment by jessfraz** [comment]
Moving the images w the docs is just kinda a pain in the ass

**Comment by adamchalmers** [comment]
Oh OK, sorry I didn't realize that was how it worked. I just saw the docs test failing on main despite visually indistinguishable images, but, maybe there's still a difference. Let me check again.

**Comment by adamchalmers** [comment]
On tag `v0.17.3` the docs are out of sync, weird, shouldn't CI have stopped that

**Comment by jessfraz** [comment]
yeah seems like tests were failing and probably got ignored
