### ISSUE TITLE
Grid Disappearing

### ISSUE THREAD

**Issue by jgomez720** [KittyCAD/modeling-app#2039]
### Description
I've seen this bug before, but couldn't replicate well. Today I just recording myself enough to see it happen. It happened on `close(%)`

### Version 
v0.17.3

### Recording
(skip to 38 seconds)
https://github.com/KittyCAD/modeling-app/assets/114548659/66557052-6cf3-4775-863f-bc79f6d89d51

Once the grid disappears, it doesn't come back until reload

**Comment by r-barton** [comment]
Bump on this as well. Don't have anything that makes it reproducible yet.

**Comment by jessfraz** [comment]
@Irev-Dev I think this might be the exit sketch bug? I can still repro w -XZ plane
