### ISSUE TITLE
Can't tab through snippet inputs at human speeds

### ISSUE THREAD

**Issue by Irev-Dev** [KittyCAD/modeling-app#2191]
I don't seem to be able to tab through snippet options unless I do it really fast

https://github.com/KittyCAD/modeling-app/assets/29681384/e448b6c1-1610-46c2-bca8-dfba63f775f1

Even though we have a test for the snippet tabs, I am able to replicate the same behaviour I'm seeing by slowing down the test a little, changing the end of the the `Auto complete works` to the following breaks the test

```typescript
  await page.keyboard.press('Enter')
  // finish line with comment
  await page.waitForTimeout(100)
  await page.keyboard.type('5')
  await page.waitForTimeout(100)
  await page.keyboard.press('Tab')
  await page.waitForTimeout(100)
  await page.keyboard.press('Tab')
  await page.waitForTimeout(100)
  await page.keyboard.type(' // lin')
  await page.waitForTimeout(100)
```

**Comment by jessfraz** [comment]
ah i know what this is
