### ISSUE TITLE
[BUG]: Zooming into part causes visual bug with grid

### ISSUE THREAD

**Issue by r-barton** [KittyCAD/modeling-app#2209]
### Describe the bug

When zooming into my part the grid is partly visible through the part. 

### Steps to Reproduce

1. Load KCL from [main.zip](https://github.com/KittyCAD/modeling-app/files/15080606/main.zip)
2. Zoom into part (see screenshot below)

### Expected Behavior

I expect that the grid should increase in density and still fill the whole screen

### Screenshots and Recordings

![image](https://github.com/KittyCAD/modeling-app/assets/3958831/f92690c7-fa58-499f-b861-750921df1a57)

### Desktop OS

Ubuntu 22.04 LTS

### Browser

Chrome

### Version

v0.18.1

**Comment by jessfraz** [comment]
we've decided in other open issues to nuke the grid entirely MEs arent used to it so closing since those can track
