### ISSUE TITLE
Add ability to define offset planes in UI

### ISSUE THREAD

**Issue by r-barton** [KittyCAD/modeling-app#2213]
It's useful to reference the same plane when creating parts. With the current KCL and modeling app you cannot define a plane outside of KCL. It would be nice to have a tool define offset planes using the UI.

## Engine notes
None, offset planes are just another plane to the engine.
## API/KCL notes
1. Ready. There is an ergonomic [`offsetPlane()` standard library function](https://zoo.dev/docs/kcl/offsetPlane) for defining a plane from a default plane or face.
2. TODO: add an issue to add the ability to use `offsetPlane` with body faces in addition to the default planes.
## Point-and-click notes
1. The biggest issue with matching existing CAD UX is that we currently don't have a pattern for UI handles for things like setting this offset distance. Related to https://github.com/KittyCAD/engine/issues/2233. This should not block an initial implementation.
2. A current implementation could be to add a modeling machine event and corresponding command with two arguments:
    1. `plane`: show default planes and make them selectable. **Note:** users will expect this to let you select faces for offset planes, so we should add a warning to this argument's step. You can take examples from the Fillet operation's configuration for a selection argument warning.
    2. `distance`: Until `1` can be supported, we can simply accept a KCL expression for the distance value.

## TradCAD demos

https://github.com/user-attachments/assets/9693d194-9144-4f86-a916-203034f5d84c

**Comment by franknoirot** [comment]
Thanks for making this @r-barton. I'm gonna make some edits to elaborate on it and get it into our current point-and-click project.

**Comment by pierremtb** [comment]
Related https://github.com/KittyCAD/modeling-app/issues/4468, and open PR https://github.com/KittyCAD/modeling-app/pull/4552

**Comment by franknoirot** [comment]
Completed by #4552
