### ISSUE TITLE
App crashes on first project

### ISSUE THREAD

**Issue by JohnOlushola** [KittyCAD/modeling-app#2225]
Description
---
While following through the onboarding steps after a creating new project and the app crashes - "An unexpected error occurred" screen. Attempted a "Reload" and "Clear Storage" but no change. No further details.

System Spec
---
- MacOS Sonoma 14.2 (23C64)
- 8GB RAM
- 256 SSD
- MacBook Pro 2018

**Comment by jessfraz** [comment]
I believed we fixed this a few releases ago, let me know if you still see it!
