### ISSUE TITLE
"Unexpected Error" pops up during basic setup. First occurred after update on 04/24/2024

### ISSUE THREAD

**Issue by justrocketsci** [KittyCAD/modeling-app#2229]
<img width="686" alt="Screenshot 2024-04-24 at 4 52 53 PM" src="https://github.com/KittyCAD/modeling-app/assets/56214800/827011ab-ad8d-471b-b863-e1b5cb008689">

**Comment by Korolen** [comment]
Same here.

**Comment by franknoirot** [comment]
Hey thanks for reporting this! Was it after updating to `v19.0.0` that you got this? I think it might be authentication-related.

**Comment by jgomez720** [comment]
@justrocketsci @Korolen we are working on this right now. Hopefully will have a fix soon.

**Comment by jgomez720** [comment]
this has been fixed now. Unfortunately, you will need to do a manual update to **v0.19.3** (re-download the app). The updater broke in v0.19.1 and v0.19.2. Let us know if this doesn't work for you.
