### ISSUE TITLE
tutorial unexpected error

### ISSUE THREAD

**Issue by jackofromspace** [KittyCAD/modeling-app#2258]
downloaded zoo yesterday, updated it to the current version today. in the tutorial, after the "streaming" slide, got an unexpected error message

**Comment by jessfraz** [comment]
this is fixed in the newly released 0.19.4, so sorry again!

**Comment by jackofromspace** [comment]
Thanks! I may have found another minor bug: this tutorial page fails to
auto-populate my api key.

[image: image.png]

**Comment by jessfraz** [comment]
@jgomez720 ^

**Comment by jgomez720** [comment]
Hey @jackofromspace, the image doesn't seem to come through on GitHub. Which tutorial page isn't auto populating your key?

**Comment by jackofromspace** [comment]
@jgomez720 my bad. it was on https://zoo.dev/docs/tutorials/beginner-onboarding-py#Windows although it seems to be working now.

Speaking of that page, it seems like some of this windows python tutorial was written for bash:

export KITTYCAD_API_TOKEN="YOUR-API-TOKEN"
pip3 install virtualenv
python3 -m venv venv
source venv/bin/activate
pip3 install kittycad
python3 tutorials/beginner_tutorial/convert.py

For powershell `export KITTYCAD_API_TOKEN="YOUR-API-TOKEN"` should be 'Set-Variable KITTYCAD_API_TOKEN "YOUR-API-TOKEN"`. And `source venv/bin/activate` should be `venv\Scripts\activate`. 

Also, for people installing python for the first time, you may need to specify that they check the box in the python installation wizard "Add python [ver] to PATH". I had my work cut out for me manually adding my system's PATH environment variables today.

Full disclosure: I'm a total novice user and I may be wrong-- I just learned how to set up a virtual environment this morning.

**Comment by jgomez720** [comment]
This is awesome @jackofromspace. Thanks for the detailed feedback. I'll get that page updated for powershell users.
