### ISSUE TITLE
[BUG]: Panning with the middle mouse button pastes clipboard text

### ISSUE THREAD

**Issue by alteous** [KittyCAD/modeling-app#2285]
### Describe the bug

When panning the camera, whatever text is stored in the user's system clipboard is inserted in the code panel.

### Steps to Reproduce

1. Copy some text into the system clipboard with Ctrl/Cmd + C or otherwise.
2. Open the code panel.
3. Move the camera with the middle mouse button.

### Expected Behavior

The camera would move without text being added.

The ability to paste text with the middle mouse button may be desirable for some users. We might want to add a check for whether the cursor is within the code panel instead of completely disabling the paste behaviour.

### Screenshots and Recordings

[Screencast from 2024-05-02 12-03-20.webm](https://github.com/KittyCAD/modeling-app/assets/8549126/3ec7d797-826b-4ba4-a19e-03c74c1e5f38)

### Desktop OS

Ubuntu 23.10

### Browser

Firefox 124.0.2

### Version

v0.19.4

**Comment by Irev-Dev** [comment]
That is very bizarre, I've not been able to replicate it so far, but will have to try it out on ubuntu.

What mouse settings do you have inside of the app? is it just the default kittycad mouse settings?

**Comment by jessfraz** [comment]
these are the same bug https://github.com/KittyCAD/modeling-app/issues/1307

**Comment by alteous** [comment]
Mouse controls are set to KittyCAD

**Comment by franknoirot** [comment]
Did some searching and it looks like [Figma has never fixed this](https://forum.obsidian.md/t/linux-middle-click-paste-is-problematic-and-needs-to-be-automatically-disabled/34717/23) but [Obsidian](https://forum.obsidian.md/t/linux-middle-click-paste-is-problematic-and-needs-to-be-automatically-disabled/34717/23) and Draw-io have. These middle click paste events do seem to be detectable and should then be able to be ignored if the click target is not the code editor (or other input/contenteditable)

**Comment by franknoirot** [comment]
Okay so looking more into this, it looks like Firefox has a unique behavior that allows global paste to the last-focused element. I can recreate this issue in Linux + Firefox, but I can also create a corollary issue of this in MacOS + Firefox where `Cmd + V` pastes into the code editor even when it is not the focused element (which I've confirmed by checking `window.document.activeElement`).

This is bonkers browser behavior; it isn't even clear where the browser is storing this "last focused" element for me to check against it. Somehow, in a way that feels magical, the `target` of the `paste` event becomes the code editor if it was the last input I typed into, and the bizarre [`explicitOriginalTarget`](https://developer.mozilla.org/en-US/docs/Web/API/Event/explicitOriginalTarget) is set to what the actual `document.activeElement` is. This is why the other browsers don't behave this way.

What's more is I seem to be able to detect this mismatch between the `activeElement` and the `explicitOriginalTarget`, but not to be able to `preventDefault` or `stopPropogation` on the resulting event. The event's `defaultPrevented` flag is turned `true`, but the paste still occurs 🫠

**Comment by franknoirot** [comment]
> What's more is I seem to be able to detect this mismatch between the activeElement and the explicitOriginalTarget, but not to be able to preventDefault or stopPropogation on the resulting event. The event's defaultPrevented flag is turned true, but the paste still occurs 🫠

The fix here was just that I needed to apply the `{ capture: true }` option to the event listener that I added to the browser `document`. Since I attached the event listener to an ancestor of the event's target element (the code editor in this case), it was firing an preventing default _after_ the target element had already handled the event, and had no effect. As you can see in [this demo](https://developer.mozilla.org/en-US/docs/Web/API/Event/eventPhase#result), adding `capture` reverses the order of event handling, so I can prevent this event globally from a document-wide listener that runs before the event drills down to the target element.
