### ISSUE TITLE
[BUG]: Scene lost after exiting visual sketch edit

### ISSUE THREAD

**Issue by alteous** [KittyCAD/modeling-app#2288]
### Describe the bug

Attempting to edit a sketch in point-and-click mode causes the scene to be lost upon exit.

### Steps to Reproduce

1. Create a sketch, either using the point-and-click mode or using code.
2. Set the cursor to the `startProfileAt` part of the code and click the 'Edit Sketch' button.
3. Perform any edit on the geometry and click the 'Exit Sketch' button.

### Expected Behavior

The scene returns to where it was before the 'Edit Sketch' button was pressed.

### Screenshots and Recordings

[Screencast from 2024-05-02 16-22-36.webm](https://github.com/KittyCAD/modeling-app/assets/8549126/85585fb5-853f-478e-8368-96e3e9f4ccc1)

At the end of the video I am attempting to scroll the mouse wheel as well as pan and rotate the camera.

### Desktop OS

Ubuntu 23.10

### Browser

Firefox 124.0.2

### Version

v0.19.4

**Comment by Irev-Dev** [comment]
This was resolved by: https://github.com/KittyCAD/modeling-app/pull/2397

But an engine issue was raised too https://github.com/KittyCAD/engine/issues/2116
