### ISSUE TITLE
Re-enable auto-complete tests

### ISSUE THREAD

**Issue by Irev-Dev** [KittyCAD/modeling-app#2298]
Auto complete kcl/lsp test is failing due to a coors issue (only effects dev, so auto complete is still working in the app), has been disable for the time being

See this commit to change back.
https://github.com/KittyCAD/modeling-app/pull/2287/commits/a1d4a54db91a1661565051d2d8d5969bdee9f932 from https://github.com/KittyCAD/modeling-app/pull/2287

**Comment by jessfraz** [comment]
I did this last week
