### ISSUE TITLE
show loader or something while engine is doing the export 

### ISSUE THREAD

**Issue by jessfraz** [KittyCAD/modeling-app#2305]
not an essential priority but we will want for v1 since its confusing

https://github.com/KittyCAD/modeling-app/assets/1445228/7311d935-0b6d-48fc-b2e4-6aac2e8da80a

**Comment by franknoirot** [comment]
Yahp you're totally right. I want to think about if we should make the command palette have a loading state, or instead do like a loading toast using [`toast.promise()`](https://react-hot-toast.com/docs/toast#promise) on the Export command or something. I have a hunch that the toast approach will be easier.

**Comment by franknoirot** [comment]
@jessfraz I looked into this today and ran into a little something trying to pass back the Promise of the success/failure/cancellation of the save dialog.

Basically with modeling commands we use this `command.resolve` to resolve the pending promise, but we don't seem to do the same with Export; [here we just void the resolution of exportSave](https://github.com/KittyCAD/modeling-app/blob/main/src/lang/std/engineConnection.ts#L1093).

I'm a little unfamiliar with the artifactMap workings, but I think I need to find the export command by ID and wire up the return value of exportSave to either its `.promise` or `.resolve`
