### ISSUE TITLE
Stop throwing in frontend code

### ISSUE THREAD

**Issue by dshaw** [KittyCAD/modeling-app#2325]
Throwing in Javascript and not handling the exception stops the execution engine, which means that the app will become unresponsive to users and it will be difficult to gracefully recover.

## Proposed strategy:
* Create a new Plausible event for “throw” since this will provide insight into how often the app is stopping due to existing code
  * This can be done before rearchitecting the thrown code’s user experience flows that follow
* Assess if the existing throws actually need to stop the user experience
* If the throw does not need to stop the user experience, implement a try/catch to handle the throw and implement a recovery strategy.
* If the throw represents a point in the application state in which the app experience cannot recover:
  * coredump
  * Present the user with the error screen and the ability to refresh their application
* Additionally, @jessfraz proposes implementing a linting rule to prevent throwing in React (components).

( Removed by Lee: this list is not representative of the situation )

* NOTE: Throwing in tests is fine.

**Additional context about throwing in React/Javascript:**
* [How to handle errors in React](https://www.developerway.com/posts/how-to-handle-errors-in-react)

**Comment by lf94** [comment]
We did it gang

**Comment by jessfraz** [comment]
WOOHOO LEE
