### ISSUE TITLE
Sketching on Wrong Plane

### ISSUE THREAD

**Issue by jgomez720** [KittyCAD/modeling-app#2335]
## Description
For this example, when I use `startSketchOn('-XZ')`, the sketch is performed on the XY plane, and then once I close and extrude the sketch, it switches to the -XZ plane.

## Version
V0.22.2

## Recording
https://github.com/KittyCAD/modeling-app/assets/114548659/b005b297-7953-44f9-882c-e6afb69c0be3

## KCL
```js
const exampleSketch = startSketchOn('-XZ')
  |> startProfileAt([0, 0], %)
  |> line([10, 0], %)
  |> arc({
       angle_start: 0,
       angle_end: 280,
       radius: 16
     }, %)
  |> close(%)
     
const example = extrude(10, exampleSketch)
```

**Comment by jessfraz** [comment]
Video for proof but either we fixed the bug, or it was a mix of zoom and view

either way zoom to fit will also help in future scenarios like this 
https://github.com/KittyCAD/modeling-app/pull/2201

https://github.com/KittyCAD/modeling-app/assets/1445228/072f5815-c8ab-43d1-bf3a-fdb51eee59e9
