### ISSUE TITLE
New Feature: Search projects in project Menu / command bar

### ISSUE THREAD

**Issue by jgomez720** [KittyCAD/modeling-app#2336]
## Description
We need the ability to search the files we have. I have officially reached the point where it's taking me too long to find the right file 😂

<img width="1582" alt="Screenshot 2024-05-10 at 10 30 41 AM" src="https://github.com/KittyCAD/modeling-app/assets/114548659/1f3e7401-baa9-435c-96ee-d3557d48afbd">

**Comment by franknoirot** [comment]
Easy, I got you

**Comment by jessfraz** [comment]
What if this was in the command bar instead

**Comment by franknoirot** [comment]
> What if this was in the command bar instead

Oh we kinda have this in the command bar, but the user has to go to the "Open Project" command first. Here's a demo and discussion:


https://github.com/KittyCAD/modeling-app/assets/23481541/a7c1606d-f31c-4d69-91ae-92a888401bdc


The discussion about adding a sort of first-class file search to the command bar is ongoing in #1468, but I think adding a little filtration UI to the home page is pretty trivial; we already have the UI components and the Fuse.js fuzzy search library implemented for the [CommandBarOptionInput](https://github.com/KittyCAD/modeling-app/blob/main/src/components/CommandBar/CommandArgOptionInput.tsx#L98) component.

**Comment by franknoirot** [comment]
@jtran I actually walked you through the CommandBarOptionInput component today, so I think you should be able to implement this as an element in [`Home.tsx` slotted in right here](https://github.com/KittyCAD/modeling-app/blob/main/src/routes/Home.tsx#L224-L268) without too much trouble at all, so I'm going to reassign this to you. You can also look at [SettingsSearchBar.tsx here](https://github.com/KittyCAD/modeling-app/blob/main/src/components/Settings/SettingsSearchBar.tsx#L0-L1).

You can probably borrow that wholecloth, with the only difference being that I think you should filter the project cards list _in situ,_ not show a Combobox of options like that search bar does.
