### ISSUE TITLE
Put "New Project" at the Top of File Menu

### ISSUE THREAD

**Issue by jgomez720** [KittyCAD/modeling-app#2337]
## Description
Really small thing, but when someone has a lot of files, they have to scroll all the way down to the bottom to create a new file. When they click it, they have to scroll all the way back up to get to their new file. Like so:

https://github.com/KittyCAD/modeling-app/assets/114548659/eff925d4-54fd-45a0-a5ea-37fe862b27b7

**Comment by franknoirot** [comment]
Oh hey great point! @JBEmbedded mentioned this in #2034 and I have it fixed in #2135, I just was waiting to get the project screenshot thing working with zoom-to-fit and all that but maybe I should pull just the other cleanups out into their own branch and get that in?

**Comment by jgomez720** [comment]
Oh if you already took care of it, no sweat. As long as we get it in at some point. I'd make a strong guess that it's a problem that only me and a handful of people are dealing with right now

**Comment by franknoirot** [comment]
Heads up I'm gonna pull out my project screenshot work into a different branch and get this in tomorrow
