### ISSUE TITLE
Can't sketch on the web app

### ISSUE THREAD

**Issue by pierremtb** [KittyCAD/modeling-app#2346]
From coreypdx on discord
> I'm probably doing something wrong, but I can't seem to create a line in sketch mode.  I have the Line tool selected, and I have selected a plane to sketch on, but I can't add any points.  This is using the web-based app   app.zoo.dev.  I've tried all combinations of shift,ctrl,left/right click, but still no points added.
Also I noticed that if I pan using shift + right click, the context menu pops up if I use firefox (but not Chrome).  I can still pan, but the context menu obscures  things.  Is there a recommended browser for app.zoo.dev?

**Comment by yeroca** [comment]
This seems to be fixed in v0.21.2.

**Comment by jessfraz** [comment]
Thank tyou! and sorry about that
