### ISSUE TITLE
cursor really hard to see light mode windows

### ISSUE THREAD

**Issue by jessfraz** [KittyCAD/modeling-app#2374]
idk how to fix this but it is near impossible to see the cursor on windows light mode when over the editor because the cursor text thing is also white, maybe just my computers or something

https://github.com/KittyCAD/modeling-app/assets/1445228/d460f1ac-0d02-41f8-8ac7-10ba39b1c987

**Comment by jessfraz** [comment]
OH MY GOD IN THE VIDEO ITS NOT WHITE

**Comment by jessfraz** [comment]
ill keep this open in case others hit this but very weird

**Comment by lbacattnyloza** [comment]
Jess, it's Lena and Michael with the Loza team.  We've been trying to reach you.  Please check your KittyCAD email!  Urgent!

**Comment by franknoirot** [comment]
OMG that's crazy lol

**Comment by lbacattnyloza** [comment]
URGENT!  Hi Jess.  We need instructions TODAY.  Please check email and respond ASAP.  Thank you.

**Comment by jessfraz** [comment]
i closed since this only happens on one windows machine i have and is super weird
