### ISSUE TITLE
`max` Math Function Doesn't Work

### ISSUE THREAD

**Issue by jgomez720** [KittyCAD/modeling-app#2384]
## Description
The `max` is failing.

## Error Response
<img width="431" alt="Screenshot 2024-05-17 at 10 26 49 AM" src="https://github.com/KittyCAD/modeling-app/assets/114548659/d6b7ba91-54a1-4282-b010-444c96cf21e7">

## KCL
```js
const exampleSketch = startSketchOn("XZ")
  |> startProfileAt([0, 0], %)
  |> angledLine({
    angle: 70,
    length: max(4, 5, 6)
  }, %)
  |> line([20, 0], %)
  |> close(%)

const example = extrude(5, exampleSketch)
```

**Comment by jgomez720** [comment]
Tried some other combinations of numbers in the `max` function, still couldn't make it work. `min` works no problem.

**Comment by Irev-Dev** [comment]
We should make sure we have unit tests for all of the stdlib functions

**Comment by Irev-Dev** [comment]
<img width="342" alt="image" src="https://github.com/KittyCAD/modeling-app/assets/29681384/78c94e2f-8be4-47e3-8b4f-365b4ec653d4">
looks like it's returning some absurdly large number

Also I'm not sure if the docs for this quite make sense
 
<img width="540" alt="image" src="https://github.com/KittyCAD/modeling-app/assets/29681384/098f6d9a-1528-40ea-86c5-3dc803a3a733">


This to me looks like I should be passing it an array like `min([1, 2, 3])` 🤷
