### ISSUE TITLE
[BUG]: Duplicate tags are allowed

### ISSUE THREAD

**Issue by adamchalmers** [KittyCAD/modeling-app#2389]
### Describe the bug

KCL programs with duplicated tags shouldn't be permitted. Currently they're allowed, and one tag will silently overwrite the other.

### Steps to Reproduce

Use this program:

```kcl
fn triangle = (len) => {
  return startSketchOn('XY')
  |> startProfileAt([-len / 2, -len / 2], %)
  |> angledLine({ angle: 0, length: len }, %, 'a')
  |> angledLine({
       angle: segAng('a', %) + 120,
       length: len
     }, %, 'b')
  |> angledLine({
       angle: segAng('b', %) + 120,
       length: len
     }, %, 'a')
}

let p = triangle(200)
```

Note that two sides are tagged 'a'. This program works just fine and it should be rejected. 

### Expected Behavior

Program should throw an error "cannot give two separate edges the same tag 'a'"

### Desktop OS

All

### Browser

All

### Version

0.21.4

**Comment by jessfraz** [comment]
yeah tags need to be a top level ast resource, which would then allow us to do this easily https://github.com/KittyCAD/modeling-app/issues/2086
