### ISSUE TITLE
reset settings resets all settings versus scoped to the pane

### ISSUE THREAD

**Issue by jessfraz** [KittyCAD/modeling-app#2435]
as a part of https://github.com/KittyCAD/modeling-app/pull/2434 i found this, now when I wrote the test in #2434 i assumed it worked in a scoped way so basically once this bug is fixed we just need to change the values that broke in the test haha

**Comment by franknoirot** [comment]
Sorry the wording is confusing me and my memory is failing me @jessfraz. Currently we reset all settings regardless of pane based on what I just checked. And this bug says that it _should_ be scoped to the current settings pane the user is hitting the Reset Settings button on. Am I understanding that correctly?

**Comment by jessfraz** [comment]
yes if thats what we want... i think thats what i expected so i was confused

**Comment by franknoirot** [comment]
Cool yeah that makes sense to me, won't be hard
