### ISSUE TITLE
[BUG]: Exit sketch camera polish

### ISSUE THREAD

**Issue by yeroca** [KittyCAD/modeling-app#2438]
--edit by @Irev-Dev: This issue has changed a bit and has been kept open because we added a temp fix, see my [comment for more details](https://github.com/KittyCAD/modeling-app/issues/2438#issuecomment-2128253259).

### Describe the bug

If I hit escape while creating a line in sketch mode, the model area goes blank

### Steps to Reproduce

Click start sketch.
Make sure you're in Line mode
Draw a few segments.
Hit Escape.

Display will go blank.  I tried this in Firefox and Chrome on Linux.

### Expected Behavior

I expected it to end the line drawing.  Actually, I'm not clear how to end a line drawing.

### Screenshots and Recordings

This is so easy to reproduce, I won't add a video.

### Desktop OS

Fedora Linux

### Browser

Chrome

### Version

124.0.6367.118 (Official Build) (64-bit)

### Additional Context

Also fails in Firefox 125.0.2 (64-bit)

**Comment by yeroca** [comment]
Just updated Chrome to 125.0.6422.76 (Official Build) (64-bit) and the problem still exists.

**Comment by jessfraz** [comment]
ah yes sorry we are working on this!

**Comment by jessfraz** [comment]
assigning @Irev-Dev mostly for tracking but its an engine side that needs the fix

**Comment by jessfraz** [comment]
engine issue: https://github.com/KittyCAD/engine/issues/2116

**Comment by jessfraz** [comment]
new release with a hot fix https://github.com/KittyCAD/modeling-app/actions/runs/9184258812 a better fix will come soon, so leaving this open for tracking

**Comment by yeroca** [comment]
> engine issue: https://github.com/KittyCAD/engine/issues/2116

Is the KittyCAD/engine a private repo?  It appears not open to the publc.

**Comment by jessfraz** [comment]
yes sorry i mainly put it there for tracking but the release w the hotfix is live now!

**Comment by yeroca** [comment]
It works better, but I think it's broken in a new way.  Let's say I draw a segmented line, then want to add a tangential arc.  If I use escape to finish the line, it seems to exit out of sketch mode.  I'm not clear how to re-enter a sketch, actually.

However, it's different if I move my cursor up to de-select the Line mode.  At  that point I can add a tangential arc.

**Comment by jessfraz** [comment]
yeah the escape is https://github.com/KittyCAD/modeling-app/issues/2442 this bug

**Comment by jessfraz** [comment]
sorry the current bug i was tracking with this was on exit sketch mode, the view was super fucked up (blank screen)

**Comment by Irev-Dev** [comment]
Going to keep this open because our exit sketch fix was a bit of a hack that should get more attention.

Some camera polish is needed in general, this areas is a bit dodgy https://github.com/KittyCAD/modeling-app/blob/main/src/machines/modelingMachine.ts#L882

As well as selections for default planes is broken and we have a client side work around which is not using engine animations

**Comment by Irev-Dev** [comment]
Oh we fixed this one I think yeah. in #2448 I believe.
