### ISSUE TITLE
[BUG]: Playwright users enter `Sketch.SketchIdle` if code pane is closed when starting a sketch

### ISSUE THREAD

**Issue by franknoirot** [KittyCAD/modeling-app#2444]
### Describe the bug

Found this odd behavior while writing an E2E test for #2419 that isn't replicable if you're a human user, only in Playwright tests, but seems like it could be a fruitful investigation. 

If the KCL code pane is toggled close in that test before starting a sketch, the test fails because the user does not have the Line Tool equipped when they enter the new sketch as they should. Watching the Playwright trace back you can see that the Line tool is equipped and then appears to be dropped, perhaps because of some error that triggers a `SketchCancel`, `Re-execute`, or other XState modeling event.

### Steps to Reproduce

1. Edit the Playwright test titled "Basic default modeling and sketch hotkeys work" such that the first call to `codePaneButton.click()` is before the line where the `s` key is pressed.
2. Re-run the test and see it fail

### Expected Behavior

Bot users should be able to start a sketch with the code pane closed and have the same experience as human users, getting the Line tool selected by default.

### Desktop OS

Any browser

### Version

v0.21.4

**Comment by jessfraz** [comment]
Pretty sure I fixed this when I added all those tests that start w the code pane closed
