### ISSUE TITLE
delete in the home screen should do nothing, right now it takes you back where you were before this is confusing if you had been using the command bar and hit delete a few too many times

### ISSUE THREAD

**Issue by jessfraz** [KittyCAD/modeling-app#2460]
steps to reproduce:

- open tauri app
- open a project
- go back home
- open command bar
- first delete closes command bar (as intended)
- second delete goes back to the project you were on (weird, should do nothing) (same goes for in a project delete raw should do nothing)

**Comment by jessfraz** [comment]
oh swweet, than sorry can we have a playwright test, want to make sure it doesnt regress

**Comment by jessfraz** [comment]
at the time i wrote this I had tried it, so unless sometjhing changes in the last week it still redirects

**Comment by franknoirot** [comment]
> at the time i wrote this I had tried it, so unless sometjhing changes in the last week it still redirects

Yeah you're right we're still allowing <kbd>Delete</kbd> to navigate backwards (the default behavior) when users are on the home page. I wanna knock this one out now should take no time.

**Comment by franknoirot** [comment]
We'll still need to come back and search for closed issues with "tauri tests" but I've added a playwright test for the backspace behavior prevention within the browser-available parts of the app; modeling and modeling settings.
