### ISSUE TITLE
after adding a constraint you are exited out of sketch mode, you should still be in sketch mode

### ISSUE THREAD

**Issue by jessfraz** [KittyCAD/modeling-app#2464]

**Comment by jessfraz** [comment]
this is working now this issue was stale

**Comment by jessfraz** [comment]
re-opening so we ensure this is true for all constraints not jsut line

**Comment by Irev-Dev** [comment]
I think duplicates https://github.com/KittyCAD/modeling-app/issues/2527 but not sure likely will make sure they are both fixed.

**Comment by Irev-Dev** [comment]
I spent a number of days playing with constraints and haven't noticed this so I think we good.
