### ISSUE TITLE
printlns in the parser/tokenizer/executor/lsp breaks kcl-lsp since it communicates over stdin/stdout, some sort of test to ensure we dont have any

### ISSUE THREAD

**Issue by jessfraz** [KittyCAD/modeling-app#2468]
opening issue as a reminder as a part of https://github.com/KittyCAD/modeling-app/pull/2467 where i had to clean some up

**Comment by adamchalmers** [comment]
https://stackoverflow.com/questions/63302814/is-there-a-way-to-disable-enable-the-println-macro

**Comment by jessfraz** [comment]
hoily shizzzz so if i do that in the kcl-lsp repo, the one that wrapss kcl-lib will it apply or do i need to add to kcl-lib w feature flag, also i 100% knew youd know a way to do this
