### ISSUE TITLE
"Show in folder" settings option crashes app

### ISSUE THREAD

**Issue by jgomez720** [KittyCAD/modeling-app#2470]
## Description
submitted from `maruel` in Discord.
> Crash v0.21.7 on macOS. Repro: Settings, Click "Show in folder" in Resets section:
10  Zoo Modeling App                         0x10310f058 core::panicking::panic_display::h66b4d024b80e8016 + 60
11  Zoo Modeling App                         0x1032b7d4c tokio::runtime::scheduler::Handle::current::panic_cold_display::h89248b565ef56a1e (.llvm.8219715392414388940) + 12
12  Zoo Modeling App                         0x1030f9008 tokio::signal::unix::signal::h7121d178f49021cb + 528
13  Zoo Modeling App                         0x10310b16c tokio::process:👿:spawn_child::h3155df24d84bc34c + 400
14  Zoo Modeling App                         0x1030f9ec4 tokio::process::Command::spawn::h32dc1565b0ec0025 + 40
15  Zoo Modeling App                         0x10289f2cc app::show_in_folder::h35df527af3ee59cd + 108

## Verison and OS
v0.21.7
MacOS

## Reproducable?
Yes. 
Settings -> Reset -> Show in folder

**Comment by franknoirot** [comment]
> 13 Zoo Modeling App 0x10310b16c tokio::process:👿:spawn_child::h3155df24d84bc34c + 400

This is hilarious

**Comment by franknoirot** [comment]
Ah nice I think this is happening because the `user.toml` file is deleted since no settings are overridden. I think this section should be hidden if no settings have been altered at the current level (whether User or Project tab is active)

**Comment by franknoirot** [comment]
Just cc'ing @jessfraz in case she magically has a bit of time because I'm locked on other bugs atm, but I think I can get to this pretty soon

**Comment by jessfraz** [comment]
i can attempt i think tis something else

**Comment by jessfraz** [comment]
it panics even if the file exists and its a delayed panic, its very weird

**Comment by jessfraz** [comment]
yeah we are violating tauri security shit by shelling out should be a fast fix
