### ISSUE TITLE
dismissing onboarding takes two clicks

### ISSUE THREAD

**Issue by jessfraz** [KittyCAD/modeling-app#2500]
i could replicate this in a new env as well

likely since this is web app too, we could have a playwright test for it too

more info here https://github.com/KittyCAD/modeling-app/issues/1917#issuecomment-2127606635

**Comment by franknoirot** [comment]
I can replicate in Tauri but not in the web version, but we should still have a Tauri E2E test. Investigating more.

**Comment by franknoirot** [comment]
There is a race condition between [these two function calls here](https://github.com/KittyCAD/modeling-app/blob/main/src/routes/Onboarding/index.tsx#L102-L106). The onboardingStatus setting is set in memory but has not been persisted to the file system by the time `navigate()` is called. Then, if we are in Tauri, the [onboardingRedirectLoader](https://github.com/KittyCAD/modeling-app/blob/main/src/lib/routeLoaders.ts#L53) reads the current onboarding status value from file.

I have to think about how to know I've persisted the setting before I can advance to navigating.

**Comment by lf94** [comment]
In the web version it closes in 1 for me as well

**Comment by franknoirot** [comment]
_tauri tests_
