### ISSUE TITLE
after hitting horizontal on a line, that line is no longer highlighted so it feels like you have to click it again to apply your next constraint

### ISSUE THREAD

**Issue by jessfraz** [KittyCAD/modeling-app#2510]
will need a playwright test as well to make sure we dont regress

**Comment by franknoirot** [comment]
After writing a test to recreate this behavior I think I've discovered that the selection is updating correctly, so you can apply both these constraints one after the other, but the client-side sketch scene is not keeping the highlight of the selected line properly, so it appears to be deselected even though it isn't


https://github.com/KittyCAD/modeling-app/assets/23481541/87ae9d96-f94e-4af6-bceb-cc7ff4d7a65d


I'll update my test to assert that the client-side line highlight is updated after constraints are applied, and I think we can rename this issue.

**Comment by franknoirot** [comment]
Okay so what's happening here is that the "Set selection" action after applying the constraint has a `selectionType` of "completeSelection", so the which does not call `updateSceneObjectColors()` like the other selection types do [here](https://github.com/KittyCAD/modeling-app/blob/main/src/components/ModelingMachineProvider.tsx#L307).

I think the thing is that these constraints need to pass along a real selection when they're applied.
