### ISSUE TITLE
[BUG]: After adding an angle constraint to polygon sketch, line segments of polygon disappear

### ISSUE THREAD

**Issue by yeroca** [KittyCAD/modeling-app#2527]
### Describe the bug

I think the title covers the explanation

### Steps to Reproduce

1. start a sketch
2. sketch a polygon with 3 or more points
3. add an angle constraint to one of its line segments
4. sketch disappears, leaving just a gray polygon.
5. highlighting code lines has no effect on the display

### Expected Behavior

I expected that the line segment I constrained will still be visible, as well as the other segments.

### Screenshots and Recordings

![image](https://github.com/KittyCAD/modeling-app/assets/514349/5c2ff90a-1008-4c4e-a8c8-ca01998367cd)

### Desktop OS

Fedora Linux 39

### Browser

Firefox 126.0

### Version

0.21.8

**Comment by yeroca** [comment]
Also, the UI seems locked up in some sense, because if I click **Line** to sketch a new line, it turns blue, but I cannot add any points at all by pointing and clicking.

**Comment by Irev-Dev** [comment]
Thanks @yeroca, the work around is to exit and enter the sketch, a total PITA so I'll get this fixed soon.

FYI @jessfraz this is the bug I wanted to fix before qa wolf does all of the constraint tests.

**Comment by yeroca** [comment]
> Thanks @yeroca, the work around is to exit and enter the sketch, a total PITA so I'll get this fixed soon.
> 
> FYI @jessfraz this is the bug I wanted to fix before qa wolf does all of the constraint tests.

Thanks. I actually noticed that exiting works, but didn't mention it.  I'll try to write more complete bug reports in the future.

**Comment by Irev-Dev** [comment]
The specific bug was fixed by #2555, but wanted to keep this open since there were similar bugs elsewhere, Once #2579 is merged we can close this one out.
