### ISSUE TITLE
[BUG]: After creating a sketch on an existing model face, sketch ends up on wrong plane, produces internal error

### ISSUE THREAD

**Issue by yeroca** [KittyCAD/modeling-app#2528]
### Describe the bug

If I select an existing face on a model, for example a face of the example shelf bracket, and then create a simple line sketch on that face, then exit the sketch, I see that the polygon sketch I created has been place on the XY plane instead of the face, and also there's an internal error showing in the code view.

### Steps to Reproduce

1. Open the existing shelf bracket model
2. click sketch
3. select a planar face of the shelf bracket
4. sketch a simple polygon
5. exit sketch
6. notice location of sketch (not on bracket face), and  internal error showing in code view

### Expected Behavior

I expected that the sketch will be on the chosen face

### Screenshots and Recordings

[Screencast from 2024-05-24 16-45-15.webm](https://github.com/KittyCAD/modeling-app/assets/514349/cf47df8b-74bb-47ad-87a6-a820797d801f)

### Desktop OS

Fedora 39

### Browser

Firefox 126.0

### Version

0.21.9

**Comment by yeroca** [comment]
Work-around for now is to comment out the revolve() call, edit the sketch, then uncomment it again.

**Comment by jessfraz** [comment]
Yeah revolve hasn’t been pulled thru to click and point yet, you can track what is pulled thru where here https://github.com/KittyCAD/modeling-app/issues/729

**Comment by yeroca** [comment]
> Yeah revolve hasn’t been pulled thru to click and point yet, you can track what is pulled thru where here #729

I think this comment may be on the wrong issue.  There's no revolve in this example.

**Comment by jessfraz** [comment]
im sorry it was! i moved it!

**Comment by jessfraz** [comment]
hmm I cant tell if this is engine side or not but its curious, the other annoying thing is did it not zoom you automatically on click to the face when you said you wanted to sketch on it?

**Comment by jessfraz** [comment]
i opened a seperate issue for the zoom thing, its giving "this this a sketch for ants" vibes

**Comment by jessfraz** [comment]
I assigned @Irev-Dev only to rule out the front end selecting the wrong face? but this could also be kcl, or even engine

**Comment by franknoirot** [comment]
> hmm I cant tell if this is engine side or not but its curious

Back in the day before we had sketches on non-XY planes working, when we would try to sketch on XZ it would successfully sketch but then render on the XY plane. This looks similar to me, that something like the face ID is invalid or missing, so when we exit sketch mode and submit it to the engine it quietly fails and bails out to rendering the sketch as if on the XY plane.

**Comment by jessfraz** [comment]
if i get rid of the fillets it works, this is an order of operations thing we need to do the fillets last in the executor since they eat ids.

**Comment by jessfraz** [comment]
related to https://github.com/KittyCAD/modeling-app/issues/2227
