### ISSUE TITLE
Start Sketch tools remain hidden while waiting for user to select plane

### ISSUE THREAD

**Issue by dshaw** [KittyCAD/modeling-app#2530]
When you click "Start Sketch" and don't do anything, you end up seemingly stuck without any sketching tools. There are no instructions indicating what to do next.

<img width="1552" alt="Screenshot 2024-05-24 at 5 55 16 PM" src="https://github.com/KittyCAD/modeling-app/assets/4322/bc018952-8933-4037-a57e-5d69468ceca6">

The UI is waiting for you to select a plane to sketch on. Now that we've implemented zoom to fit, I guess I have been doing less arbitrary clicks which would have automatically led me to click _somewhere_ just to be able to see what's going on. We should let the user know what they are expected to do after "Start Sketch" and should probably consider showing the sketch tools as soon as the user clicks. Then we can handle manage user expectations while they have the tools they expect to be there which might not yet be usable due to some condition like "select a plane".

**Comment by franknoirot** [comment]
I think I’d like to route the Start/Edit sketch commands through the command bar, and use the selection input step to select a plane. This will be best to implement after edit mode goes away.

I still agree with the idea of showing all the tools for muscle memory, but what do you think of that? The command bar popping up would be eye catching and say “select a plane”

**Comment by dshaw** [comment]
Additionally, 'ESC' keybinding doesn't seem to work while you are in this sketch started, but haven't selected a plane yet.

**Comment by dshaw** [comment]
Off topic, if you stop sketching and have an empty sketch, should we leave the start sketch invocation in the KCL? As far as I can tell, there's no way to continue an abandoned sketch.
![Screenshot 2024-06-03 at 3 38 02 PM](https://github.com/KittyCAD/modeling-app/assets/4322/ed46dea1-0e60-4292-a343-4091445b481e)

**Comment by dshaw** [comment]
> I think I’d like to route the Start/Edit sketch commands through the command bar, and use the selection input step to select a plane. This will be best to implement after edit mode goes away.
> 
> I still agree with the idea of showing all the tools for muscle memory, but what do you think of that? The command bar popping up would be eye catching and say “select a plane”

I have concerns about routing too many things through the command bar. Would the user be able to select the available options and input them there ('XY' | 'XZ' | 'YZ' | '-XY' | '-XZ' | '-YZ')?

**Comment by franknoirot** [comment]
> Off topic, if you stop sketching and have an empty sketch, should we leave the start sketch invocation in the KCL? As far as I can tell, there's no way to continue an abandoned sketch.

I believe this is a bug. There is an invoked service on the modelingMachine that is supposed to tear down the sketch code if it's exited while empty called [`AST-undo-startSketchOn`](https://github.com/KittyCAD/modeling-app/blob/main/src/components/ModelingMachineProvider.tsx#L439-L450). I can get it to work if the sketch is the only thing in the model, but it must not be reliable.

https://github.com/KittyCAD/modeling-app/assets/23481541/b22a1dc8-216e-4dd3-a213-358152f85328

**Comment by franknoirot** [comment]
> I have concerns about routing too many things through the command bar. Would the user be able to select the available options and input them there ('XY' | 'XZ' | 'YZ' | '-XY' | '-XZ' | '-YZ')?

Fair I have them too. My vision of this would work like the Selection step of the Extrude command:

![Screenshot 2024-06-04 at 10 20 04 AM](https://github.com/KittyCAD/modeling-app/assets/23481541/6b0df050-b48b-4b01-93f2-ac86fbdd5d65)

The only differences being:
1. The default planes would show
2. It would auto-submit (by being marked as `needsReview: false`) and have no other steps

**Comment by lf94** [comment]
Could we just have it says "Selecting plane" beside "Exit sketch" ?
