### ISSUE TITLE
[BUG]: After creating model using revolve, I cannout use the point/click modeling editor to edit the sketch

### ISSUE THREAD

**Issue by yeroca** [KittyCAD/modeling-app#2546]
### Describe the bug

I created a simple polygon sketch on XY, then revolved it around the Y axis.  Once the revolve operation as added, and I select the sketch in the model view or in the code view, the "Edit sketch" button comes up, but clicking on the button yields no change in the model view.  I cannot edit the sketch.

### Steps to Reproduce

1. Use the following example:

const part001 = startSketchOn('XY')
  |> startProfileAt([2, 0], %)
  |> line([10, 0], %)
  |> line([0, 2], %)
  |> line([-2, 0], %)
  |> line([-0, -1], %)
  |> line([-8, 0], %)
  |> close(%)
  |> revolve({ axis: 'Y' }, %) // default angle is 360
  
 2. At this point you should see a line in the disk representing the edge of the sketch polygon
 3. select line or select the StartProfileAt line.
 4. The "Edit sketch" button should appear
 5. Click it.
 6. Nothing happens.  No sketch mode is entered.
 

### Expected Behavior

I expected that I should be able to edit the polygon sketch.

### Desktop OS

Windows 10

### Browser

N/A

### Version

0.21.9

### Additional Context

I made a video, but it turned out too large to attach here.  If you are unable to reproduce this bug, please let me know.

**Comment by yeroca** [comment]
Work-around for now is to comment out the revolve() call, edit the sketch, then uncomment it again.

**Comment by jessfraz** [comment]
yes revolve has not been pulled thru yet to the point and click can track progress of all primitives here https://github.com/KittyCAD/modeling-app/issues/729

**Comment by yeroca** [comment]
Ah, nice work-around!  Thanks!
