### ISSUE TITLE
after sketch has been extruded cannot edit it with point and click

### ISSUE THREAD

**Issue by jessfraz** [KittyCAD/modeling-app#2557]
similar to https://github.com/KittyCAD/modeling-app/issues/2546 but for extrude

**Comment by jessfraz** [comment]
I’m going to reopen since we still want the ones with extrude in the block to work

**Comment by Irev-Dev** [comment]
Do you think it should still have the high-priority label on it?

**Comment by lf94** [comment]
Reassigning to dshaw since I think it's a nice focused, narrow issue that is rewarding

**Comment by jessfraz** [comment]
got it will kill both isssue one stone, just need tests
