### ISSUE TITLE
KCL function calls with a space between identifier and parens is an error?

### ISSUE THREAD

**Issue by lf94** [KittyCAD/modeling-app#2569]
Example: `myFn (0, 0)` is a syntax error. Should it be? cc @adamchalmers

**Comment by adamchalmers** [comment]
Personally I think it should be, but we should probably give a clear error explaining it.

Reason why: KCL is very strict about formatting due to all the codegen.

**Comment by jessfraz** [comment]
marking as cryptic error so we can improve it

**Comment by jessfraz** [comment]
Well we could make this parse fine but fix it always when we fmt :) I actually think that's better
