### ISSUE TITLE
[BUG]: While in sketch mode, any modification to the code which (temporarily) causes a syntax error causes the sketched line segments to disappear

### ISSUE THREAD

**Issue by yeroca** [KittyCAD/modeling-app#2590]
### Describe the bug

While in sketch mode, if I move to the code pane to manually change something, and as a result produce a syntax error while typing, for example I start to type the keyword "const", and when I type the c, that becomes a syntax error.  In addition to showing the syntax error in the code pane, the line segments I sketched go invisible, and won't reappear even if I remove my change.  In order to get back into a functioning sketch mode, I have to exit out of sketch mode and re-enter again.

### Steps to Reproduce

1. Start with an empty model
2. Click on "start sketch"
3. pick a plane
4. sketch a simple triangle
5. In the code pane, add a blank line at the top, then type "c" there.
6. notice the triangle segments disappeared
7. hit "exit sketch"
8. re-enter sketch mode on the triangle and the segments will reappear

### Expected Behavior

I expected that the model won't change until there's valid syntax present in the code pane.

### Desktop OS

Windows 10

### Version

v0.22.0

**Comment by jessfraz** [comment]
tjhis is covered by https://github.com/KittyCAD/modeling-app/issues/2590
