### ISSUE TITLE
[BUG]: Cannot pattern3d a pattern3d

### ISSUE THREAD

**Issue by r-barton** [KittyCAD/modeling-app#2597]
### Describe the bug

In the [docs](https://zoo.dev/docs/kcl/patternLinear3d) a pattern produces an ExtrudeGroup and accepts an ExtrudeGroup, which means it should be possible to pattern a pattern. The use case for this is creating a pattern in multiple axes (e.g. 'x' and 'y') as currently a linear pattern is only across a single axis.

### Steps to Reproduce

See KCL code snippets, I believe both of these should be valid KCL

```
const exampleSketch = startSketchOn('XZ')
  |> startProfileAt([0, 0], %)
  |> line([0, 2], %)
  |> line([3, 1], %)
  |> line([0, -4], %)
  |> close(%)
  |> extrude(1, %)

const pattn1 = patternLinear3d({
       axis: [1, 0, 0],
       repetitions: 6,
       distance: 6
     }, exampleSketch)

const pattn2 = patternLinear3d({
       axis: [0, 0, 1],
       distance: 1,
       repetitions: 6
     }, pattn1)
```

```
const exampleSketch = startSketchOn('XZ')
  |> startProfileAt([0, 0], %)
  |> line([0, 2], %)
  |> line([3, 1], %)
  |> line([0, -4], %)
  |> close(%)
  |> extrude(1, %)

const pattn1 = patternLinear3d({
       axis: [1, 0, 0],
       repetitions: 6,
       distance: 6
     }, exampleSketch)
  |> patternLinear3d({
       axis: [0, 0, 1],
       repetitions: 6,
       distance: 6
     }, %)
```

### Expected Behavior

I expect that the first linear pattern should be patterned along the second linear pattern definition.

See the discussion from [slack](https://kittycadworkspace.slack.com/archives/C06L2RHP9SL/p1717448334427019)

### Desktop OS

Windows

### Browser

Chrome

### Version

v0.22.0

**Comment by jessfraz** [comment]
To who every tries to solve this it also just needs to accept a vec of extrude groups versus a singular
