### ISSUE TITLE
[BUG]: Sketch axes visible after using Exit Sketch keyboard shortcut

### ISSUE THREAD

**Issue by alteous** [KittyCAD/modeling-app#2608]
### Describe the bug

This may or may be intended behaviour but it is certainly inconsistent with the 'Exit Sketch' button in the toolbar.  I was able to get the sketch axes to persist in the 3D mode using the 'Exit Sketch' keyboard shortcut and wasn't able to do the same with the button in the toolbar.

### Steps to Reproduce

1. Open app.zoo.dev.
2. If there is any code, clear it and refresh the page.
3. Enter sketch mode (any plane) with the 'Enter Sketch' tool.
4. Exit sketch mode with the 'Exit Sketch' keyboard shortcut, which is `ESC` for me.
5. Note the axes continue to be rendered in 3D mode, even when panning the camera.

### Expected Behavior

The behaviour of the 'Exit Sketch' keyboard shortcut would match the dedicated button, i.e., the camera would return to 3D mode without the sketch axes being drawn.

### Screenshots and Recordings

[Screencast from 2024-06-05 16-43-07.webm](https://github.com/KittyCAD/modeling-app/assets/8549126/9018b0b5-8fc6-4abe-8d05-649709aac7b5)

### Desktop OS

Ubuntu 23.10

### Browser

Firefox 124.0.2

### Version

v22.0.0

**Comment by nadr0** [comment]
I was able to recreate these issues.

State | No Code | Colored Planes Visible | Visible Axis Helpers | Grid (if settings are on)
-----|-----|-----|-----|-----|
Page Load / Idle | ✅ | ✅  | ❌ | ✅  |
On `ESC` exit | ❌  | ✅ | ✅ | ✅ |
On Button Click Exit | ✅  | ✅  | ✅ | ✅ |

`idle` -> `Sketch Mode` -> `ESC` actually throws an error and I need to hit `ESC` twice.
The ideal state is the `Page Load / Idle`. So we need to have the other workflows match this.

Here are the workflows
`Page Load / Idle` -> `Start Sketch` -> `Exit Sketch`
`Page Load / Idle` -> `Press S` -> ` Press ESC`
