### ISSUE TITLE
[BUG]: Desktop app shows bad network until a project is opened

### ISSUE THREAD

**Issue by franknoirot** [KittyCAD/modeling-app#2610]
### Describe the bug

Presumably because the engine connection is not initialized until the first project is opened, the network health indicator shows a nebulous problem state until the user enters their first file. We will want tauri tests for this eventually.

Some solutions in my order of preference:
1. Connect to the engine on app start up. I think this would have the knock-on effect of making first project load faster too.
2. Make the network health indicator only check the validity of network connected status until the engine connection is attempted.
3. Hide the network connection on home page

### Steps to Reproduce

1. Open the desktop app

### Expected Behavior

The network health indicator should only show a problem if there is a problem the user needs to address or that is otherwise interfering with app use.

### Screenshots and Recordings

![Screenshot 2024-06-05 at 1 19 43 PM](https://github.com/KittyCAD/modeling-app/assets/23481541/06fe3574-3f54-44d9-8665-14f4175dacff)

tauri tests playwright tests electron tests test

### Desktop OS

Any

### Browser

None (desktop version only)

### Version

v0.22.0

### Additional Context

@jessfraz this one might be borderline not high-priority: it's high visibility but low user impact.

**Comment by lf94** [comment]
The '-' actually means no connection yet - I think you could actually fix this quite easily looking in NetworkHealthIndicator (add a new state called 'Not started' and make it grey I guess). But yeah the alternative is starting engine immediately, which is probably best TBH. If the user forgets and never presses anything, our soon-to-be idle logic will kick in and kill the engine.

**Comment by lf94** [comment]
I can take this tomorrow

**Comment by lf94** [comment]
will be setting up the mac mini and squashing this one in the current tauri stuff should be a small one

**Comment by lf94** [comment]
maybe i can do it in a way that it translates over to the electron build

**Comment by franknoirot** [comment]
Hey this might be able to be closed since I made the network health indicator hidden until the user is on the project view with #3393

**Comment by lf94** [comment]
Oh that works IMO

**Comment by jessfraz** [comment]
yeah thats perfect
