### ISSUE TITLE
Strange Offset Behavior With `patternCircular2d`

### ISSUE THREAD

**Issue by jgomez720** [KittyCAD/modeling-app#2612]
## Description
I found this while helping `jacko_from_space` in our discord with their code. This code should make a circular pattern of circles centered on the origin, but for some reason the center is offset from the origin.

## Screenshot
<img width="2032" alt="Screenshot 2024-06-05 at 1 54 45 PM" src="https://github.com/KittyCAD/modeling-app/assets/114548659/695aec44-9505-4878-8f7f-04985216717f">

## KCL
```js
const height = 2
const Hn = 2
const ric = 1.2
const rcc = 2 * ric * sqrt(3) / 3
const a = Hn * rcc + (Hn - 1) * ric * 2 * sqrt(3) / 3
const rlu = 0.45 // rlu = ratio of lumen radius to incircle radius
const radlu = rlu*ric

const circles = startSketchOn("XY")
  |> circle([-2 * ric, 0], ric * rlu, %)
  |> patternCircular2d({
    arcDegrees: 360,
    center: [0, 0],
    repetitions: 5,
    rotateDuplicates: false,
  }, %)
```

**Comment by gserena01** [comment]
Hi! I was able to recreate this in the engine. Thank you for bringing this up. I'm looking for a solution now!
