### ISSUE TITLE
Engine connection reset doesn't use the current theme setting

### ISSUE THREAD

**Issue by franknoirot** [KittyCAD/modeling-app#2635]
Something is stale when the engine reconnection happens, because after setting my theme to white and experiencing a connection interruption (no refresh) and re-establishment, I got a dark themed stream:

![image](https://github.com/KittyCAD/modeling-app/assets/23481541/d9f9b6fd-c766-496a-b1f8-eda0288e544f)

Don't want to assign it to you but @lf94 might have some insights for whoever picks this up.

**Comment by lf94** [comment]
Hm, really no idea off the top of my head. Wouldn't that mean it's not saved in storage or something? I feel like the issue is probably not difficult to pinpoint
