### ISSUE TITLE
[BUG]: can't select features or sketch lines until the KCL Code pane is opened at least once

### ISSUE THREAD

**Issue by franknoirot** [KittyCAD/modeling-app#2636]
### Describe the bug

If you enter a project and begin sketching or editing an existing sketch without ever having the KCL Code pane opened, selecting lines fails. I've confirmed the selection fails, not just the blue segment highlighting, because attempting to apply a constraint after the failed selection does nothing. Opening the KCL Code pane remedies this issue.

### Steps to Reproduce

1. Close the KCL Code pane
2. Refresh
3. Start sketching or editing an existing sketch
4. Try selecting lines. This should fail

### Expected Behavior

Users should not need to open the KCL Code pane to initialize the selection behavior.

### Screenshots and Recordings

https://github.com/KittyCAD/modeling-app/assets/23481541/f6f0c68a-4f1f-4aca-8791-cde0bd9ec091

### Desktop OS

Any

### Browser

Any

### Version

v0.22.1

**Comment by franknoirot** [comment]
@jessfraz and @Irev-Dev might have insights into this, it seems at the intersection of KclManager and selections

**Comment by franknoirot** [comment]
Was going to file a separate issue for this but it's really the same issue I think: the same behavior holds for selecting a sketch to edit it. You cannot select a sketch until the KCL Code pane is opened at least once.

https://github.com/KittyCAD/modeling-app/assets/23481541/79fe62a0-743d-4909-9a94-e5e31def4181

**Comment by jessfraz** [comment]
i think i can figure it out, sometjing is getting triggered by the pane rendering initially

**Comment by jessfraz** [comment]
okay this is working now and i wonder if had to do with some other fix, i might try and bisect it super weird but legit it works for me

**Comment by jessfraz** [comment]
oh just part does... okay so you can create a new sketch when the code pane is closed but cant edit

**Comment by jessfraz** [comment]
let me write a failing test for fun so we know
