### ISSUE TITLE
Nothing can be deleted without modifying code in code editor

### ISSUE THREAD

**Issue by lf94** [KittyCAD/modeling-app#2666]
After a user creates a sketch, they can't delete it without messing with the code view.

**Comment by jessfraz** [comment]
same as https://github.com/KittyCAD/modeling-app/issues/782 so close them both

**Comment by jessfraz** [comment]
i might take a swing at this since i kinda know the selection code from some other shit now

**Comment by jessfraz** [comment]
Okay this one is harder than i thought but i got pretty far basically console logs what is selected and you hit delete and it goes thru a path but I need some ast functions for basiucally removing pathToNode i really dont grok the whole path to node thing like i see what its doing but i dont understand how to go from that to delete the parent node and anything that calls that variable

i would just write a helper function in rust just for this but seems kinda stupid when likely the js side already has shit like this and will need other customizations in the future so anyways progress is here and there is a nice failing playwright test https://github.com/KittyCAD/modeling-app/pull/2752

**Comment by max-mrgrsk** [comment]
hey, copy-pasting the message from slack as Lee suggested : 

initial state:

![del01](https://github.com/KittyCAD/modeling-app/assets/156543465/39275579-fe2c-4498-9e72-093b57578a0d)

**step 1. press delete**
code stays as it is, almost:
part to delete is getting parameter del, engine renders it wireframe
ast walker marks all stuff in the affected cascade with err property and engine renders it red. or blue ... to be a bit more friendly : )

![del02](https://github.com/KittyCAD/modeling-app/assets/156543465/9826b0b5-a9e4-4747-850b-ee87e7fb82eb)

explanation:

![del02-explanation](https://github.com/KittyCAD/modeling-app/assets/156543465/ac348481-a7fa-409b-9404-08199e7b2e66)

**step 2. press one of trash icons:**
grey deletes grey code (what you deleted initially)
red purges whole affected cascade.

**what would normally happen before step 2:**
1. you would create a new stuff to apply your red code.
2. reassign your red stuff to it,
3. walker would remove err property.
4. red trash icon disappears
5. you just press grey trash icon to get rid of the redundant deleted code
or even better, walker while removing the err property also wipes the gray code.

like this:
![del03](https://github.com/KittyCAD/modeling-app/assets/156543465/9eea0225-2bb1-4073-98a8-de25dfcf97a0)

in this pipeline you are super relaxed
you kinda see visually what bodies have to be reassigned
you see the place in code to make a new body for them
the bodies are red, so you kinda know what's left to do..

i think this could be a super nice experience, much better then elsewhere.

copy-paste from this thread: https://kittycadworkspace.slack.com/archives/C04KFV6NKL0/p1719568623360489?thread_ts=1719496085.848529&cid=C04KFV6NKL0

**Comment by Irev-Dev** [comment]
https://github.com/KittyCAD/modeling-app/assets/29681384/11414573-95c0-462d-84e3-1203b6b405ea

**Comment by lf94** [comment]
The delete key can be used now to delete stuff right? So we can close this? :)

**Comment by Irev-Dev** [comment]
Yeah let's close it, should still be able to find it later for Max's comment.
