### ISSUE TITLE
Grid continues to jump and disorient

### ISSUE THREAD

**Issue by lf94** [KittyCAD/modeling-app#2668]
We need to remove the grid I think, and re-evaluate how it's used. Right now it is too confusing.

**Comment by lf94** [comment]
Related https://github.com/KittyCAD/modeling-app/issues/2039

**Comment by lf94** [comment]
It's been decided, we are removing the grid.

**Comment by nicboone8** [comment]
The jumpiness of the grid can be avoided by just running the gridlines off the ends of the viewer in every direction. Zooming in and out could reveal finer and finer minor grid lines within each square so that the coarseness of the grid is always appropriate for whatever scale you're working in
![grid concept](https://github.com/user-attachments/assets/98a14b2c-ee5e-4365-ba09-d34c370a401e)

**Comment by nicboone8** [comment]
(my gif isn't very smooth. The squares-within-a-square should probably also gain or lose transparency as you zoom in/away)

**Comment by nicboone8** [comment]
This would also make it a lot easier to distinguish up from down if the user has spun the camera around a lot

**Comment by nicboone8** [comment]
The scale indicator could live in the bottom right corner of the screen with the units indicator, rather than move around with the grid
![image](https://github.com/user-attachments/assets/f712dd9c-abdc-4e7e-9570-02f20832d562)

**Comment by lf94** [comment]
Sorry if you're still seeing the grid the intent was to be off by default :)

**Comment by jessfraz** [comment]
he likes the grid :)

**Comment by lf94** [comment]
Ah ok, grid is back on :)

This involves 2 engine changes and 1 modeling-app change:

1. We need engine to do the new drawing logic
2. We need engine to report scale changes as some event

1. We need modeling-app to use these events to display the current scale

I'll open the issues when I get around to it, I may even try to do it myself

**Comment by jessfraz** [comment]
actually it turns out he just wanted something on empty scene, I pointed him to https://github.com/KittyCAD/modeling-app/issues/2880 @nicboone8 let us know if you'd still even use the grid with that, if not, we can close :)

**Comment by lf94** [comment]
Oh much easier then

**Comment by nicboone8** [comment]
yea, disabling the primary grid makes sense to me in that case. The sketch grid is still pretty useful
