### ISSUE TITLE
Code editor is not clearly focused when available to type

### ISSUE THREAD

**Issue by lf94** [KittyCAD/modeling-app#2669]

**Comment by franknoirot** [comment]
I think a couple things will help this:
1. make the line highlight less opaque when the user's focus is not on the pane. This will create a more start difference when entering focus
2. make the outline of the pane thicker and bolder when the user's focus is within it (for any pane, not just the KCL Code one). This is actually well demonstrated in the GitHub comment box I'm using right now: the border gets thicker and blue when focus is within it.
3. Make the cursor a little more noticeable, it gets lost with the other highlights like matching brace highlights, for example.
