### ISSUE TITLE
On large syntax errors, show something less threatening

### ISSUE THREAD

**Issue by lf94** [KittyCAD/modeling-app#2670]
When there is a large error, it's pretty much nonsense to the user.
Instead we need something that just says "KCL error". They can use coredump to inform us. Maybe on this special case, a "report error" appears?

**Comment by jessfraz** [comment]
we now have a "crytpic error template" so I think we can capture thesse and fix them as we go https://github.com/KittyCAD/modeling-app/issues/new?assignees=&labels=cryptic-error&projects=&template=cryptic_error.yml&title=%5BCRYPTIC%5D%3A+ easier than this big over-arching issue and theres already a few filed
