### ISSUE TITLE
Multiple constraints are not possible?

### ISSUE THREAD

**Issue by lf94** [KittyCAD/modeling-app#2675]
An example: parallel two lines, then set the length of one. One of the two cannot have length constrained.

**Comment by Irev-Dev** [comment]
Probably going to need a little more detail on this one, not really sure what you mean.

**Comment by lf94** [comment]
https://youtu.be/eGnSAdD9fFs?t=333 is a really really quick example as I get you another video. I can't seem to apply any constraints to the two lines I've selected, but it may not be because of a constraint already.

**Comment by lf94** [comment]
Looking a tad deeper into this I think the issue is more around selecting the last line for things! I've opened a different issue: https://github.com/KittyCAD/modeling-app/issues/2734

**Comment by Irev-Dev** [comment]
Sweet thanks.
