### ISSUE TITLE
Objects visibly pop in

### ISSUE THREAD

**Issue by lf94** [KittyCAD/modeling-app#2676]
A major goal of ours is "speed". It completely kills the selling of that goal.

We need to eliminate any instances of this, at least for < 100 objects as an initial goal, so let's start with that.

**Comment by adamchalmers** [comment]
this is just an issue saying "batch everything"

**Comment by adamchalmers** [comment]
duplicate of https://github.com/KittyCAD/modeling-app/issues/1972

**Comment by lf94** [comment]
Pretty much and why I assigned you too

It may not be a duplicate though, because you may find another strategy. This is **specifically for first model loading**.
