### ISSUE TITLE
"Edit Sketch" only appears on first "startProfileAt" ?

### ISSUE THREAD

**Issue by lf94** [KittyCAD/modeling-app#2684]
See video. I thought it was my branch, but it's on prod too:

https://github.com/KittyCAD/modeling-app/assets/547923/60e1a218-cf0d-43a1-ae4b-d6b1d176b2f1

**Comment by lf94** [comment]
Our tests were probably passing before because they were zooming so fast that the Edit Sketch button probably stayed visible long enough.

**Comment by franknoirot** [comment]
Is it possible this is duplicate with #2426?

**Comment by nadr0** [comment]
This bug has already been resolved. It is working correctly within `main`. I tested locally myself with multiple `startProfileAt` and I was able to see `edit sketch`.

I checked and we already have a playwright test to test this exact scenario so the regression case is covered. The test is called `multi-sketch file shows multiple Edit Sketch buttons` within `sketch-tests.spec.ts`.
