### ISSUE TITLE
"Position _ Is Out Of Range..." Error

### ISSUE THREAD

**Issue by jgomez720** [KittyCAD/modeling-app#2688]
### Description
This was a bug we saw a while ago, but it seemed to come back just for the `shell` function

### Recording
https://github.com/KittyCAD/modeling-app/assets/114548659/587df932-f84f-4d9a-a8fa-2ef3fb566d6b

### Version
v0.22.1 (web app)

### KCL
I had an error in my KCL while I was recording (aside from the error of this issue), I'm leaving it in just in case that was causing it.
```js
const exampleSketch = startSketchOn("XZ")
  |> startProfileAt([0, 0], %)
  |> angledLine({ angle: 50, length: 45 }, %)
  |> yLineTo(0, %)
  |> close(%)
  |> 

const example = extrude(5, exampleSketch)
  shell({ faces: ['end'], thickness: 0.25 }, exampleSketch)
```

**Comment by jgomez720** [comment]
similar to https://github.com/KittyCAD/modeling-app/issues/1335

**Comment by jessfraz** [comment]
I think its not exclusive to shell but more the fact shell is after the missing pipe, idk will take a look
