### ISSUE TITLE
Need to show length of draft straight sketch line segments while placing them

### ISSUE THREAD

**Issue by franknoirot** [KittyCAD/modeling-app#2692]
See [this flow in Figma](https://www.figma.com/design/5UUPOawPLEs3D0Gptf42vy/Designs?node-id=2965-12498&t=nLNLOzGtSyqVqkjS-11)

Here is the important step in the flow: it shows a draft line with an annotation of its length shown around its midpoint. This length annotation should update on mouse move:
![image](https://github.com/KittyCAD/modeling-app/assets/23481541/428d5edb-740b-4c3f-8fee-e887086306df)

After the user places the line the annotation should convert to a text input for the user to edit, but this will be covered in a sibling issue.

**Comment by lf94** [comment]
All right @pierremtb you said send a high priority item your way and so here's one 😆

**Comment by pierremtb** [comment]
@lf94 Thanks haha! Will get on it now that the updater stuff is back on track

**Comment by lf94** [comment]
@pierremtb I'm going to reassign to @franknoirot just because I think he has more capacity to do this right now
