### ISSUE TITLE
Extrude button is disabled after exiting sketch and canvas is a darker shade

### ISSUE THREAD

**Issue by ZooSpiritWolf** [KittyCAD/modeling-app#2697]
Edit: see Kurt's comment below, the fix for this is to make sure the user's cursor goes on the `startProfileAt` when exiting a sketch, so that the user can click "exit sketch" -> "extrude" without having to select the sketch after the exit sketch

🐛 on Dev

Steps to reproduce:
1. Login
2. Clear editor to clear sketch
3. Start a new sketch
4. Select a plane to start sketch
5. Sketch a closed shape
6. Click "Exit Sketch" button
7. Observe canvas and "Extrude" button
Expected: 
- Canvas to visually remain the same shade 
- The extrude button to be enabled to extrude the newly created sketch
Actual: 
- Canvas to visually a darker shade 
- The extrude button is disabled, but can be enabled upon clicking the sketch again. 

Timestamp: 0:12
Video: 
https://www.loom.com/share/44f221dbd26a481288408eb4625f5b47?sid=ad6cdd03-ec4b-4210-bf93-6c247435f659 (https://www.loom.com/share/44f221dbd26a481288408eb4625f5b47?sid=ad6cdd03-ec4b-4210-bf93-6c247435f659)

Bug report:
https://app.qawolf.com/zoo/bug-reports/b7c22cff-abd8-4149-a945-290a6dc4924f

Affected workflows:
• Extrude a Sketch - https://app.qawolf.com/zoo/workflows/clw9mvdsk0wbg12bvswg2cbwp

If you are aware of this bug you can set the priority to low which will prevent it from causing a run failure.

**Comment by Irev-Dev** [comment]
Okay so the darkening is not an issue anymore, but after the sketch is exited maybe we should put the cursor is a position so that it's already select and therefore can be extruded?

**Comment by Irev-Dev** [comment]
I'm going to unassign Frank and myself, as I think anyone could pick this up, so it's now open for anyone to pick up.

**Comment by jessfraz** [comment]
reopening this is failing again in qawolf

**Comment by jessfraz** [comment]
they are closing this one and opening up a newer specific one
