### ISSUE TITLE
No longer able to create or edit multiple variables on extrude distance menu

### ISSUE THREAD

**Issue by ZooSpiritWolf** [KittyCAD/modeling-app#2698]
🐛

Steps to reproduce:
1. Login
2. Clear editor to clear sketch
3. Start a new sketch
4. Select a plane to start sketch
5. Sketch a closed shape
6. Click "Exit Sketch" button
7. Click the sketch
8. Click the "Extrude" button
9. Click "Create new variable"
Expected: 
- To be able to create multiple variables
- Have a list of variables shown with editable names
Actual: 
- Only able to create a single variable
- No list of variables is displayed

Timestamp: 0:05
Video: 
https://www.loom.com/share/d34ca9f99e35467badd75735a9bdb494?sid=e6bfa647-3aa2-453e-bc3d-6132b193cb47 (https://www.loom.com/share/d34ca9f99e35467badd75735a9bdb494?sid=e6bfa647-3aa2-453e-bc3d-6132b193cb47)

Bug report:
https://app.qawolf.com/zoo/bug-reports/9fc5436e-049d-495f-b147-f7993eaa3762

Affected workflows:

If you are aware of this bug you can set the priority to low which will prevent it from causing a run failure.

**Comment by Irev-Dev** [comment]
This one is super confusing, we never allowed making multiple variables a thing with extrude,

I've asked for [clarification from the wolf team](https://kittycadworkspace.slack.com/archives/C071JD7EZGF/p1720414348601669), removing the high priority label until this issue is in a state where one of us can work on it.

**Comment by Irev-Dev** [comment]
Going to close this out because it was wrong and they're closing it out on their end too
https://kittycadworkspace.slack.com/archives/C071JD7EZGF/p1720444628905009?thread_ts=1720414348.601669&cid=C071JD7EZGF
