### ISSUE TITLE
Prevent mousewheel events while dragging for orbit/pan/zoom

### ISSUE THREAD

**Issue by franknoirot** [KittyCAD/modeling-app#2699]
In some mouse control configurations (possibly only "Solidworks") users can incidentally move their mouse wheel (zoom) while middle-click-dragging (orbit). This leads to competing unreliable and reliable channel messages being sent to the engine to move the camera, resulting in sporadic behavior like this, where the camera jumps back to the position it was in when the mouse wheel moved:

https://github.com/KittyCAD/modeling-app/assets/23481541/33324464-a5ef-47a3-b67e-cec1e4ba534b

A better long term fix is to allow these competing commands to resolve nicely so that zooms, pans, and orbits can be done simultaneously. This will be especially important for [space mouse](https://3dconnexion.com/us/spacemouse/) users. But a fix for the current degraded experience for Solidworks mouse control users is to disallow `mousewheel` events while dragging.

**Comment by dshaw** [comment]
For reference there was a previous issue with the Solidworks settings which we were unable to reproduce or get further feedback on: https://github.com/KittyCAD/modeling-app/issues/1911

**Comment by r-barton** [comment]
Just want to add to this, I'm still having this issue even after switching to KittyCAD controls

**Comment by Irev-Dev** [comment]
> A better long term fix is to allow these competing commands to resolve nicely so that zooms, pans, and orbits can be done simultaneously

Would that require engine updates, or is it all on our end still?

**Comment by franknoirot** [comment]
> Would that require engine updates, or is it all on our end still?

My understanding is that would require an engine-side change, but I don't know if I'm ignorant of some way we could merge the camera movements client-side.

**Comment by franknoirot** [comment]
> But a fix for the current degraded experience for Solidworks mouse control users is to disallow mousewheel events while dragging

I'm going to try to make this smaller fix, I can replicate it still. Apologies for the delay.
