### ISSUE TITLE
Chamfer - change radius to length 

### ISSUE THREAD

**Issue by jgomez720** [KittyCAD/modeling-app#2701]
### Description
Change `radius` parameter to `length`. Our chamfers are symmetric, so this equivalent to what we are calling radius. This is just for clarity, since radius implies that we are dealing with a curve. When we can do asymmetric chamfers, this will be a little different.

### Screenshot
Radius = 5 is the same as length = 5 (Some CAD programs treat this as 5 x 5)
<img width="1023" alt="Screenshot 2024-06-18 at 5 03 20 PM" src="https://github.com/KittyCAD/modeling-app/assets/114548659/cd056d9a-2981-433a-ad0d-93506d51261a">

### KCL
```js
const sketch001 = startSketchOn('XY')
  |> startProfileAt([-10, 10], %)
  |> line([20, 0], %, 'edge1')
  |> line([0, -20], %, 'edge2')
  |> line([-20, 0], %, 'edge3')
  |> lineTo([profileStartX(%), profileStartY(%)], %, 'edge4')
  |> close(%)

const extrusion = extrude(3, sketch001)
  |> chamfer({
    radius: 5,
    tags: [
      getNextAdjacentEdge('edge1', %),
      getNextAdjacentEdge('edge2', %),
      getNextAdjacentEdge('edge3', %),
      getNextAdjacentEdge('edge4', %)
    ],
  }, %)
```

**Comment by jgomez720** [comment]
@jessfraz assign as needed

**Comment by jessfraz** [comment]
i can fix this fast
