### ISSUE TITLE
[BUG]: Redefining a variable produces 'cannot redefine' error, works anyway

### ISSUE THREAD

**Issue by dcl** [KittyCAD/modeling-app#2716]
### Describe the bug

Consider the following KCL:
```
let test = startSketchOn('XY')
  |> circle([0, 0], 10, %)

let test = hole(circle([0,0], 9, test), test)
  |> extrude(10, %)
```

This produces a error of `Cannot redefine test`, but still works to create a hollow cylinder. At least one of these behaviors must be wrong.

### Steps to Reproduce

1. Paste the example above into any version of the modeling app

### Expected Behavior

Either this would work without complaint, or that it would produce an error and stop. The KCL documentation provides no hint as to which is the intended behavior.

### Screenshots and Recordings

![ss (2024-06-19 at 07 21 36)](https://github.com/KittyCAD/modeling-app/assets/700781/adb1128f-450d-4e1b-89bf-8c54fff3576f)

### Desktop OS

Windows 10

### Browser

Firefox

### Version

0.22.2

**Comment by dcl** [comment]
I suspect this is related to the behavior outlined in #2728, with the modification in place happening before the failing reassignment is attempted

**Comment by jtran** [comment]
> modification in place happening before the failing reassignment is attempted

You've almost got it. It's unrelated to mutation. But currently, KCL built-in functions have the side-effect of drawing. So this is happening when it evaluates the right-hand-side of the `=` before it tries to bind the result to the variable name. The binding to the name `test` that's already bound is what's causing the error.

**Comment by dcl** [comment]
> It's unrelated to mutation. But currently, KCL built-in functions have the side-effect of drawing.

This is functionally the same thing, as it is mutating the engine state, but point taken.

**Comment by jessfraz** [comment]
closing as this is just how the executor works, and the error is more for whenever you reference that variable elsewhere
