### ISSUE TITLE
On step 6 of tutorial, clicked on modeling UI in the background accidentally and received an unexpected error message

### ISSUE THREAD

**Issue by nat** [KittyCAD/modeling-app#2719]
Here's the error I saw:
<img width="667" alt="image" src="https://github.com/KittyCAD/modeling-app/assets/56260/555b2569-c5a7-4783-8e09-3f34ce362c0a">

I clicked "Reload" and got this:
<img width="1728" alt="image" src="https://github.com/KittyCAD/modeling-app/assets/56260/42fcf288-18c3-423a-bfb0-b8e42aa8917b">

It looks like the modeling UI didn't load back entirely?

**Comment by jessfraz** [comment]
likely has to do with the code not loading for the onboarding

**Comment by franknoirot** [comment]
Yup that's the issue, and the stream is coming in just slowly. Sometimes we'll see distortion with the stream but that would be more apparent with the grid being squished in the XY direction. Was your connection pretty rough here by any chance? 

The onboarding example code not loading is unrelated to connection speed, just a straight up bug I can reproduce, writing a test for it now.
