### ISSUE TITLE
if user has no avatar to click on in onboarding then the text makes no sense

### ISSUE THREAD

**Issue by jessfraz** [KittyCAD/modeling-app#2720]
also why they ahve no avatar seems super suspicious because i thought we generate one in those cases

**Comment by franknoirot** [comment]
Did you see someone hit this? We don't generate avatars in modeling app like we do in the website; we fall back to a [button that says "User menu" in a tooltip](https://github.com/KittyCAD/modeling-app/blob/main/src/components/UserSidebarMenu.tsx#L56-L65) that looks like this:

![Screenshot 2024-06-20 at 10 55 31 AM](https://github.com/KittyCAD/modeling-app/assets/23481541/988e2ab7-9f42-477b-9cc6-401e27aecdf6)

**Comment by jessfraz** [comment]
yeah so the onboarding says "avatar" tho which is the problem

**Comment by franknoirot** [comment]
Oh should be easy enough to update that text based on whether the image load succeeded or not, cool I can make a test for it
