### ISSUE TITLE
trying to extrude something that has already been extruded shoudl let the user either edit the extrusion or tell them its already extruded

### ISSUE THREAD

**Issue by jessfraz** [KittyCAD/modeling-app#2722]
if no sketches in the current file can be extruded we should not show the extrude button it is confusing, will drop a vid

**Comment by jessfraz** [comment]
https://github.com/KittyCAD/modeling-app/assets/1445228/ed7c5634-0584-4d5a-ad51-4f529972858e

**Comment by Irev-Dev** [comment]
https://github.com/KittyCAD/modeling-app/assets/29681384/84536d53-9e13-4e2e-bec5-4c2da7d18703

**Comment by Irev-Dev** [comment]
https://github.com/KittyCAD/modeling-app/assets/29681384/61364581-9f79-4d4f-8828-ac63c8c9c294

**Comment by jessfraz** [comment]
Nice those are def better

**Comment by Irev-Dev** [comment]
I've got #2730, but we can make this experience even nicer if https://github.com/KittyCAD/engine/issues/2256 is figured out

**Comment by Irev-Dev** [comment]
btw the bug I pointed out in my [second comment](https://github.com/KittyCAD/modeling-app/issues/2722#issuecomment-2181723367)  is actually a knock on from https://github.com/KittyCAD/modeling-app/pull/2549.
