### ISSUE TITLE
Randomly hit "An Unexpected Error Occurred"

### ISSUE THREAD

**Issue by jgomez720** [KittyCAD/modeling-app#2737]
### Description
I was using the Zoo Modeling App and I believe I was deleting items from the code pane, and then got hit with this page

### Version
v0.22.3

<img width="1470" alt="Screenshot 2024-06-21 at 10 49 36 AM" src="https://github.com/KittyCAD/modeling-app/assets/114548659/99dcd302-b74f-48a8-8a4d-c8bcd43db7a1">
<img width="1582" alt="Screenshot 2024-06-21 at 10 48 06 AM" src="https://github.com/KittyCAD/modeling-app/assets/114548659/cce1d330-1f22-46fa-a352-c793d3f3ac51">

**Comment by jgomez720** [comment]
going to try and reproduce. I'm not sure if this belongs to you @franknoirot I was more just putting a name down until I can figure out more about it

**Comment by jgomez720** [comment]
not reliably reproducible, I'll comment if I see it again

**Comment by jessfraz** [comment]
reopen if it happens again
