### ISSUE TITLE
Windows updater stopped working

### ISSUE THREAD

**Issue by pierremtb** [KittyCAD/modeling-app#2741]
Reported by @r-barton 

Updating from 0.22.2 to 0.22.3 doesn't work on **Windows**

Prior versions to 0.22.3 work.

This is the error message and the update doesn't get done

![image](https://github.com/KittyCAD/modeling-app/assets/10795683/42045fab-f08e-4a15-95ea-23cef7359808)

**Comment by pierremtb** [comment]
After investigating a little bit using the nightly builds https://github.com/KittyCAD/modeling-app/actions?query=event%3Aschedule, it stopped working between those two commits https://github.com/KittyCAD/modeling-app/compare/50fcdff879606e8107dcd4ec57276ca57ab2d65c..0add26cf61a390bafcb954cbf4721b0274691a19

Could be related to the bump from tauri v2 beta15 to beta22

**Comment by jessfraz** [comment]
I think its the update to the updater https://github.com/KittyCAD/modeling-app/compare/50fcdff879606e8107dcd4ec57276ca57ab2d65c..0add26cf61a390bafcb954cbf4721b0274691a19#diff-91fed938c12ef6620ac89e4130fe1f2b92c58b68083fc6bbc71c3e0f381a25cdR5732

**Comment by jessfraz** [comment]
I wanna try a hypothesis and see if it works on the new version with a new release and if not we can revert

**Comment by jessfraz** [comment]
in that maybe its just not backwards compatible ya know

**Comment by jessfraz** [comment]
actually i dont think that can be it, im going back versions, lets see

**Comment by jessfraz** [comment]
revert back to old cargo.lock, keeping open but removing high priority, its fixed now but going to be hard to update when we need to until tauri gets their stuff together

**Comment by pierremtb** [comment]
Need to make sure we're solid for this, looks like https://github.com/tauri-apps/plugins-workspace/releases/tag/updater-v2.0.0-beta.9 is out, changelog doesn't say but it has the msi fix I believe
