### ISSUE TITLE
[BUG]: helix() does not work on cylinders with a hole

### ISSUE THREAD

**Issue by dcl** [KittyCAD/modeling-app#2774]
### Describe the bug

Intuitively one might begin to describe a threaded pipe with the following KCL:
```
let threadedPipe = startSketchOn("XY")
    |> circle([0, 0], 5, %)
    |> hole(circle([0, 0], 4, %), %)
    |> extrude(20, %)
    |> helix({angle_start: 0, length: 10, revolutions: 10}, %)
```
This results in an error, with `helix()` being unable to recognize the extrude as a valid cylinder: 
![ss (2024-06-24 at 03 48 25)](https://github.com/KittyCAD/modeling-app/assets/700781/7ae409ae-9bd2-4cc8-837f-4fa1ec8103c5)

### Steps to Reproduce

1. Copy the above KCL into the app

### Expected Behavior

`helix()` would recognize a valid cylinder based on the exterior surface of the extrude group

### Desktop OS

Windows 10

### Version

0.22.6

**Comment by jessfraz** [comment]
unsure if this is an engine bug or not but @gserena01 might know

**Comment by gserena01** [comment]
It's an engine bug! I'm on it!
