### ISSUE TITLE
kcl Objects have a formatting problem

### ISSUE THREAD

**Issue by Irev-Dev** [KittyCAD/modeling-app#2780]
The following kcl
```typescript
const bing = { yo: 55 }
const myNestedVar = [{ prop: callExp(bing.yo) }]
```
when formatting the code, recasts to

```typescript
const bing = { yo: 55 }
const myNestedVar = [{ prop:   callExp(bing.yo) }]
```

Notice the extra white space before `callExp` (3 spaces instead of 1)

It must be related to the value being a call expression as `const myNestedVar2 = [{ prop: 'callExp(bing.yo)' }]` does not have the formatting problem

**Comment by jessfraz** [comment]
oh i can fix this

**Comment by jessfraz** [comment]
literally one second

**Comment by Irev-Dev** [comment]
Nice, I got another one for you if you're interested
```typescript
const myNestedVar = [
  {
  prop:   line([bing.yo, 21], sketch001)
}
]
```
Look pretty bad too

**Comment by jessfraz** [comment]
these are the same bug

**Comment by jessfraz** [comment]
oh i see you mean the params ill try

**Comment by Irev-Dev** [comment]
Yeah I meant the `}` indentation

**Comment by jessfraz** [comment]
i improved it

**Comment by jessfraz** [comment]
its not like 100% perfect but it looks better someone else can eff w it more if they wwant to

**Comment by Irev-Dev** [comment]
Sounds good.
