### ISSUE TITLE
badge icon on errors icon button panel so users know when there are errors thats where to find them

### ISSUE THREAD

**Issue by jessfraz** [KittyCAD/modeling-app#2794]
wouldnt show up if no errors but would look lke ios when yuou have messages ya know

**Comment by franknoirot** [comment]
Cool that makes sense. Should this badge disappear after the user opens the error panel for the first time since new errors have been added? And should the badge go away if the code gets updates and the errors are cleared?

**Comment by jessfraz** [comment]
moving this to high priority because it took me WAYYYY too long to realize a file had an error today 

https://github.com/user-attachments/assets/ebc4c0da-5078-476f-86a5-423543cf0b1d
