### ISSUE TITLE
Sketch on face + typing in code editor deletes all the code

### ISSUE THREAD

**Issue by jgomez720** [KittyCAD/modeling-app#2832]
### Description
When I select a face to sketch on and start the sketch mode, I decided to start typing in the code editor while still in sketch mode, if you exit the sketch mode while you have typed stuff in the editor, it will delete everything you have

### Recording
https://github.com/KittyCAD/modeling-app/assets/114548659/0f715d2a-aa1d-49c0-bc07-5fc3dff64d0d

### Version
v0.22.6 Tauri App

### KCL
I had to redo this KCL because it deleted it lol
```js
const sketch001 = startSketchOn('XZ')
  |> startProfileAt([-200, 200], %)
  |> xLine(400, %)
  |> yLine(-400, %)
  |> xLine(-400, %)
  |> lineTo([profileStartX(%), profileStartY(%)], %)
  |> close(%)
const extrude001 = extrude(200, sketch001)
```
click on the face, do what I did in the video and it should recreate

**Comment by Irev-Dev** [comment]
Thanks, I'm able to replicate, I have a hunch what might be happening here.

**Comment by Irev-Dev** [comment]
This was a very specific situation, 
It only happens if you edit directly in the editor BEFORE making any clicks with the line tool
And the code needs to have a syntax error in it. 
So it was a good catch in that sense.

#2890 has test to cover this case.
