### ISSUE TITLE
Exiting and Entering sketch changes zoom level and sometimes flips and mirrors the sketch

### ISSUE THREAD

**Issue by ZooSpiritWolf** [KittyCAD/modeling-app#2833]
🐛

Steps to reproduce:
1. Login
2. Click "Start Sketch" button
3. Click the blue plane (XZ)
4. Sketch a line
5. Note the Line scale and positioning
6. Click "Exit Sketch"
7. Open Code Panel
8. Click "startProfileAt" line in the editor
9. Click "Edit Sketch" button
10. Note the Line's new scale and positioning
Expected:
- Sketch to remain at the same scale it was drawn
- If zooming out or zooming in, sketch to remain in the same position it was drawn
Actual: 
- Sketch slightly zoomed in after entering edit mode than
- If zooming out or zooming in, sketch is sometimes in a flipped and mirrored position

Timestamp: 0:04
Video: 
https://www.loom.com/share/92928b56489d416c97a2d1051a404845 (https://www.loom.com/share/92928b56489d416c97a2d1051a404845)

Bug report:
https://app.qawolf.com/zoo/bug-reports/3aa883b5-b83f-4d62-88cc-eacdeca58e48

Affected workflows:

If you are aware of this bug you can set the priority to low which will prevent it from causing a run failure.

**Comment by Irev-Dev** [comment]
I have not been able to replicate the flipping, I can see the problem with the zoom being slightly off.

I think the problem is likely related to the hand off to the engine to animate to the sketch, and switching to orthographic.

**Comment by lf94** [comment]
I would ask them to remove this test. It's just too unreliable / undeterminable.

**Comment by Irev-Dev** [comment]
I think it does highlight an issue with the hand off between the two, this is a good impetus to do something about it.

I have some ideas I want to run past the good engine people at least.

**Comment by Irev-Dev** [comment]
I thought maybe could be solved on the FE, but does need som engine help, created
https://github.com/KittyCAD/engine/issues/2322

Even though I agree I don't think this bug is a big deal, solving it will help remove some camera hacks the the frontend had been doing.

**Comment by lf94** [comment]
@Irev-Dev maybe unassign since this is a long lived issue and notify qawolf to not do this test for now

**Comment by nadr0** [comment]
I looked at this issue and was able to recreate it. I opened a PR to solve this problem.
