### ISSUE TITLE
Reload required for Code Editor changes to take effect 

### ISSUE THREAD

**Issue by ZooSpiritWolf** [KittyCAD/modeling-app#2862]
🐛 on Dev

Steps to reproduce:
1. Login
2. Close web banner
3. Close onboarding modal
4. Wait for stream to load
5. Observe the initial sketch
6. Observe KCL Code
7. Clear KCL Code Editor
Expected: 
- Code to have syntax highlighting
- Initial sketch to disappear after clearing the editor
Actual: 
- Code does not have syntax highlighting
- Initial sketch does not disappear after clearing the editor
- CORS Policy errors in the console

Additional Context: Upon reload, Syntax Highlighting returns and clearing the KCL Code Editor correctly removes the initial sketch

Timestamp: 0:12
Video: 
https://www.loom.com/share/9b6072624db34caab581b5a4797953f4?sid=1ecb2529-b0f4-41d2-93ff-ab9085c4e961 (https://www.loom.com/share/9b6072624db34caab581b5a4797953f4?sid=1ecb2529-b0f4-41d2-93ff-ab9085c4e961)

Bug report:
https://app.qawolf.com/zoo/bug-reports/a5afcee2-b03a-4eed-8716-9f7a99c9827e

Affected workflows:
• Start Sketch on each plane - https://app.qawolf.com/zoo/workflows/clweyu8lr03hj11xbmsk0u0ry

If you are aware of this bug you can set the priority to low which will prevent it from causing a run failure.

**Comment by jessfraz** [comment]
The cors fix is deploying now should be good in like 20 min
