### ISSUE TITLE
Show default planes when scene is empty

### ISSUE THREAD

**Issue by franknoirot** [KittyCAD/modeling-app#2880]
When the user has nothing in the scene, show some default planes to give them a way to orient themselves. Here is a goal of how we would like the planes to eventually look, although they can use their current styling for now[^1]:

![view of the app with an empty scene, showing 3 labeled default planes](https://github.com/KittyCAD/modeling-app/assets/23481541/ea475d52-2a95-411e-afa1-ff19c8a866ad)

[^1]: See [this Figma flow](https://www.figma.com/design/5UUPOawPLEs3D0Gptf42vy/Designs?node-id=3231-32156&t=PQBIJPfroQjQZGTa-11) for that mockup in the broader context

**Comment by Irev-Dev** [comment]
At first I was thinking, "just show the planes"

But now I'm thinking we transition them straight to "Sketch no face" state if there's nothing in the scene, because that really is the way to get started besides typing in the editor right?

**Comment by jgomez720** [comment]
I definitely wouldn't start them in the sketch, because there are other ways to start designing. Importing a file is a big one for example
