### ISSUE TITLE
Command Bar state does not persist when alternating arguments

### ISSUE THREAD

**Issue by ZooSpiritWolf** [KittyCAD/modeling-app#2881]
🐛

- Steps to reproduce:
1. Login
2. Click the "Command Bar" button
3. Select a setting with User and Project level options
4. Start typing a value in the Value's input field
5. Note the value typed
6. Note the value currently selected for the "Level" argument
7. Click the "Level" argument button
8. Not the currently selected level matches the button's value
9. Click back to the "Value" argument
10. Observe the input field
11. Observe the "Level" button's value
Expected: 
- The value shown in the "Level" argument's button to persist when alternating tabs
- The value typed in the "Value" argument's input field to persist
Actual: 
- The value shown in the "Level" argument's button is removed when alternating tabs
- The value typed in the "Value" argument's input field does not persist
Timestamp: 0:10
Video: 
https://www.loom.com/share/1b5fad65c06b4d5fa14788efd300532a?sid=bc5b2ad7-8fdc-44ec-8893-77a2336ca7db (https://www.loom.com/share/1b5fad65c06b4d5fa14788efd300532a?sid=bc5b2ad7-8fdc-44ec-8893-77a2336ca7db)

Bug report:
https://app.qawolf.com/zoo/bug-reports/c2370041-cd5f-479c-b811-3003efd4fa10

Affected workflows:

If you are aware of this bug you can set the priority to low which will prevent it from causing a run failure.

**Comment by franknoirot** [comment]
> The value shown in the "Level" argument's button to persist when alternating tabs
This is a bug

> The value typed in the "Value" argument's input field to persist
I don't think we want this as expected behavior. The user navigated away from the current argument, and I am taking that as abandoning the current step. Tracking what they've done within a single argument would require tracking state that I do not think we want to keep track of, and would become a slippery slope. Maybe in the future
