### ISSUE TITLE
[BUG]: Ctrl + / no longer comments code

### ISSUE THREAD

**Issue by r-barton** [KittyCAD/modeling-app#2896]
In both the tauri (Windows) desktop app and web app, the command `ctrl + /` no longer works on commenting the selected line(s) of code

**Comment by Irev-Dev** [comment]
Yeah I noticed this just this morning too.

**Comment by jessfraz** [comment]
Yeah I know the reason I explained to Ryan we have to either use codemirror lexer which I really don’t want to maintain two parsers or hijack this tooOn Jul 4, 2024, at 16:42, Kurt Hutten ***@***.***> wrote:﻿
Yeah I noticed this just this morning too.

**Comment by Irev-Dev** [comment]
When this get's fixed, please also let the QAWolf team know it needs to be re-evaluated. Their link for the bug is https://app.qawolf.com/zoo/bug-reports/416582fa-36b2-49be-9d1e-45f23201ed17
