### ISSUE TITLE
Syntax highlighting is slow

### ISSUE THREAD

**Issue by Irev-Dev** [KittyCAD/modeling-app#2925]
Could my deferred theory have merit Jess?

https://github.com/KittyCAD/modeling-app/assets/29681384/f4d1ce17-a18a-4866-9b10-eb6bac1b7489

**Comment by jessfraz** [comment]
Could be but more likely just semantic tokens takes a bit

**Comment by jessfraz** [comment]
I don’t think we’d want to remove the deferrer honestly or else shit would get super backed up

**Comment by Irev-Dev** [comment]
Okay,

why does the current syntax highlight have to disappear when there's an edit?

**Comment by jessfraz** [comment]
This will be fixed when we go back to a codemirror lexer

**Comment by jessfraz** [comment]
It’s the decorators

**Comment by Irev-Dev** [comment]
If it'll get closed out for free with something else. I'm thinking we might as well close now instead of trying to track down later.
