### ISSUE TITLE
Make KCL tags scoped by functions

### ISSUE THREAD

**Issue by franknoirot** [KittyCAD/modeling-app#2928]
This KCL code does not work:

```kcl
fn rect = (origin) => {
  return startSketchOn('XZ')
  |> startProfileAt(origin, %)
  |> angledLine([0, 191.26], %, $rectangleSegmentA001)
  |> angledLine([
       segAng(rectangleSegmentA001, %) - 90,
       196.99
     ], %, $rectangleSegmentB001)
  |> angledLine([
       segAng(rectangleSegmentA001, %),
       -segLen(rectangleSegmentA001, %)
     ], %, $rectangleSegmentC001)
  |> lineTo([profileStartX(%), profileStartY(%)], %)
  |> close(%)
}

rect([0, 0])
rect([20, 0]) // <--- this line of code breaks
```

Because tags are global, the tags defined in the function count as being `redefined` when the second rectangle is called.

Instead, we should make tags scoped based on where they're defined, starting with a global scope by default, so that the two calls to `rect()` create two distinct sets of scoped tags.

**Comment by jtran** [comment]
Related:

- #1285

**Comment by jessfraz** [comment]
yeah these behave different than variables so i can fix this without fixing https://github.com/KittyCAD/modeling-app/issues/1285

**Comment by jessfraz** [comment]
I can fix https://github.com/KittyCAD/modeling-app/issues/1285 at the same time but wanted to give you a shot at it to learn the ast, but if you already got a lot on your plate im happy to kill two birds one stone

**Comment by jtran** [comment]
Don't let me stop you if you think it's similar enough to #1285 to do them both. In my opinion, tags _are_ variables, except they have their own namespace.

**Comment by Irev-Dev** [comment]
Related to https://github.com/KittyCAD/modeling-app/issues/2929 too right?
