### ISSUE TITLE
functions that operation on a tag should not require the %

### ISSUE THREAD

**Issue by jessfraz** [KittyCAD/modeling-app#2942]
One thing that annoys me about tags now that they are high level is they should map directly back to the uuid in engine so like `getNextAdjacentEdge(bs.tags.edge7, %)` should just be `getNextAdjacentEdge(bs.tags.edge7)` like you should not need the `%`

part of https://github.com/KittyCAD/modeling-app/pull/2941 and making tags high level functions

- [ ] #2943
- [x] remove getEdge
- [ ] #3144

**Comment by Irev-Dev** [comment]
Yes, I agree! (and @max-mrgrsk will too)

It makes it much more cumbersome to use, I know you mentioned the `%`, but I would assert that having to include the variable and the tag is less of a pain within the same pipeExpression with the `%` when compared to matching up a tag and some other variable as can be the case for sketchOnFace, will also make the AstMods much easier since we don't need to track down the exact right variable to slot in.

Feels like a win on all fronts.

**Comment by max-mrgrsk** [comment]
totally agree! super nice idea and it looks so much cleaner

**Comment by jessfraz** [comment]
yeah I started on a PR for this, its going to be a bit because its more involved than i realized , it will get there but ill do it in small changes lol

**Comment by jtran** [comment]
Can someone explain this to me? `getNextAdjacdntEdge()` uses the extrude group.

https://github.com/KittyCAD/modeling-app/blob/6e7e6e96cfadffd5590863546133121f9d58505c/src/wasm-lib/kcl/src/std/fillet.rs#L283-L292

Are you saying that we can skip this step using only the tag and prior information?

I also want to make sure that we're not breaking the rule that the pipe operator is syntax sugar to convert this:

```
a |> b(%) |> c(%) |> d(%)
```

to this:

```
d(c(b(a)))
```

**Comment by jessfraz** [comment]
it will make this:
```
const width = 20
const length = 10
const thickness = 1
const chamferLength = 2

const mountingPlateSketch = startSketchOn("XY")
  |> startProfileAt([-width / 2, -length / 2], %)
  |> lineTo([width / 2, -length / 2], %, $edge1)
  |> lineTo([width / 2, length / 2], %, $edge2)
  |> lineTo([-width / 2, length / 2], %, $edge3)
  |> close(%, $edge4)

const mountingPlate = extrude(thickness, mountingPlateSketch)
  |> chamfer({
       length: chamferLength,
       tags: [
         getNextAdjacentEdge(edge1, %),
         getNextAdjacentEdge(edge2, %),
         getNextAdjacentEdge(edge3, %),
         getNextAdjacentEdge(edge4, %)
       ]
     }, %)

```

be this:

```
const width = 20
const length = 10
const thickness = 1
const chamferLength = 2

const mountingPlateSketch = startSketchOn("XY")
  |> startProfileAt([-width / 2, -length / 2], %)
  |> lineTo([width / 2, -length / 2], %, $edge1)
  |> lineTo([width / 2, length / 2], %, $edge2)
  |> lineTo([-width / 2, length / 2], %, $edge3)
  |> close(%, $edge4)

const mountingPlate = extrude(thickness, mountingPlateSketch)
  |> chamfer({
       length: chamferLength,
       tags: [
         getNextAdjacentEdge(edge1),
         getNextAdjacentEdge(edge2),
         getNextAdjacentEdge(edge3),
         getNextAdjacentEdge(edge4)
       ]
     }, %)
```

not changing the behvior of pipes
