### ISSUE TITLE
Editing a sketch that has an extrude in the same pipe expression fails to update scene

### ISSUE THREAD

**Issue by franknoirot** [KittyCAD/modeling-app#2958]
I discovered this while debugging failed tests for line length indicators. I thought that our "Can undo a sketch modification with ctrl+z" test was failing due to this and it was an issue with my branch, but it turns out this is happening on main and I just misunderstood what that test was doing.

## Steps to reproduce
1. Use some sample code below to start with a sketch that is piped into an extrude call
2. Click a face on the extrude and click Edit Sketch
3. Try to drag one of the sketch segment's handles
4. Observe that the sketch shape doesn't update, but the code does, and that there are many errors in the console

I believe this is because [in updateSegment here](https://github.com/KittyCAD/modeling-app/blob/main/src/clientSideScene/sceneEntities.ts#L1078-L1080) we assume this `sketchGroup` is actually a sketchGroup, but in the case where the pipe expression contains an extrude call the real sketch group is present on `sketchGroup.sketchGroup`.

## Sample code
```kcl
const sketch001 = startSketchOn('XZ')
    |> startProfileAt([4.61, -14.01], %)
    |> line([12.73, -0.09], %)
    |> tangentialArcTo([24.95, -5.38], %)
    |> close(%)
    |> extrude(5, %)
```

## Demo

https://github.com/KittyCAD/modeling-app/assets/23481541/e8ab7605-7daf-4285-bbde-9387e41c86f6

**Comment by lf94** [comment]
Stolen

**Comment by lf94** [comment]
Fixed :)
