### ISSUE TITLE
Unable to comment out code using Control + /

### ISSUE THREAD

**Issue by ZooSpiritWolf** [KittyCAD/modeling-app#2968]
🐛 on Dev

Steps to reproduce:
1. Log in
2. Navigate to Modeling App
3. in the KCL Code editor, select everything using Cmd + A
4. Attempt to comment out the selected areas with Control + /
Expected: Code is commented out
Actual: Code is not commented

Video: 
https://www.loom.com/share/e9abbc81cbd845f9a3a71bffc54725e3?sid=2bc417f7-8e21-407b-a243-8e8e3ab9e4cb (https://www.loom.com/share/e9abbc81cbd845f9a3a71bffc54725e3?sid=2bc417f7-8e21-407b-a243-8e8e3ab9e4cb)

Bug report:
https://app.qawolf.com/zoo/bug-reports/416582fa-36b2-49be-9d1e-45f23201ed17

Affected workflows:
• Comment & Uncomment Code - https://app.qawolf.com/zoo/workflows/clwh4n3uz0f1wi92v1sja5377

If you are aware of this bug you can set the priority to low which will prevent it from causing a run failure.

**Comment by Irev-Dev** [comment]
Duplicates https://github.com/KittyCAD/modeling-app/issues/2896
