### ISSUE TITLE
Editor can get into a state where cursor position and document contents change unexpectedly

### ISSUE THREAD

**Issue by franknoirot** [KittyCAD/modeling-app#2993]
I managed to capture a video, but dang it all I can't seem to reproduce this after the fact. I'm sorry, if I see it again I'll be sure to smash that coredump shortcut.

https://github.com/KittyCAD/modeling-app/assets/23481541/540971ce-5f1e-4093-a914-1f22ff2f4436

This seems to occur after extended code editing, but I may be mistaken. In order to shake it off I had to Cmd+A and Cmd+C to copy the contents, delete them all, and refresh and paste. Trying to make any edits wouldn't persist, and moving around the code would cause changes, undos (or what felt like it), and other spooky behavior.

**Comment by jessfraz** [comment]
This is a race that marijn has a fix for I just need to push it up but it’s the classic out of range bullshit

**Comment by jessfraz** [comment]
I know the cause so don’t worry

**Comment by franknoirot** [comment]
Oh phew I thought it was the result of some Marijn and was bugging, that's great.
