### ISSUE TITLE
[BUG]: Keyboard shortcut to open command palette collides in Firefox

### ISSUE THREAD

**Issue by jtran** [KittyCAD/modeling-app#3000]
### Describe the bug

In Firefox, Command+K [focuses on the search bar](https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly). I ran into this the first time I used the modeling app because the tour on first use tells you to press the shortcut.

If we use Command+K, we should not also do the browser's default, i.e. we should make sure we're calling `event.preventDefault()`.

Alternatively, we could use a different shortcut. Command+Shift+P is the default for the command palette in both [Sublime Text](https://rowannicholls.github.io/sublime_text/key_bindings.html) and [VS Code](https://code.visualstudio.com/docs/getstarted/keybindings#_advanced-customization).

### Steps to Reproduce

1. Open the app in Firefox
2. Press the keyboard shortcut for the command palette: Command+K or Ctrl+K

### Expected Behavior

I expect the command palette to open. Instead, it opens, but also the Firefox search bar opens and moves the keyboard focus there.

### Screenshots and Recordings

<img width="953" alt="Screenshot 2024-07-10 at 6 09 48 PM" src="https://github.com/KittyCAD/modeling-app/assets/10803/8395d381-c63f-40fc-949d-617ca6b0fb80">

### Desktop OS

macOS 14.6

### Browser

Firefox

### Version

127

**Comment by jessfraz** [comment]
closing since firefox wont be a priority or supported
