### ISSUE TITLE
[FEATURE]: Open Modeling App after update

### ISSUE THREAD

**Issue by r-barton** [KittyCAD/modeling-app#3018]
[On Windows] The modeling app does not open after installing the latest update. I think for a good UX, the modeling app was already opened, we should provide an option to the user at the end of the installer to open the latest installed version. Currently the installer just exits with no option to open the app.

**Comment by jessfraz** [comment]
this is def on the tauri side

**Comment by jessfraz** [comment]
also windows specific on macos this works

**Comment by jessfraz** [comment]
@pierremtb was sayign this works now, @r-barton can you confirm

**Comment by r-barton** [comment]
Did not work on my machine when updating the app. I started from v0.24.2 of the modeling app. Screen recording attached. If I run the installer as a fresh install I do get the option to open the app after installation is complete

https://github.com/user-attachments/assets/5bbc6e26-93a1-4449-80cb-cd5f96dbbfe4

**Comment by r-barton** [comment]
So I think this issue is partially solved

**Comment by jessfraz** [comment]
yes i always got that too and its not working on upgrade for me, will follow up after next release to see if fixed making sure it wasnt just me

**Comment by pierremtb** [comment]
Sorry for the confusion, this should get fixed as part of https://github.com/KittyCAD/modeling-app/pull/2815 as we're bumping a few tauri dependencies. But hasn't landed on main or in releases yet!

**Comment by pierremtb** [comment]
Stumbled on it while looking for something else: the feature was added upstream 2 weeks ago with https://github.com/tauri-apps/plugins-workspace/pull/1498

**Comment by jessfraz** [comment]
we should test this works with electron after the first release

**Comment by pierremtb** [comment]
https://github.com/KittyCAD/modeling-app/pull/3600#issuecomment-2307704325

**Comment by jessfraz** [comment]
I think this is fine now
