### ISSUE TITLE
More of the logic in `AST fillet` action should be tested

### ISSUE THREAD

**Issue by Irev-Dev** [KittyCAD/modeling-app#3036]
The function `addFillet` has some unit tests, but there's plenty of logic that goes into the AST mod that is still in the `AST fillet` action that isn't captured by these tests.

We could put more in a testable function, something like
```typescript
function AstFillet(ast: Program, selections: Selections, cmdValue: KclCommandValue: programMemory: ProgramMemory): Program {
  // ...
}
```
☝️ I might be missing inputs, main thing I'm worried about is the `pathToExtrudeNode` being neglected

**Comment by max-mrgrsk** [comment]
### Added tests for getPathToExtrudeForSegmentSelection:

Implemented tests to check if the function correctly identifies extrude paths from selected segments in different sketches. The tests cover various scenarios, including multiple extrusions and cases where no extrusion exists, ensuring the logic works as expected.
