### ISSUE TITLE
Idle Happening Too Fast on Focused Window

### ISSUE THREAD

**Issue by jgomez720** [KittyCAD/modeling-app#3040]
### Description
This technically has two issues:
- The idle is happening even when the window is focused. During a call with Me, Paul, and Jess, I had the Modeling App open and would stop to talk with the guests. While I was talking, the modeling app would go in idle. If the Modeling App is focused, idle shouldn't happen at all.
- Idling is happens too quick. Sometimes when modeling I have to reference something else (say like a spreadsheet with tolerance numbers) and flip back. The model is gone within seconds of switching to a new window. Can we increase that time a bit? 

### Version
v0.24.1

**Comment by Irev-Dev** [comment]
This might have been resolved by https://github.com/KittyCAD/modeling-app/pull/3032? maybe @lf94 ?

**Comment by lf94** [comment]
eh guess we need to further increase from 2min to like 20 for mouse  idle
