### ISSUE TITLE
TagDeclarators cannot be used as function parameters

### ISSUE THREAD

**Issue by jtran** [KittyCAD/modeling-app#3071]
This is a weird use of TagDeclarators that we may not care about, but I wanted to write down everything I learned about them.

A TagDeclarator like `$a` cannot be passed as a parameter and used.

```kcl
fn pentagon = (len, taga, tagb, tagc) => {
  const sg = startSketchOn('XY')
  |> startProfileAt([-len / 2, -len / 2], %)
  |> angledLine({ angle: 0, length: len }, %,taga) // <-- taga does not modify ProgramMemory here.
  |> angledLine({
       angle: segAng(a, %) + 180 - 108, // <-- After merging #3015, `a` is not defined here.
       length: len
     }, %, tagb)
  |> angledLine({
       angle: segAng(b, %) + 180 - 108,
       length: len
     }, %,tagc)
  |> angledLine({
       angle: segAng(c, %) + 180 - 108,
       length: len
     }, %, $d)
  |> angledLine({
       angle: segAng(d, %) + 180 - 108,
       length: len
     }, %)

  return sg
}

const p = pentagon(32, $a, $b, $c) // <-- `a` gets defined in ProgramMemory here.
  |> extrude(10, %)
```

This was revealed by #3015. Prior to that, it used to work because there was only a single global scope. The TagIdentifier was defined in that global scope of ProgramMemory, and that's what was being used inside the function.

The issue is that evaluating a TagDeclarator like `$foo` binds an identifier `foo` to its corresponding TagIdentifier, but returns the TagDeclarator. If you have a TagDeclarator passed in as a parameter to a function, you can never get its corresponding TagIdentifier.

https://github.com/KittyCAD/modeling-app/blob/6e7e6e96cfadffd5590863546133121f9d58505c/src/wasm-lib/kcl/src/ast/types.rs#L2048-L2059

When a TagDeclarator is stored in a variable like a function parameter, looking up the identifier `foo` in ProgramMemory doesn't re-evaluate the TagDeclarator; it (sensibly) assumes it has already been evaluated.

This seems like a case where TagDeclarator and TagIdentifier evaluation needs to be revisited, especially now that we have scoped tags #2941.

**Comment by jessfraz** [comment]
yeah I think its fine for this not to be supported, its an anti-pattern

**Comment by jtran** [comment]
Jess, I know you don't like a whole lot of issues open, so I'm going to close this 🙂

I think that in the future we can either add a static check to disallow this or make function calls to functions that can create tags inspect the argument and define it, similar to an output parameter.
