### ISSUE TITLE
Double-click to open KCL file doesn't navigate to `/file/*` route until user has navigated there conventially first

### ISSUE THREAD

**Issue by franknoirot** [KittyCAD/modeling-app#3074]
1. Install the app
2. Close it without opening a project file
3. Double-click a KCL file on your computer
4. The automatic routing to the `/file/*` route will not work

This I believe is because there is no AppState yet until the user navigates into `/file/*` after opening the app conventionally, which we currently need to do the automatic routing thing on double-click-to-open.

**Comment by jessfraz** [comment]
The curious thing about this is I’ve installed the app numerous times this week and auto double clicked on a downloads file not like in my projects and like it’s fine, I have no idea what this bug is basically

**Comment by jessfraz** [comment]
It doesn’t make any sense to me why tauri wouldn’t be sending the state in this case, it’s a poorly named variable app state it’s just the state that comes from the rust side when you double click

**Comment by lf94** [comment]
@jessfraz I will take this since it's part of the File Behavior bug group

**Comment by lf94** [comment]
Just tested it; it's definitely fixed on Mac!
