### ISSUE TITLE
Segment length indicators get unweildy at scale

### ISSUE THREAD

**Issue by Irev-Dev** [KittyCAD/modeling-app#3076]
take a script that has large values

```js
const sketch002 = startSketchOn('XZ')
  |> startProfileAt([977.86, 1889.8], %)
  |> line([2505.09, 461.46], %)
  |> line([-122.94, -2915.18], %)
  |> line([-1871.89, -1464.62], %)
  |> line([-524.76, 1174.83], %)
  |> lineTo([profileStartX(%), profileStartY(%)], %)
  |> close(%)
```

Go into sketch mode

numbers don't match with the segments very well.

![image](https://github.com/user-attachments/assets/d6f971f7-d742-4711-8533-4872fee92177)

Video is better

https://github.com/user-attachments/assets/3502d645-8dea-41cf-803f-76d86ae68854

**Comment by Irev-Dev** [comment]
I'll CC but won't assign @franknoirot

**Comment by franknoirot** [comment]
Woah gnarly!

**Comment by Irev-Dev** [comment]
Thinking this might be a good one for @nadr0.

Here's the PR where these were initially added
https://github.com/KittyCAD/modeling-app/pull/2935/files

@franknoirot if you have any more context or theories of what might be happening feel free to chip in.

**Comment by franknoirot** [comment]
Yes, I feel somewhat confident that it is because [this code](https://github.com/KittyCAD/modeling-app/blob/main/src/clientSideScene/sceneEntities.ts#L1392-L1409) where we calculate the text and position of these length labels do not take scale or the current zoom level properly into account.
