### ISSUE TITLE
Close and Open code pane breaks syntax highlighting

### ISSUE THREAD

**Issue by Irev-Dev** [KittyCAD/modeling-app#3077]
1. observe syntax highlighting
2. close code pane
3. open code pane
4. observe different/broken syntax highlighting

![2024-07-19 10 10 06](https://github.com/user-attachments/assets/08122980-3eb1-428a-9865-e7df3ced9ab0)

Not going to assign anyone, but CC @franknoirot and @jessfraz, (not sure if editor or pane problem)

**Comment by jessfraz** [comment]
Super weird because it’s all just codemirror now, maybe I fucked up the codemirror react thing when we got rid of the other plugin?

**Comment by jessfraz** [comment]
I 100% am convinced it’s the react component I made, the theme gets set thru there, I’m sorry I literally am not good enough at react to properly figure this out

**Comment by jessfraz** [comment]
Mostly because admittedly I didn’t know what I was doing in the first place

**Comment by jessfraz** [comment]
Maybe @lf94 can help 🙏

**Comment by jessfraz** [comment]
Moved to high priority since it’s a regression and we can get qa wolf to add a test

**Comment by lf94** [comment]
Roger
