### ISSUE TITLE
Electron test: (regression) deleting all files, creating multiple untitled files, creating a file with the same name, creating a file and renaming it to an already existing file

### ISSUE THREAD

**Issue by franknoirot** [KittyCAD/modeling-app#3088]
It must be something about our routing logic sending the user to a fallback part that is causing the issue, probably assuming a `main.kcl`. We should just send the user to the project root because we have Rust-side fallback logic that will go to the first available file or create a `main.kcl` if no KCL files at all are found.

## Demo

https://github.com/user-attachments/assets/af0b3f2c-5c11-4e0b-b410-c170c0057397

**Comment by jessfraz** [comment]
we will want a tauri test/electron test/playwright test whatever for this

**Comment by jessfraz** [comment]
be sure to test this as well:

open project -> rename main.kcl to hello.kcl
restart app, go back, try to open settinsg

**Comment by jessfraz** [comment]
create a new file with the same same; delete all files; create a new file leave it as Untitled, create another, etc

**Comment by lf94** [comment]
> delete all files;
This causes the stream to not reload the model, leaving the old model there (but deletes all the code)

**Comment by lf94** [comment]
> create new file with same name

This causes the old file to be overwritten with no warning.

**Comment by lf94** [comment]
Both are fixed now in the upcoming PR.

**Comment by lf94** [comment]
Resolved by https://github.com/KittyCAD/modeling-app/pull/3679
