### ISSUE TITLE
Trackpad controls improvement

### ISSUE THREAD

**Issue by lf94** [KittyCAD/modeling-app#3093]
Jordan: Can pan not be shift+drag, zoom be normal trackpad zoom (two finger touch), and rotate be alt + drag?

![Image](https://github.com/user-attachments/assets/adbd95ba-abc1-4352-ad75-9f30760f59d0)

**Comment by jtran** [comment]
@franknoirot [said](https://kittycadworkspace.slack.com/archives/C06L2RHP9SL/p1721619100934319?thread_ts=1721611737.200859&cid=C06L2RHP9SL):

> Left-click actions are selection, and shift+left click will eventually be area selection when we get around to it, so we need a modifier key.

So I'm guessing OP meant "Can pan not be **alt**+shift+drag?" And Frank's answer was no.

> The zoom should say something other than scroll wheel though lol, that's not very trackpaddy

This was already changed to "Scroll" in #3648.

> Can ... zoom be normal trackpad zoom (two finger touch), and rotate be alt + drag?

It already is these things. Maybe Jordan was confused by the UI labels. These were generally improved by #3648.

So can this be closed as completed? I feel that this is related to #3112, but that's asking for a lot more.

**Comment by lf94** [comment]
Cool yeah if there are more problems we will open a new one with more specific issues.
