### ISSUE TITLE
Mention of "OS" should be actual OS specific key

### ISSUE THREAD

**Issue by lf94** [KittyCAD/modeling-app#3095]
Jordan: should be consistent here, or modify based on detected OS. Is “OS” the “windows” key? What is the equivalent of that on mac? Can mac users just have it updated to “option”?

![Image](https://github.com/user-attachments/assets/9b9880ad-108d-4d5d-943a-03a4df32ceb1)

**Comment by jtran** [comment]
Yes, this is the Windows key on Windows. But it's Command on Mac, not Option. I'm working on a fix for this to make everything clearer.
