### ISSUE TITLE
Tab auto-complete of stdlib functions should not confirm to alphabetical order

### ISSUE THREAD

**Issue by Irev-Dev** [KittyCAD/modeling-app#3110]
It appears that autocomplete for object properties is in alphabetical order, which can be unintuitive since it will put `end` before `start`

![image](https://github.com/user-attachments/assets/f40f9ace-cb44-452a-a913-3fdddd301347)

**Comment by jessfraz** [comment]
I have a fix for this but @jgomez720 if you want the order changed on any of the others let me know, for autocomplete! now the autocompleter will preserve the order from the struct definition so easy to change
