### ISSUE TITLE
Patterns clone more than they're supposed to

### ISSUE THREAD

**Issue by Irev-Dev** [KittyCAD/modeling-app#3127]
The following code is supposed to pattern only the circular knob on top of the brick, but it instances the base as well

![image](https://github.com/user-attachments/assets/5d44804f-396f-4916-8fec-1d24efde9fb0)

Not sure exactly what's happening but maybe execution is sending too many uuids through, seems like that might be the case

![image](https://github.com/user-attachments/assets/67072fc8-90e3-48ab-a192-2485f55ed36b)

The kcl:

```js
// Lego Brick


const lbumps = 10 // number of bumps long
const wbumps = 6 // number of bumps wide
// const thin = true  // True for thin, False for thick


const pitch = 8.0
const clearance = 0.1
const bumpDiam = 4.8
const bumpHeight = 1.8
const height = 3.2
// if thin:
// height = 3.2
// else:
// height = 9.6


const t = (pitch - (2 * clearance) - bumpDiam) / 2.0
const postDiam = pitch - t // works out to 6.5
const total_length = lbumps * pitch - (2.0 * clearance)
const total_width = wbumps * pitch - (2.0 * clearance)

const lSegments = total_length / (lbumps + 1)
const wSegments = total_width / (wbumps + 1)

// make the base
// s = cq.Workplane("XY").box(total_length, total_width, height)
const s = startSketchOn('XY')
  |> startProfileAt([-total_width / 2, -total_length / 2], %)
  |> line([total_width, 0], %)
  |> line([0, total_length], %)
  |> line([-total_width, 0], %)
  |> close(%)
  |> extrude(height, %)

  // shell inwards not outwards
  // s = s.faces("<Z").shell(-1.0 * t)

const shellExtrude = startSketchOn(s, "start")
  |> startProfileAt([
       -(total_width / 2 - t),
       -(total_length / 2 - t)
     ], %)
  |> line([total_width - (2 * t), 0], %)
  |> line([0, total_length - (2 * t)], %)
  |> line([-(total_width - (2 * t)), 0], %)
  |> close(%)
  |> extrude(-(height - t), %)

const peg = startSketchOn(s, "end")
  |> circle([
       -(total_width / 2 - wSegments),
       -(total_length / 2 - lSegments)
     ], bumpDiam / 2, %)
  |> extrude(bumpHeight, %)
  |> patternLinear3d({
       axis: [1, 0, 1],
       repetitions: 3,
       distance: 10
     }, %)
```     

Originally an engine issue, but seems to be on our end https://github.com/KittyCAD/engine/issues/1905

**Comment by jessfraz** [comment]
You are patterning the solid which is a sketch on face on another solid, so its all underlying the same "uuid" to the engine, josh hit this too, the work around is pattern the sketch _then_ extrude, look at the lego code as an exmaple

**Comment by jessfraz** [comment]
see this same issue: https://github.com/KittyCAD/engine/issues/1905 its hard for us to know your intent honestly

**Comment by jessfraz** [comment]
this is an old video 

https://github.com/user-attachments/assets/98fdda82-df60-408e-8953-6778f55d912c

**Comment by jessfraz** [comment]
closing as this was solved w using 2d sketches, and anything else would need engine not to eat the id of the solid, also its just hard to disambiguate, just watch the video or look at joshes lego sample
