### ISSUE TITLE
Error tooltip missing CSS

### ISSUE THREAD

**Issue by ZooSpiritWolf** [KittyCAD/modeling-app#3170]
🐛 on Dev

Steps to reproduce:
1. Login
2. Fill editor with malformed KCL code
3. hover over error marker
Expected: 
Error tooltip with CSS (red border left)
Actual: 
Tooltip missing CSS
Video: 
https://www.loom.com/share/99f2dabb74974b82aa56b3cedf1df2d3?sid=97262649-438b-488e-83b7-bbe04b7f6fce (https://www.loom.com/share/99f2dabb74974b82aa56b3cedf1df2d3?sid=97262649-438b-488e-83b7-bbe04b7f6fce)

Bug report:
https://app.qawolf.com/zoo/bug-reports/5ac1f200-0783-4dcc-9174-b1a76ed2bf46

Affected workflows:
• Enter KCL Expressions - https://app.qawolf.com/zoo/workflows/clwdt12av00ix11xbfij6ikrq

If you are aware of this bug you can set the priority to low which will prevent it from causing a run failure.

**Comment by jessfraz** [comment]
not really that bad a regression but when we made tool tips selectable they lost some style

**Comment by jessfraz** [comment]
https://github.com/KittyCAD/modeling-app/pull/3149

**Comment by jackdelamotte** [comment]
Ack! Sorry!

**Comment by jessfraz** [comment]
oh. no worries i didnt notice either!

**Comment by jackdelamotte** [comment]
Just to confirm before I go down a rabbit hole, no other commits were made today that would have impacted tooltip styling, right? I'm back on my local feature branch from yesterday and I still see the red bar as well as the red squiggles but I'm not seeing those on a fresh pull from main now

feature branch:
<img width="535" alt="image" src="https://github.com/user-attachments/assets/6251babb-c5e2-42d0-b99b-7760d3bee34f">

main:
<img width="596" alt="image" src="https://github.com/user-attachments/assets/cd25b818-c7b8-48a1-8c24-f7a89a10b3db">

**Comment by jessfraz** [comment]
oh weird, maybe... cc @franknoirot

**Comment by jessfraz** [comment]
oh I know what it is, its not you... i can fix

**Comment by jackdelamotte** [comment]
Oh yay! Awesome

**Comment by jessfraz** [comment]
sorry about that!

**Comment by jackdelamotte** [comment]
nw!
