### ISSUE TITLE
[BUG]: Failed exports appear to hang at exporting.

### ISSUE THREAD

**Issue by iterion** [KittyCAD/modeling-app#3203]
### Describe the bug

When attempting to export the toast showing "Exporting..." never goes away if the export actually fails. So, it appears that the export just hangs forever.

<img width="1647" alt="Screenshot 2024-07-31 at 11 41 29 AM" src="https://github.com/user-attachments/assets/86d91e82-288f-46f9-a10c-9aefd5de6376">

### Steps to Reproduce

```
const outer_diameter = 4.47
const outer_radius = outer_diameter / 2
const height = 3.6
const y_thickness = 0.25
const x_thickness = 0.15
const flat_thickness = 0.1
const back_flat_thickness = 0
const hole_diam = 0.384
const hole_spacing = 2.36
const stage_height = hole_diam*2
fn earProfile = (plane) => {
  const prof = startSketchOn(plane)
    |> startProfileAt([outer_radius, 0], %)
    |> yLineTo(0.01, %)
    |> tangentialArcTo([0.00001, height], %)
    |> yLine(-y_thickness, %)
    |> angledLine({ angle: -30, length: 0.00001 }, %)
    |> tangentialArcTo([outer_radius - x_thickness, 0], %)
    |> close(%)
  return prof
}
const earLeft = earProfile('XZ')
  |> revolve({ axis: "Y", angle: 180 }, %)
// const earRight = earProfile('YZ')
//   |> revolve({ axis: "Y", angle: -90 }, %)
const stage = startSketchOn('XY')
  |> startProfileAt([
       outer_radius + back_flat_thickness / 2,
       0
     ], %)
  |> yLine(outer_radius, %)
  |> xLineTo(-(outer_radius + back_flat_thickness / 2), %, $stage_back)
  |> yLineTo(0, %)
  |> close(%, $stage_front)
  |> extrude(-stage_height, %)
const hole001 = startSketchOn(stage, stage_front)
  |> circle([hole_spacing/2, -hole_diam], hole_diam/2, %)
  |> extrude(-outer_radius, %)
const ho002 = startSketchOn(stage, stage_front)
  |> circle([-hole_spacing/2, -hole_diam], hole_diam/2, %)
  |> extrude(-outer_radius, %)
```
kcl to use to reproduce export failure atm. Will need to be fixed in format probably. 

Load the above KCL, then click export in any format.

### Expected Behavior

Failed exports should surface errors and not appear to hang forever.

### Desktop OS

all

### Browser

all

### Version

all

**Comment by jessfraz** [comment]
we can probably make a playwright test of a failing export as well to make sure this doesnt regress

**Comment by lf94** [comment]
If no one picks this up I can get on it after the theme problem which shouldn't take very long

**Comment by franknoirot** [comment]
Yo that code no longer causes an error, is there another way to reproduce this reliably? In the meantime I can find where the error is and stub it to force an error

**Comment by jessfraz** [comment]
basically it would be like the command id comes back with an error versus the export data, so hitting another code path

**Comment by lf94** [comment]
Actually I'm seeing this may be fixed now also. I'll keep trying to trigger it but when I input invalid kcl or empty kcl modeling-app seems to handle it well, showing a toast error message

**Comment by jessfraz** [comment]
yeah when it occurs is when engine returns an error to the websocket, ill deploy an engine and fix but we might need mocks to prevent regressions of it, but for now ill just fix it

**Comment by jessfraz** [comment]
heres the branch im using to trigger and it def isnt fixed https://github.com/KittyCAD/engine https://github.com/KittyCAD/engine/tree/jess/engine-fail-every-export-for-testing
