### ISSUE TITLE
Remove double "zoom_to_fit"

### ISSUE THREAD

**Issue by Irev-Dev** [KittyCAD/modeling-app#3217]
in https://github.com/KittyCAD/modeling-app/pull/3205

A hack was added to stop weird ness with zoom to fit, in that the zoom_to_fit code was duplicated so it makes the request twice in a row

![image](https://github.com/user-attachments/assets/6fa12dff-48a3-4dd7-9cf9-ef5696b8412e)

This smells like a race condition, or some other client side bug, but my best theory is that it's related to  https://github.com/KittyCAD/engine/issues/2310, and that's because of some [debugging code](https://github.com/KittyCAD/modeling-app/pull/3216) I was trying out 

Explanation here:

https://github.com/user-attachments/assets/275373ca-e99a-4278-96ea-f267601a9985

But essentially the first zoom to fit looks wrong and it takes a second for it to to come good.

Other work around attempts

### Don't send an empty array

https://github.com/KittyCAD/engine/issues/2310 has been difficult to replicate in the engine, so it's likely something unique about the scene when the modeling app has connected to it, it might be that there are more default planes created and they are effecting the zoom to fit, but I don't want to speculate too much. However I thought it might be worth looping over the artifactMap and sending through all of the `start_path` ids in `object_ids` the API because these become the object ids, however this had no effect.

### Delete default planes for zooming

I did try
```
delete planes
zoom to fit
re-create planes
```
To make sure there wasn't anything extra in the scene but this didn't work either.

**Comment by Irev-Dev** [comment]
I might be wrong about the above, but it's my best theory atm, and I think the double zoom_to_fit probably needs to stay there until https://github.com/KittyCAD/engine/issues/2310 is closed out.

anyone else is welcome to look into it though ofc.

**Comment by jessfraz** [comment]
I’m marking as high priority because if feels like bandaidig over these versus fixing will fuck us in the limit

**Comment by jessfraz** [comment]
looks like this was closed in engine, we good here?

**Comment by Irev-Dev** [comment]
Yup we good.
