### ISSUE TITLE
[CRYPTIC]: function with no defined return results in error at callsite, not function definition 

### ISSUE THREAD

**Issue by paultag** [KittyCAD/modeling-app#3224]
### Paste minimal KCL source that produces a cryptic error

```javascript
fn test = (origin) => {
  origin
}

test([0, 0])
```

### Expected Behavior

The error in this case (no defined return) ought to be placed on the function declaration, not at the callsite(s)

**Comment by jessfraz** [comment]
thats right here for anyone who gets to it before me: https://github.com/KittyCAD/modeling-app/blob/b32f5c1d4e7040fbe8dd4be2441fd539931a5be4/src/wasm-lib/kcl/src/ast/types.rs#L1499
