### ISSUE TITLE
file pane is a weird ux

### ISSUE THREAD

**Issue by jessfraz** [KittyCAD/modeling-app#3248]
video attached

but dont create the file/folder by default, instead wait until they input something

otherwise you just have more clicks to delete this file you didnt want

https://github.com/user-attachments/assets/85d2e582-a7e1-4eaf-b685-4908e655783f

**Comment by franknoirot** [comment]
Currently, clicking these buttons in the file pane UI immediately creates a new file or folder with the name "Untitled" and an index suffix, then sets that new item to be in "renaming mode" so you can immediately set its name.

![Screenshot 2024-08-21 at 8 59 15 PM](https://github.com/user-attachments/assets/b7531cdd-a9ed-49b9-82aa-18af3b1e21ef)

Instead, we should follow the example of VS Code. Clicking those buttons opens a UI form to set its name, and if you submit this form the file or folder is _then_ created. If you cancel with <kbd>Esc</kbd> or by blurring focus on the input no file system access occurs.

This should include an Electron E2E test or Vitest component test of the behavior.

**Comment by Irev-Dev** [comment]
Jordan made the following comments

>  right click on KCL file window only accepts a click ontop of the shortcut, additionally right click window doesn’t dissapear upon part deletion

Uploading Screen Recording 2024-09-04 at 8.00.10 PM.mov…

> renaming should auto close the right click window.. doesnt feel right

**Comment by lf94** [comment]
Ok these two were fixed by someone at one point:

1. right click on KCL file window only accepts a click ontop of the shortcut, additionally right click window doesn’t dissapear upon part deletion
2. renaming should auto close the right click window.. doesnt feel right

I'll fix up the create file / directory to match vs code
