### ISSUE TITLE
Design not displaying

### ISSUE THREAD

**Issue by zlite** [KittyCAD/modeling-app#3258]
[Add a title above and insert a description of the issue here]

![Screenshot](https://public.blob.zoo.dev/176cc834-3fcd-4f59-9f95-5cfc1458caf2/modeling-app/coredump-0dd1dc4a-9f0d-4930-b5f4-ed7a924d32b1-screenshot.png)

<details>
<summary><b>Core Dump</b></summary>

[coredump-0dd1dc4a-9f0d-4930-b5f4-ed7a924d32b1.json](https://public.blob.zoo.dev/989ffb54-43a9-4fce-a308-3ef8b62bd755/modeling-app/coredump-0dd1dc4a-9f0d-4930-b5f4-ed7a924d32b1.json)

Reference ID: 0dd1dc4a-9f0d-4930-b5f4-ed7a924d32b1
</details>

**Comment by jessfraz** [comment]
just for tracking putting same info here:

the code is failing but the error diagnostics arent showing... probably related to https://github.com/KittyCAD/modeling-app/issues/3209 

why the code is failing...

we made a few breaking changes to the language sorry. So in https://github.com/KittyCAD/modeling-app/releases/tag/v0.22.7  tags changed, there are some docs about it in that tagged release link.

But TLDR when you declare a tag its `$myDeclaredTag`, then when you use it later its `myDeclaredTag` an identifier. Previous to this they were all strings. Now that release had backwards compatibility and it would update your code if you ran “format” on it to the new way of doing it. 

Even tho its an alpha we really hate breaking people… but as of https://github.com/KittyCAD/modeling-app/releases/tag/v0.24.5  which was a few months after I removed the backwards compatibility so we could make another language change in that functions like `segAng` which previously were called like `segAng(myDeclaredTag, %)` now don't need the sketch group: so  `segAng(myDeclaredTag)` again this change has backwards compatibility for the time being. BUT a lint error will show and tell you to update your code. We will remove backwards compatibility in a few releases.
