### ISSUE TITLE
Reconnection issue (theme change)

### ISSUE THREAD

**Issue by Irev-Dev** [KittyCAD/modeling-app#3265]
It seems killing the browser's connection doesn't re-establish the stream when theme changes

https://github.com/user-attachments/assets/8427cf81-d5a5-4dc4-9055-83bc11e84333

Failing test for this issue here https://github.com/KittyCAD/modeling-app/pull/3264

Related to #3250 

CC @lf94

**Comment by Irev-Dev** [comment]
@lf94 I have a feeling this might have been resolved. did it?

**Comment by jessfraz** [comment]
should we add the test on main and see?

**Comment by lf94** [comment]
I thought we (me) fixed it for AME yeah.
