### ISSUE TITLE
Unable to Login/Sign Up with Google Account

### ISSUE THREAD

**Issue by ZooSpiritWolf** [KittyCAD/modeling-app#3283]
🐛 on Dev

Steps to reproduce:
1. Navigate to Zoo URL
2. Click Sign Up at the top right
3. Click Google
4. Enter Google Credentials, the email we tried to login with is, zoooauth871@gmail.com, and click Next
Expected: Ability to sign up/login with Google Account
Actual: Unable to sign up/login with Google Account, 400 error in console, Client fetch error in console (states "You must be a zoo employee to access the preview environment")

Timestamp: 0:29
Video: 
https://www.loom.com/share/788c2f1919c9464d8c639955f035391b (https://www.loom.com/share/788c2f1919c9464d8c639955f035391b)

Bug report:
https://app.qawolf.com/zoo/bug-reports/2d851ce9-e3d2-4434-9c24-e8cc1cc94f93

Affected workflows:
• Onboarding Flow - f2) User Menu - Updates to "Your Avatar" for Oauth User - https://app.qawolf.com/zoo/workflows/clz1k8x740esm10lrzygm4fd9

If you are aware of this bug you can set the priority to low which will prevent it from causing a run failure.

**Comment by Irev-Dev** [comment]
Going to close this out, we don't want qa wolf testing our auth flows.
