### ISSUE TITLE
stream crash building scene 

### ISSUE THREAD

**Issue by JordanNoone** [KittyCAD/modeling-app#3291]
[Add a title above and insert a description of the issue here]

![Screenshot](https://public.blob.zoo.dev/1aa97b88-93a3-46ed-82e6-23c65d76c294/modeling-app/coredump-d7270d16-8cfd-49ae-bd01-bc8c629db38c-screenshot.png)

<details>
<summary><b>Core Dump</b></summary>

[coredump-d7270d16-8cfd-49ae-bd01-bc8c629db38c.json](https://public.blob.zoo.dev/ae80bf77-e5e9-4a6d-bc9c-f45caf414c1a/modeling-app/coredump-d7270d16-8cfd-49ae-bd01-bc8c629db38c.json)

Reference ID: d7270d16-8cfd-49ae-bd01-bc8c629db38c
</details>

**Comment by Irev-Dev** [comment]
CC @lf94,

Jordan and I were looking at this together and sometimes it would just stall on building-stream.

Not sure how much useful information is in the core dump
There's
```json
"engine_connection": {
  "state": {
    "type": "connection-established"
  }
},
```

Obviously the xstate stuff never got serialed properly 😬 
```json
"editor_manager": {},
"auth_machine": {},
"command_bar_machine": {},
"file_machine": {},
"home_machine": {},
"modeling_machine": {},
"settings_machine": {}
```

It would be good to get insight into these vars
<img width="530" alt="image" src="https://github.com/user-attachments/assets/6001c3fa-d132-4414-b332-f55c84103172">

Maybe there's some race or something and `isFirstRender` is not getting unset or something like maybe the stream underneath is fine. 🤷

**Comment by lf94** [comment]
This is completely changed in my network PR so it's probably fixed there

**Comment by JordanNoone** [comment]
On quick test it does seem more robust

**Comment by Irev-Dev** [comment]
Let's reopen if we see it again.
