### ISSUE TITLE
Reset EngineManager inSequence on WebSocket/WebRTC reconnect

### ISSUE THREAD

**Issue by paultag** [KittyCAD/modeling-app#336]
when we do a WebSocket/WebRTC reconnect, we may get a different `engine-api`, which means the sequence would be reset. I reckon we need to zero out `inSequence` in the `EngineManager` when we have a `EngineConnection` open event

https://github.com/KittyCAD/modeling-app/pull/334#discussion_r1307421970

**Comment by jessfraz** [comment]
is this still relevant @paultag otherwise we can close

**Comment by paultag** [comment]
@jessfraz shoot yeah, I never sent a PR for this; it's like a 1 line change, let me just close this issue with a PR
