### ISSUE TITLE
Electron tests: project creation

### ISSUE THREAD

**Issue by lf94** [KittyCAD/modeling-app#3361]
The test should:

1. Click on the new Project button
2. Check the name is in the format project-nnn
3. Check 1 file and 1 folder are created (both for-real and the UI).
4. If it's the N+1 project, check that it's the proper numbered project (project-001, project-002, etc).
5. Repeat 10 times

**Comment by Irev-Dev** [comment]
This is basically the example test I created, I tweak it a little to match this better.

**Comment by Irev-Dev** [comment]
Will be closed by https://github.com/KittyCAD/modeling-app/pull/3315/commits/c17f0ab04fb50ffcdda92f258567eee7144c659a once we merge the electron branch
