### ISSUE TITLE
Electron tests: project search

### ISSUE THREAD

**Issue by lf94** [KittyCAD/modeling-app#3363]
Before each test:

1. Create 11 projects. (important it's 11)

We need tests for:

1. Searching with an empty field (clear the search -> show all projects)
2. Search for an existing project ("project-003")
3. Use a search term that matches all projects ("project")
4. Use a search term that matches 2 projects ("01", because "project-010" and "project-011")

**Comment by franknoirot** [comment]
I don't think we need 11 projects, as long as we have a set of projects that we can search for some of them reliably. Thanks to our `folderSetupFn` I think we can set up a handful of searchable projects

**Comment by franknoirot** [comment]
Yeah that's working with 3 projects that include the word "basic" in there name and 1 that does not

**Comment by lf94** [comment]
Perfect was just a suggestion
