### ISSUE TITLE
Electron tests: project rename

### ISSUE THREAD

**Issue by lf94** [KittyCAD/modeling-app#3364]
We need tests for:

1. Rename project to an empty string, resulting in no renaming (clicking ✓).
2. Renaming a project to something else entirely (clicking ✓).
3. Renaming a project to something else entirely (typing Enter).
4. Canceling the rename operation (clicking X).
5. Canceling the rename operation (typing ESC).
6. Try using the left-right arrow keys when in the input prompt - must not change the name at all.

**Comment by Irev-Dev** [comment]
Done in https://github.com/KittyCAD/modeling-app/pull/3315/commits/cc9aedd1ac8e80a64c180ff3d99ffd6c1deb1d52, can close out when we merge the electron branch
