### ISSUE TITLE
Electron tests: project deletion

### ISSUE THREAD

**Issue by lf94** [KittyCAD/modeling-app#3365]
We need 2 tests:

1. Creates 3 projects.
2. Deletes the 2nd project.
3. Checks the other 2 projects are there but the one deleted is missing.

and

1. Creates 3 projects.
2. Deletes all 3 projects.
3. Able to still create another project.

**Comment by Irev-Dev** [comment]
Partially check in  https://github.com/KittyCAD/modeling-app/pull/3315/commits/cc9aedd1ac8e80a64c180ff3d99ffd6c1deb1d52, but I'll add a dedicated test for this one too.
