### ISSUE TITLE
Electron tests: network status turns to connected on project selection view (home)

### ISSUE THREAD

**Issue by lf94** [KittyCAD/modeling-app#3366]
THIS TEST WILL CURRENTLY FAIL. USE `test.fail()`.

Please add a test that checks the system connects to the engine on the home view.

**Comment by jessfraz** [comment]
@franknoirot did you cover this one as well then?

**Comment by jessfraz** [comment]
covered by [#3393](https://github.com/KittyCAD/modeling-app/issues/3393)
