### ISSUE TITLE
Electron tests: clicking a project goes to modeling view and loads the model

### ISSUE THREAD

**Issue by lf94** [KittyCAD/modeling-app#3367]
This test needs to:

1. Create a project
2. Click on the project
3. Insert some KCL for a cube
4. Verify a cube is rendered

**Comment by jessfraz** [comment]
to whoever does this one, make sure we can do this then go to another project after and that also works, since that was a regression, like the test can not only do one project

**Comment by Irev-Dev** [comment]
Has already been implemented by [Electron test: (regression) Stream should still work after switching projects](https://github.com/KittyCAD/modeling-app/issues/3420) I believe (maybe double check)

But the test opens a project (and it verifies that a project loaded by checking a pixel on the model is the right color (which means the it might be brittle when ever the engine changes render stuff) but as far as I can tell, this is the most e2e verification we can do i.e. what the user sees, not just that the frontend things the execution is complete.

Then navigates to another project and does the same.

Maybe I'll name the test though.
