### ISSUE TITLE
Electron tests project tests racing in the same directory

### ISSUE THREAD

**Issue by lf94** [KittyCAD/modeling-app#3370]
@Irev-Dev @franknoirot @jtran we need to brainstorm how to write these tests in such a way that they can remain parallel. Since they access the filesystem there's the issue of races.

**Comment by lf94** [comment]
It just occurred to me we can generate a hash based on the test name to create new "test folders".

**Comment by jtran** [comment]
That works. We don't want the app to have logic like "if (are we inside a test?) { use generated value } else { use constant }". So pass this generated value down into the app via a container. Outside of tests, we use the same container with real values.

**Comment by Irev-Dev** [comment]
So I think this is pretty much sorted, Frank and I have been overriding the main settings such we can change the default directory, Frank took it further and automatically creates the folder name from the test title.

Besides running these in parallel it also means you can safely run them locally without them messing with personal projects.

**Comment by Irev-Dev** [comment]
https://github.com/KittyCAD/modeling-app/pull/3315/files#diff-a125754132d46c902a7e44e8a63e293305e196ba8d82d13ef063768c4fab0c46R678

**Comment by lf94** [comment]
Great work :)
