### ISSUE TITLE
App errors upon file delete consistently 

### ISSUE THREAD

**Issue by JordanNoone** [KittyCAD/modeling-app#3374]
<img width="734" alt="image" src="https://github.com/user-attachments/assets/637a0d76-b391-4167-bf58-fb946a51bd5b">

**Comment by lf94** [comment]
Probably resolved by the electron port. I manually tested deleting files and projects quite a bit

**Comment by jessfraz** [comment]
this is most likely a dupe of https://github.com/KittyCAD/modeling-app/issues/3088 we can add a test for it once electron is in
