### ISSUE TITLE
Electron tests: go to home view

### ISSUE THREAD

**Issue by lf94** [KittyCAD/modeling-app#3375]
There are 2 tests for this:

1. Clicking the Zoo logo at the top left.
2. Clicking "Go to Home" in the dropdown right beside the Zoo logo.

**Comment by Irev-Dev** [comment]
Will be closed by https://github.com/KittyCAD/modeling-app/pull/3315/commits/7e0efaa2549d1f20b07555aba7c7718123c81e18 once we merge the electron branch
