### ISSUE TITLE
Electron test: (regression) file in the file tree open with a single click

### ISSUE THREAD

**Issue by jessfraz** [KittyCAD/modeling-app#3385]
see the original issue here: https://github.com/KittyCAD/modeling-app/issues/2505

**Comment by Irev-Dev** [comment]
A failing test was written for this in [e82b39d](https://github.com/KittyCAD/modeling-app/pull/3315/commits/e82b39d72d986f5bc663e38800037c026a7d9df2) as this functionality is currently broken. (does not re-execute)

The test has the prefix `test.fixme` but it should only need minimal tweaking once the app has been fixed.
