### ISSUE TITLE
Electron test: (regression) pressing "delete" on home screen should do nothing

### ISSUE THREAD

**Issue by jessfraz** [KittyCAD/modeling-app#3387]
see the original issue here: https://github.com/KittyCAD/modeling-app/issues/2460

**Comment by Irev-Dev** [comment]
Will be closed by https://github.com/KittyCAD/modeling-app/pull/3315/commits/5b3ad376af3bf7e1dd1415a7159f0e6f23125903 once we merge the electron branch.
