### ISSUE TITLE
Electron test: (regression) Stream should still work after switching projects

### ISSUE THREAD

**Issue by Irev-Dev** [KittyCAD/modeling-app#3420]

**Comment by Irev-Dev** [comment]
Will be closed by https://github.com/KittyCAD/modeling-app/pull/3315/commits/7e0efaa2549d1f20b07555aba7c7718123c81e18 once we merge the electron branch

**Comment by jessfraz** [comment]
i think we can close these as they get into the electron branch otherwise hard to remember to add to the other pr

**Comment by jessfraz** [comment]
anyways up to you
