### ISSUE TITLE
Pressing enter on the command bar refreshes the page

### ISSUE THREAD

**Issue by alteous** [KittyCAD/modeling-app#3466]
I was trying out the Text to CAD command and found the page would refresh if I pressed enter in the prompt rather than click the tick button.

[Screencast from 2024-08-15 18-54-02.webm](https://github.com/user-attachments/assets/923b92a3-7d7f-4a5c-9f47-869a9ca3e5f9)

<details>
<summary><b>Core Dump</b></summary>

[coredump-acdaa509-4803-4c5e-9ae1-8bb87cba7835.json](https://public.blob.zoo.dev/6b3d0191-16c8-42f6-9df7-3c0e72fe4be2/modeling-app/coredump-acdaa509-4803-4c5e-9ae1-8bb87cba7835.json)

Reference ID: acdaa509-4803-4c5e-9ae1-8bb87cba7835
</details>

**Comment by jessfraz** [comment]
since this is firefox only we won't fix, we are focused on the app, which is chrome with electron (soon) or the current app
