### ISSUE TITLE
User Settings - Reset Settings button not working

### ISSUE THREAD

**Issue by ZooSpiritWolf** [KittyCAD/modeling-app#3491]
🐛 on Dev

Steps to reproduce:
1. Login
2. Go to User Settings
3. Toggle some settings
4. Click Reset Settings button
Expected: 
Settings are reset and we see success message
Actual: 
Nothing happens and we get an error in console
Video: 
https://www.loom.com/share/16128cd5365249aa998c0044824b5879?sid=b137a3a4-ed4e-47de-b2bd-7825f63e9f98 (https://www.loom.com/share/16128cd5365249aa998c0044824b5879?sid=b137a3a4-ed4e-47de-b2bd-7825f63e9f98)

Bug report:
https://app.qawolf.com/zoo/bug-reports/58450c5a-2a42-460b-ad5b-8d7318d4e35e

Affected workflows:
• Restore Default Settings - User Level - https://app.qawolf.com/zoo/workflows/clwdwc4dj088izn90ddjjtt1s

If you are aware of this bug you can set the priority to low which will prevent it from causing a run failure.

**Comment by Irev-Dev** [comment]
fix me should be remove with this fix for `test.fixme('Project and user settings can be reset', ...`
