### ISSUE TITLE
nested dirs in project with kcl files create main.kcl if not exists

### ISSUE THREAD

**Issue by jessfraz** [KittyCAD/modeling-app#3538]
@JordanNoone  said the tauri app did this, idk if electron does but we should have a test for it not doing this regardless, aka the app shouldnt create rando main.kcl files in dirs unless the user explicitly says to

**Comment by jtran** [comment]
Do you know what triggered the file create? I.e. did it happen when the project was opened from Home?

**Comment by jtran** [comment]
Jess told me she doesn't have any more details, so we'll just do our best.
