### ISSUE TITLE
[BUG]: User menu should show Command, not Control, on mac

### ISSUE THREAD

**Issue by jtran** [KittyCAD/modeling-app#3567]
### Describe the bug

On mac, it should show the command symbol for the User Settings shortcut.

### Steps to Reproduce

1. `yarn tron:start`
2. Click user menu

### Expected Behavior

This is what the current production app looks like.

<img width="212" alt="Screenshot 2024-08-20 at 12 17 30 PM" src="https://github.com/user-attachments/assets/9179281e-3fc0-46fe-bb68-ea54e0c29d64">

### Screenshots and Recordings

This is what I see now.

<img width="230" alt="Screenshot 2024-08-20 at 12 14 20 PM" src="https://github.com/user-attachments/assets/898dd6af-c6e8-4ff1-8c5f-b067fc6f6bcf">

### Desktop OS

macOS 14.6.1

### Version

main, post electron `aac758b396`

**Comment by jessfraz** [comment]
this is so weird since it was fine on tauri
