### ISSUE TITLE
double click to open files from explorer/ app.exe path/to/kcl/file/or/dir should open in app

### ISSUE THREAD

**Issue by jessfraz** [KittyCAD/modeling-app#3577]
there are a bunch of tests here for various weird shit https://github.com/KittyCAD/modeling-app/blob/main/src/wasm-lib/kcl/src/settings/types/file.rs#L539

like `app.exe .` should open the curdir

**Comment by jessfraz** [comment]
more data https://github.com/microsoft/vscode/blob/main/src/main.js#L543

**Comment by jessfraz** [comment]
windows uses process.argv

**Comment by Irev-Dev** [comment]
What are you thinking for how to do these tests?
Bash scripts kinda thing?

**Comment by jessfraz** [comment]
No manual but right now this doesn’t work

**Comment by jessfraz** [comment]
Which is the issue

**Comment by jessfraz** [comment]
And people use this feature now so we can’t skip it

**Comment by jessfraz** [comment]
Like I don’t think lee hooked it up at all

**Comment by jessfraz** [comment]
ill take this one since i know all the weird bits from tauri

**Comment by Irev-Dev** [comment]
Oh sorry I just assumed test, cool sounds good.
