### ISSUE TITLE
[BUG]: Command palette label says `Control /` even though it's really `Control k`

### ISSUE THREAD

**Issue by jtran** [KittyCAD/modeling-app#3578]
The command palette label and on-boarding tour say the key binding is `^/` even though it's actually `^k` on non-mac platforms.

1. Press Control / 👉  Nothing happens
2. Press Control k 👉 Command palette opens

Control / is for comment/uncomment in the editor.

<img width="216" alt="Screenshot 2024-08-20 at 5 25 13 PM" src="https://github.com/user-attachments/assets/5f0a7e68-0d90-4a43-a26f-98cd9e9a7826">

**Comment by jessfraz** [comment]
I really wanna know where the eff that slash is coming from becuase it isnt the hotkey

**Comment by jessfraz** [comment]
it seems impossible to get rid of like a virus like we changed it from being / a long time ago why the eff is it back

**Comment by jessfraz** [comment]
also why dont the hotkey and the thing that shows up reference the same const or value like why are these seperate

**Comment by jtran** [comment]
I think the label was just never updated.

**Comment by jessfraz** [comment]
but like why are they even seperate seems like a recipe for disaster
