### ISSUE TITLE
Test: there are three different ways to change units, make sure all are tested and re-execute model only once

### ISSUE THREAD

**Issue by jessfraz** [KittyCAD/modeling-app#3581]
- command bar
- gizmo
- raw dog settings (project/user)

**Comment by jessfraz** [comment]
this might not need a test, its just a sanity check of someone going thru and making sure we are covered

**Comment by Irev-Dev** [comment]
I think this would have only one of the cases covered, other two probably need to be.

FYI don't need to be an electron test.
