### ISSUE TITLE
add xstate tests for file manager/some way of testing the stuff that should happen on disk is actually happening versus relying on just file pane

### ISSUE THREAD

**Issue by jessfraz** [KittyCAD/modeling-app#3587]
comment here: https://github.com/KittyCAD/modeling-app/pull/3584#issuecomment-2300290754

**Comment by Irev-Dev** [comment]
I just sent Farzad a quick message about this, just in case he thinks it's worth waiting until after the v5 migration is done. We'll see what he says.

**Comment by Irev-Dev** [comment]
He thinks with how close we are to the migration it's worth waiting. @jessfraz do you mind if this is done post electron?

**Comment by Irev-Dev** [comment]
Oh when the tests are running you can still just run normal node fs stuff, so we can do electron tests in the pain, and back it up by verifying that the file is created?
