### ISSUE TITLE
we should also watch the current file on disk and if they change out of band we update it in the app

### ISSUE THREAD

**Issue by jessfraz** [KittyCAD/modeling-app#3665]
i realized this when crossing streams and using vim, i know im a sinner

**Comment by jtran** [comment]
No, you're doin' it right. https://www.youtube.com/watch?v=LL-gyhZVvx0 (Daft Punk - Doin' it Right)

**Comment by franknoirot** [comment]
I might be wrong, but I think we could do this in a [`visibilitychange` listener](https://developer.mozilla.org/en-US/docs/Web/API/Document/visibilitychange_event)

**Comment by jessfraz** [comment]
or https://nodejs.org/docs/latest/api/fs.html#fspromiseswatchfilename-options on the electron side with a hook to tell the front end

**Comment by jessfraz** [comment]
however vscode does it is probably the current state of the art

**Comment by pierremtb** [comment]
Duplicate https://github.com/KittyCAD/modeling-app/issues/2893
