### ISSUE TITLE
MVP Revolve UI

### ISSUE THREAD

**Issue by Irev-Dev** [KittyCAD/modeling-app#3716]
MVP can be just the same as extrude, where we automatically pick the "X" axis for you (we can merge this but hide the button etc unless in dev mode)

We're going to be modeling this off of extrude since there are some similarities.

When the user clicks the extrude button, the experience is large interacting with the command pallet, that's why when you look at where the extrude button is defined in `src/lib/toolbar.ts` the Xstate action it fires off is `Find and select command`

```ts
{
  id: 'extrude',
  onClick: ({ commandBarSend }) =>
    commandBarSend({
      type: 'Find and select command',
      data: { name: 'Extrude', groupId: 'modeling' },
    }),
  disabled: (state) => !state.can('Extrude'),
  icon: 'extrude',
  status: 'available',
  title: 'Extrude',
  hotkey: 'E',
  description: 'Pull a sketch into 3D along its normal or perpendicular.',
  links: [{ label: 'KCL docs', url: 'https://zoo.dev/docs/kcl/extrude' }],
},
```

To make something similar work for revolve you'll need to add a config to `src/lib/commandBarConfigs/modelingCommandConfig.ts` because this is the MVP we can make this exactly the same as Extrude and automatically use `axis: "X"` so we don't need to add a selection for the axis for the time being, since there's plenty to work on in getting the code-mods working.

Once the cmd pallet cmd is added, you should be able to get it to fire an event in the main modeling app that should now have all of the details needed for the code mod
- Selection of the solid2d/sketch
- how far to revolve
- and we're going to assume the axis is just "X" for now

You will need to create a new event in the modeling state machine that triggers a `AST revolve` action. Again we can copy what Extrude is already doing.
![image](https://github.com/user-attachments/assets/e9fdd978-2ea7-4b19-b2a8-d44a828aa5db)
An event from `idle` going back to `idle` with our action, just with revolve names instead of extrude.

Here's the typing for the extrude event

![image](https://github.com/user-attachments/assets/b819ec2c-0dd8-4f83-83c5-0a7bba1e2f7f)

![image](https://github.com/user-attachments/assets/cbe77785-ea13-4d60-baa5-0cf5867a3b47)

So we're pretty much just going to want something like
```ts
Revolve: {
    selection: Selections
    angle: KclCommandValue
    // TODO axis
  }
```

Then when it comes to writing the AST mod
We can pretty much copy [AST extrude](https://github.com/KittyCAD/modeling-app/blob/c2e9d18f92cb911cc1f5787af432d597adaa4eb3/src/machines/modelingMachine.ts#L1086)

The difference should just be the specifics

The core of the extrude though is this here

```ts
const extrudeCall = createCallExpressionStdLib('extrude', [
    distance,
    shouldPipe
      ? createPipeSubstitution()
      : createIdentifier(variableDeclarator.id.name),
  ])
```
We can ignore the shouldPipe so it's really
```ts
const extrudeCall = createCallExpressionStdLib('extrude', [
    distance,
    createIdentifier(variableDeclarator.id.name),
])
```
so for revolve it will something like
```ts
const revolveCall = createCallExpressionStdLib('revolve', [
    createObjectExpression({
      angle: angle,
      axis: createLiteral('X'),
    }),
    createIdentifier(variableDeclarator.id.name),
  ])
```

Hopefully that make sense why it look a little different with the `createObjectExpression` because extrude looks like
`const extrude01 = extrude(20, sketch002)`
And revolve looks like
`const revolve01 = revolve({ angle: 90, axis: "X" }, sketch001)`

I think I'll leave it there, I'm probably missing stuff that we'll have to figure out along the way.

One final tip is, if you want to look at the ast is to use the ast explorer.

https://github.com/user-attachments/assets/e5b6d02d-1d7f-43db-b25d-e22c9d4d0b92

**Comment by franknoirot** [comment]
Wow what a walk-through!

**Comment by nadr0** [comment]
I think there is a bug with the `development` section to be able to select a branch. I am currently working out of the branch https://github.com/KittyCAD/modeling-app/tree/nadro/3716/mvp-revolve

Here is an example of the UI working to generate the revolve. 
https://github.com/user-attachments/assets/1b8ac515-4964-43bc-b320-d55cc0c08236

**Comment by Irev-Dev** [comment]
> I think there is a bug with the development section to be able to select a branch

Sorry not sure what you mean by this?

But that's great you got this working, if we make this only available in dev like what's done for fillet UI `status: DEV ? 'available' : 'kcl-only',` we should be able to get this merged, that way we have a series of concise PRs.

**Comment by nadr0** [comment]
![image](https://github.com/user-attachments/assets/c0b4c6bc-8c10-4dfd-8203-cdfffa79d7e6)
I wanted to link my branch to this issue so others can see it but for some reason it isn't showing up in this dropdown.

Ope, also I didn't mean to branch off my branch in this ticket https://github.com/KittyCAD/modeling-app/pull/3703. I'll fix that as well as the dev only button.

**Comment by Irev-Dev** [comment]
Oh right 🤷
