### ISSUE TITLE
Dark mode doesn't work anymore

### ISSUE THREAD

**Issue by mlfarrell** [KittyCAD/modeling-app#3726]
Looks like we've had a regression in this.  Tried it in prod.

even refreshing doesn't fix it

![image](https://github.com/user-attachments/assets/b5dc0a02-efde-4afe-87d4-b3ca0956d0c3)

**Comment by franknoirot** [comment]
This is very strange and troubling. I am able to switch the theme in my browser: does switching to light theme and back fix the behavior for you? I'd be interested in getting your settings files' contents from localStorage before you try that, if you have the time.

**Comment by mlfarrell** [comment]
TL;DW - was local storage.  still worth recovering in this scenario tho

https://github.com/user-attachments/assets/d044de3a-907c-4ff1-9f18-ccc207902330

**Comment by franknoirot** [comment]
Yeah definitely, thank you. I think I'll convert this to be about properly parsing out from the localStorage contents, but feel free to mute this I think this is enough to go on.

**Comment by franknoirot** [comment]
Oh no lol I'm sorry you don't have to clear everything though! Just wanted to see what the contents were

**Comment by franknoirot** [comment]
Okay looking closer at the video, here is a still showing your various localStorage values (which is where those settings are loading from):

![Image](https://github.com/user-attachments/assets/c0193b9c-28e1-4884-953a-12a2056b4b6f)

I can see that you have the following entries that would impact settings:
1. `/user.toml`, but no `settings.app.theme` value
2. `/settings...`, with a valid value of `settings.app.theme = "dark"`
3. `/browser...`, with a valid value of `settings.app.theme = "light"`

I think I can safely assume the third is short for `/browser/project.toml`. We removed the ability to _set_ the theme at the project level with #3312, but that did not remove the ability for the app to _read_ such a setting if it is set. This is the problem. I'll make sure that settings configured to be hidden at the project level are never even applied at that level. This is related to #3805, and is I believe the same issue.
