### ISSUE TITLE
[BUG]: Fillet operation producing ApiError

### ISSUE THREAD

**Issue by yeroca** [KittyCAD/modeling-app#3757]
### Describe the bug

I have a fillet operation that used to work, but now I'm getting an API error:

![image](https://github.com/user-attachments/assets/5250a550-a80f-4661-abbf-d1daa8e4189f)

### Steps to Reproduce
Paste following code in to the code pane:

const holeFudge = 0.4
const frontBarD = 5.0
const yBarD = 6.7
const lowerBlockTransHoleD = frontBarD + holeFudge
const lowerBlockTransHoleR = lowerBlockTransHoleD / 2
const upperBlockLongHoleD = yBarD + holeFudge
const upperBlockLongHoleR = upperBlockLongHoleD / 2
const upperBlockTransHoleD = yBarD + holeFudge
const upperBlockTransHoleR = upperBlockTransHoleD / 2
const tubeClr = 1.5
const lowerBlockH = lowerBlockTransHoleD + 2 * tubeClr
const upperBlockH = upperBlockLongHoleD + 2 * tubeClr
const elevateH = 5
const upperBlockL = 25
const lowerBlockL = 60
const blockSz = max(upperBlockH, lowerBlockH)
const sketch001 = startSketchOn('XZ')
  |> startProfileAt([0, 0], %)
  |> yLine(blockSz, %, $edgeA)
  |> xLine(blockSz, %, $edgeB)
  |> yLine(-blockSz, %, $edgeC)
  |> xLine(upperBlockL - blockSz, %, $edge1)
  |> yLine(-(elevateH + blockSz), %, $edge2)
  |> xLine(lowerBlockL - blockSz, %, $edge3)
  |> yLine(-blockSz, %, $edge4)
  |> xLine(-lowerBlockL, %, $edge5)
  |> yLine(blockSz + elevateH, %, $edge6)
  |> xLine(-(upperBlockL - blockSz), %, $edge7)
  |> lineTo([profileStartX(%), profileStartY(%)], %, $seg01)
  |> close(%)
  |> hole(circle([blockSz / 2, blockSz / 2], upperBlockTransHoleR, %), %)
  |> hole(circle([
       upperBlockL + lowerBlockL - blockSz - (lowerBlockTransHoleR) - tubeClr,
       -(blockSz + elevateH + blockSz / 2)
     ], lowerBlockTransHoleR, %), %)
const rad = 3
const extrude001 = extrude(blockSz, sketch001)
  |> fillet({
       radius: rad,
       tags: [
         getNextAdjacentEdge(edgeA),
         getNextAdjacentEdge(edgeB),
         getNextAdjacentEdge(edgeC),
         getNextAdjacentEdge(edge2),
         getNextAdjacentEdge(edge3),
         getNextAdjacentEdge(edge4),
         getNextAdjacentEdge(edge5),
         getNextAdjacentEdge(edge6)
       ]
     }, %)

const sketch002 = startSketchOn(extrude001, seg01)
   |> startProfileAt([0, 0], %)
   |> circle([blockSz / 2, -blockSz / 2], upperBlockLongHoleR, %)
const extrude2 = extrude(-upperBlockL, sketch002)

### Expected Behavior

I expected the fillet operation to work as before.

### Desktop OS

Windows 10

### Browser

N/A

### Version

V0.24.13

**Comment by jessfraz** [comment]
we merged a breaking change engine side to `getNextAdjacentEdge` but your file will work once we get this release out, tomorrow! so sorry!

**Comment by jessfraz** [comment]
I promise we wont do this once we hit v1 but for now you can use it on app.zoo.dev

**Comment by yeroca** [comment]
No worries!  Thanks for the quick response!
