### ISSUE TITLE
Starting sketches on faces defined in a function does not work. 

### ISSUE THREAD

**Issue by nadr0** [KittyCAD/modeling-app#3771]
There are two problems
1. The modeling app does not find the correct line of code to safely add the sketch on face from the result of a function call
2. We do not guarantee that the function returns something you can sketch on

Starting file
```
fn iAmABox = (start, distance, plane) => {
  const box = startSketchOn(plane)
    |> startProfileAt([0, 0], %)
    |> line([start, 1], %)
    |> line([1, 0], %)
    |> line([0, -1], %)
    |> lineTo([profileStartX(%), profileStartY(%)], %, $seg01)
    |> close(%)
    |> extrude(distance, %)
  return box
}

const myCoolBox = iAmABox(0, 1.5, "XY")
```

Example after trying to sketch on a face
```
fn iAmABox = (start, distance, plane) => {
  const box = startSketchOn(plane)
    |> startProfileAt([0, 0], %)
    |> line([start, 1], %)
    |> line([1, 0], %)
    |> line([0, -1], %)
    |> lineTo([profileStartX(%), profileStartY(%)], %, $seg01)
    |> close(%)
    |> extrude(distance, %)
  return box
}

const sketch001 = startSketchOn(box, 'END')
  |> startProfileAt([0.16, 0.36], %)
const myCoolBox = iAmABox(0, 1.5, "XY")
```

This creates a new `sketch001` with the variable name `box` from line 2 of the code instead of `myCoolBox`. 

Example for second problem 
```
fn iAmABox = (start, distance, plane) => {
  const box = startSketchOn(plane)
    |> startProfileAt([0, 0], %)
    |> line([start, 1], %)
    |> line([1, 0], %)
    |> line([0, -1], %)
    |> lineTo([profileStartX(%), profileStartY(%)], %, $seg01)
    |> close(%)
    |> extrude(distance, %)
  return distance
}

const myCoolBox = iAmABox(0, 1.5, "XY")
```

What if we returned the `distance` from the function then started the sketch on face; it would not be able to handle this.

**Comment by Irev-Dev** [comment]
We are likely also going to need to change the way functions are defined to make argument default mandatory, in the above sketchMode is going to need some sane values for `start, distance, plane` before it's able to render the sketch, because when your editing something defined in a function, your editing the abstraction.

**Comment by nadr0** [comment]
Closing this since this is a duplicate of https://github.com/KittyCAD/modeling-app/issues/2207
