### ISSUE TITLE
Phantom panes still open when all panes are closed

### ISSUE THREAD

**Issue by Irev-Dev** [KittyCAD/modeling-app#3779]
https://github.com/user-attachments/assets/5d2e09f2-7891-445e-b503-fa8c2c49d28c

Steps to reproduce
1. close panes
2. move mouse to where resizer was before panes were close
3. see it's still there.

**Comment by jessfraz** [comment]
spooky

**Comment by franknoirot** [comment]
This is probably where to start investigating https://github.com/KittyCAD/modeling-app/blob/main/src/components/ModelingSidebar/ModelingSidebar.tsx#L207-L224

**Comment by franknoirot** [comment]
Is this Mac-specific maybe, or v0.25.0-specific? I can't seem to replicate with v0.25.1. Maybe I'll try to find the binary from the v0.25.0 PR and try it there

**Comment by franknoirot** [comment]
I think this may be a malformed `openPanes` sort of thing, as I'm not able to reproduce with [the v0.25.0 test release binary on MacOS](https://github.com/KittyCAD/modeling-app/actions/runs/10710666344). Would you mind seeing what that stored value is in your app if you're still experiencing this @Irev-Dev? I'll try to reproduce by butchering my `openPanes`

**Comment by franknoirot** [comment]
Got it! If the `Show debug panel` setting is set to `off` while the pane is open, a phantom pane will appear. I've confirmed this in the web on main, so I'll write a web playwright test for it.
