### ISSUE TITLE
Large files are unusable in the code editor

### ISSUE THREAD

**Issue by Irev-Dev** [KittyCAD/modeling-app#3786]
Likely something the react profiler will help fix because this feels like the main thread is getting blocked.

Notice the key spam but the cursor moves in jumps.

https://github.com/user-attachments/assets/3f1425c4-0901-48eb-92c1-adef01e6049f

**Comment by lf94** [comment]
i fear this touches a few things

**Comment by jessfraz** [comment]
I highly doubt it is any of the codemirror code tho, or plugins since none of those changed in the electron port and now all of a sudden its doing this, which makes me lean towards react

**Comment by jessfraz** [comment]
isnt happening in the browser for me

**Comment by jessfraz** [comment]
actually finding it hard to repro on the latest build off the main branch on desktop too, but let me try a larger model

**Comment by jessfraz** [comment]
okay yep its large files

**Comment by jessfraz** [comment]
try the server rack

**Comment by jessfraz** [comment]
https://github.com/user-attachments/assets/e8c28778-5fd6-425c-b99a-1ef5d1d77588

**Comment by Irev-Dev** [comment]
If it's large files, my gut guess would be that we're maybe parsing the code on cursor moves when we should only do that on actual text change, and that's blocking the main thread.

**Comment by adamchalmers** [comment]
@lf94 is this actually closed? Isn't https://github.com/KittyCAD/modeling-app/pull/3825 the fix, which still needs to be merged?
