### ISSUE TITLE
double arrow key required to move select export format

### ISSUE THREAD

**Issue by Irev-Dev** [KittyCAD/modeling-app#3787]
https://github.com/user-attachments/assets/122ae27e-62d6-43c8-8b4a-81ce54a39f2d

**Comment by franknoirot** [comment]
I think I can explain what's happening here. [This line](https://github.com/KittyCAD/modeling-app/blob/main/src/components/CommandBar/CommandArgOptionInput.tsx#L66) sets the initially-selected combobox option, and whichever is the currently-active value is highlighted by the classnames [`ui-active:bg-primary/10 dark:ui-active:bg-chalkboard-90` here](https://github.com/KittyCAD/modeling-app/blob/main/src/components/CommandBar/CommandArgOptionInput.tsx#L167). We could remove the line that sets the initial value and it would be more honest UX I think?

Explainer video:

https://github.com/user-attachments/assets/a741d755-9b85-4c73-991a-041c9b15a576

**Comment by Irev-Dev** [comment]
Fix in https://github.com/KittyCAD/modeling-app/pull/3809, it's not pretty though.
