### ISSUE TITLE
Navigating to a file with parser errors will not update the stream, making it feel like no navigation happened

### ISSUE THREAD

**Issue by jessfraz** [KittyCAD/modeling-app#3803]
i thought there was a test for this???

https://github.com/user-attachments/assets/b4e43c26-7c34-4bd3-befb-fc9cc5bbe9a0

**Comment by jessfraz** [comment]
from @Irev-Dev "I think maybe the generated code has a error in it, I can replicate it not responding to clicks with the following code"

but i still think if this does happen even tho the model shouldnt give us erroredd code we should still open the file... def still a bug

**Comment by jessfraz** [comment]
so perhaps the bug is files don't open if code has bugs which i also thought we had a test for...?

**Comment by jessfraz** [comment]
greg is also going to start intentionally giving us the failed kcl versus good kcl if its that or nothing, so like copilot you can fix it yourself, so like we def need to support this

**Comment by Irev-Dev** [comment]
https://github.com/user-attachments/assets/b450910b-6e8c-4862-a896-9fc100baa287

i.e. how this got through with our tests.

**Comment by jessfraz** [comment]
oh gotcha that makes sense

**Comment by franknoirot** [comment]
Nice, thank you for your debugging @Irev-Dev, I'm able to easily reproduce that issue with a minimal example here: [gh-3803.zip](https://github.com/user-attachments/files/16965188/gh-3803.zip)

**Comment by franknoirot** [comment]
Working on the text-to-cad issues currently, so unassigning myself for now

**Comment by lf94** [comment]
Fixed some time but I'm not sure which PR did it. I just tried it and the scene clears as expected.
