### ISSUE TITLE
"Light" mode is dark and hard to read

### ISSUE THREAD

**Issue by jgomez720** [KittyCAD/modeling-app#3829]
### Description
On light theme, the UI is dark with hard to read text. I switched to dark and back to light to see if that would fix it, it did not.

### Version
0.25.1

### Screenshot
<img width="1912" alt="Screenshot 2024-09-06 at 9 14 52 PM" src="https://github.com/user-attachments/assets/19996bcb-bdf2-46e8-8d96-5458076c9e08">

**Comment by jgomez720** [comment]
Problem occurs when OS is in dark, modeling app is in light

**Comment by franknoirot** [comment]
Sorry this never got added to our Extermination Station which has been source of truth for a bit. This was fixed with #3844
