### ISSUE TITLE
getSelectionType needs improvement for handling multiple types and selections

### ISSUE THREAD

**Issue by max-mrgrsk** [KittyCAD/modeling-app#3834]
This issue is part of the larger Fillet UI (#2606) project. 

### Issue Description:
The current `getSelectionType` function defaults most selections to `extrude-wall` and struggles to handle multiple selection types (e.g., edges, faces) accurately. This results in incorrect labels and counts in the command bar when different types are selected. 

### Expected Improvement:
- Accurately distinguish between selection types (e.g., edges, faces, points).  
- Display correct labels and counts in the command bar for multiple selection types.

**Comment by Irev-Dev** [comment]
Unless this is blocking your work, I think this would be wasted cycles as https://github.com/KittyCAD/modeling-app/issues/3837 is going to stop it anyway, the selection type is going stored directly on the selections after the refactor.

**Comment by max-mrgrsk** [comment]
since there is an upcoming update : https://github.com/KittyCAD/modeling-app/issues/3837 , I would take a shortest way just to enable multiple selections working for fillets. Just to move forward
