### ISSUE TITLE
KCL docs: param list is hard to read

### ISSUE THREAD

**Issue by adamchalmers** [KittyCAD/modeling-app#3846]
The current KCL docs list each function's parameters. The parameter list looks like:

![kcl docs arg list](https://github.com/user-attachments/assets/2d767a15-d9ef-4ac4-ae74-42e533b98163)

In my opinion, this is hard to read. I think it's hard to immediately tell where the parameter name ends and the parameter type begins. Each one takes up an inconsistent visual height too.

I suggest we actually display a table, with one row for each parameter. Columns would be Name, Type and Required.

| Name  | Type | Required |
| ------------- | ------------- | ------------- |
| `num_repetitions`  | u32  | Required |
| `transform_function`  | Function  | Required |
| `extrude_group_set`  | ExtrudeGroupSet  | Required |

**Comment by franknoirot** [comment]
I love this idea. The tables for the API docs can serve as a reference if you like https://zoo.dev/docs/api/file/get-cad-file-mass?lang=typescript#parameters-material_density

**Comment by jessfraz** [comment]
i think @franknoirot they'd be markdown tables here and in the docs, then will convert when passed to website

**Comment by jessfraz** [comment]
for whoever wants this is generated in docs.rs, its just traverses the jsonschema and yes it could be A LOT better, we could generate files per types like SketchGroup as well and cross link, anyways, all i care about is we don't hand write we can get really nice things buy just making the generation better we have all the data.
