### ISSUE TITLE
[BUG]: Broken images in onboarding

### ISSUE THREAD

**Issue by greg-kcio** [KittyCAD/modeling-app#3865]
### Describe the bug

Page 5 of onboarding tries to display two broken or missing images.

### Steps to Reproduce

1. Start from a fresh install, or reset onboarding
2. Advance to page 5

### Expected Behavior

2 images related to the shelf bracket are displayed.

### Screenshots and Recordings

![image](https://github.com/user-attachments/assets/5d78b92c-795f-4b79-9124-055aa6826d6e)

### Desktop OS

Ubuntu

### Version

v0.25.1

**Comment by jessfraz** [comment]
cc @franknoirot or @lf94 we will want to prioritize this since it’s a first experience thing

**Comment by lf94** [comment]
@franknoirot if you're not doing anything in particular I'd like if you can take this one

**Comment by jgomez720** [comment]
I got it. I'm changing that onboarding bracket anyway, I will fix this too.
