### ISSUE TITLE
Sketch on chamfer wigs out on second chamfer

### ISSUE THREAD

**Issue by Irev-Dev** [KittyCAD/modeling-app#3919]
To reproduce, past in this code
```ts
const sketch001 = startSketchOn('XZ')
  |> startProfileAt([75.8, 317.2], %) // [$startCapTag, $EndCapTag]
  |> angledLine([0, 268.43], %, $rectangleSegmentA001)
  |> angledLine([
       segAng(rectangleSegmentA001) - 90,
       217.26
     ], %, $seg01)
  |> angledLine([
       segAng(rectangleSegmentA001),
       -segLen(rectangleSegmentA001)
     ], %)
  |> lineTo([profileStartX(%), profileStartY(%)], %, $seg02)
  |> close(%)
const extrude001 = extrude(100, sketch001)
  |> fillet({ radius: 20, tags: [seg01] }, %)
  |> chamfer({ length: 50, tags: [seg02] }, %, $seg04)
  |> chamfer({
       length: 50,
       tags: [getOppositeEdge(seg01)]
     }, %, $seg03)

const sketch003 = startSketchOn(extrude001, seg04)
  // |> startProfileAt([-69.1, 277.34], %)
  // |> angledLine([0, 41.48], %, $rectangleSegmentA003)
  // |> angledLine([
  //      segAng(rectangleSegmentA003) - 90,
  //      104.8
  //    ], %, $rectangleSegmentB002)
  // |> angledLine([
  //      segAng(rectangleSegmentA003),
  //      -segLen(rectangleSegmentA003)
  //    ], %, $rectangleSegmentC002)
  // |> lineTo([profileStartX(%), profileStartY(%)], %)
  // |> close(%)
const sketch002 = startSketchOn(extrude001, seg03)
  |> startProfileAt([159.25, 278.35], %)
  |> angledLine([0, 40.82], %, $rectangleSegmentA002)
  |> angledLine([
       segAng(rectangleSegmentA002) - 90,
       132.27
     ], %, $rectangleSegmentB001)
  |> angledLine([
       segAng(rectangleSegmentA002),
       -segLen(rectangleSegmentA002)
     ], %, $rectangleSegmentC001)
  |> lineTo([profileStartX(%), profileStartY(%)], %)
  |> close(%)
const extrude002 = extrude(50, sketch002)
```
And uncomment the comment block and you see at error at `startProfileAt`

Original vid from the [slack thread](https://kittycadworkspace.slack.com/archives/C04KFV6NKL0/p1726176791045929)

https://github.com/user-attachments/assets/e715c115-a799-4315-9294-fe2039762b3f

**Comment by Irev-Dev** [comment]
I have a theory is itit could be related to [this comment](https://github.com/KittyCAD/modeling-app/pull/3675#discussion_r1732422235), just because I know that there was some deferred logic with how fillets and chamfers work, but since the above PR gets all of the [edges of the extrusion right](https://github.com/KittyCAD/untitled-lang/blob/5cc92f01624dcf300f944ae5c193f2f40be1fdd4/src/wasm-lib/kcl/src/std/extrude.rs#L193) after the extrusion happens, maybe it would be better to load all of the edge ids onto the sketch group, but it might not be related.

**Comment by jessfraz** [comment]
I'm looking into this but i dont think thats it, the logic for chamfers will execute it before a sketch a face, i think this is just a bug in general :)

**Comment by jessfraz** [comment]
yup just a dumb ass bug, pr incoming
