### ISSUE TITLE
Constraint overlays are hidden by line labels

### ISSUE THREAD

**Issue by lf94** [KittyCAD/modeling-app#3975]
See video in https://github.com/KittyCAD/modeling-app/issues/3974

**Comment by lf94** [comment]
Fixed, was easy as zindex: 1

**Comment by Irev-Dev** [comment]
This is duplicated by https://github.com/KittyCAD/modeling-app/issues/3946

You say fixed, mind linking to the PR, because possibly both of these should be closed.

**Comment by lf94** [comment]
PR will come, it's part of a large set of changes I will break up when ready!

**Comment by lf94** [comment]
Closing because dup like Kurt said
