### ISSUE TITLE
[BUG]: An unexpected error occurred on version 0.25.4

### ISSUE THREAD

**Issue by troy12x** [KittyCAD/modeling-app#4011]
### Describe the bug

An unexpected error occurred

i just setuped the new version and already go this problem 
![image](https://github.com/user-attachments/assets/3ea64ac4-4ddc-4eac-9bee-70d3c83ca6a9)

### Steps to Reproduce

simply new setup

### Expected Behavior

it should run normal

### Desktop OS

windows 11

### Version

0.25.4

**Comment by lf94** [comment]
How did you build?

**Comment by troy12x** [comment]
> How did you build?

normal setup ? 

yarn install
yarn build:wasm-dev
yarn install 

i added the .env.development.local

**Comment by lf94** [comment]
The normal setup would be:

```
yarn install
yarn build:wasm
yarn start
```
For _web_; the steps the are a bit different for the desktop app!

You will not want to use `yarn build:wasm-dev` because it makes the app pretty much unusable.

**Comment by troy12x** [comment]
oh let me try it

**Comment by troy12x** [comment]
> The normal setup would be:
> 
> ```
> yarn install
> yarn build:wasm
> yarn start
> ```
> 
> For _web_; the steps the are a bit different for the desktop app!
> 
> You will not want to use `yarn build:wasm-dev` because it makes the app pretty much unusable.

i did that and it's still the same

**Comment by troy12x** [comment]
![image](https://github.com/user-attachments/assets/92e488be-99d9-44dd-ba3a-446dc4d6a757)

**Comment by lf94** [comment]
Yes you are encountering wasm-pack issues on Windows. You will need to download wasm-pack the recommended way, via cargo, build the wasm blob, and copy it to public/.

**Comment by lf94** [comment]
I _highly_ suggest reading our github workflow files for a better understanding how to build on Windows or Mac. I build on Linux so it is quite easy for me.

**Comment by troy12x** [comment]
i will check it thanks

**Comment by troy12x** [comment]
fixed thanks
