### ISSUE TITLE
"This project" tab in settings no longer has "Theme" as an option

### ISSUE THREAD

**Issue by ZooSpiritWolf** [KittyCAD/modeling-app#4014]
🐞 on Dev

Steps to reproduce:
1. Log in
2. Ensure you're in a project
3. Go to settings
4. Navigate to the "This project" tab
Expected: An option to set theme for the individual project is visible
Actual: The option to set theme is not available per project, however we can still set the theme color. 

Timestamp: 0:00
Video: 
https://www.loom.com/share/37c745f581f94dfb92c38936f68aef22?sid=7dfa9ab5-a400-4634-90a0-ee73d8915540 (https://www.loom.com/share/37c745f581f94dfb92c38936f68aef22?sid=7dfa9ab5-a400-4634-90a0-ee73d8915540)

Bug report:
https://app.qawolf.com/zoo/bug-reports/ca3645d2-ff0a-4437-9d2f-5de491a12d98

Affected workflows:
• App - Update Color Theme - https://app.qawolf.com/zoo/workflows/clwey41ns0c8izn90tib2drfz

If you are aware of this bug you can set the priority to low which will prevent it from causing a run failure.

**Comment by jessfraz** [comment]
we removed this feature
