### ISSUE TITLE
KCL: Support dynamic ranges

### ISSUE THREAD

**Issue by jessfraz** [KittyCAD/modeling-app#4021]
# Background

Currently KCL array expressions are basically just a list of numbers n, n+1, ..., m -- they're a list of consecutive numbers from their start to their end. The start and end are known when the KCL AST is parsed (i.e. compile-time).

# Problem

This doesn't parse, but it definitely should.
```
const end = 10
const myRange = [0..end]
```

found by @JordanNoone.

# Proposed solution

Expand array expressions to use dynamic start and end values, that are only known during runtime. We might want to use separate AST nodes for arrays whose members are known at compile-time vs. run-time, but I don't really see what benefit that would bring.

# Testing plan

This can be tested by adding a new unit test inside `parser_impl.rs`, and checking that Jess's program above now parses. Add a test under the snapshot tests (that use `cargo insta`).

To test the runtime, you could just write a program under `no_visuals` tests which makes a runtime-known array and then assert it sums to what you expect (use the KCL stdlib `reduce` to sum up the array)

**Comment by adamchalmers** [comment]
Context: https://github.com/KittyCAD/modeling-app/issues/3842#issuecomment-2350075210

**Comment by jessfraz** [comment]
ah this is a bit harder than I thought I will leave to @adamchalmers

**Comment by jessfraz** [comment]
I did attempt but i didn't realize ast needed fixing too

**Comment by adamchalmers** [comment]
So, currently, KCL array expressions are basically just a list of numbers n, n+1, ..., m -- they're a list of consecutive numbers from their start to their end. The start and end are known when the KCL AST is parsed (i.e. compile-time).

This issue should expand array expressions to use dynamic start and ends that are only known during runtime. We might want to use separate AST nodes for arrays whose members are known at compile-time vs. run-time, but I don't really see what benefit that would bring.
