### ISSUE TITLE
Opening the modeling app from the CLI with a path that does not exist shows a blank page

### ISSUE THREAD

**Issue by nadr0** [KittyCAD/modeling-app#4060]
When testing the the manual check [list](https://github.com/KittyCAD/modeling-app/pull/4046) for the latest cut release I found an edge case we are missing when opening files and folders.

## Preexisting working workflows
This opens the folder `default` and works.
```
/home/kevin-nadro/Downloads/Zoo\ Modeling\ App-0.25.5-x86_64-linux.AppImage /home/kevin-nadro/Documents/zoo-modeling-app-projects/default
```

This opens an empty folder and creates a blank `main.kcl`
```
rm /home/kevin-nadro/Documents/zoo-modeling-app-projects/empty/main.kcl

/home/kevin-nadro/Downloads/Zoo\ Modeling\ App-0.25.5-x86_64-linux.AppImage /home/kevin-nadro/Documents/zoo-modeling-app-projects/empty
```

## Bug

```
$ ./Zoo\ Modeling\ App-0.255.255-x86_64-linux.AppImage /home/dog/cat/mouse
```

>don't worry about the version updater number there, I've tested this on the local package, a real v0.25 and this app updater one

error messages in the terminal 
```
Loading project at startup: /home/dog/cat/mouse
Checking for update
Error: ENOENT: no such file or directory, stat '/home/dog/cat/mouse'
[25939:1001/095127.135049:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
Update for version 0.255.255 is not available (latest version: 0.25.5, downgrade is disallowed).
checkForUpdatesAndNotify called, downloadPromise is **null**
```

What the application looks like, it will hang forever on this blank page. 
![Screenshot from 2024-10-01 09-51-48](https://github.com/user-attachments/assets/85bf21ff-e126-4900-abf3-d5c6305270c2)

## Possible solutions

- [ ] ?
- [ ] ?
- [ ] ?
- [ ] ?

**Comment by lf94** [comment]
guptaarnav took care of this one :)

**Comment by lf94** [comment]
Closed by https://github.com/KittyCAD/modeling-app/pull/4161
