### ISSUE TITLE
Export to STEP results in hollow `base`

### ISSUE THREAD

**Issue by spoon16** [KittyCAD/modeling-app#4105]
Playing around with the modeling app on MacOS.

I have two KCL files in my project. When I export `cube.kcl` to STEP the 3D object represented by `base` in the KCL is solid (expected). When I export `main.kcl` to STEP the 3D object represented by `base` in the KCL is hollow (not expected).

I am using PrusaSlicer 2.8.1 to load and render the STEP file after export.

I'm guessing... but it appears that the solid `base` object is being incorrectly converted to a shell when `main.kcl` is export to STEP. I wonder if this is somehow related to #4104 

`cube.kcl`
```
const base = startSketchOn('XY')
  |> startProfileAt([0, 0], %)
  |> line([50, 0], %)
  |> line([0, 50], %, $leftPlane)
  |> line([-50, 0], %, $rightPlane)
  |> lineTo([profileStartX(%), profileStartY(%)], %)
  |> close(%)
  |> extrude(50, %)
```

`main.kcl`
```
const base = startSketchOn('XY')
  |> startProfileAt([0, 0], %)
  |> line([50, 0], %)
  |> line([0, 50], %, $leftPlane)
  |> line([-50, 0], %, $rightPlane)
  |> lineTo([profileStartX(%), profileStartY(%)], %)
  |> close(%)
  |> extrude(50, %)

const bracketBottom = startSketchOn(base, 'START')
  |> startProfileAt([0, 0], %)
  |> line([-50, 0], %, $b1)
  |> line([0, 50], %, $b2)
  |> line([50, 0], %, $b3)
  |> lineTo([profileStartX(%), profileStartY(%)], %, $b4)
  |> close(%)
  |> extrude(18, %)
  |> shell({ faces: ['END'], thickness: 6 }, %)
  |> fillet({
       radius: 3,
       tags: [
         getNextAdjacentEdge(b1),
         getNextAdjacentEdge(b2),
         getNextAdjacentEdge(b3),
         getNextAdjacentEdge(b4)
       ]
     }, %)

const bracketLeft = startSketchOn(base, leftPlane)
  |> startProfileAt([0, 0], %)
  |> line([50, 0], %, $l1)
  |> line([0, 50], %, $l2)
  |> line([-50, 0], %, $l3)
  |> lineTo([profileStartX(%), profileStartY(%)], %, $l4)
  |> close(%)
  |> extrude(18, %)
  |> fillet({
       radius: 3,
       tags: [
         getNextAdjacentEdge(l1),
         getNextAdjacentEdge(l2),
         getNextAdjacentEdge(l3),
         getNextAdjacentEdge(l4)
       ]
     }, %)

const bracketRight = startSketchOn(base, rightPlane)
  |> startProfileAt([0, 0], %)
  |> line([-50, 0], %, $r1)
  |> line([0, 50], %, $r2)
  |> line([50, 0], %, $r3)
  |> lineTo([profileStartX(%), profileStartY(%)], %, $r4)
  |> close(%)
  |> extrude(18, %)
  |> fillet({
       radius: 0.09,
       tags: [
         getNextAdjacentEdge(r1),
         getNextAdjacentEdge(r2),
         getNextAdjacentEdge(r3),
         getNextAdjacentEdge(r4)
       ]
     }, %)
```

![Screenshot](https://public.blob.zoo.dev/6a5dd8bf-4add-4f55-9fef-102c3b88c3b0/modeling-app/coredump-6597d97a-0e7a-40bc-865e-2020120ca6f5-screenshot.png)

<details>
<summary><b>Core Dump</b></summary>

[coredump-6597d97a-0e7a-40bc-865e-2020120ca6f5.json](https://public.blob.zoo.dev/6872f19a-c2fe-4692-8bee-544a8a48a242/modeling-app/coredump-6597d97a-0e7a-40bc-865e-2020120ca6f5.json)

Reference ID: 6597d97a-0e7a-40bc-865e-2020120ca6f5
</details>

**Comment by spoon16** [comment]
Also, screenshot gen from Modeling App on MacOS seems still broken, see #3079 

Here is a screenshot I manually took at time of report, in case it's helpful.

![Image](https://github.com/user-attachments/assets/26088b43-a05f-41e5-92fe-6fba1a1cd1f1)

**Comment by jessfraz** [comment]
Adding @alteous who knows the export code

**Comment by spoon16** [comment]
I figured this out. I have been misunderstanding the semantics of `shell`. The shell function applies to the full object. This is discussed with some examples @ #4104
