### ISSUE TITLE
Auto-completion is overly aggressive when an expression ends with "10"

### ISSUE THREAD

**Issue by yeroca** [KittyCAD/modeling-app#4119]
[Add a title above and insert a description of the issue here]

When writing some code, if an expression ends with 10 somehow, then I hit enter, the 10 turns into "log10(3.14)" because that was what  was suggested by auto-completion.

![Screenshot](https://public.blob.zoo.dev/a2c9f454-eccb-4500-b5a1-b1728b3714de/modeling-app/coredump-71f4c7ee-7925-40c6-bc12-7e294bf17753-screenshot.png)

<details>
<summary><b>Core Dump</b></summary>

[coredump-71f4c7ee-7925-40c6-bc12-7e294bf17753.json](https://public.blob.zoo.dev/b292c3c9-a607-4a95-b12b-59c8c3dcf7e6/modeling-app/coredump-71f4c7ee-7925-40c6-bc12-7e294bf17753.json)

Reference ID: 71f4c7ee-7925-40c6-bc12-7e294bf17753
</details>

<details>
<summary><b>KCL Code</b></summary>

```kcl
numSides = 12

cornerAngle = 360 / numSides
diam = 19.9

rad = diam / 2

sideLen = rad * sin(toRadians(cornerAngle / 2)) * 2
centerYOffset = rad * cos(toRadians(cornerAngle / 2))

slowMode = log10(3.14)
fn dodecagon = () => {
  sketch001 = startSketchAt([-sideLen / 2, -centerYOffset])
  return reduce([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10], sketch001, (i, sg) => {
  return angledLine({
  angle: i * cornerAngle,
  length: sideLen
}, sg)
})
}

sketch010 = dodecagon()
  |> close(%)
  |> extrude(7, %)

sketch002 = startSketchOn(sketch010, 'END')
  |> circle({ center: [0, 0], radius: 16 }, %)
  |> extrude(4, %)

```
</details>

**Comment by guptaarnav** [comment]
Closed by #4341.
