### ISSUE TITLE
[BUG]: extrude will accept a list, but not a dynamic list

### ISSUE THREAD

**Issue by paultag** [KittyCAD/modeling-app#4128]
### Describe the bug

extrude will accept a list, but not a dynamic list of Sketch values -- I'm guessing there's something going on with implicit `SketchSet` types

### Steps to Reproduce

```
fn square = (origin, size, surface) => {
  return surface
    |> startProfileAt(origin, %)
    |> line([0, size], %)
    |> line([size, 0], %)
    |> line([0, -size], %)
    |> close(%)
}

map([[0, 0], [1, 1], [2, 2]], (origin) => {
  return startSketchOn("XY")
    |> square(origin, 0.5, %)
})
  |> extrude(1, %)
```

### Expected Behavior

I expected the ability to extrude 3 squares -- but i can't, even though I can do this

```
fn square = (origin, size, surface) => {
  return surface
    |> startProfileAt(origin, %)
    |> line([0, size], %)
    |> line([size, 0], %)
    |> line([0, -size], %)
    |> close(%)
}

extrude(1, [
  startSketchOn("XY")
    |> square([0, 0], 0.5, %),
  startSketchOn("XY")
    |> square([1, 1], 0.5, %),
  startSketchOn("XY")
    |> square([2, 2], 0.5, %),
])
```

### Desktop OS

Debian

### Browser

Chrome

### Version

main

**Comment by guptaarnav** [comment]
This bug appears to have been fixed at some point in the main code that is yet to be released.  I can replicate this issue on the latest production build of ZMA (0.25.6) but as of main branch commit [7d44de0](https://github.com/KittyCAD/modeling-app/commit/7d44de0c12fe61a296f9781b97bb6cdc220951f4) (somewhere between the last release and this commit) I am able to extrude on a dynamic list, i.e. your supplied code snippet shows no errors and produces identical output to your static list extrude snippet.  

I think this issue should be closed.
