### ISSUE TITLE
[BUG]: Import does not work for any *.obj *.step

### ISSUE THREAD

**Issue by imadcat** [KittyCAD/modeling-app#4147]
### Describe the bug

`model = import('cube.obj')
`

### Steps to Reproduce

1. copy the cube.obj from "litterbox-main" in the example to the current project folder
2. add the following KCL code in the app `model = import('cube.obj')`
3. you will see the error

### Expected Behavior

the files imported properly

### Screenshots and Recordings

![Image](https://github.com/user-attachments/assets/08ac4050-193b-4176-ac7c-aab85ef84370)

### Desktop OS

Windows 11 x64

### Version

v0.25.6

**Comment by jtran** [comment]
Thank you for reporting this. We found the cause, and we'll do our best to push a fix as soon as we can.
