### ISSUE TITLE
Add Boolean 'and' and 'or' to kcl stdlib

### ISSUE THREAD

**Issue by guptaarnav** [KittyCAD/modeling-app#4188]
Currently boolean and/or is not implemented.

**Comment by nrc** [comment]
I think these should be operators (`&` and `|`). I guess that `&` is pretty clear, I'm not sure if `|` has any intuition for non-programmers, but it is a well-established convention, and I don't think it's a big thing to learn. We might want to make `&&` and `||` aliases for the simpler version (I don't think we should make short-circuiting part of the semantics, we can leave that as an implementation detail, but the doubled versions are more common in the wild)
