### ISSUE TITLE
Sketch on plane incorrectly orients the viewport

### ISSUE THREAD

**Issue by JBEmbedded** [KittyCAD/modeling-app#4226]
See video attached!!https://github.com/user-attachments/assets/9547e508-c469-4baa-92cc-1f57f3e3bb00

**Comment by franknoirot** [comment]
Hell yeah @JBEmbedded thanks for logging this. I wish I had seen it before I made up #4410. That one's got a bit more info in it, so I'm gonna close this one as duplicate.
