### ISSUE TITLE
`arc` (using center, to, and radius) is incorrect.

### ISSUE THREAD

**Issue by jgomez720** [KittyCAD/modeling-app#4235]
### Description
Jordan and Oscar (from makeathon) ran into a heavy bug using the version of `arc` that takes `center`, `to`, and `radius`. 
1. `to` and `center` are swapped. `to` calculates the center and `center` calculates the to. We found that out by the error message we were getting.
2. startProfileAt is incorrect. 

### KCL
```js
startSketchOn("XY")
|> startProfileAt([1, 0], %)
|> arc({
to:[0,0],
center:[1*cos(toRadians(45)),1*sin(toRadians(45))],
radius:1
}, %)
```
### Version
v0.26.0

### Screenshot
![Image](https://github.com/user-attachments/assets/303294a8-d315-4391-afa8-09bab92290eb)

**Comment by jgomez720** [comment]
@adamchalmers feel free to reassign, I only picked you because I think it's a KCL issue

**Comment by lf94** [comment]
Closed by https://github.com/KittyCAD/modeling-app/pull/4238
