### ISSUE TITLE
Do not show .git as a project folder

### ISSUE THREAD

**Issue by adamchalmers** [KittyCAD/modeling-app#4250]
![Image](https://github.com/user-attachments/assets/1f1a4c04-9a2b-4767-ad83-68f16d8ae75a)

ZMA registers a directory as its "main dir" or something. Then every subdirectory of that "main dir" is considered a project. But not all of them should be. Probably no folder whose name begins with `.` should be shown, but especially not `.git`

**Comment by lf94** [comment]
Closed by https://github.com/KittyCAD/modeling-app/pull/4317
