### ISSUE TITLE
network machines does not _react_ when it should

### ISSUE THREAD

**Issue by jessfraz** [KittyCAD/modeling-app#4278]
https://github.com/user-attachments/assets/bfa2d2d2-f24d-45f0-ab81-05f90945da9c

**Comment by lf94** [comment]
How can I get fake printers up with fake data? Or do I just guess and push to a branch and have you run?

**Comment by lf94** [comment]
@paultag do you think machine-api will work with my Elegoo Neptune 2 so I can test this locally or nah

**Comment by lf94** [comment]
Eh, guess I can mock with some setIntervals, all good.

**Comment by jessfraz** [comment]
i wqas gunna add a settings field so yall; can ping ours over tailscale sorry its on my list i will get there

**Comment by lf94** [comment]
No problem, I should be able to recreate no problem with mock data :) I'll do it between my work with Frank on fixing PW tests in my other branch.

**Comment by paultag** [comment]
The Noop printer should "work" -- see the nada machine example in the readme

**Comment by lf94** [comment]
I fixed this in https://github.com/KittyCAD/modeling-app/pull/4311
