### ISSUE TITLE
Switching mouse control schemes while in sketch mode unlocks the locked-down orbit

### ISSUE THREAD

**Issue by franknoirot** [KittyCAD/modeling-app#4280]
For now we are locking camera orbit while in sketch mode, but if you change the mouse controls setting while in sketch mode at the moment this stops being the case.

**Comment by Irev-Dev** [comment]
https://github.com/user-attachments/assets/14548bac-a2a8-4472-bf7f-1bef29d8454b

**Comment by franknoirot** [comment]
Shoot you're right that this was my initial misunderstanding of #4279. This is duplicate, closing.
