### ISSUE TITLE
On Linux (Fedora 40 - x86-64), code edited (and saved) outside of the zoo app is not reflected inside the zoo app editor

### ISSUE THREAD

**Issue by yeroca** [KittyCAD/modeling-app#4323]
[Add a title above and insert a description of the issue here]

If I have a  source file being shown in the code editor in zoo app,  and then edit and save it outside of the zoo app (e.g. using vim), the changes are not reflected inside of the zoo app. In other words, the app is not detecting that any change has been made to the file.
 
![Screenshot](https://public.blob.zoo.dev/f0eec22f-e437-4ddf-88aa-4df571f1a7cc/modeling-app/coredump-799c39d0-f4bc-45f7-a962-bf79dedec8b9-screenshot.png)

<details>
<summary><b>Core Dump</b></summary>

[coredump-799c39d0-f4bc-45f7-a962-bf79dedec8b9.json](https://public.blob.zoo.dev/49f89df9-ee5a-4a44-977c-f3cf3eb3d065/modeling-app/coredump-799c39d0-f4bc-45f7-a962-bf79dedec8b9.json)

Reference ID: 799c39d0-f4bc-45f7-a962-bf79dedec8b9
</details>

<details>
<summary><b>KCL Code</b></summary>

```kcl
moldingH = 5
rimW = 2

fn molding = (plane, startingPoint, len) => {
  return startSketchOn(plane)
  |> startProfileAt(startingPoint, %)
  |> yLine(moldingH, %)
  |> xLine(rimW, %)
  |> line([moldingH, -moldingH], %)
  |> close(%)
  |> extrude(len, %)
}

test1 = molding('XZ', [0, 0], 200)
test2 = molding('-YZ', [0, 0], -200)
test3 = molding('-XZ', [-200, 0], -200)
test4 = molding('YZ', [-200, 0], 200)


```
</details>

**Comment by lf94** [comment]
User has confirmed it works (coreypdx on Discord)
