### ISSUE TITLE
Need a way to make line after tangential arc tangent to the arc as well

### ISSUE THREAD

**Issue by franknoirot** [KittyCAD/modeling-app#4403]
> [!NOTE]
> As with all other sketch geometry creation tools, this will take on new iterations as we develop constraint-based language features into KCL, which we are exploring now and preparing for after an initial V1 pass. This issue will serve as a place for discussing both solutions for today and the future.

Currently users can make an arc that is tangential to the line before it using the `tangentialArc` KCL function or the tangential arc tool that automatically writes that function for them. But there is no way to make a straight segment that follows a tangential arc be exactly tangent to the arc's outgoing point. Traditionally, this is what a true tangential arc tool does, so we should support it.

## Engine notes
May need support here to get the outgoing tangent angle of an arc, but someone should edit this if I'm wrong and we either have this capability from the engine or don't need it because we can handle it higher up.
## API/KCL notes
May require a `tangentialLine` standard library function or other standard library function that allows users to get the outgoing tangent angle of an arc, which could then be fed into the `angle` parameter of an `angledLine` function.
## Point-and-click notes
Once the above is ready, add snapping logic to the straight segment tool that detects when near the outgoing tangent of the arc and changes the code mod to a tangentialLine accordingly.

## TradCAD demos

https://github.com/user-attachments/assets/71ab2bb1-c611-465a-a1d6-11c935c62c4f

**Comment by jtran** [comment]
Frontend sync meeting decisions:

- We'll make a function to return the angle tangent to an arc. In the future, we may want to inform the engine about this for better accuracy, but we're willing to go without that for right now.
- We need to do this all client-side without touching the engine because we need this in sketch mode
