### ISSUE TITLE
Add shell point-and-click operation

### ISSUE THREAD

**Issue by franknoirot** [KittyCAD/modeling-app#4472]
[See discussion here](https://github.com/KittyCAD/modeling-app/discussions/503) for more background.

## Engine notes
Ready. Initial passes and bug fixes complete.
## API/KCL notes
Ready. There is an ergonomic [`shell` standard library function](https://zoo.dev/docs/kcl/shell) available for use
## Point-and-click notes
1. Add a modeling machine command with 2 arguments:
    1. `faces`: a selection-type argument that only allows for selection of planar faces. If the endcaps of an extrude or revolve are selected, use keywords `"start"` and `"end"` in the code mod's faces array. If it is a an extrude wall, apply a tag to the segment if needed and add that.
    2. `thickness`: a KCL-type argument. Default to `1` or some sensible number
2. In future when [operation previews](https://github.com/KittyCAD/engine/issues/2233) are supported, add handles to adjust thickness live.

**Comment by franknoirot** [comment]
While the shell operation has cleared up many of its limitations in and of itself, it does make the model mostly unusable _after_ applying a shell. We should discuss whether to turn it on publicly if that remains the case when the UI side of this is done.

**Comment by pierremtb** [comment]
Internal discussion on Dec 4th: the current limitation of not being able to refer to and therefore sketch on inside shell faces **should not** prevent us from releasing this feature. But should be a warning until this is solved
