### ISSUE TITLE
KCL code is missing lines when lines are adjusted on the sketch

### ISSUE THREAD

**Issue by ZooSpiritWolf** [KittyCAD/modeling-app#4508]
🐞 on Dev

Steps to reproduce:
1. Log in
2. Close KCL code panel
3. Click "Start Sketch"
4.  Click the blue plane (XZ)
5. Sketch 4 lines (like a box)
6. Open kcl code panel
7. Ensure the code editor shows 4 sketch lines
8. Close kcl code panel
9. Click "Exit Sketch" button
10.  Open kcl code panel
11. Click "startProfileAt" line in the editor
12. Click "Edit Sketch" button
13. Close kcl code panel
14. Move the third line
15. Move the second line
Expected: Two additional lines should be produced and as a result, the KCL code should adjust to show 6 lines total
Actual: The KCL code remains the same and does not account for the two new lines in the sketch - it only shows 4 lines

Timestamp: 0:54
Video: 
https://www.loom.com/share/b635637c5ebf43e78219105c433ec605?sid=b6bedeb6-9a04-4f68-8bf4-21fcc1e677d1 (https://www.loom.com/share/b635637c5ebf43e78219105c433ec605?sid=b6bedeb6-9a04-4f68-8bf4-21fcc1e677d1)

Bug report:
https://app.qawolf.com/zoo/bug-reports/95da1305-3ffd-4359-9a83-68700bcb127b

Affected workflows:
• Edit Sketch - Drag to Move Multiple Lines - https://app.qawolf.com/zoo/workflows/clxxkyi5f03pr1yl66anfm74y

If you are aware of this bug you can set the priority to low which will prevent it from causing a run failure.

**Comment by Irev-Dev** [comment]
I had a chat to them about this, and their test just needed adjusting.

https://kittycadworkspace.slack.com/archives/C071JD7EZGF/p1731966521233189
