### ISSUE TITLE
[BUG]: Source range incorrect for `map` function arg type mismatch

### ISSUE THREAD

**Issue by greg-kcio** [KittyCAD/modeling-app#4528]
### Describe the bug

When passing the wrong arg types to the `map` function, and one of the args is itself a function, the wrong line is underlined.

### Steps to Reproduce

Enter this KCL into the editor. In this example, Text-to-CAD misused the `map` function by swapping the order of the args.

```
// Generated by Text-to-CAD: Module 1 rack with a length of 100mm, a width of 10mm, and a height of 10mm.
// Define constants
length = 100
width = 10
height = 10
toothHeight = 2.5
toothWidth = 5
toothSpacing = 10
// Create the body of the rack
rackBody = startSketchOn('XY')
  |> startProfileAt([-length / 2, 0], %)
  |> line([length, 0], %)
  |> line([0, height - toothHeight], %)
  |> line([-length, 0], %)
  |> close(%)
  |> extrude(width, %)
// Create a function for sketch of a single tooth
fn tooth = (origin) => {
  toothSketch = startSketchOn('XY')
  |> startProfileAt([origin, height - toothHeight], %)
  |> line([toothWidth / 2, toothHeight], %)
  |> line([toothWidth / 2, -toothHeight], %)
  |> close(%)
  |> extrude(width, %)
  return toothSketch
}
// Function to calculate tooth positions
fn calculateToothPosition = (i) => {
  return -length / 2 + toothSpacing / 2 + i * toothSpacing
}
// Generate positions for the teeth
toothPositions = map(calculateToothPosition, [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
// Pattern the single tooth over the length of the rack body
teeth = map(tooth, toothPositions)
```

### Expected Behavior

Line 32 (`toothPositions = map(calculateToothPosition, [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])`) should be underlined, rather than the function expression on lines 28-30.

### Screenshots and Recordings

![Image](https://github.com/user-attachments/assets/b12d7dc6-033d-49c5-a7ad-6faaa13c95a0)

### Desktop OS

Ubuntu

### Version

0.27.0

**Comment by paultag** [comment]
I reckon the arguments to `map` are flipped - easy to do since this is opposite to `python`'s `map`. Can you try flipping the order of arguments to `map` there and see if it helps?

Definitely a cryptic-error. Tagged!

**Comment by jtran** [comment]
Hmm, `FromArgs` is using the source range of the arg value (in this case, the function), not the arg expression (the variable used in the call).
