### ISSUE TITLE
Regression on "car wheel"

### ISSUE THREAD

**Issue by mlfarrell** [KittyCAD/modeling-app#4635]
Running https://zoo.dev/docs/kcl-samples/car-wheel on webapp main + engine main gives a broken result

![Image](https://github.com/user-attachments/assets/8447f0ac-52d8-495f-8cfd-66a0e8e07879)

while the red lines will "go away" in an upcoming engine merge, there's still something regressed/broken here.

**Comment by adamchalmers** [comment]
This was a problem with units of measurement
