### ISSUE TITLE
[BUG]: Setting mouse controls to OnShape resets to KittyCAD

### ISSUE THREAD

**Issue by pierremtb** [KittyCAD/modeling-app#4639]
### Describe the bug

Setting mouse controls to OnShape resets to KittyCAD. Both on onboarding and in the user settings.

### Steps to Reproduce

1. Go to Settings
2. Go to Modeling
3. Select OnShape for Mouse Controls

### Expected Behavior

I should be able to select OnShape as the option for Mouse Controls.

### Screenshots and Recordings

https://github.com/user-attachments/assets/e22ec73e-9a19-4526-a948-15dd64515f04

### Desktop OS

macOS

### Version

5ae1aec

**Comment by pierremtb** [comment]
Also broken on v28

**Comment by franknoirot** [comment]
It's likely something small, like a wrong key/id name for the OnShape controls that isn't agreeing between WASM and TS (like `Onshape` vs `OnShape` comes to mind)

**Comment by pierremtb** [comment]
Yeah makes sense! Haven't found a smoking gun yet but didn't look super closely.

Can reproduce on Windows 10 too

**Comment by pierremtb** [comment]
Works on v0.25.0

**Comment by pierremtb** [comment]
v0.26.0 has this bug

**Comment by pierremtb** [comment]
v0.25.6 doesn't have this bug. So it's in https://github.com/KittyCAD/modeling-app/compare/v0.25.6...v0.26.0

**Comment by pierremtb** [comment]
Bisect led to https://github.com/KittyCAD/modeling-app/commit/24cd1b2ea514ff739337045929f27e1e3bca6ae9 as the commit bringing in the regression here

**Comment by pierremtb** [comment]
It's not a list order thing.

But AutoCAD also doesn't work!! Both OnShape and AutoCAD get reset to KittyCAD on selection

**Comment by pierremtb** [comment]
What's common with these two is the underscore in their keys. KittyCAD also has it, but since it's the default one maybe we don't see that behaviour happening.

https://github.com/KittyCAD/modeling-app/blob/441d9572287e45aa6e7b613a9749331fe6f34fd6/src/lib/cameraControls.ts#L31-L52
