### ISSUE TITLE
Replace button hard to see on dark mode

### ISSUE THREAD

**Issue by jgomez720** [KittyCAD/modeling-app#4715]
### Description
Small issue. This is on nightly. The replace button for the warnings is hard to see. On light mode, it is clear that it is a button that can be pressed.

### KCL
```js
export fn antenna = (plane, origin)  {
  antennaX = origin[0]
  antennaY = origin[1]
  
  antennaBaseWidth = .5
  antennaBaseHeight = .25
  sketch001 = startSketchOn(plane)
    |> startProfileAt([origin[0], origin[1]], %)
    |> line([antennaBaseWidth, 0], %)
    |> line([0, -antennaBaseHeight], %)
    |> line([-antennaBaseWidth, 0], %)
    |> close(%)
    
  loftPlane = offsetPlane(plane, 3)
  
  antennaTopWidth = .30
  antennaTopHeight = .05
  
  sketch002 = startSketchOn(loftPlane)
    |> startProfileAt([origin[0] + (antennaBaseWidth - antennaTopWidth)/2, origin[1] - (antennaBaseHeight - antennaTopHeight)/2], %)
    |> xLine(antennaTopWidth, %)
    |> yLine(-antennaTopHeight, %)
    |> xLine(-antennaTopWidth, %)
    |> close(%)
  
  return loft([sketch001, sketch002])
}
```

### Version
v24.12.9

### Recordings/Screenshots
**Light mode**
![Image](https://github.com/user-attachments/assets/623ef791-3382-4d44-a012-0efd68d7f193)

**Dark mode**
![Image](https://github.com/user-attachments/assets/43f1a1bb-1dab-4dba-94fb-6caab1f32ad3)

**Comment by pierremtb** [comment]
Nice thanks for reporting! Cc @franknoirot

**Comment by franknoirot** [comment]
I am pleasantly surprised that we have these buttons now 😅 I had no idea. This'll be pretty straightforward after inspecting the element

**Comment by pierremtb** [comment]
This is the button to style
```
<button type="button" class="cm-diagnosticAction" aria-label=" Action: Remove `const`.">Remove `const`</button>
```
