### ISSUE TITLE
Generate an operation list while parsing to pass back to TS

### ISSUE THREAD

**Issue by franknoirot** [KittyCAD/modeling-app#4720]
Map over both:
1. Stdlib function calls
2. User function calls + User function returns

To generate a list of operations to send back to the frontend. This will be used in displaying an operation timeline (often referred to as a "feature tree" by mechanical engineers).

Along the way, capture:
1. The arguments of those function calls
2. Their source ranges and/or artifacts

So that these can be mapped back to within the operation list's UI. For example, this will enable a right-click "go to source" right-click menu item in the UI.

**Comment by franknoirot** [comment]
Related to #4274

**Comment by franknoirot** [comment]
@jtran is my understanding of the shape of the data in the ballpark? Using TS types because I'm lazy :/

```ts
type Operation = {
    /** idk why I assume there is a uuid */
    id: string
    /** the function calling name */
    name: string
    /** the parameters passed into the function */
    parameters: Record<string, Expr>
    /** the code reference (just mimicked the artifactGraph codeRef) */
    codeRef: {
      range: SourceRange
      pathToNode: PathToNode
    }
    /** the returned value of the operation's function */
    returnValue: Expr
}

type OperationList = Array<Operation>
```

**Comment by jtran** [comment]
Overall, it looks good. A couple things.

1. I can't think of why we need an ID, so we might not have that. As you pointed out, an edge cut could have multiple engine commands, so it's not an engine UUID. Perhaps we could have a sequential numeric ID if that would help, but that might be easier to generate on the JS side. We can discuss it.
2. For parameters and returnValue, replace `Expr` with `KclValue`. `2 * x + 1` is an expression. `7` would be the fully-evaluated value.
3. For `codeRef`, I'm not sure how we'll build the PathToNode. We haven't done that on the Rust side yet.

**Comment by franknoirot** [comment]
> 1. I can't think of why we need an ID, so we might not have that. As you pointed out, an edge cut could have multiple engine commands, so it's not an engine UUID. Perhaps we could have a sequential numeric ID if that would help, but that might be easier to generate on the JS side. We can discuss it.

Great, I have no problem with having no ID; I would probably just use it as a key for React array rendering which I can make from anything.

> 2. For parameters and returnValue, replace `Expr` with `KclValue`. `2 * x + 1` is an expression. `7` would be the fully-evaluated value.

Hm if the parameters are to be useful in the feature tree UI built on the operations list, I think having the original expression is at least as valuable as the evaluated value. That way we can pipe that into the command palette flow as the initial value for the argument to be edited: we would want to let the user edit `2 * x + 1` in the command palette, not the `7`.

> 3. For `codeRef`, I'm not sure how we'll build the PathToNode. We haven't done that on the Rust side yet.

Ah okay no sweat, I bet we could get by on source range alone for a first pass; we have utilities like [`getNodePathFromSourceRange`](https://github.com/KittyCAD/modeling-app/blob/main/src/lang/queryAst.ts#L407) available on the TS side.

**Comment by jtran** [comment]
Instead of duplicating the KCL code of all arguments, we can use a source range. That would be way more efficient. This is what I have so far.

```typescript
type Operation = {
  /** what kind of operation it is */
  type: "userDefinedFunctionCall" | "userDefinedFunctionReturn" | "stdlibFunctionCall"
  /** the name of the function being called, if it has one. Anonymous functions wouldn't have a name. */
  name: string | null
  /** the arguments passed into the function. (This is great for new keyword
      arguments, but not sure about legacy positional arguments.) */
  arguments: Record<string, SourceRange>
  /** the code reference (just mimicked the artifactGraph codeRef) */
  codeRef: {
    range: SourceRange
    // Maybe...
    // pathToNode: PathToNode
  }
}

type OperationList = Array<Operation>
```

**Comment by franknoirot** [comment]
I failed to discuss this with you earlier, but I'm not certain how I ought to derive that "dependency graph" from an operation list item instead of the artifactGraph. It was actually kind of easy with the artifactGraph, as far as I got, because I built up the "feature tree" kind of in dependency order. Just something I'll have to figure out, honestly not required for a first pass of this.

**Comment by jtran** [comment]
I talked about this briefly with Kurt. It would definitely be nice if we could link the operations and the artifact graph together. If we can extract the `ArtifactId`s/UUIDs from the stdlib function calls, I think it can be done. I'm trying to understand how it can be done in a clear way that isn't a maintenance burden. But in the case when the client generates the UUID in the stdlib Rust function, we could add that to the operation. Then TS could use that to look up artifacts in the graph.

The only thing I don't completely understand is how sometimes tags get updated by later stdlib calls. `Sketch` has an `original_id` field that I don't really get.

https://github.com/KittyCAD/modeling-app/blob/058fccb5e103d1c80843ca65a3ad72c1a3eb6423/src/wasm-lib/kcl/src/execution/mod.rs#L786
