### ISSUE TITLE
[BUG]: KCL LSP doesn't start in dev mode

### ISSUE THREAD

**Issue by TomPridham** [KittyCAD/modeling-app#4739]
### Describe the bug

The KCL LSP doesn't start when running the app locally with `yarn tron:start`. It fails on this line https://github.com/KittyCAD/modeling-app/blob/main/src/wasm-lib/src/wasm.rs#L332 because there is a CORS error when trying to get the privacy settings. Commenting the error out and returning false instead lets the server start normally
Is there a reason not to just return false there instead of returning an error and bailing?

### Steps to Reproduce

1: copy the `.env.production` to `.end.development`
2: open a sketch
3: see KCL LSP fail to start
4: changes in editor don't have any effect on sketch, highlighting doesn't work, etc

### Expected Behavior

The KCL LSP should start and I should be able to make changes in the editor pane

### Desktop OS

Ubuntu 24

### Version

main

**Comment by jessfraz** [comment]
yeah thats fine we dont use it today at all anyways, the lang is changing too much
