### ISSUE TITLE
Cut release v0.32.0

### ISSUE THREAD

**Issue by Irev-Dev** [KittyCAD/modeling-app#4811]
Follow process at https://github.com/KittyCAD/modeling-app/blob/548c664db0e30876c9a9fcd6aeec30f9c1d89e6a/README.md?plain=1#L129

**Comment by Irev-Dev** [comment]
Building here
https://github.com/KittyCAD/modeling-app/actions/runs/12348124543

**Comment by pierremtb** [comment]
Change of direction, now going for a revert of multi-profile to be on the safer side as we fix the remaining things with multi-profile ahead of the next one

Waiting on https://github.com/KittyCAD/modeling-app/pull/4812 to go green

**Comment by pierremtb** [comment]
Prepared a backup branch off main that we can tag if need be at https://github.com/KittyCAD/modeling-app/commits/pierremtb/backup-cut-release-v0.32.0/

**Comment by pierremtb** [comment]
Deleted existing tag for v0.32.0 as we'll be replacing it

<img width="1192" alt="Image" src="https://github.com/user-attachments/assets/821c30d5-f7e2-4496-9198-8690ef55ffb8" />

**Comment by pierremtb** [comment]
As we wait for the merge we can start smoke testing with https://github.com/KittyCAD/modeling-app/actions/runs/12354823041?pr=4812

Only diff with these builds versus the future v0.32.0 tag are the codesign and package version @nadr0

**Comment by pierremtb** [comment]
## Manual test tasklist: macOS from https://github.com/KittyCAD/modeling-app/actions/runs/12354823041?pr=4812

* [ ] The application opens
* [ ] User can sign in
* [ ] The onboarding can be replayed and looks solid
* [ ] A project can be created
* [ ] A sketch can be draw (line, arc, rect, circle).
* [ ] Lines and shapes can be modified.
* [ ] Select face and extruding works.
* [ ] Reloading the application gets you back in the same state
* [ ] Can create additional files and directories.
* [ ] Models can be exported to a file.
* [ ] I repeated some code done with point-and-click by typing in the code editor and everything was responsive and ok.
* [ ] Double clicking a KCL file opens ZMA, and with the CLI too on project directory or file
* [ ] Offset plane can be created and shows up
* [ ] The auto-updater works.

**Comment by nadr0** [comment]
Testing `out-x64-linux`


* [ ] The application opens
* [ ] User can sign in
* [ ] The onboarding can be replayed and looks solid
* [ ] A project can be created
* [ ] A sketch can be draw (line, arc, rect, circle).
* [ ] Lines and shapes can be modified.
* [ ] Select face and extruding works.
* [ ] Reloading the application works.
* [ ] Can create additional files and directories.
* [ ] Models can be exported to a file.
* [ ] I repeated some code done with point-and-click by typing in the code editor and everything was responsive and ok.
* [ ] Double clicking a KCL file opens ZMA, and with the CLI too on project directory or file
* [ ] Offset plane can be created and shows up
* [ ] The auto-updater works.

**Comment by pierremtb** [comment]
## Manual test tasklist: Windows

* [ ] The application opens
* [ ] User can sign in
* [ ] The onboarding can be replayed and looks solid
* [ ] A project can be created
* [ ] A sketch can be draw (line, arc, rect, circle).
* [ ] Lines and shapes can be modified.
* [ ] Select face and extruding works.
* [ ] Reloading the application works.
* [ ] Can create additional files and directories.
* [ ] Models can be exported to a file.
* [ ] I repeated some code done with point-and-click by typing in the code editor and everything was responsive and ok.
* [ ] Double clicking a KCL file opens ZMA, and with the CLI too on project directory or file
* [ ] Offset plane can be created and shows up
* [ ] The auto-updater works.

**Comment by pierremtb** [comment]
## Manual test tasklist: macOS, building on the one before

* [x] The application opens
* [x] User can sign in
* [x] The onboarding can be replayed and looks solid
* [x] Models can be exported to a file.
* [ ] The auto-updater works.

**Comment by pierremtb** [comment]
v0.32.0 is out
