### ISSUE TITLE
Horiz. Scroller in the way of toolbar on linux + firefox

### ISSUE THREAD

**Issue by mlfarrell** [KittyCAD/modeling-app#482]
Linux + firefox + dev has a horizontal scroller come up in the way of the toolbar buttons (such as when trying to select move)

If other OSes aren't affected, then i'd consider this minor.

![image](https://github.com/KittyCAD/modeling-app/assets/7664370/f59893ac-03dc-42b5-9710-6acdb7387bd4)

**Comment by jgomez720** [comment]
@franknoirot I just tested this in Firefox and this was no longer an issue, I think this was a problem in the old UI. I'm closing, but please reopen if you need it
