### ISSUE TITLE
zoo

### ISSUE THREAD

**Issue by zhang120aa** [KittyCAD/modeling-app#4870]
[Add a title above and insert a description of the issue here]

![Screenshot](https://public.blob.zoo.dev/29cdec01-5993-44d6-b514-c723cdbe2d85/modeling-app/coredump-80286608-6f3a-4f34-8eac-f79d1f8e082f-screenshot.png)

<details>
<summary><b>Core Dump</b></summary>

[coredump-80286608-6f3a-4f34-8eac-f79d1f8e082f.json](https://public.blob.zoo.dev/64c04854-3d56-47d2-8395-9845a6b88f6f/modeling-app/coredump-80286608-6f3a-4f34-8eac-f79d1f8e082f.json)

Reference ID: 80286608-6f3a-4f34-8eac-f79d1f8e082f
</details>

**Comment by Irev-Dev** [comment]
Going to close for now, Feel free to open back up if you're able to add more details as to what went wrong.
