### ISSUE TITLE
Keyboard commands failing

### ISSUE THREAD

**Issue by jgomez720** [KittyCAD/modeling-app#545]
### Description
If I wait around in the app for long enough without doing anything, I tend to get this bizarre error where my keyboard commands get erased. Can't describe this one well.

### Version
Dev build - **0.7.0**

https://github.com/KittyCAD/modeling-app/assets/114548659/28a5c57a-8a21-4e62-8b49-a90659933409

**Comment by jessfraz** [comment]
i think editor improvments fixed this
