### ISSUE TITLE
benchmark ast parts

### ISSUE THREAD

**Issue by jessfraz** [KittyCAD/modeling-app#580]
this would be really nice to see if we regress or get faster

- [x] tokenizer
- [x] parser
- [ ] executor (for this I have some integration tests (src/wasm-lib/tests_ that are likely helpful to kinda copy the setup of since it needs engine connection)

the would be really cool to say something to users like just opening a model and exporting it to step in autocad versus like us thru command line would be so much faster ya know but actually have the data on how much faster

assigned @adamchalmers since you usually have good ideas about this stuff

related to https://github.com/KittyCAD/modeling-app/issues/755

**Comment by adamchalmers** [comment]
We have benchmarks for the parser and tokenizer already, just run "cargo criterion". Not for the executor yet though because benchmarking network requests is very different.
