### ISSUE TITLE
if the engine disconnects and reconnects when you are in sketch mode your state is effed

### ISSUE THREAD

**Issue by jessfraz** [KittyCAD/modeling-app#584]
so say I am in sketch mode and it disconnects and reconnects, you get bumped back out to non sketch mode, but your toolbar thinks you are still in sketch mode, and usually i just refresh to un-eff the world, because if you only hit exit, your whole stream goes blur mode and you cant get out of it, its very weird

2 solutions:
- [ ] (likely easiest) if engine disconnects and reconnects reset the state for toolbar and everthing else
- [ ] put the user back in the state they were in (likely harder)

cc @paultag @franknoirot @Irev-Dev  to coordinate on what should be done here

as a side note it would be really cool to simulate stuff like this with playwright if at all possible -> https://github.com/KittyCAD/modeling-app/issues/536

**Comment by Irev-Dev** [comment]
most likely calling `setupSketch` again on reconnect will be part of the solution (`src/clientSideScene/sceneEntities.ts:289`)

**Comment by Irev-Dev** [comment]
And the params that it expects should still be in xstate context as "sketchDetails"

**Comment by Irev-Dev** [comment]
I might be wrong though, probabyl good to first figure out in what way is the state effed.

**Comment by jessfraz** [comment]
to be fair i dont think state is "effed" its just when the engine comes back its not in sketch mode even tho xstate thinks you still are, so i think on engine network interrupt we should exit sketch mode by default

**Comment by jessfraz** [comment]
that seems safest option for now, we could get fancy w it down the road

**Comment by Irev-Dev** [comment]
It might be worth doing this the xstate way, like when we disconnect we fire an event that puts in you a "disconnected" state. That when we re connect you can just fire a reconnection event that puts you back into the sktech state, and all of the enter sketch actions will fire as per usual.

One thing I think might be tricky about this is I think it's probably easier if we say, user's can lose their currently equipped tool, i.e. we always transition them back into sketchIdle.

This seems to important to not have in our state diagram.

idk wdyt @franknoirot

**Comment by Irev-Dev** [comment]
Sorry I'm trying to make this more complicated, if you get something that works, it can always be tweaked later.
