### ISSUE TITLE
Zoom latency with macbook trackpad

### ISSUE THREAD

**Issue by dundermane** [KittyCAD/modeling-app#630]
### System
Macbook M1, Ventura 13.4.1

### Description
When scrolling with the trackpad to zoom, the zoom continues about 500ms after I stop sliding my fingers.   When using a mouse on the same machine, I do not experience this behavior.

### Severity: Minor

**Comment by Irev-Dev** [comment]
Resolved by https://github.com/KittyCAD/modeling-app/pull/1287
