### ISSUE TITLE
Graphics rendering issue: Fuzzy edges and artifacts

### ISSUE THREAD

**Issue by dundermane** [KittyCAD/modeling-app#652]
### System
Macbook M1, Ventura 13.4.1

### Description
Edges of model are pixel-y.  Also you can see a horizontal line on part002, which should not be there.

<img width="1480" alt="image" src="https://github.com/KittyCAD/modeling-app/assets/6868722/198b1b53-d646-4b9d-970d-da6c026607b2">

### Severity: Minor

**Comment by jessfraz** [comment]
this should be good now let me know if otherwise
