### ISSUE TITLE
Stream blurred after trying "extrude as new" on a line

### ISSUE THREAD

**Issue by jgomez720** [KittyCAD/modeling-app#655]
Edit by Kurt: #682 has fixed the immediate problem of getting stuck on blur, however extrude being available on sketches that isn't closed should get follow up with the xstate migration.

---

Shown by Kegan in Discord

Frank, I have a feeling this has something to do with the blur you used to have when the user drags the screen, but I might be wrong

https://github.com/KittyCAD/modeling-app/assets/114548659/7fcc68e7-d535-4668-abaf-faa5a374d1cd

**Comment by Irev-Dev** [comment]
There's now a guard against extruding unclosed sketches so will be resolved by
https://github.com/KittyCAD/modeling-app/pull/713
