### ISSUE TITLE
Custom updater dialog so we can render mark down

### ISSUE THREAD

**Issue by Irev-Dev** [KittyCAD/modeling-app#695]
I find the generated release notes to be pretty good and convenient for releases of the app (maybe I'm just lazy), but they are markdown and are not displaying well in the updater dialog

We're able to use a custom dialog according to the tauri docs
https://tauri.app/v1/guides/distribution/updater/#custom-dialog

Related to https://github.com/KittyCAD/website/issues/1388

This is far from urgent.

**Comment by pierremtb** [comment]
Yup, done in #1738
