### ISSUE TITLE
Tokenizing should be fallible

### ISSUE THREAD

**Issue by adamchalmers** [KittyCAD/modeling-app#696]
Right now the tokenizer discards tokens it doesn't recognize. But it should error about them instead.

Consequences:

- Currently the tokenizer ignores semicolons, but it should probably either error out on them, or put them into the AST.

**Comment by notalfredo** [comment]
Hi, I want to tackle this!

**Comment by adamchalmers** [comment]
That'd be great, thank you! Would you mind please waiting until I finish a large PR around the related codebase: https://github.com/KittyCAD/modeling-app/pull/731 -- otherwise we're going to stomp all over each other's work haha

**Comment by notalfredo** [comment]
> That'd be great, thank you! Would you mind please waiting until I finish a large PR around the related codebase: #731 -- otherwise we're going to stomp all over each other's work haha. That PR should be done in a few days.
> 
> (I mean, feel free to start it, but be aware that I might cause a bunch of merge conflicts for you)

I will wait the few days. This should give me a bit more time to get familiar with the part of the code base I will be working on. Excited to contribute !

**Comment by notalfredo** [comment]
@adamchalmers im going to start working on this since I noticed you pr got merged #731. I also saw on your pr mentioned issue #784. I believe I could probably knock out both of them with one PR ?  Any helpful tips ? 

Thank you ! :)
