### ISSUE TITLE
Stream Clipping

### ISSUE THREAD

**Issue by jgomez720** [KittyCAD/modeling-app#718]
Reported by `EppicJR` in Discord.

<img width="318" alt="Screenshot_2023-09-25_at_8 28 45_PM" src="https://github.com/KittyCAD/modeling-app/assets/114548659/a1c30ce1-462c-4a0a-aaae-f8cd17ad86ce">

**Comment by jessfraz** [comment]
I know the fix here we need to pull thru from engine so ill do this one

**Comment by mlfarrell** [comment]
@jessfraz this should be already fixed.  this is why we need linked issues better in GH.  
https://github.com/KittyCAD/engine/issues/1465

**Comment by jessfraz** [comment]
oh my bad I thought it depended on a websocket call! nice!
