### ISSUE TITLE
Can't select segments without exiting and re-entering + phatom lines

### ISSUE THREAD

**Issue by Irev-Dev** [KittyCAD/modeling-app#757]
- [ ] When starting a sketch, segments can't be selected until the sketch has been exited and re-entered
- [x] When adding a constraint, the re-execute clean up isn't firing (I'm guessing), leading to phantom lines

https://github.com/KittyCAD/modeling-app/assets/29681384/231fd1b2-fdb7-4f48-8951-f7a632af0b84

Apologies to non-kittycad staff, but there's some more discussion in this slack thread
https://kittycadworkspace.slack.com/archives/C04KFV6NKL0/p1696283385851489
https://kittycadworkspace.slack.com/archives/C04KFV6NKL0/p1696282664891419?thread_ts=1696270978.680849&cid=C04KFV6NKL0

**Comment by Irev-Dev** [comment]
sketch has been exited and re-entered had been fixed (forget which PR) but has since broken, looking into it again now.

**Comment by jessfraz** [comment]
i think this works now
