### ISSUE TITLE
the step file from the sample code exported looks weird

### ISSUE THREAD

**Issue by jessfraz** [KittyCAD/modeling-app#766]
cc @jgomez720 to make sure its not this shitty viewer i used

<img width="423" alt="Screenshot 2023-10-03 at 12 21 11 PM" src="https://github.com/KittyCAD/modeling-app/assets/1445228/5417bb77-21d1-4726-9256-eabe2001947c">

```
const sigmaAllow = 15000 // psi
const width = 11 // inch
const p = 150 // Force on shelf - lbs
const distance = 12 // inches
const FOS = 2
const thickness = sqrt(distance * p * FOS * 6 / ( sigmaAllow * width ))
const filletR = thickness * 2
const shelfMountL = 9
const wallMountL = 8

const bracket = startSketchAt([0, 0])
  |> line([0, wallMountL], %)
  |> tangentalArc({
    radius: filletR,
    offset: 90
  }, %)
  |> line([-shelfMountL, 0], %)
  |> line([0, -thickness], %)
  |> line([shelfMountL, 0], %)
  |> tangentalArc({
    radius: filletR - thickness,
    offset: -90
  }, %)
  |> line([0, -wallMountL], %)
  |> close(%)
  |> extrude(width, %)

show(bracket)
```

**Comment by jgomez720** [comment]
Nope, something is certainly weird. 

Also, the tauri dev app doesn't export something readable at all. I could only get something from the web app. I think @franknoirot and I talked about that once before too

![Screenshot 2023-10-03 at 12 50 09 PM](https://github.com/KittyCAD/modeling-app/assets/114548659/e3154b9d-4fdd-457a-ab3d-8e7d5a7dda98)

**Comment by jgomez720** [comment]
@alteous, this has something to do with the `tangentialArcs`, because @franknoirot and I exported a good looking bracket without that before.

**Comment by jessfraz** [comment]
I can def look into the specific tauri side

**Comment by jessfraz** [comment]
is it just step on tauri or all types?

**Comment by jgomez720** [comment]
Just tested. All file types. Creating an issue now

**Comment by alteous** [comment]
That’s interesting. I expect this is a problem with the export code in the engine repository although it is strange we don’t get the same(?) output from the dev app. If you happen to have it at hand,  could you provide the glTF output from both the dev app and the web app? I’ll try to reproduce today otherwise.

**Comment by jgomez720** [comment]
[Issue766.zip](https://github.com/KittyCAD/modeling-app/files/12799472/Issue766.zip)

There's one GLTF from the tauri app and one from the web app

**Comment by alteous** [comment]
![image](https://github.com/KittyCAD/modeling-app/assets/8549126/12495c2e-8963-4297-9502-26d3a0c2e041)
For my reference, this is what the model should look like.

**Comment by alteous** [comment]
I'm attempting to reproduce this issue in the engine tests. Are these the expected commands? https://github.com/KittyCAD/engine/pull/1501/files

**Comment by jessfraz** [comment]
yeah pretty much that looks right! thanks!

**Comment by jessfraz** [comment]
Fwiw the issue was fixed so you do get the same output from both the web and tauri side so it’s just the tangential arc bit remaining :)

**Comment by alteous** [comment]
```
 66 SelectClear
 67 SelectAdd(SelectAdd { entities: [] })
 68 CameraDragStart(CameraDragStart { interaction: Rotate, window: Point2d { x: 994.0, y: 278.0 } })
 69 CameraDragEnd(CameraDragEnd { interaction: Rotate, window: Point2d { x: 1000.0, y: 290.0 } })
 70 ReconfigureStream(ReconfigureStream { width: 1708, height: 884, fps: 60 })
 71 ReconfigureStream(ReconfigureStream { width: 1708, height: 928, fps: 60 })
 72 SelectClear
 73 SelectAdd(SelectAdd { entities: [] })
 74 SelectClear
 75 SelectAdd(SelectAdd { entities: [] })
 76 SelectClear
 77 SelectAdd(SelectAdd { entities: [] })
 78 RemoveSceneObjects(RemoveSceneObjects { object_ids: {4c9c1917-d432-4f84-b180-8578b43a6aa6} })
 79 StartPath
 80 MovePathPen(MovePathPen { path: ModelingCmdId(5f182efe-cfe5-4bbe-b058-58aef57de04a), to: Point3d { x: 0.0, y: 0.0, z: 0.0 } })
 81 ExtendPath(ExtendPath { path: ModelingCmdId(5f182efe-cfe5-4bbe-b058-58aef57de04a), segment: Line { end: Point3d { x: 0.0, y: 8.0, z: 0.0 }, relative: true } })
 82 ExtendPath(ExtendPath { path: ModelingCmdId(5f182efe-cfe5-4bbe-b058-58aef57de04a), segment: TangentialArc { radius: 0.7236272269866327, offset: Angle { unit: Degrees, value: 90.0 } } })
 83 ExtendPath(ExtendPath { path: ModelingCmdId(5f182efe-cfe5-4bbe-b058-58aef57de04a), segment: Line { end: Point3d { x: -9.0, y: 0.0, z: 0.0 }, relative: true } })
 84 ExtendPath(ExtendPath { path: ModelingCmdId(5f182efe-cfe5-4bbe-b058-58aef57de04a), segment: Line { end: Point3d { x: 0.0, y: -0.3618136134933164, z: 0.0 }, relative: true } })
 85 ExtendPath(ExtendPath { path: ModelingCmdId(5f182efe-cfe5-4bbe-b058-58aef57de04a), segment: Line { end: Point3d { x: 9.0, y: 0.0, z: 0.0 }, relative: true } })
 86 ExtendPath(ExtendPath { path: ModelingCmdId(5f182efe-cfe5-4bbe-b058-58aef57de04a), segment: TangentialArc { radius: 0.3618136134933164, offset: Angle { unit: Degrees, value: -90.0 } } })
 87 ExtendPath(ExtendPath { path: ModelingCmdId(5f182efe-cfe5-4bbe-b058-58aef57de04a), segment: Line { end: Point3d { x: 0.0, y: -8.0, z: 0.0 }, relative: true } })
 88 ClosePath(ClosePath { path_id: 5f182efe-cfe5-4bbe-b058-58aef57de04a })
 89 Extrude(Extrude { target: ModelingCmdId(5f182efe-cfe5-4bbe-b058-58aef57de04a), distance: 11.0, cap: true })
 90 PathGetInfo(PathGetInfo { path_id: 5f182efe-cfe5-4bbe-b058-58aef57de04a })
 91 Export(Export { entity_ids: [], source_unit: Inches, format: Step(ExportOptions { coords: System { forward: AxisDirectionPair { axis: Y, direction: Negative }, up: AxisDirectionPair { axis: Z, direction: Positive } }, created: None })     })
```
Modelling commands dumped from local dev-stack.

**Comment by jessfraz** [comment]
Startpath movepathpen extendpath closepath extrude are all that really matters

**Comment by alteous** [comment]
The model doesn't display immediately, even in the local setup. The commands are at least correct and still produce the same export data as reported.

**Comment by alteous** [comment]
This explains why the test image doesn't show any geometry.

**Comment by alteous** [comment]
I wrote a program that edits the glTF file and inserts points to visualise the control points of the NURBS surfaces. The points are coloured differently for each surface. These are the only points I can see and they are in weird places. The export data says there are six control points in each surface.

![control-points](https://github.com/KittyCAD/modeling-app/assets/8549126/b4660906-1ee3-4593-b8de-ae619646eb58)

**Comment by alteous** [comment]
I amended the code to display little cubes instead. The control points are much easier to see now. They are still in strange places.

![image](https://github.com/KittyCAD/modeling-app/assets/8549126/c646b342-c849-4624-adac-733afb25bc70)

**Comment by alteous** [comment]
The contents of the dump for the NURBS surfaces from OpenNURBS doesn't match the glTF output.

```
ON_NurbsSurface dim = 3 is_rat = 1
        order = 3 X 2 cv_count = 3 X 2
Knot Vector 0 ( 4 knots )
index                     value  mult       delta
    0       27.361813613493318     2
    2       28.361813613493318     2           1
Knot Vector 1 ( 2 knots )
index                     value  mult       delta
    0                        0     1
    1                       11     1          11
Control Points  6 rational points
  index               value
  CV[ 0][ 0] [-0.72362722698663262, 8.3618136134933163, 0, 1] = (-0.72362722698663262, 8.3618136134933163, 0)
  CV[ 0][ 1] [-0.72362722698663262, 8.3618136134933163, 11, 1] = (-0.72362722698663262, 8.3618136134933163, 11)

  CV[ 1][ 0] [-0.25584085962673253, 5.912695109119114, 0, 0.70710678118654757] = (-0.36181361349331631, 8.3618136134933181, 0)
  CV[ 1][ 1] [-0.25584085962673253, 5.912695109119114, 7.7781745930520234, 0.70710678118654757] = (-0.36181361349331631, 8.3618136134933181, 11)

  CV[ 2][ 0] [-0.36181361349331626, 8, 0, 1] = (-0.36181361349331626, 8, 0)
  CV[ 2][ 1] [-0.36181361349331626, 8, 11, 1] = (-0.36181361349331626, 8, 11)
ON_NurbsSurface dim = 3 is_rat = 1
        order = 3 X 2 cv_count = 3 X 2
Knot Vector 0 ( 4 knots )
index                     value  mult       delta
    0                        8     2
    2                        9     2           1
Knot Vector 1 ( 2 knots )
index                     value  mult       delta
    0                        0     1
    1                       11     1          11
Control Points  6 rational points
  index               value
  CV[ 0][ 0] [0, 8, 0, 1] = (0, 8, 0)
  CV[ 0][ 1] [0, 8, 11, 1] = (0, 8, 11)

  CV[ 1][ 0] [0, 6.1685359687458456, 0, 0.70710678118654757] = (0, 8.7236272269866326, 0)
  CV[ 1][ 1] [0, 6.1685359687458456, 7.7781745930520234, 0.70710678118654757] = (0, 8.7236272269866326, 11)

  CV[ 2][ 0] [-0.72362722698663273, 8.7236272269866326, 0, 1] = (-0.72362722698663273, 8.7236272269866326, 0)
  CV[ 2][ 1] [-0.72362722698663273, 8.7236272269866326, 11, 1] = (-0.72362722698663273, 8.7236272269866326, 11)
```
```

        {
          "type": "nurbs",
          "nurbs": {
            "controlPoints": [
              [
                0.0,
                0.203,
                0.0,
                1.0
              ],
              [
                0.0,
                0.203,
                0.279,
                1.0
              ],
              [
                0.0,
                0.157,
                0.0,
                0.707
              ],
              [
                0.0,
                0.157,
                0.198,
                0.707
              ],
              [
                -0.018000000000000002,
                0.222,
                0.0,
                1.0
              ],
              [
                -0.018000000000000002,
                0.222,
                0.279,
                1.0
              ]
            ],
            "numControlPoints": [
              3,
              2
            ],
            "numKnots": [
              6,
              4
            ],
            "knotVector": [
              8.0,
              8.0,
              8.0,
              9.0,
              9.0,
              9.0,
              0.0,
              0.0,
              11.0,
              11.0
            ],
            "order": [
              3,
              2
            ]
          }
        },

        {
          "type": "nurbs",
          "nurbs": {
            "controlPoints": [
              [
                -0.018000000000000002,
                0.212,
                0.0,
                1.0
              ],
              [
                -0.018000000000000002,
                0.212,
                0.279,
                1.0
              ],
              [
                -0.006,
                0.15,
                0.0,
                0.707
              ],
              [
                -0.006,
                0.15,
                0.198,
                0.707
              ],
              [
                -0.009000000000000001,
                0.203,
                0.0,
                1.0
              ],
              [
                -0.009000000000000001,
                0.203,
                0.279,
                1.0
              ]
            ],
            "numControlPoints": [
              3,
              2
            ],
            "numKnots": [
              6,
              4
            ],
            "knotVector": [
              27.362,
              27.362,
              27.362,
              28.362,
              28.362,
              28.362,
              0.0,
              0.0,
              11.0,
              11.0
            ],
            "order": [
              3,
              2
            ]
          }
        },
```

**Comment by alteous** [comment]
@mlfarrell, are you able to confirm you are using the same B-rep data to render with? I can only work with the data I'm given, so either I'm reading the wrong data or the data is incorrect.

**Comment by mlfarrell** [comment]
@alteous the ON data is generated from ON itself when converting curves (tangent arcs in this case) to nurbs curves and eventually nurbs surfaces.   When I render, I'm simply calling the ON surface evaluator.  So i'd be very surprised if the data that I was using to render is wrong.

**Comment by alteous** [comment]
I created a similar part which renders correctly in the modelling app but fails to generate a valid B-rep when calling `Scene::Model::Brep::Brep::getForRust`:

![image](https://github.com/KittyCAD/modeling-app/assets/8549126/e5770c7f-e988-4a9b-bc55-6b2b8292f5de)

BC and FG are the expected control points for the NURBS curves.

![sketch](https://github.com/KittyCAD/modeling-app/assets/8549126/85003b43-315b-4a6c-9fff-c88a0ff8cc52)

I have modified a test to reproduce the issue locally: https://github.com/KittyCAD/engine/pull/1501/commits/767182c17647feeea0e1f3a53c80a1266fa69683#diff-a0262fea108af44a98cc49e5eb72641963dd816513f2d0a22eb738fcfed55ebe

This is the output:
```
running 1 test
KittyCAD Engine Renderer Initialized 
  NVIDIA GeForce RTX 3060 Laptop GPU (2)
  Vulkan 1.3
CUDA (nvenc) GPU in use: NVIDIA GeForce RTX 3060 Laptop GPU
center: (0, 0)
pole: (0, -1)
angle: 90 degrees
offset: 0 degrees
endpoint: (2, 0, 0)
endpoint: (2, 0, 0)
endpoint: (2, 0, 0)
endpoint: (2, 0, 0)
endpoint: (2, 0, 0)
endpoint: (2, 0, 0)
endpoint: (2, 0, 0)
endpoint: (2, 0, 0)
endpoint: (2, 0, 0)
endpoint: (2, 0, 0)
endpoint: (2, 0, 0)
endpoint: (2, 0, 0)
endpoint: (2, 0, 0)
endpoint: (2, 0, 0)
endpoint: (2, 0, 0)
Warning: Brep validation failed!
Warning: brep.m_E[19] edge is not valid.
	edge.m_tolerance=-1.23432e+308 (should be >= 0.0)
ON_Brep.m_E[19] is invalid.

test tests::serial_test_run_engine_stream_check_lines_with_extrude_export_to_step ... FAILED

failures:

---- tests::serial_test_run_engine_stream_check_lines_with_extrude_export_to_step stdout ----
thread 'tests::serial_test_run_engine_stream_check_lines_with_extrude_export_to_step' panicked at src/tests.rs:894:23:
called `Result::unwrap()` on an `Err` value: CppErrors([CppError { code: InternalEngine, msg_internal: "Invalid boundary representation", msg_external: "Invalid boundary representation" }])
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Note the endpoint of the tangental arc is point C as expected. I'm not sure why the B-rep is invalid in this case but it is certainly related to the arcs. If I replace the arcs with simple line curves then I get a correct result:

![image](https://github.com/KittyCAD/modeling-app/assets/8549126/7aad9cb8-71a5-4940-a6e9-fbb97824eab3)

**Comment by alteous** [comment]
I also notice some artifacts which may or may not be related:

![artifacts](https://github.com/KittyCAD/modeling-app/assets/8549126/7235af30-197b-4c71-bede-17262eaef9ef)

**Comment by alteous** [comment]
I understand the surfaces are being evaluated using the 2D trim space rather than the 3D curves. If the 2D curves and the 3D curves do not agree with each other then this would explain why it is rendered correctly but does not produce a valid B-rep.

Until now, I have only been exporting the 3D curves in the glTF, since this is the all that's strictly necessary. I plan to add the 2D curves next and will verify the correctness then.

**Comment by mlfarrell** [comment]
https://github.com/KittyCAD/engine/pull/1515

**Comment by mlfarrell** [comment]
for the rendering glitch - https://github.com/KittyCAD/engine/pull/1516

**Comment by alteous** [comment]
For clarity, the point I'm trying to get across is the path is counter-clockwise when viewed from below as the picture above it doing, so I would expect the face to be visible on this side.

**Comment by alteous** [comment]
I can make the B-rep appear as expected by tweaks the control points. The NURBS control points are computed at [`ON_ArcCurve::GetNurbForm`](https://github.com/KittyCAD/internal-open-nurbs/blob/88d25ac5bc2ce13da511b2860035978111a3726c/opennurbs_arccurve.cpp#L756) which is called by [`Scene::Model::Brep::Face::updateDrawInfo`](https://github.com/KittyCAD/engine/blob/main/cpp/engine/scene/model/brep/face.cpp#L491). Using the debugger, I inspected the values computed by `GetNurbForm` and found them to be the same as what I'm getting. I have no idea how the engine is rendering this correctly but I am quite certain these values are wrong. My tweaked values are those based on this document: https://www.geometrictools.com/Documentation/NURBSCircleSphere.pdf.

```
diff -u lines_with_extrude.gltf original_lines_with_extrude.gltf
--- lines_with_extrude.gltf	2023-10-10 17:18:42.911129785 +0100
+++ original_lines_with_extrude.gltf	2023-10-10 17:15:50.476390344 +0100
@@ -810,9 +810,9 @@
                 1.0
               ],
               [
-                1.0,
+                0.707,
                 0.0,
-                -1.0,
+                -0.707,
                 0.707
               ],
               [
@@ -863,9 +863,9 @@
                 1.0
               ],
               [
-                1.0,
-                2.0,
-                -1.0,
+                0.707,
+                1.414,
+                -0.707,
                 0.707
               ],
               [
@@ -1201,15 +1201,15 @@
                 1.0
               ],
               [
-                1.0,
+                0.707,
                 0.0,
-                -1.0,
+                -0.707,
                 0.707
               ],
               [
-                1.0,
-                2.0,
-                -1.0,
+                0.707,
+                1.414,
+                -0.707,
                 0.707
               ],
               [
```

![image](https://github.com/KittyCAD/modeling-app/assets/8549126/c37ae89b-875f-4bd4-8cd9-bd7a108326b2)

**Comment by mlfarrell** [comment]
@alteous i'll take a closer look.   i dont have your full path set up (the brep export step part), but I'll at least see if I can understand why you're getting the values that you do.

**Comment by alteous** [comment]
@mlfarrell and I discussed this on Slack. Mike recognised the 3D part of the control points were pre-multiplied by the 4D homogeneous component.

I'm disappointed I didn't notice this myself sooner but at least we know what the problem is now. Amending the export code to un-pre-multiply (i.e., divide :stuck_out_tongue:) the spatial components by the `w` component fixes the issue.

I'll make the required changes soon and add a new test for this arc case soon. This will add more work to the looming engine test refactor but this fix really can't wait.

**Comment by alteous** [comment]
https://github.com/KittyCAD/engine/pull/1518 fixes this issue and adds my reproducer code as a new test.

**STEP**

![image](https://github.com/KittyCAD/modeling-app/assets/8549126/b15c8a7a-14ce-4dd7-9ee7-215bef0edba2)

**glTF**

![image](https://github.com/KittyCAD/modeling-app/assets/8549126/695ebe7a-e872-4f2b-ad8b-da62e87f7caa)
