### ISSUE TITLE
More flexible operands in KCL operators

### ISSUE THREAD

**Issue by adamchalmers** [KittyCAD/modeling-app#783]
Currently KCL parser cannot handle using function calls as operands.

e.g. this works:

```kcl
let x = f()
let y = x + 1
```

but this doesn't

```kcl
let y = f() + 1
```

It should work, though!

**Comment by jtran** [comment]
This works, so maybe it was already fixed.

<img width="1624" alt="Screenshot 2024-07-25 at 6 20 05 PM" src="https://github.com/user-attachments/assets/353dc951-dc02-4fc3-9ad9-eac5a5e308f4">

**Comment by jessfraz** [comment]
Huh we should make sure we have a test for it so it doesn't break
