### ISSUE TITLE
🧙 Multifile support

### ISSUE THREAD

**Issue by franknoirot** [KittyCAD/modeling-app#793]
Support multiple files within projects. This is part of a larger effort to begin to build in VS Code-like live sharing.  We already have some legwork done for this:
- Our projects are folders
- Our projects each have a ([currently hardcoded](https://github.com/kittycad/modeling-app/blob/main/src/lib/tauriFS.ts#L15)) project entrypoint file, and this is what is being opened and operated on within the `/file/` path that is the modeling area of the app
- Operations on the `/home` route operate on these folders instead of the underlying files
- We have a left sidebar "Project" menu with few menu items, giving us UX space to manage multiple files from within a project

## What we need
- Ability to create, rename, open, and delete files from within the left sidebar
- Ability to mark a file within the project as the "default" when opening it
- Indicators on the home page for how many files a project contains
- Indicators of what file in a project you're viewing

## What we don't need (yet)
- Assemblies: this issue does not cover creating a single file that imports geometry from other files
- Command bar support: just saying this to myself so that I don't fall into scope creep 😅 
- Keyboard shortcuts: eventually I want context-specific shortcuts but I think we need a broader framework for that first

**Comment by jessfraz** [comment]
for sure, but we should have some "best practices" around it

**Comment by franknoirot** [comment]
Yeah definitely. We could even incorporate that into linting right?
> "You have helper functions used by other files in this file, and also an assembly. This can make reading through the project harder for others. Would you like to consolidate your helper functions into a `lib.kcl` file?

idk if that's too heavy-handed.

**Comment by franknoirot** [comment]
Should we support sub-folders in a project? I have a hunch that we should.

<img width="316" alt="Image showing the VSCode file manager sidebar, which we will likely take inspiration from" src="https://github.com/KittyCAD/modeling-app/assets/23481541/9f3b44e4-6d59-4223-869e-44c823228400">

**Comment by franknoirot** [comment]
Here's my idea for the project menu. ([Figma link](https://www.figma.com/file/5UUPOawPLEs3D0Gptf42vy/Designs?type=design&node-id=377-273&mode=design&t=RzOgNIWqrUnKv8Pd-11))

<img width="494" alt="Screenshot 2023-10-05 at 4 52 31 PM" src="https://github.com/KittyCAD/modeling-app/assets/23481541/47920bf7-824e-49f8-afff-5866df541727">
