### ISSUE TITLE
Move/rework the debug panel to not block the orientation gizmo

### ISSUE THREAD

**Issue by franknoirot** [KittyCAD/modeling-app#805]
Currently the debug panel obfuscates the gizmo:

<img width="558" alt="Screenshot 2023-10-06 at 7 18 03 AM" src="https://github.com/KittyCAD/modeling-app/assets/23481541/a5f4689c-150d-4e66-acf1-029ed615eaea">

Maybe try having the debug panel in the upper right for now. We may need a think about the panels in the near future.

**Comment by jessfraz** [comment]
this no longer applies
