### ISSUE TITLE
Origin plane culls objects

### ISSUE THREAD

**Issue by notalfredo** [KittyCAD/modeling-app#806]
Not sure if this is by design but looks like origin plane is culling objects. I couldn't find an issue regarding this?

![image](https://github.com/KittyCAD/modeling-app/assets/82833619/d1706c8d-6349-4dac-b5a2-dc7925f8d513)

**Comment by mlfarrell** [comment]
boop

https://kittycadworkspace.slack.com/archives/C04KFV6NKL0/p1696526224562409
