### ISSUE TITLE
Does KCL even need strings?

### ISSUE THREAD

**Issue by adamchalmers** [KittyCAD/modeling-app#807]
Why does KCL even have string values? Do they get used in the stdlib anywhere? Would they be useful for user-defined functions? 

I can see maybe in the future we let users render text on surfaces, like an embossing on the lid of a box you're designing. But we're not there yet.

**Comment by jessfraz** [comment]
tags on surfaces and lines and stuff for constraints

**Comment by jessfraz** [comment]
this works today if you tag something https://github.com/KittyCAD/modeling-app/blob/629f326f4cdf13d83a62f471b4b9a40d3c3a2a88/src/wasm-lib/kcl/src/std/sketch.rs#L110

**Comment by adamchalmers** [comment]
Ah yeah OK tags are important
