### ISSUE TITLE
Docs change: kcl/std.md

### ISSUE THREAD

**Issue by notalfredo** [KittyCAD/modeling-app#808]
Today when trying to create a bezier curve I looked at the docs as reference. 

What I found I found confusing was that type types on `std.md` did not match the types that I found in the source code. For example for the type `BezierData` it can be constructed as *according to `std.md`*
```ts
{
// The first control point.
control1: [number],
// The second control point.
control2: [number],
// The to point.
to: [number],
}
```

but in the source code its represented as 

```rust
/// The to point.
to: [f64; 2],
/// The first control point.
control1: [f64; 2],
/// The second control point.
control2: [f64; 2],
```

So in the first one I understood at as an array of a numbers of length one when it was actually a length 2. I noticed that for a couple other things. 

I think something like 
```ts
{
// The first control point.
control1: [number, number],
// The second control point.
control2: [number, number],
// The to point.
to: [number, number],
}
```
is better

Not sure if it was intended or not. I can go in and fix it up *if its an issue at all*. What do yall think ?

**Comment by jessfraz** [comment]
To give you a bit of history of how this all works I recorded this but happy to answer any questions you have along the way, but TLDR we would love a fix :)


https://github.com/KittyCAD/modeling-app/assets/1445228/a2c5cf57-4800-4536-9fce-3a1dedeef2c6

**Comment by notalfredo** [comment]
sweet ill give it a go !
