### ISSUE TITLE
Path winding order on sketches are in the opposite sense after extrusion

### ISSUE THREAD

**Issue by alteous** [KittyCAD/modeling-app#824]
The winding order is wrong to me. The code I wrote in https://github.com/KittyCAD/modeling-app/issues/766 makes a clockwise circuit for the inside face of the solid. After extrusion, the top face is oriented correctly but the bottom face remains the wrong way up. Reversing the order in the code corrects the bottom face orientation but this is not a solution.

![winding](https://user-images.githubusercontent.com/8549126/273964273-63981ba8-e6fe-4a11-8f5d-ad1644a8588a.png)

For clarity, the point I'm trying to get across is the path is counter-clockwise when viewed from below as the picture above it doing, so I would expect the face to be visible on this side.

Is the winding order meant to have any significance on the solid in the modelling app? Whether it is or not, either the modelling app or the engine needs to ensure outward faces have counter clockwise loops for export to work properly.

**Comment by jessfraz** [comment]
I think the engine should own this but cc @jgomez720 @Irev-Dev for comment

**Comment by Irev-Dev** [comment]
Yeah seems like a engine should own thing to me too.

**Comment by jessfraz** [comment]
@alteous are you still seeing this? If so can you hit the transfer button and move to engine repo :)

**Comment by alteous** [comment]
I wasn't able to reproduce this anymore so consider it solved. :smile:
