### ISSUE TITLE
Make sure to catch parse errors

### ISSUE THREAD

**Issue by Irev-Dev** [KittyCAD/modeling-app#827]
Search for `TODO #827` in `src/hooks/useSetupEngineManager.ts`

**Comment by Irev-Dev** [comment]
Ended up getting resolved in #713 anyway

**Comment by franknoirot** [comment]
I think this still may be occurring. In main while running `yarn tauri dev`, now whenever I edit the tutorial code by adding/removing spaces, I see the following error:
```
Error from server:
  - invalid_json: UUID parsing failed: invalid length: expected length 32 for simple format, found 0
```

And I am unable to get models to load in the stream. Here is my console output:
<img width="609" alt="Screenshot 2023-10-11 at 9 59 45 AM" src="https://github.com/KittyCAD/modeling-app/assets/23481541/9c81faaa-f9c7-46f6-b0ff-756faacffef5">

And here is where that referenced line (336) in [`useStore`](https://github.com/kittycad/modeling-app/blob/main/src/useStore.ts#L237) leads back to that is throwing, resulting in the console error.

Here's the editor code I used for reference:

```
const sigmaAllow = 15000 // psi
const width = 11 // inch
const p = 150 // Force on shelf - lbs
const distance = 12 // inches
const FOS = 2
const thickness = sqrt(distance * p * FOS * 6 / ( sigmaAllow * width ))
const filletR = thickness * 2
const shelfMountL = 9
const wallMountL = 8

const bracket = startSketchOn('XY')
  |> startProfileAt([0, 0], %)
  |> line([0, wallMountL], %)
  |> tangentalArc({
    radius: filletR,
    offset: 90
  }, %)
  |> line([-shelfMountL, 0], %)
  |> line([0, -thickness], %)
  |> line([shelfMountL, 0], %)
  |> tangentalArc({
    radius: filletR - thickness,
    offset: -90
  }, %)
  |> line([0, -wallMountL], %)
  |> close(%)
  |> extrude(width, %)

show(bracket) 
```

The stream is reliable, and I can move my camera around, but no models can appear by editing the code pane.

**Comment by franknoirot** [comment]
Okay so the raw error we're seeing come out the end is actually and error-parsing error. The engine (I think?) is returning a string error and we're trying to parse it as JSON no matter what [here](https://github.com/kittycad/modeling-app/blob/main/src/lang/wasm.ts#L160C10-L160C10).

The real error being returned from the engine is:
```
"UUID parsing failed: invalid length: expected length 32 for simple format, found 0 at line 1 column 8"
```

So something needs a UUID but isn't getting it.

**Comment by adamchalmers** [comment]
I'm seeing similar errors:

```
'invalid type: map, expected usize at line 1 column 276556'
```

I think this is being emitted by the engine/API and sent back to the client. This is incorrect behaviour, the engine/API should always send JSON responses. The "expected usize at line 1" looks like a serde error message -- it's trying to deserialize some data and it's getting the wrong data (got a map object but it's expecting a number). 

So I suspect something on the backend is returning a serde error string directly instead of wrapping it in JSON.

**Comment by adamchalmers** [comment]
Actually the errors aren't on main, they're just on my new parser branch, ignore my comment sorry
