### ISSUE TITLE
move lines is broken w xstate stuff

### ISSUE THREAD

**Issue by jessfraz** [KittyCAD/modeling-app#834]
- [x] edit sketch cannot move more than once
- [x] inital sketch move not updating code
- [x] Make vertex selection work again #869 

https://github.com/KittyCAD/modeling-app/assets/1445228/a0380130-c3cb-4573-a7db-efdbc04d81f7

**Comment by Irev-Dev** [comment]
Re-opening because #850 still had some issues, namely vertex selection is a bit wonky.
