### ISSUE TITLE
Building and running from source takes me to wrong start page ?

### ISSUE THREAD

**Issue by notalfredo** [KittyCAD/modeling-app#845]
Not sure if im doing something wrong. Was running the usual commands `yarn install`, `yarn build:wasm`, `yarn start` this would normally take me to the UI editor but in the video I linked it took me to a different page. Is there something im not realizing ? I could of sworn I have always gone to the main UI editor this way.

https://github.com/KittyCAD/modeling-app/assets/82833619/2bdf7bb1-e0d7-46e4-968b-eff0ea8fbe22

**Comment by jessfraz** [comment]
oh so you should get 2 browsers opening
1. localhost:3000
2. the stately machine site, which is that second one you see

likely since you are using arc the preview for the localhost:3000 is being overwritten by #2 if that makes sense!

**Comment by notalfredo** [comment]
Yes that does, it works now thanks !
