### ISSUE TITLE
Holes vs difference/subtract

### ISSUE THREAD

**Issue by adamchalmers** [KittyCAD/modeling-app#860]
KCL stdlib just added holes. You can put holes into a closed path (aka a 2d shape) like this. This models a cube with two circular holes through it.

```kcl
const part = mySquare([0, 0], 20, 20, 4)
  |> hole(circle0, %)
  |> hole(circle1, %)
  |> extrude(2, %)
```

Holes are useful, but they seem like a special case of a more general "cut this closed path out of that larger closed path". In the future I imagine we'd support more general cuts, so you can cut other shapes. Imagine we want to cut away a star shape, you could do:

```kcl
const part = cut(
  // This is the shape to cut from
  mySquare([0, 0], 20, 20, 4),
 // Cut this away from the previous shape.
  myStarShape(),
)
  |> extrude(2, %)
```

I imagine that in this future, `hole` would either be removed, or become syntactic sugar for cutting away a circle. What do y'all think?

**Comment by jessfraz** [comment]
I lean more towards syntactic sugar

**Comment by jessfraz** [comment]
linking https://github.com/KittyCAD/modeling-app/discussions/510

**Comment by adamchalmers** [comment]
Am I right that we only support circular holes right now?

**Comment by jessfraz** [comment]
no you pass in any 2d solid could be a traingle or even a gear shape, whatever as long as its a 2d solid

**Comment by mlfarrell** [comment]
I'd be _very_ careful calling anything "cut" or "subtract" right now.   We shouldn't be naming things that have connotations of more functionality than where we're currently at in the alpha.

Holes is a bit informal.   Basically these things are "inner profiles" of a closed 2D path.  They lie (for now completely) within the same 2D plane that the path does.

**Comment by mlfarrell** [comment]
Jess is right, any path that falls completely within another path can be used as an inner "hole"

**Comment by adamchalmers** [comment]
Oh, OK, that's awesome. So it's basically an operation on two closed paths, where one path becomes a "hole" within the other.

Also, is there a difference between "closed path" and "2d solid"?

**Comment by mlfarrell** [comment]
> Also, is there a difference between "closed path" and "2d solid"?
there is in the engine lol.   The actor currently does both.  However if you close a path manually (closing it where it started), then it can be used anywhere that a closed path is required
