### ISSUE TITLE
restarting onboarding needs to re-execute the model

### ISSUE THREAD

**Issue by jessfraz** [KittyCAD/modeling-app#862]
https://github.com/KittyCAD/modeling-app/assets/1445228/029ca791-948d-4dca-bb54-0c8cbce81eb3

**Comment by Irev-Dev** [comment]
https://github.com/KittyCAD/modeling-app/assets/29681384/4ddc740b-4ed0-44e1-aef9-4dc7ac47f129


https://github.com/KittyCAD/modeling-app/assets/29681384/8170f27a-7441-44cd-8a15-b471db741970

We mostly got this for free in #897, but I did find a bug when checking this, so fixed that up too.
