### ISSUE TITLE
Can't add anything to code editor

### ISSUE THREAD

**Issue by davidstelter** [KittyCAD/modeling-app#867]
I can't add code in the editor. I can delete existing text, but I can't add anything new, neither values I've just deleted nor fresh values. I CAN edit numbers by doing the cool alt+drag thing, and I can enter newlines, but can't even add new comments. This happens to me 100% of the time, I've never been able to enter anything. Happens with the tutorial as well as a fresh, empty file.

I'm on an x86_64 MacBook Pro with macos Monterey 12.7. Not seeing any errors in the console.

Steps to reproduce:

1. open app
2. try to type anything into code editor - I cannot!

**Comment by Irev-Dev** [comment]
Thansk @davidstelter, How odd.

Are you using the desktop-app? is it any different from the web-app version? https://app.kittycad.io/

(we're not officially supporting the web-app but can help in debugging sometimes)

**Comment by Irev-Dev** [comment]
@franknoirot, thinking out loud here, is there a possibility that this could be file permissions not letting us write to the file-system, therefore code-mirror never updates?

**Comment by davidstelter** [comment]
> Are you using the desktop-app? is it any different from the web-app version? https://app.kittycad.io/

I'm using the desktop app, yes. Just tried the web app, that works fine and lets me insert code in the editor.

**Comment by davidstelter** [comment]
> @franknoirot, thinking out loud here, is there a possibility that this could be file permissions not letting us write to the file-system, therefore code-mirror never updates?

That was a reasonable guess, but I've exported an STL model successfully to the local filesystem, and I've just tried manually granting full disk access to kittycad with no change.

**Comment by Irev-Dev** [comment]
@davidstelter The good news is I've been able to replicate it on an x86 mac I have access to but haven't got any further so far.

But definitely a good first step. I was worried for a moment I was going to have trouble replicating it.

**Comment by franknoirot** [comment]
That is so strange. I don't have access to an x86 mac unfortunately, but the fact that that is different makes me think we should check the ["universal" mac app image](https://github.com/KittyCAD/modeling-app/releases/download/v0.10.0/KittyCAD.Modeling_0.10.0_universal.dmg) against the [`.targz` one](https://github.com/KittyCAD/modeling-app/releases/download/v0.10.0/KittyCAD.Modeling.app.tar.gz).

@davidstelter do you know which one you used? It was probably the universal DMG if you downloaded it from [the website download page](https://kittycad.io/modeling-app/download), but we have other downloads on our [GitHub release page](https://github.com/KittyCAD/modeling-app/releases/tag/v0.10.0).

**Comment by Irev-Dev** [comment]
@davidstelter there's definitely no errors in the console?
I'm seeing `Unhandled Promise Rejection: CompileError: WebAssembly.Module doesn't parse at byte xxx` when the app boots up. I think there might be a problem with our wasm blob and x86, but want to check if this is the same bug or a different oneL

**Comment by davidstelter** [comment]
> That is so strange. I don't have access to an x86 mac unfortunately, but the fact that that is different makes me think we should check the ["universal" mac app image](https://github.com/KittyCAD/modeling-app/releases/download/v0.10.0/KittyCAD.Modeling_0.10.0_universal.dmg) against the [`.targz` one](https://github.com/KittyCAD/modeling-app/releases/download/v0.10.0/KittyCAD.Modeling.app.tar.gz).
> 
> @davidstelter do you know which one you used? It was probably the universal DMG if you downloaded it from [the website download page](https://kittycad.io/modeling-app/download), but we have other downloads on our [GitHub release page](https://github.com/KittyCAD/modeling-app/releases/tag/v0.10.0).

I started just before the app was released on the site, believe I got it from the GitHub releases section. I just downloaded the universal dmg from https://github.com/KittyCAD/modeling-app/releases/download/v0.10.0/KittyCAD.Modeling_0.10.0_universal.dmg and it's exhibiting the bug for me consistently.

**Comment by jessfraz** [comment]
Since it’s dealing with webrtc maybe @paultag has ideas?

**Comment by paultag** [comment]
What's interesting is the stream sounds like it's up and running (and the webapp working is a good sign since it's the same browser); and the WebSocket seems like it's up and healthy - but the weird thing is that `rtc_frames_dropped` error is coming from our backend, being displayed by the front-end (an `{"type": "error"}` sent over the websocket from the backend), and the only way for that to trigger would be when the metrics report for stream reliability was missing the `rtc_frames_dropped` json field.

After looking at it for a second, I suspect we must be getting back an `undefined`, which would cause:

```js
> JSON.stringify({rtc_frames_dropped: undefined})
< '{}'
```

I'll send a PR up to add some `||0` on those calls.

**Comment by davidstelter** [comment]
I've just checked and this problem with the editor isn't manifesting on my M1 mac mini, works just fine there!

**Comment by davidstelter** [comment]
Since the issue doesn't have a clearly-associated error message, are there any steps I can take to help collect more info on this from my end? I'm reasonably familiar with web app debug tools.

Or @paultag do you think that error with `rtc_frames_dropped` could be related?

**Comment by paultag** [comment]
@davidstelter I don't think it's related but here's some info that would help a TON if you're able to share! If you feel like any of this is leaking too much information about your setup, we're able to handle the info out of band (via discord, email, etc).

The below info can be skipped if the app, when it's broken, shows the grid behind the code (it would be super helpful to know if you see the grid or if it always says "Loading Stream")

If it says "Loading Stream", the following would be huge:

 1.  Any information you can find about the [WebRTC state](https://stackoverflow.com/questions/63036996/how-to-get-webrtc-logs-on-safari-browser)
    1.1: If you can get the remote/local SDP that would be super helpful.
    1.2: What is the ICE state?
  2. Any information regarding the open WebSocket to the backend; does it look like it's alive in the inspector?
  3. Any of the above when it's working in Safari directly on [app.kittycad.io](https://app.kittycad.io)

If it loads the grid, we can go through some different steps to collect more info about the internal state of the app. Thank you so much for offering, I know collecting all this is a big hassle.

**Comment by nilpunning** [comment]
Here is a PR which fixes this issue: https://github.com/KittyCAD/modeling-app/pull/2350.

**Comment by jessfraz** [comment]
let us know if you still see this in the latest release, thank you @nilpunning
