### ISSUE TITLE
For a bit the Windows build have had rendering issues

### ISSUE THREAD

**Issue by pierremtb** [KittyCAD/modeling-app#878]
Seem be stuck on the blur

![image](https://github.com/KittyCAD/modeling-app/assets/10795683/34599442-254e-43c8-bdb4-95a141fd0ae7)

**Comment by pierremtb** [comment]
I think https://github.com/KittyCAD/modeling-app/commit/d0930477ad9e386ff96959c6df50951c27911b37 might be what introduced it, need to verify

**Comment by pierremtb** [comment]
![image](https://github.com/KittyCAD/modeling-app/assets/10795683/20a9fef2-0b7f-45f8-8717-8df6426c3b3d)

**Comment by pierremtb** [comment]
Can confirm, https://github.com/KittyCAD/modeling-app/commit/d0930477ad9e386ff96959c6df50951c27911b37 introduced this, the same code works on the build originating from its parent commit

```
const part001 = startSketchOn('XY')
  |> startProfileAt([-0.02, 0], %)
  |> line([7.22, 7.39], %)
  |> line([2.9, -9.22], %)
  |> line([-6.48, -2.41], %)
  |> close(%)
  |> extrude(4, %)
```

**Comment by franknoirot** [comment]
I'm able to reproduce in our EC2 Windows setup when trying this with [the v0.11.0 PR artifact](https://github.com/KittyCAD/modeling-app/actions/runs/6533227463)

<img width="1505" alt="Screenshot 2023-10-16 at 4 21 59 PM" src="https://github.com/KittyCAD/modeling-app/assets/23481541/e906564c-0bf7-4b13-9075-1be370df170b">

I believe the thing that is being failed to fetch is the WASM here:

https://github.com/KittyCAD/modeling-app/blob/3b15bc12f70b6a787b2086fbadf9362e7e9c6b1a/src/lang/wasm.ts#L76

**Comment by franknoirot** [comment]
I'm gonna try on my actual Windows machine juuust in case it's something gnarly about our EC2 thing. It really gave me the itchies when I saw they have ***IE*** as the default browser on them 💀

**Comment by franknoirot** [comment]
I was able to replicate on my Windows machine so EC2 isn't the issue.

When running `yarn build:wasm` in Windows Powershell I get the following error:
```
cp: cannot stat `src/wasm-lib/pkg/wasm_lib_bg.wasm': No such file or directory
```

Which makes sense because the slashes are going the wrong way for Windows. This has been the case but I'm wondering if that same command is failing in CI, resulting in a Windows binary build that doesn't have the `wasm_lib_bg.wasm` file where it needs to be?

**Comment by franknoirot** [comment]
Okay I can confirm that copying `wasm_lib_bg.wasm`  into the proper place before running `yarn tauri dev` fixes the issue:

![Screenshot 2023-10-16 165919](https://github.com/KittyCAD/modeling-app/assets/23481541/726c57a9-ccd1-443f-8b38-00c65df71d62)

And I've confirmed that deleting this file then recreates the issue exactly, with the app stuck in a blur after everything finishes loading.

I feel pretty confident that file isn't being copied to the correct place in CI when we're building the Windows version of the app.

**Comment by franknoirot** [comment]
I think this step runs on all OSes, and on Windows it would need to have the slashes reversed?

https://github.com/KittyCAD/modeling-app/blob/main/.github/workflows/ci.yml#L144-L150

I think the same might be true of the other instances where we use the `cp` command, such as here:

https://github.com/KittyCAD/modeling-app/blob/main/.github/workflows/ci.yml#L115-L116

**Comment by franknoirot** [comment]
However, I'm not seeing anything like the error I saw when running `yarn build:wasm` locally when I look through CI action runs like [this one](https://github.com/KittyCAD/modeling-app/actions/runs/6537158724/job/17750658721).
