### ISSUE TITLE
We don't clear sketch (non-3D) entities from the scene when restarting onboarding

### ISSUE THREAD

**Issue by franknoirot** [KittyCAD/modeling-app#892]
If the user has sketch entities in the scene and they restart onboarding, or if they move past the Sketching onboarding step with one, their sketch entities persist until refresh.

<img width="1496" alt="Screenshot 2023-10-17 at 1 12 47 PM" src="https://github.com/KittyCAD/modeling-app/assets/23481541/36ed1f64-fc57-45b3-81d9-68963648d0f5">

**Comment by Irev-Dev** [comment]
As mention on the issue, #895 resolves this.
