### ISSUE TITLE
Creating New File Keeps Old Text

### ISSUE THREAD

**Issue by jgomez720** [KittyCAD/modeling-app#900]
## Description
When I create a new file, it keeps text from another file. 

## What it should do
When creating a new file, the file should be blank.

### Version
Tauri App - **v0.11.0** 

### Screenshots/Recordings
(I have a video with this too, but I haven't been able to successfully upload in the last 10 minutes, I'll try again tomorrow)

**Comment by jgomez720** [comment]
https://github.com/KittyCAD/modeling-app/assets/114548659/fb818913-16d2-4208-a3b1-835d89d5a7df

**Comment by Irev-Dev** [comment]
I think https://github.com/KittyCAD/modeling-app/pull/897 will solve this (if not already) There are a few weird things going on with say the current code and what happens to it both when changing files and when the code get's re-executed that I'm hoping to solve all together.

**Comment by Irev-Dev** [comment]
Oh wait I'm a little confused actually now that I think about it. That looks like it might be the default code, I actually agree with you that a new file should be empty but I thought it was desired behaviour to put the bracket sample code in there?

**Comment by jessfraz** [comment]
It should be empty not sample code

**Comment by Irev-Dev** [comment]
Should be resolved by https://github.com/KittyCAD/modeling-app/pull/897
