### ISSUE TITLE
Drag Restarts Camera Position

### ISSUE THREAD

**Issue by jgomez720** [KittyCAD/modeling-app#902]
## Description
When I drag the camera, the camera position restarts, thus never getting further than I did on my previous drag.

## Expected Behaviour
Once I drag and let go, I expect the camera to stay where it is, and when I drag again, for it to keep that new location.

------

### Version
Tauri App - v0.11.0

### Screenshots/Screen Recordings

https://github.com/KittyCAD/modeling-app/assets/114548659/6402e39b-16ab-4722-90d0-01e0d51eb146

**Comment by franknoirot** [comment]
This is no longer an issue in the app[^1], here is a demo of the panning behavior 

https://github.com/KittyCAD/modeling-app/assets/23481541/2aa8ec80-af31-4df6-ba06-7ff8b6868653

[^1]: with the caveat that I don't know how to reproduce this messed up state where the user is in sketch mode but the stream has a 3D perspective. Please open another issue if that state is ever reproducible.
