### ISSUE TITLE
Have a standard library (not core)

### ISSUE THREAD

**Issue by adamchalmers** [KittyCAD/modeling-app#922]
In Rust, there's a difference between the `std` library and the `core` library. 

- The "core" library is implemented directly in the compiler, this includes types like arrays. 
- The "standard" library is written in Rust, it can call code in core. E.g. the type `Vec` is defined in the stdlib, and it uses the `array` type from core.

Currently KCL has a "standard library" but IMO this is actually a _core_ library, _not_ a standard library. Why? Because it's written in Rust and maps directly to engine API calls. IMO a real standard library would be written in KCL.

So, I propose:

- We rename the current standard library to a "core" library
- We start building a standard library for KCL

## What goes in the KCL stdlib?

The core library would map neatly to Engine API calls, and KCL standard library would be convenient extra functions built on top. For example, the engine API has methods to draw an arc. But no method to draw a circle. The stdlib would define a "circle" function which just calls the "arc" function from core, creating an arc from 0 degrees to 360 degrees.

This way, the engine API can provide a few general-purpose methods (like arcs and lines) and KCL can build convenience methods (like circles, squares, rectangles) on top of that. And this way the API doesn't become big and bloated.

**Comment by jgomez720** [comment]
I approve this message

**Comment by adamchalmers** [comment]
Thanks Josh

**Comment by adamchalmers** [comment]
Implementation:

We could either build this into the kcl executor, or maybe we build a more general library system, and KCL is just one specific library that we always load implicitly.

**Comment by adamchalmers** [comment]
After thinking more, the stdlib should not be treated like a normal lib, because the stdlib will _always_ be bundled with KCL. And also, the stdlib is immutable -- we can distribute it pre-parsed as an AST instead of as source code. This way you don't have to parse the stdlib every time you parse your normal programs.

**Comment by adamchalmers** [comment]
Proposal: we ship a new Rust crate called kcl-stdlib. This crate exports pre-parsed KCL functions (i.e. already parsed into KCL AST nodes) as constant values.

Then the KCL executor includes all these pre-parsed nodes in the user's program AST.

How does this crate work? Well, it would include the stdlib as a .kcl file in the source repo. Then its build.rs would run the KCL parser on these, parsing into the AST nodes, and output them as Rust source code for the library.

**Comment by franknoirot** [comment]
I like this idea. We've got some named constants in our standard library right? Would those continue to be in the standard library—not core—because they don't map to engine API calls? All named constants go into stdlib as a rule

**Comment by adamchalmers** [comment]
Yep, they'd go into stdlib! They can be defined in KCL, not Rust.

**Comment by lf94** [comment]
>  KCL is just one specific library that we always load implicitly.
 
Maybe a long time ago I would've said yes, but I have learned seeing the explicit imports of what a script uses is useful because **it gives you an idea of the primitives the script will be using**.

IMO it should not be a separate crate from core. I would like to read and meditate on actual scenarios where **you would not include stdlib**, but you would core. To me this is additional organizational effort for very little gain.

**Comment by lf94** [comment]
Yeah, but let me say the obvious: you don't need two separate projects to enable this contribution workflow

**Comment by adamchalmers** [comment]
Right now, KCL doesn't have any way to express that a function's parameters are optional. This means we'd have to choose whether the `circle` stdlib function has parameters like

 - radius, center, plane
 - radius, center, plane, tag

Ideally `tag` would be optional, but right now, if you want optional arguments you have to define the function in Rust, not in KCL. I think this is a big blocker for writing a KCL stdlib right now. Our users can define their own functions to fit their specific needs -- they know if they want a `tag` parameter in their `fn circle` for example. But we, stdlib authors, do not, and so we need optionals. Otherwise we'll end up creating two stdlib functions, `fn circle` and `fn circleWithTag`.

Note that we don't actually a dedicated syntax for optionals -- simply using KCL enums (https://github.com/KittyCAD/modeling-app/issues/1006) would be enough. So I suggest we ship KCL enums first, then a KCL stdlib.

**Comment by adamchalmers** [comment]
Also we'll probably want another awesome stdlib doc macro like the one @jessfraz made for the Rust core functions (implemented [here](https://github.com/KittyCAD/modeling-app/blob/6cc8af5c239b15a87b6cec19a03671b156e14d01/src/wasm-lib/derive-docs/src/lib.rs)) but this one generates docs from the KCL itself. Which would require compile-time parsing of KCL (see #1018)

**Comment by adamchalmers** [comment]
I think we can decouple enums from stdlib. We build a stdlib function with no enums for now. Then once we impl enums, we can change stdlib functions parameters to be just one variant of an enum. Then we can add more variants.
