### ISSUE TITLE
Decouple tauri build/sign in CI

### ISSUE THREAD

**Issue by pierremtb** [KittyCAD/modeling-app#982]
I really don’t love that we have to wait for that super long CI for every commit. Maybe we could run a first simplified Linux tauri build just for testing purposes, with e2e and seing if tauri build works. And build all platforms + sign only on merge to main, release PRs, and releases.

Would like to keep tauri in the loop for every commit and PR, but keep that simple and quick (no need for secrets for external contributors for instance)

**Comment by adamchalmers** [comment]
The tauri action [docs](https://github.com/tauri-apps/tauri-action/tree/v0/) show two config items we can set: `includeDebug` (false by default) and `includeRelease` (true by default).

We could use debug builds for PRs and only use release for releasing on main.
