### ISSUE TITLE
unexpected large data transfer

### ISSUE THREAD

**Issue by indirectlylit** [KittyCAD/modeling-app#989]
Hello!

This might be known behavior but I found it surprising. I had KittyCAD running in a background window with just the default test project open, and nearly 30GB of data was downloaded:

![image](https://github.com/KittyCAD/modeling-app/assets/2367265/997d1a12-943b-4084-820a-9bb00ae2a717)

The majority of this was from `52.86.2.247` and about 1GB was from the `k8s-stunner-gateway...` AWS host.

At this point I closed the app. When I opening it again later, I did not observe the same behavior so I cannot give steps to reproduce.

Version: `0.11.1 (20231026.115616)`
MacOS: `13.6`

**Comment by jessfraz** [comment]
that is insane! Idk what you could even download from stunner?

cc @paultag @iterion

**Comment by indirectlylit** [comment]
> how long was the app running?

Yes, I had left it open in the background. It looks like the network activity occurred over the course of about 18 hours, mostly on port 3478.

**Comment by jessfraz** [comment]
okay 18hours of 1080p frames (i think?) that kinda adds up to me

**Comment by paultag** [comment]
OK I think we have a handle on what caused this here. I'm going to summarize and put this into that other bug. Feel free to add on anything additional on the new bug @indirectlylit - thanks for the report, definitely not the ideal outcome here.
